### ISSUE TITLE
Audience Display: No indication on Audience Display when a team has a yellow card

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#10]
Audience Display: No indication on Audience Display when a team has a yellow card

**Comment by adwiii** [comment]
This support has been added. 
It shows at the post of the match results
![image](https://user-images.githubusercontent.com/9453262/47858701-08c09480-ddc3-11e8-98cc-f6ad5782b7ad.png)
And also in a subsequent match:
![image](https://user-images.githubusercontent.com/9453262/47858883-62c15a00-ddc3-11e8-9e74-70f2057b094e.png)
