### ISSUE TITLE
Team view (Enhancement request)

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#100]
It would be great to be able to have a read-only team view of the day. This could have their list of matches (details on field number, alliance partner, opposing alliance teams, etc.), an overview of the day (matches they are scheduled for, field #, and alliance color) - perhaps with a list of all of the teams they have as alliance partners and all opponents, links to the event info pages (schedule, rankings, results, pits), and a link to the scoresheet (as available from the match results) for each of their completed matches. This would reduce the crowding around the pit display and save the scoring team a lot of questions.
I suggest that the team view would start with being able to select any team for the detailed viewing.
As we get further into the season, it will also be useful to have links to the league stats as well.

**Comment by cmacfarl** [comment]
Thank you Vince for the feedback you've provided in the last few issues.  

This particular functionality has, in the past, been provided by 3rd party sites such as ftcscores.com or theorangealliance.org, and/or others I don't know about, and that's the plan for new system as well.   They both implement a client that runs beside the scoring server that scrapes data during an event and pushes it to the cloud.   Take a look at one or the other.  They both have pretty slick UI's for viewing the data you want.

**Comment by vwestin** [comment]
Thanks Craig. Are we working with those organizations to have support ready for our events later this year (without local teams building their own integrations)? We are running our scoring on a private LAN for events right now, so we would need to bridge the scraper to get to the Internet, but that is workable. If we have some resources available to work on setting up the web pages, is this something we could help add to the default code?

**Comment by cmacfarl** [comment]
Both organizations have the documentation necessary to do the integration and last I heard were working on clients.  If you want to help with client integration you should contact one or the other to see where they are at in the process.

**Comment by maths22** [comment]
ftc-events.firstinspires.org provides this information now
