### ISSUE TITLE
Login option not available on iPad 2 running IOS 8.1

### ISSUE THREAD

**Issue by Nate2019** [FIRST-Tech-Challenge/scorekeeper#105]
When the scoring system is set up on my computer, and I go to log in on my iPad 2, the option to log in is not available. When trying this out on my iPhone, it works perfectly fine and I am able to log in.
![img_0001](https://user-images.githubusercontent.com/7596387/47333526-d9828880-d648-11e8-9a98-b410ae671aca.PNG)

**Comment by firewires12014** [comment]
It's there actually. It is off the screen. The mobile styling seems to need some work.

**Comment by maths22** [comment]
iOS 8 is no longer supported
