### ISSUE TITLE
Error 500 - Database Error

### ISSUE THREAD

**Issue by christopherwestcott** [FIRST-Tech-Challenge/scorekeeper#108]
I installed and ran the web-server from the bin folder in the extracted directory from the original .zip archive, as instructed. I create an event. I added teams. I generated a schedule. I made referee accounts. I connected to the web-server using a referee account using the browser on my phone. I later shut down the Command Prompt, that terminated the web-server but I didn't close the browser still connected. The extracted folder that was created from the .zip disappeared when I clicked on it. I had to extract the directory again from the original .zip archive. I was able to run the web-server again, but I could not create events. It seems the database was corrupted or something. What should I do to fix this. This my first experience with score keeper software.

**Comment by adwiii** [comment]
The most immediate solution I have for you is to download a fresh install of the software from this repository.

I will have to think about what could cause this. What version of the software were you running?

If the folder disappeared then I do not know what could cause this - the software never attempts to operate on the folder that it runs in so something else would have to have done that. 

There is a bug currently in the software where if not all of the fields are specified for an event then it will give you an error message, but not tell you why. You might try making sure that all fields were specified when creating the event.

**Comment by christopherwestcott** [comment]
Hummm... The first time I created an event, I didn't give it an event code, and got an error stated that all fields had to be populated. I then created the event again with an unique event code. Later, I saw that it had actually created the first event without the event code. I wanted to delete it, but could not find a way to do so. I wonder if this caused the problem somehow. I will download the software again, v.0.4.2

**Comment by adwiii** [comment]
How did you know that it had created the first event without an event code?

**Comment by christopherwestcott** [comment]
There was a screen that listed current events, there were two, the first event, and the second one.

**Comment by adwiii** [comment]
in v0.5.0 it will prevent you from creating an event with no event code. The page will also provide useful error messages to guide the user through what needs to change on the page.
