### ISSUE TITLE
Additional Data Output formats

### ISSUE THREAD

**Issue by hightechkids** [FIRST-Tech-Challenge/scorekeeper#110]
Is it possible to save the ranking report and match results (and any other match data) in some format besides printing it?  In past years, this data was saved as html and was easy for us to manipulate, reformat and post to our website. This year, the only choice seems to be to print these reports from the software.
From reading a past issue:  (#76) I read: _**The 3rd party api will give you all the matches and rankings via a few simple http GET queries that return JSON formatted data. You can write a script to convert json to whatever csv file you need, but again, you should not be doing raw database queries yourself.**_
Could I get an example of these GET requests and scripts? And how to use them?

**Comment by afera15** [comment]
I agree and CSV or XLSX format would be very helpful for at events for Ranking, Results and Schedule

**Comment by gearsincorg** [comment]
I'd like to add "Team List" to the request for CSV format output.

I assume that some events just start using the scorekeeper software on the day of the event, but I know that many organizers will use it to help prep for an event weeks in advance.

My goal is to use the Scorekeeper software as my master source for all other activities.  
This includes exporting the team list to other programs for: public websites, event program, drive team badge generation, pit signs etc.  All of these can use a simple CSV to import the latest team list.

Seems crazy that I should have to maintain (keep up to date) an external team list.  
Having a simple Export button on the teams page (like before) would be wonderful .

**Comment by cmacfarl** [comment]
There's a public API which will give you what you want if not in the exact
format you want it.
Documentation for which can be found on the GitHub wiki page.

I don't anticipate in the short term supporting more formats than the
existing json. Note that both TOA and FTCScores have 3rd party plugin
support for exporting data to their respective public websites.
