### ISSUE TITLE
API 404 returns the HTML 404 page rather than a proper 404

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#111]
API returns a "200 OK" (as well as the punny 404 page HTML) when an incorrect API route is accessed.

**Comment by adwiii** [comment]
It appears all 404 pages are returning `200 OK`, not just those with the API. This has been fixed and will be in 0.4.4

**Comment by adwiii** [comment]
Turns out all pages that said 404 actually had `200 OK` - this has been fixed in 0.5.0.
