### ISSUE TITLE
events/<eventid>/elim/sf/# Returns "NOT_READY" after alliance selections

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#115]
This should be populated with data now, correct? Empty Matches?

**Comment by cmacfarl** [comment]
Nope.  As the documentation states, that endpoint returns an array of matches that have been played.  If no matches have been played, it will return NOT_READY.  You should be able to deduce the matchups before any matches have been played from the elims/alliances endpoint.

**Comment by Techno11** [comment]
This is frustrating. Why have 1 endpoint (`/event/<eid>/matches`) return all matches whether they are played or not, and another completely the opposite?  We know that at least 2 SF matches of each bracket (1 and 2) are going to be played. Why not return them empty when unplayed?  If a third (or even 4th) is required, just append it to the end of the query!
