### ISSUE TITLE
Add route to API to get Yelow Cards, DQs, and No show

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#116]
Add route to API to get Red Cards, Yelow Cards, DQs, and No shows.  Similar to how you can get if the match is a surrogate

**Comment by ofekashery** [comment]
Any update?

**Comment by adwiii** [comment]
The api now tells if a team was disqualified from a match, though it does not give specific information about how this occurred, and does not give yellow card information. See [the swagger documentation](https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation) for more information.
