### ISSUE TITLE
Add Route to API to track number of time the score has been commited

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#117]
Add Route to API to track number of time the match has been replayed

**Comment by cmacfarl** [comment]
We are working on something that will timestamp matches.   When that exists, the API will expose it.

**Comment by adwiii** [comment]
To be clear, we have have no way of knowing how many times a match has been *replayed*, only how many times the score has been committed. If a match has been played and committed once and is then committed again, there is no way to tell if the second commit was an edit (someone mistyped something) or a replay.

**Comment by cmacfarl** [comment]
What adwii said.

**Comment by Techno11** [comment]
Can that be added to the API? In reality, that is all we care about.

**Comment by afera15** [comment]
Can we make the timestamp off when the controller clicks the start match button?

**Comment by adwiii** [comment]
As of 0.5.2 the commit time is returned.
