### ISSUE TITLE
Add Total Qualification Points scored and Team High Score to Rankings route

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#121]
Add Total Qualification Points scored and Team High Score to Rankings route `events/<eid>/rankings`

**Comment by kenpugsley** [comment]
Please consider prioritizing, at least the Highest Score, as apps using this data technically cannot provide a correct Rankings list without it.  Given the following test from the API Guidelines, external apps cannot technically display a valid rankings list without it.

> Applications must not generate their own rankings from match data without explicitly labelling them as not event official. The easiest to reach rankings, if not the only rankings available, should only be populated from the rankings resource described below.

**Comment by adwiii** [comment]
The ranking route returns the teams ranking, so you should not need to recalculate the order. I understand that it may be of interest to have the Highest Score to display to people out of their curiosity, but it should not be required.  
Here is sample output from the route:
```
{
  "rankingList": [{
    "team": 99997,
    "teamName": "",
    "ranking": 2,
    "rankingPoints": "1.20",
    "tieBreakerPoints": "12.0",
    "matchesPlayed": 5
  }, {
    "team": 99996,
    "teamName": "",
    "ranking": 4,
    "rankingPoints": "0.40",
    "tieBreakerPoints": "12.0",
    "matchesPlayed": 5
  }, {
    "team": 99999,
    "teamName": "",
    "ranking": 1,
    "rankingPoints": "1.60",
    "tieBreakerPoints": "12.0",
    "matchesPlayed": 5
  }, {
    "team": 99998,
    "teamName": "",
    "ranking": 3,
    "rankingPoints": "0.80",
    "tieBreakerPoints": "12.0",
    "matchesPlayed": 5
  }]
}
```
The ranking field indicates that 99999 is ranked 1st, followed by 99997, 99998, then 99996. All other data is meant purely for display purposes.

**Comment by kenpugsley** [comment]
Agree... though if you're trying to replicate the "normal" way that rankings are displayed, you have no "official" way to display the highest score on the ranking list other than figuring it out from matches, which you're not supposed to do.

As an aside ... thanks for the immediate triage of this topic!  👍

**Comment by cmacfarl** [comment]
Perhaps you want highest score and that's a legitimate request, however I caution you from stating that you can not provide an official rankings list without that as, you note in the comment, the API provides the one, and only, official rankings list.  

To which maybe you want to display highest score, but you must not attempt to replicate, or calculate, your own rankings, with or without using highest score, without clearly labeling them as 3rd party, unofficial, rankings.

**Comment by kenpugsley** [comment]
If this is a legitimate request, and there is no "official" way to display a rankings list with full data other than to get the data from the API, why is this request being closed?

**Comment by Techno11** [comment]
I would disagree with @cmacfarl .  I believe that an official rankings list would be something that resembles the official scoring system UI, which, does include High score and Total QP. Since this data is already being calculated, it would be great to have this included in the API.

**Comment by afera15** [comment]
@cmacfarl as you say "the API provides the one, and only, official rankings list."  then I would think as developer I would get everything that is included in ranking calculations asit is incuded in the UI as @Techno11 stated.  Which per the manual includes: 
1. Average Ranking Points; highest to lowest
2. Average TieBreaker Points; highest to lowest
3. Highest Match Score
With out the high score from the API we will need to do some calculation in our backend to do so which means we will be breaking the terms of using the API.
