### ISSUE TITLE
Match Score Display shows previous match score

### ISSUE THREAD

**Issue by mcchesneyc** [FIRST-Tech-Challenge/scorekeeper#125]
Tried to search for this but could not find as a current issue.  
Displays - When clicking on "Show Match" after loading the next match, the field and audience display continue to show the previous match scores with the new active match team numbers.  I've followed the sequence of green buttons as recommended in the manual.  The scores don't change to "0" until the scorekeeper clicks on "Start Match".  At that point the scores change to "0".  Previous match scores have been committed and posted.  I can submit pics/screen shots if needed.  v0.4.3

**Comment by adwiii** [comment]
We were able to get this into the v0.5.1 patch. Let us know if you see any further issues.
