### ISSUE TITLE
randomization display

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#126]
Need to determine from which direction the randomization display on both audience and field is shown.  It appears as if the field display is from outside the field but the pictures in the game manual are from inside the field.  Am I correct in these orientations.  It's just odd that when you are standing in the field to setup the sample field the the display you are looking at is the opposite.

**Comment by adwiii** [comment]
You are correct that every time a display shows the Sample Field, it shows the randomization as seen from the outside of the field. For example:
![image](https://user-images.githubusercontent.com/9453262/47609814-3fd62500-da14-11e8-9816-a2fdc9b0d81c.png)


Is this the below image in the manual what you are referring to?
![image](https://user-images.githubusercontent.com/9453262/47609771-18328d00-da13-11e8-9fea-a619cf4f0cee.png)

This shows it from the top with the reference made clear by displaying where the corner of the field is. We can attempt to make it clearer that the randomization presented as seen from the outside.

A note on why we present it the way we do:
We felt that it would be easier for the audience when looking at the Audience Display and the Score Tracker in the Alliance Station if the Sample Field was presented from the outside of the field. We then decided that it would be least confusing for everyone if the system always presented them from the same perspective, and thus the Field Display presents the Sample Field as seen from the outside of the field, even though the person setting up the field might be inside the field.

**Comment by rgutentag** [comment]
Yes that is the image from the game manual that I was referring to.  Just wanted to know that we were sure which way to look at it.  You can close this item now that we understand how to look at the displays.  Thanks  for the clarification.

**Comment by emmell620** [comment]
Please reopen with this suggestion.  Putting the corner of the field on your display screen like in the manual.  You might need to reduce the dice size and increase the pattern size, but it would definitely be more cleaner that way with no ambiguity.

**Comment by emmell620** [comment]
+1 bump

**Comment by adwiii** [comment]
Preference between:
![image](https://user-images.githubusercontent.com/9453262/49695023-9336a980-fb62-11e8-98c0-045e80fadcb8.png)
or
![image](https://user-images.githubusercontent.com/9453262/49695291-dc88f800-fb66-11e8-965e-f2ffa15dc99e.png)

**Comment by rgutentag** [comment]
NJ FTC prefers the one with the statement "As viewed from outside of the field"  Our reasoning is that everyone has been seeing this view.  If you use the other view it will be new to all the field personnel.

**Comment by cmacfarl** [comment]
Uh, that is totally confusing.

**Comment by emmell620** [comment]
Craig: How??  That is just like the manual. The angle signifies the corner of the field, so it doesn't matter if the referees are inside or outside of the field placing the randomized minerals.  Or, I hope you were being sarcastic.

**Comment by cmacfarl** [comment]
Well then the manual is confusing, as is indicated by the fact that the refs at my first league meet consistently set the sample field backward.  Not sarcasm.  I pointed out to the head ref they were setting it backward, but figured in the long run it didn't really matter as long as they were consistent (it's just randomization after all).

But looking at what you have there, I have no intuitive notion of how to set the field.  Looking at @adwiii's "Field Corner" image I immediately know how to set the field.  Whether or not you are inside or outside the field the relative location of the corner is abundantly clear.

**Comment by adwiii** [comment]
This has been added in v0.6.1. The Displays now emulate Figure D-2 in [Game Manual Part 2](https://firstinspiresst01.blob.core.windows.net/ftc/2019/gemf2.pdf)
