### ISSUE TITLE
change event from scrimmage to league meet

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#127]
The person that setup the event last week for one of our leagues made it a scrimmage and not a league meet.  Then went and played it to completion.  I got a change to look at it today and saw that it was a scrimmage and not a league meet.  Need to get that league straighten out before their next event.  Any ideas what to do.  Need this fixed before next Sat. and I won't be attending the event.

**Comment by rgutentag** [comment]
It looks like when I tried to load a copy on my home machine it loaded wrong.  I am at an event today and it is ok on the live scorekeeping .  Close this item

**Comment by adwiii** [comment]
It is concerning that it could have loaded wrong. Can you send the db file
along? Thanks

**Comment by adwiii** [comment]
The ability to edit an event, including type of the event, has been added in v0.5.0
