### ISSUE TITLE
Alliance Selection for League Events uses wrong ranking list

### ISSUE THREAD

**Issue by kevinwross** [FIRST-Tech-Challenge/scorekeeper#130]
[feynmantwo.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2523466/feynmantwo.zip)

I created a league, created 4 league meet events.   I then created a new event, a 'League Tournament'. I imported the data from the 4 league meet events. The combined rankings look about right. Generate a match schedule, can run all the way to Alliance selection. 

Alliance selection is using the rankings from only the League Tournament qualification rounds and is ignoring the combined rankings.  Leagues use the combined scores for the whole season. 

This is a showstopper! 

I have included the .db file here

**Comment by tvbarnette999** [comment]
This has been addressed and will be correct in the next release, along with a few other League Tournament related rankings fixes.

**Comment by kevinwross** [comment]
Thanks for the quick response. Our first league events are on November 3rd. Is there a release drop before then?

**Comment by tvbarnette999** [comment]
Yes, the next release should be available about midweek.

**Comment by adwiii** [comment]
This has been addressed in [v0.5.0](https://github.com/FIRST-Tech-Challenge/scorekeeper/releases/tag/v0.5.0). Please use v0.5.0 or later for League Tournaments.
