### ISSUE TITLE
School Name column shows sponsors before School Name

### ISSUE THREAD

**Issue by Tomrish** [FIRST-Tech-Challenge/scorekeeper#132]
I am aware that according to the FIRST online registration portal it does say that on the FIRST team and event search page sponsors will be listed before the school names in the order that they are added, and as far as I can see the database that contains team information for the scoring software is comprised of data straight from the team search, but in the scoring software's current configuration when it is listing the sponsors before the school names it just doesn't seem right, as for example my own team (Team 9219 from North Kingstown Senior High School, _sponsored by Dave's Fresh Marketplace_) shows up as Team 9219 from Dave's Fresh Marketplace.
[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2525831/db.zip)
![screenshot](https://user-images.githubusercontent.com/33290191/47659548-93a75200-db6b-11e8-9757-538333b2520d.jpg)

**Comment by adwiii** [comment]
The scoring system has no way to know what is a school and what is a sponsor - as you noted, they are all pulled together in the registration portal. I understand that the column header says `School`, when it should more accurately say something like `Affiliation` to reflect that the same field contains sponsor and school information. I have logged this change to be made.

**Comment by Tomrish** [comment]
Is there any way it could also be listed in the documentation for event organizers that sponsors will list before the school name if a team has inputted sponsors through FIRST? That way those people know for both electronic displays and emcee duties that a specific team is not FROM a grocery store, for example, rather they are SPONSORED BY a grocery store but they are really from school [xyz].

**Comment by adwiii** [comment]
In version 0.5.0 it now says `Affiliation` instead of `School`. I don't think the documentation needs to be updated since the label is now not claiming something that is incorrect.
