### ISSUE TITLE
Team Information Database NOT up to date

### ISSUE THREAD

**Issue by Tomrish** [FIRST-Tech-Challenge/scorekeeper#133]
Going along with my last issue, the team information database that is used when importing teams into an event does not seem up to date. One of the teams at my school had their name changed on the FIRST online registration portal three weeks ago, long before the latest release of the match software, and their name is still showing as the name they had before the name change. Included below are some screenshots to verify. 

[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2525841/db.zip)
![firstonlinescreenshot](https://user-images.githubusercontent.com/33290191/47659928-5c857080-db6c-11e8-8df9-ee2acf080cbb.jpg)
![matchsoftwarescreenshot](https://user-images.githubusercontent.com/33290191/47659929-5c857080-db6c-11e8-92a2-9dfb11c20ae6.jpg)

**Comment by adwiii** [comment]
We try to update the database that ships with the scoring software every release, but unfortunately did not update it before the 0.4.3 release - 0.4.3 contains the same database as 0.4.2. However, the database should have been current about 2 weeks ago when v0.4.2 was released. If the update was made before 0.4.2, but the data does not match, then this is an issue. I will work to investigate what could have caused this.

**Comment by jvens** [comment]
Would it be possible to add a feature in the score system that would allow an event to sync with the data in the cloud database manually to get the latest information.  It could be done after entering the team numbers so you only update the relevant teams instead of all of them in the system to help cut down on server load if that is a concern.

**Comment by adwiii** [comment]
I am not sure why this was not closed earlier. This is not new with v1.0.0, but the scoring system can now download an updated team list. This does not update teams that have already been added to an event. We will continue to include the most up-to-date team list with each release.
From the Manage Server page, there is a button to perform a data download to update the local team list. 
![image](https://user-images.githubusercontent.com/9453262/64711977-7da33700-d488-11e9-9ba8-66e31f5e93ec.png)
