### ISSUE TITLE
Expansion Request: Under "Video Switch" on the match control screen, add a button to show the pit display/scoreboard on the field/audience displays

### ISSUE THREAD

**Issue by Tomrish** [FIRST-Tech-Challenge/scorekeeper#134]
As the title says, I would like to see a button under "Video Switch" on the match control screen that shows the pit display/scoreboard on the field/audience displays. We run a scrimmage each December where we have two projectors projecting the audience display onto screens on both sides of the field, at this event, teams get 45 minutes for lunch and during that time we would like to put the scoreboard on the large projector screen to avoid everybody trampling each other to get photos of the pit TV. We were able to do this last year with the relic recovery software but it has been missing since the software change.
[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2525949/db.zip)
![screenshot 30](https://user-images.githubusercontent.com/33290191/47661370-4a590180-db6f-11e8-98e2-9594e0189a0f.png)

**Comment by adwiii** [comment]
As of 0.7.6, all displays can now show the rankings by using the "Show Ranks & Results" button on the Video Switch tab on the Match Control Page.

![image](https://user-images.githubusercontent.com/9453262/52743644-75ddeb80-2fa8-11e9-8de1-29584232ec1e.png)
