### ISSUE TITLE
match results disappeared after alliance selection of league meet

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#137]
At our league meets we go ahead select alliances and play elimination matches even though they don't count in the league rankings.  The teams like the extra experience they get with this.  I noticed that after doing alliance selection that the pit display wasn't showing the results of the qualification matches.

**Comment by adwiii** [comment]
I have reproduced this issue - it appears to be purely a display problem. Rebooting the server should work as a temporary fix, and we will work to have this fixed by next week.

**Comment by adwiii** [comment]
This has been resolved in 0.5.2
