### ISSUE TITLE
Option to not display match timer on audience display

### ISSUE THREAD

**Issue by Crossle86** [FIRST-Tech-Challenge/scorekeeper#138]
Forcing the display of the match counter on audience display is somewhat redundant with the field displays for small events. We'd rather display results and ranking on audience display for our league events.

**Comment by adwiii** [comment]
If you would like, I would recommend setting up a Pit Display on whatever screen you would normally display your Audience Display on - it contains a scrolling list of match results and rankings. I believe this would achieve the desired result. Note, the Pit Display is an entirely separate webpage from the other displays.

**Comment by Crossle86** [comment]
I am going to do that to work around what we see as a problem. We normally have an audience display between our fields where we show match preview, results and rankings. This is what the audience wants to see and is easy for them as it is centrally located in front of the fields and seating. With a separate display they will have to look elsewhere (and we will have to find a place) to see the rankings from thier seats. Rankings are part of what the audience wants to see and so should be on the audience display.

Richard Corn 
Software Devices LLC / RAC Consulting 
P.O. Box 12299 
Olympia, WA. 98508 
360.357.9572   fax 360.352.8453 
rac@swdevs.com     www.swdevs.com    
  ----- Original Message -----

**Comment by adwiii** [comment]
Closing as #280 covers this.
