### ISSUE TITLE
API Should Support Current Match

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#139]
One of the tools I would like to build around the API requires knowing the current match (an announcer tablet application).  Could this be surfaced by the API?

**Comment by adwiii** [comment]
Do you mean which match is in progress or what match is next?

**Comment by maths22** [comment]
I'm thinking whichever match is displayed on the audience display, but next
could also be nice.

**Comment by adwiii** [comment]
With v1.0.0, the system now has a websocket that informs you whenever a match is started, aborted, or committed. In addition, there is an api route that displays all active matches. See the [swagger documentation](https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation) for more information.
