### ISSUE TITLE
Pit display overflow

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#140]
The match results on the pit display are longer than the rankings and reach all the way to the bottom of the outline (at which point they are clipped).  They should be the same height.

(Amusingly, this is a bug that existed in the old scoring system too.)

**Comment by adwiii** [comment]
Can you post a screenshot of this with your description for reference?

**Comment by maths22** [comment]
I observed this on the screen of a host for a call, so I can't post an exact screenshot.  That said, my own screenshot looks worse (see how the tables have no bottom padding between the table and the white line):

![image](https://user-images.githubusercontent.com/3067361/47761158-5e8f2280-dc85-11e8-9116-802349326e88.png)

**Comment by adwiii** [comment]
This is not so much a bug as expected behavior. The list is longer than what could show on the screen, so it shows as much as it can and then scrolls over time. What would you suggest it show instead? Is the concern that there is a half of a table cell at the bottom? In my mind this serves as an indicator that there is more to be shown that can't fit and thus it will scroll to show.

**Comment by maths22** [comment]
It's that half cell, exactly.  In the old system, it tried to avoid that, but there were some calculation errors that lead to the behavior shown here in certain cases (that at least last season were actually pretty common).  IMO it looks bad, but I'll think about if there is a clear way to indicate that that also looks good.

**Comment by Techno11** [comment]
I always imagined a Smooth, infinately scrolling display, but I can see that being difficult to read

**Comment by rickliner** [comment]
ftcscores.com has implemented a much nicer Pit Display screen with additional information and smooth scrolling that's much easier to read. Would be great to see it incorporated here.

**Comment by adwiii** [comment]
As of 0.7.5, the pit display scrolls smoothly. (On refresh of data it loses its place in the scroll, we will work on this for a future release)
