### ISSUE TITLE
Timer Images

### ISSUE THREAD

**Issue by mihir-chauhan** [FIRST-Tech-Challenge/scorekeeper#145]
Hi scorekeeper developers,
I was using the scorekeeper website and made an event and opened the match control page and the score/timer page and when I ran a match, the time was shown by just 3 boxes that are changing shades of color instead of the time left of the match. I am not sure if the images didn't load or if the file didn't download properly

**Comment by adwiii** [comment]
What browser are you using? I know that this issue occurs when using Edge.

**Comment by bsimmons99** [comment]
I've had this issue using Edge.

**Comment by mihir-chauhan** [comment]
Oh, I was actually using edge. Maybe I should try Chrome.
Thanks!!

**Comment by adwiii** [comment]
In general we test everything in Chrome. Some pages will work in other browsers, but there are several pages that are known to not work in Edge or Firefox.

**Comment by mihir-chauhan** [comment]
Thank you for your help, adwii, it works now!
