### ISSUE TITLE
I just downloaded 0.5.1 but when it runs it displays the version as 0.4.3

### ISSUE THREAD

**Issue by Crossle86** [FIRST-Tech-Challenge/scorekeeper#146]

**Comment by adwiii** [comment]
Are you sure you do not have a copy of v0.4.3 still running on the system? Are you running on a Mac perchance?

**Comment by Crossle86** [comment]
So it fixed itself. Assume there was a copy of 4.3 but I closed all cmd windows so no server should  have been running and if 4.3 was running, 5.1 should have been unable to bind to port  80. Seems to be working, moving on.

**Comment by adwiii** [comment]
If it detects another copy of the software running it refuses to create another copy and will open the browser to point to whatever copy it found, even if that is an old copy. In the future we will add something that tells you if that version is known to be old.
