### ISSUE TITLE
Some permissions require "Event Admin"

### ISSUE THREAD

**Issue by rezafouladian** [FIRST-Tech-Challenge/scorekeeper#148]
It seems that some of the permissions do not work without the "Event Admin" permission. For example, I want an account for running the scoring/timing displays. I assign the "Display" permission, but that account still can't access the scoring/timing displays. The only permission setting that gives access is "Event Admin", which makes it pointless to even have the other permission because Event Admin gives access to everything. This is also very insecure, as someone could come over to the display and have full control over the event.

**Comment by adwiii** [comment]
As of 0.7.0, all display accounts use the "Display" permission, and can be accessed using any of the default accounts with display in the name, or overlay. The different types of displays (Field, Audience, Overlay) do not have separate permissions, and any account can access any type - the separate accounts are there to give the user the option if it helps with planning or organizing the devices.
