### ISSUE TITLE
Enhancement: check in screen

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#151]
It would be very useful to have a check in screen for events. After the team are selected for the event, a set of columns by each with present, check in, robot inspection, and field inspection. It would be great if each cell could be selected as blank, green (done), yellow (working), red (issues). This would help us to expedite the process. Thank you for a fine scoring system!

**Comment by Nate2019** [comment]
I will echo this! I have seen that there is a inspector role that can be created so I assume you could make like 4 inspector logins who are able to constantly edit this. It would also be nice to have a display when using the inspection check list

**Comment by tvbarnette999** [comment]
Added in v0.7.1.
