### ISSUE TITLE
(Bug) Qualifacation Matches Return "Finished:false" when Elim Starts

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#153]
Once we did alliance selections and started to run elim matches, all of the Qualifacation matches in the API returned their "finished" variable as false

**Comment by adwiii** [comment]
I believe this is the same issue as #137. We are looking into it. Note, #137 appears to be corrected upon server reboot.

**Comment by Techno11** [comment]
@cmacfarl Howell was our "Pilot" per say, I am here developing and testing our DataSync as the event goes on. https://theorangealliance.org/events/1819-FIM-Q3  . We WERE pushing data semi-live, but there are quite a few problems I've been having (with my code, not your API) in trying to upload elims.  @adwiii And Let me just convince my FTA to restart the server. (sorry for being so rude)  Not really an option, though.

**Comment by adwiii** [comment]
I was not suggesting you do it at an event, I just was clarifying that the data is not lost and everything is fine for recovery later, sorry for the difficulty.

**Comment by adwiii** [comment]
This has been resolved in 0.5.2
