### ISSUE TITLE
Can't create event with 0.5.1

### ISSUE THREAD

**Issue by khoyt5** [FIRST-Tech-Challenge/scorekeeper#154]
I downloaded 0.5.1 and I can no longer create an event. This is the error log...
I'm on Windows 10 and using Chrome. I had no issues with 0.4. 0.5.1 doesn't look right. It doesn't have the FTC graphic.

[main] INFO org.usfirst.ftc.server.SQLiteServerDAO - Creating server.db
[main] INFO org.usfirst.ftc.server.Server - External Static Files
[main] INFO spark.staticfiles.StaticFilesConfiguration - External StaticResourceHandler configured with folder = ../lib/public
[main] WARN spark.staticfiles.StaticFilesFolder - Registering external static files folder [../lib/public] as [C:/Users/bk/Documents/FTC/FIRST-Tech-Challenge-Live-0.5.1/bin/../lib/public].
[main] INFO org.usfirst.ftc.server.Server - Attempting to start server on port 80
[Thread-0] INFO org.eclipse.jetty.util.log - Logging initialized @2985ms
[Thread-0] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
[Thread-0] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:80
[Thread-0] INFO org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
[Thread-0] ERROR org.usfirst.ftc.server.Server - Could not bind to port 80
[main] INFO org.usfirst.ftc.server.Server - Attempting to start server on port 8080
[Thread-10] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >>> Spark shutting down ...
[Thread-10] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@2ccfec1b{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
[Thread-10] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - done
[Thread-11] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
[Thread-11] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:8080
[Thread-11] INFO org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
[Thread-11] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@6b7c5093{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[Thread-11] INFO org.eclipse.jetty.server.Server - Started @5660ms
[main] INFO org.usfirst.ftc.server.Server - Server started on port 8080
[main] INFO org.usfirst.ftc.server.Server - Launching browser for OS: Windows 10
Nov 03, 2018 6:39:14 PM org.apache.velocity log
SEVERE: Left side ($disallowedTypes.size()) of '>' operation has null value at /velocity/event/createEvent.vm[line 197, column 46]

**Comment by cmacfarl** [comment]
It looks like you already have a server running on that computer. The
second server should run on an alternate port but in this case that doesn't
appear to be working.

If you reboot the computer and try again do you still have the problem?

**Comment by khoyt5** [comment]
Thank you - Restarting works.
