### ISSUE TITLE
Enhancement: red/blue vs blue/red

### ISSUE THREAD

**Issue by jlaipunahou** [FIRST-Tech-Challenge/scorekeeper#157]
I don't know if there is chatter in FRC world about this, but after years of scorekeeping for FTC, I notice that often red is listed first, then blue, i.e. left to right. But on the display for match and the display for results on the screen, it is blue then red.

This forces me to double check every time, but if a convention could be consistent, that would be much appreciated.

![screen shot 2018-11-03 at 9 22 02 pm](https://user-images.githubusercontent.com/14628949/47961415-a1673800-dfae-11e8-95d5-2bc857e99b6a.png)
![screen shot 2018-11-03 at 9 22 37 pm](https://user-images.githubusercontent.com/14628949/47961416-a330fb80-dfae-11e8-988d-6b10b6c68453.png)

**Comment by bsimmons99** [comment]
My understanding is that the scoring computer is usually located behind and facing the field, therefore that screen has red on the left as from their perspective red is on the left. From the audience's perspective, red will be on the right, hence the audience display shows red on the right.
Someone correct me if I'm wrong.

**Comment by tvbarnette999** [comment]
Yep, that's our reasoning behind it. FRC does the same thing, with their scorekeeper's screen flipped to match their perspective. And FRC & FTC fields are done opposite from each other😃. Long term, we can look into adding the ability to flip the two alliances for scenarios where the scoring table (or display) is not directly behind the fields, and thus the flipped perspective is counter-productive.

**Comment by jlaipunahou** [comment]
Thank you for the clarification/explanation. This makes sense.

Historically, we've never had the scorekeeper laptop screen facing the main projection screen (as you describe and as I see at our FRC event). It's always been some other orientation.

As you know from my other tickets, this issue is not a priority, especially since I understand there's a reasoning behind it :)
