### ISSUE TITLE
updating latest version

### ISSUE THREAD

**Issue by jlaipunahou** [FIRST-Tech-Challenge/scorekeeper#158]
I ran 0.4.3 at last week's League Event. In preparing for today's, I downloaded 0.5.1

I deleted 0.4.3 and unzipped 0.5.1

After launching in Chrome, it was still stuck on 0.4.3. I had to restart computer for it to recognize 0.5.1

This may be a smaller issue, but still reporting it.

Running MacOS 10.12.6

**Comment by adwiii** [comment]
This means that 0.4.3 was still running on the system. In Mac, closing the terminal window *does not* shut down the server - you must kill the process then close the terminal. We are looking into ways to solve this.

**Comment by jlaipunahou** [comment]
I was thinking that was the case too. For anyone watching this thread, this is how you do it, and you may need a sudo in front of the kill command

https://www.hongkiat.com/blog/force-quit-mac-app/

Thanks!
