### ISSUE TITLE
match display shows previous generation of match schedule

### ISSUE THREAD

**Issue by jlaipunahou** [FIRST-Tech-Challenge/scorekeeper#159]
Running today's League Event, I got 0.5.1 up and running

I did an initial generation of matches based on 12 teams, just to make sure things were working. It turns out 1 team did not show, so I ran it again with 11 teams.

We printed out the schedule for all teams after inspections finished. The Match Control page reflected these properly.

To our horror, 10 minutes before matches started, the Match Display showed the **wrong** Q1, based off the first generation of matches. In fact, it was very clear since the team that had not shown up happened to be assigned to Q1 so it was clear it was off.

We couldn't figure out how to fix it, so we told everyone to ignore the team numbers on match display and just focus on the timer.

By Q4 today, it worked again!

Unfortunately, I didn't save the log file (I will do so from now on)

**Comment by adwiii** [comment]
We have made several fixes for re-generating match schedules. However, if you have a match control page set up and re-generate the match schedule, then you must refresh the page for this to take effect. We will add the functionality so it updates itself, but hopefully the manual refresh is not an undue burden given the sparse number of times this should occur.

**Comment by adwiii** [comment]
As of v1.0.0, the Match Control page now updates when a new schedule is generated.
