### ISSUE TITLE
Match Control – Score Edit tab and Active Match screen - missing Cargo Hold and Depot Minerals entry fields for Autonomous.

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#16]
Match Control – Score Edit tab and Active Match screen – There is no place to enter Cargo Hold and Depot Minerals for Autonomous period. The Scoretracker screens have this function.

**Comment by adwiii** [comment]
The minerals are not scored in the autonomous period - anything that the scoretracker enters in autonomous shows up in driver-controlled as well. Then, on the Match Control page, it only appears in the driver-controlled area because that is where it scores.
