### ISSUE TITLE
Imported League Meet and Get Server Error occurs.

### ISSUE THREAD

**Issue by khoyt5** [FIRST-Tech-Challenge/scorekeeper#161]
I received the .db file from a league event. After I import and try to click on the event, it shows 

"It appears that a Server error occurred. Please contact your FTA.

Error 500 

Importing their first event results in no errors and the event data can be looked at. I imported meet 1 first and then meet 2.

The scoring software used to generate the db file was 0.4.0. I am reading them in with 0.5.1

[main] INFO org.usfirst.ftc.server.SQLiteServerDAO - Creating server.db
[main] INFO org.usfirst.ftc.server.Server - External Static Files
[main] INFO spark.staticfiles.StaticFilesConfiguration - External StaticResourceHandler configured with folder = ../lib/public
[main] WARN spark.staticfiles.StaticFilesFolder - Registering external static files folder [../lib/public] as [C:/Users/bk/Documents/FTC/2018-2019 Season/FIRST-Tech-Challenge-Live-NEFTC/bin/../lib/public].
[main] INFO org.usfirst.ftc.server.Server - Attempting to start server on port 80
[Thread-0] INFO org.eclipse.jetty.util.log - Logging initialized @1478ms
[Thread-0] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
[Thread-0] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:80
[Thread-0] INFO org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
[Thread-0] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@40db33ed{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
[Thread-0] INFO org.eclipse.jetty.server.Server - Started @1637ms
[main] INFO org.usfirst.ftc.server.Server - Server started on port 80
[main] INFO org.usfirst.ftc.server.Server - Launching browser for OS: Windows 10
Imported very old db! Resolve issues outside DAO.
Error loading commit history
Error loading elims commit history
db for neflmeet1 updated from 2019_0 to 2019_1
Imported very old db! Resolve issues outside DAO.
Error loading commit history
Error loading elims commit history
db for neflmeet2_Final updated from 2019_0 to 2019_1

**Comment by adwiii** [comment]
Can you please upload the db for the meet that is causing the error so that I can try to reproduce the error locally?

**Comment by khoyt5** [comment]
[neflmeet2_Final.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2550799/neflmeet2_Final.zip)

**Comment by adwiii** [comment]
The issue here is that the file is capitalized. When you are creating an event using the online form, it prevents you from creating a capitalized event code; however, apparently we did not add that safeguard for importing. If you rename the file to have a lowercase f (eg `neflmeet2_final.db`). We will add safeguards against importing files with uppercase names - thanks for catching this edge case for us.

**Comment by adwiii** [comment]
We have added safeguards in 0.5.2 to prevent this scenario from happening in the future.
