### ISSUE TITLE
Pit display doesn't update with new matches

### ISSUE THREAD

**Issue by tcflanag** [FIRST-Tech-Challenge/scorekeeper#162]
When running a league event, "Pit Display (This Event Only)" doesn't automatically update when new matches are scored.  The other versions of the pit display "Combined Pit Display" and "<League Name> Pit Display" both update to reflect the new match data (albeit not for a minute or two). Hitting refresh in the browser does update the display as expected.

![image](https://user-images.githubusercontent.com/24835710/47980635-80214d00-e07d-11e8-8581-e70de0650269.png)

[test5.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2547096/test5.zip)

Running:
Version 0.5.1
Chrome on Win 7

**Comment by adwiii** [comment]
I have located the issue and this should be fixed by next release.

**Comment by jlaipunahou** [comment]
> I have located the issue and this should be fixed by next release.

@adwiii I know it's hard to pinpoint, but around when do you expect the next release? This way, I know when to plan to advise my colleagues who will scorekeep at our event this weekend. Thank you!

**Comment by adwiii** [comment]
In general, we try to have the builds up on Wednesday. However, the past two releases have ended up being on Thursday. The next release should be either this coming Wednesday or Thursday, 11/7 or 11/8.

**Comment by adwiii** [comment]
This has been resolved in 0.5.2.

Also, @jlaipunahou we are adopting an official release schedule of 12pm Eastern on Thursays. This week we were an hour late. More details can be found in the 0.5.2 release notes.
