### ISSUE TITLE
Enhancement: Show elapsed time between matches on match screen

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#165]
It would be useful to understand how long it has been since the end of the prior match. Displaying this on the match screen when a match is not in progress would help to understand the time transition. Also, if there is a field break required (5 minutes for a team with back to back matches), a note of that on the screen with the time (maybe a yellow time color until it reaches 5 minutes) would be useful.

**Comment by adwiii** [comment]
This is not exactly what is requested here, but as of 0.7.1, the Match Control Page now shows the relative timing of the matches to the schedule. If you set up the schedule using the times you intend to follow, then this can tell you how far ahead or  behind you are. In the lower left of the page:
![image](https://user-images.githubusercontent.com/9453262/50659306-357f5c80-0f6a-11e9-8178-0c2110e2dfe2.png)
This will update at the start of the match.
