### ISSUE TITLE
Enhancement: Match delay on preview screen

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#166]
When the match preview is displayed on the audience display, it would be useful to display a countdown if the match has a 5 minute delay planned. Since the delay officially starts once the prior match has been cleared by the referees (final scoring noted, etc.), we may need to add a way to start that countdown.

**Comment by tvbarnette999** [comment]
In the meantime, you can use the "Field Timeout" button under settings on match control to start a 5 minute timer. It does not show on the Preview Screen, it has its own screen. The scorekeeper will need to manually start it at the appropriate time. It will immediately show on Field Displays, but not Audience Displays. To show it on an Audience Display, click "Show Timeout". You can toggle view on the AD to something else, like Results or Preview, and then revert back to the timeout by clicking "Show Timeout" again. If you do this during Quals, it still shows the Alliance Timeout Window at the bottom, just tell everyone to ignore that 😃.

**Comment by maths22** [comment]
Field timeouts now show on all pages in the scoring system, so if one is started it will be shown on the preview screen
