### ISSUE TITLE
Enhancement: team match history

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#167]
As we get deep into the league season, we have teams asking about details on the history coming into new events. It would be useful to be able to print a team event history. Ideally, this would include the match performance from the current day, the (up to 10) matches being used for combined ranking from prior events, and then any additional matches they have played that are not being included in their combined ranking.  I suggest these all be ordered best to worst (RP first, then TBP). A bonus would be if we could include the details on the breakdown of the points as shown on the summary screen (autonomous, tele-op, end game, and penalties). This would really help our teams to understand the details of how their current standing was derived (and save the scorekeepers from answering a lot of questions from the teams). Thank you.

**Comment by cmacfarl** [comment]
Not a native solution, but the scoring system has integration with both ftcscores.com and theorangealliance.org.  If you use one of their clients at an event to push data to the cloud then you will have match history.  If you don't have internet access at an event, I know that one (TOA) or both of those sites wants your databases after the fact.

**Comment by Techno11** [comment]
The Orange Alliance (theorangealliance.org) is recognised by FIRST as the official event history database. If you have archival data, you can email it to data@theorangealliance.org and it will go up onto our site.  TOA also have a public API for teams to pull from for scouting.

**Comment by vwestin** [comment]
Thanks again for this great scoring system. We are paperless and things are working really well for our events.

Since we want to have control over getting the data to the teams, I built the attached Python script to read the meet database files (not the exports, the actual meet files) and generate a per-team HTML file of their history (see attached). The one thing I did not find in the software docs is the meaning of the values saved in the sample field. Any chance you can point me to a definition for it?

[TeamHist-HTML.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2568911/TeamHist-HTML.zip)

We have also used this to verify that all of our imports of past matches are correct, as this gives cumulative data for each team that we can compare against a new meet we are creating.

**Comment by cmacfarl** [comment]
We really do want to discourage people from scraping the database for a whole host reasons, but first and foremost is we want to be able to change it at will and not have to worry about breaking N clients and/or fielding questions from N clients about why it broke and how to fix it.

We implemented a public API specifically to provide a vehicle for interested parties to gather the data they need.  There are publicly oriented clients that are eager to push event data to cloud services.  See ftcscores and theorangealliance.

If you can describe what you need from the public API that doesn't exist, we can put that on the list of things to do.  In the meantime, please be patient and understand that the scorekeeping team can't answer questions about database schema.

**Comment by cmacfarl** [comment]
https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation

**Comment by vwestin** [comment]
Sorry I missed it.

**Comment by adwiii** [comment]
We are working on implementing team match history natively in the scoring system. Reopening until released.

**Comment by adwiii** [comment]
Team history view has been added in 0.5.3. From the league/combined rankings, you can select the history for each team and see which matches are contributing and their RP/TBP/Score.
