### ISSUE TITLE
Team alliance colors flipped on overlay

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#169]
I was testing audience display with chroma key overlay this weekend and noticed that the team numbers were associated with the wrong colors on the display.  As you can see below, on the server the red alliance was 14560 and 11391 and the blue alliance was 3609 and 6103.  This matched the field timer display and the match list, and everything else.  The audience display with chroma overlay had the red aliance being 3609 and 6103 and the blue aliance being 14560 and 11391.  We were running version 0.5.1.  I can upload the db files if that would be helpful.

![server](https://user-images.githubusercontent.com/7074504/48022464-c966b080-e100-11e8-9564-2c0298b20b96.jpg)
![display](https://user-images.githubusercontent.com/7074504/48022463-c8ce1a00-e100-11e8-8c1b-174a81743e29.jpg)

**Comment by jvens** [comment]
Sorry, in my attempts to recreate this and another issue we had this weekend I stumbled on the cause.  Apparently on some GPUs the Xcomposite capture source in OBS studio flips the red and blue channels.  There is an option in OBS to swap the red and blue channels which resolves this problem.  I should have caught that earlier.

See this thread for more info: https://obsproject.com/mantis/view.php?id=65

**Comment by adwiii** [comment]
Well I must say I am glad you came up with this because I would have never even thought of this. Good to know...
