### ISSUE TITLE
Audience Display: Cargo Hold and Depot Mineral points scored during autonomous are reflected in the Driver-Controlled period score, not Autonomous mode period.

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#17]
Audience Display: Cargo Hold and Depot Mineral points scored during autonomous are reflected in the Driver-Controlled period score, not Autonomous mode period.

**Comment by adwiii** [comment]
This is intentional - they do not score during autonomous.
