### ISSUE TITLE
Default Chroma key on display overlay does not work with borders

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#170]
The default green overlay that is used in the overlay mode does not work with the cyan borders shown during "Show Preview" and "Show Random".  Also, the strips in the background become semi-transparent as well.

![image](https://user-images.githubusercontent.com/7074504/48023877-a211e280-e104-11e8-8810-4b2817439d2d.png)

**Comment by adwiii** [comment]
Is this issue a suggestion to change the default color to something that works better? The user does have the ability to change this color in the settings of the display, but I understand the user likely will just accept the default.

Do you have a suggested alternate color? I am not at all familiar with this, but I know some systems use magenta by default.

**Comment by jvens** [comment]
There are two possible options.  One is to change the default key to something different although that is unlikely since any color that has red or blue in it is going to start keying out the red and blue alliance colors.  Magenta for example is 50% red and 50% blue so all of the red and blue would start to become transparent transparent.  I did experiment with a few different key colors and all of them were worse than using straight green.

To me the better option is to change the colors of the borders so that they contain less green.  The current color appears to be #9cf7e9 which has a lot of green (#00ff00) in it.  Choosing a color with less green would help prevent the border color from getting filtered out.  It doesn't have to be completely void of green either.  The background color of the rectangles is #375752 and it works just fine with a green chroma key.

**Comment by tvbarnette999** [comment]
Can you reduce your tolerance? The chroma colors are guaranteed to be exactly the set value, unlike a normal greenscreen operation. FRC uses FF00FF (magenta), which is what we will probably change the default to. I adjusted my tolerances with magenta and it works pretty well:
![chroma_1](https://user-images.githubusercontent.com/13516182/48026959-8531db00-e115-11e8-9d08-8e7977775937.PNG)
![chroma_2](https://user-images.githubusercontent.com/13516182/48026960-8531db00-e115-11e8-80aa-70f86a7aabf4.PNG)

This software required me to select the chroma color from the image for each one, hence the weird square below the preview that I manually made magenta. The images were also not the same size, hence the chroma'd border. The problem making it green is the timer bar or the overlay is green (to match FRC).

**Comment by jvens** [comment]
In OBS studio I reduced the "Similarity" from the default value of 400 to 200 and that does seem to resolve this issue.  The green timer also seems to look fine with this setting as well.

This might be something worth mentioning in the manual, although it is certainly out of scope for what most scorekeepers will need to know for most events.
