### ISSUE TITLE
Enhancement: Show if depot is claimed.

### ISSUE THREAD

**Issue by djpirocchi** [FIRST-Tech-Challenge/scorekeeper#171]
Have to admit we didn't actually test depot claimed to see if it is already there.

Would be great if the timer screen at the field not only showed the scores but, also if an alliance's depot is claimed.  This way the coaches at the field can clearly see and know if they are claimed.

**Comment by adwiii** [comment]
When using the Audience Display, you can tell if the depot is claimed by both flags being raised, but there is no additional indicator that this means claimed:

![image](https://user-images.githubusercontent.com/9453262/48025756-4baba080-e112-11e8-9d78-ce948776da8d.png)

It is on our list of things to do to add live scoring indicators for specific scoring achievements to the field display and overlay.

**Comment by adwiii** [comment]
Closing as #213 is open to address the remaining issue of adding scores to the field display.
