### ISSUE TITLE
Match Preview unavailabe

### ISSUE THREAD

**Issue by Crossle86** [FIRST-Tech-Challenge/scorekeeper#173]
Before our first match, we had the sponsor listing up on the audience display. When we started the first match we clicked load next match and the match control reflected the first match. However, the match preview button would not display the preview. We had to complete the first match with sponsor list on audience display and after the first match completed, the match preview button worked correctly. 051.

**Comment by adwiii** [comment]
I have been unable to reproduce this issue by showing the sponsor page and then pressing load next match and show preview. Can you upload your DB and list what browsers were running the Match Control and Display pages? Is there any other detail you can give about what was happening at the time? What was the next thing the display showed? The results for match 1? The preview for match 2?

**Comment by Crossle86** [comment]
Browsers chrome. Nothing happening except sponsor view. Loaded first match clicked match preview, no go. Sponsor view remained. Started and completed first match. Loaded second match clicked preview and then it worked. Entered scores for first match while second match running.
[lovelace110318.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2555867/lovelace110318.zip)
