### ISSUE TITLE
remove test matches that were not completed

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#175]
We have been using the test matches to test our display setups and for training scoring refs.  We don't let them run to completion and abort after checking things are working correctly.  Is there any way to remove them from the listing of matches on the scoring refs tablets.

**Comment by vwestin** [comment]
You may want to build a test event to use for this purpose. Then do not roll that event up to anything.

**Comment by jkelbick** [comment]
Can we revisit this question? I think it's worth addressing. Scrolling through 10+ test matches is not ideal.

**Comment by tvbarnette999** [comment]
The has been addressed as part of Test Mode in v1.1.0. The matches are never removed, but they do not show up once you leave Test Mode. When you re-enter Test Mode, previous Test Matches will still be there in whatever state they were in. (Unless they were in REVIEW, in which case they are automatically moved to SUBMITTED). The opposite is also true, Quals and Elims matches will not appear while in Test Mode, but will re-appear upon exiting Test Mode.
