### ISSUE TITLE
Clicking Save in the Matchmaker removes T14 breaks

### ISSUE THREAD

**Issue by rezafouladian** [FIRST-Tech-Challenge/scorekeeper#176]
Clicking the "Save" button in the match generator after you run the matchmaker removes the T14 breaks for consecutive matches when you leave the page.

For example:

1. Add 10 teams
2. Run the matchmaker. Several breaks will be added.
3. If you print the match schedule at this point, the breaks are still there.
4. Go back to the match generator and click save
5. Now if you go to print the match schedule, the breaks are gone
6. If you return to the match generator, the breaks are also gone from there as well.

**Comment by adwiii** [comment]
Ah, good catch. This is a mix-up on our part. The save button was intended for use *before* Matchmaker was run. It was meant for the scenario of "I have created all of the match blocks and break blocks, but I am not yet ready to run Matchmaker, so I want to save the data and return later". If you run Matchmaker and it introduces breaks, then the actual schedule is not the same as the one outlined by the blocks due to the &lt;T14&gt; breaks. Hitting save causes the system to remove the &lt;T14&gt; breaks to match the schedule outline. 

I believe the answer is that we need to re-think how the save button works after Matchmaker has been run.

**Comment by emmell620** [comment]
I suggest that the scheduling software not worry about the T14 breaks and let the event organizers and Head Referee deal with it.  In the case of scrimmages you might not care about running back-to-back matches.

**Comment by rezafouladian** [comment]
> I suggest that the scheduling software not worry about the T14 breaks and let the event organizers and Head Referee deal with it. In the case of scrimmages you might not care about running back-to-back matches.

Well the issue we were having was that we had to frequently check manually if teams had consecutive matches and act accordingly, which took extra time and caused us to miss a few that nobody caught. Additionally most teams failed to understand the temporary rule put in place regarding T14 and they didn't really check to see when they had consecutive matches and understand they had the option of a break.

**Comment by tvbarnette999** [comment]
The resolution for this took into account all three things mentioned above.
1. The "Save" and "Run MatchMaker" buttons will both clear the existing match schedule if pressed. When a schedule exists, they are textured with the "Danger" style used elsewhere in the system for deleting data, and require a second confirmation via browser alert popup. If a schedule is already generated and you need to experiment with changing timings, only use the "Preview" button.
2. The &lt;T14&gt; breaks persist properly, show up properly in all the various schedule views and match times, and get wiped/reset on re-save/MM re-run.
3. If your event has fewer than 13 teams, we now give you the option to "minimize &lt;T14&gt; breaks." This will consider the cycle time in the timing for these breaks using the formula 
```<T14> time = max(0, 5:00 - (cycle time - 2:38 ))```, then rounded to the nearest 30 seconds. This means that if you have a cycle time of 8 minutes or more, the break time will be 0, but the break will still appear in the schedule to remind Volunteers and Teams to not cut that cycle short without consent from all Teams involved. If this is left unchecked, every &lt;T14&gt; break will be 5 minutes long. While this does not allow you to remove them, it does mean they will no longer affect the timing on the schedule if the cycle time is sufficient.


![image](https://user-images.githubusercontent.com/13516182/64706447-788dba00-d47f-11e9-915d-9f4e68840e8c.png)

Example schedule with 10 minute cycle times and 0 minute break:
![image](https://user-images.githubusercontent.com/13516182/64707968-d3c0ac00-d481-11e9-999b-d6f930273958.png)
