### ISSUE TITLE
Start sound not synced with display

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#179]
At an event today the match start sound is not synced with the field timer.  When the score keeper starts the match the timer starts counting but the start sound is not heard for several seconds.  Closing and reopening the timer page will fix the problem once, but the problem returns for the next match.  This issue is only with the start match sound, all other sounds are synced correctly.

The event is running a single computer that is the server and also has the field timer display connected directly to it.  The audio is being run directly from the server computer as well.  Here is a video showing the issue (sorry for the poor quality): https://photos.app.goo.gl/bWoPxb8g65JgwkwK9.  Let me know if you need any additional information.

- Server version: 0.5.2
- OS version: Windows 7
- Live scoring: No

**Comment by rgutentag** [comment]
We were having a similar problem today.  We have a 2 field setup with each field having its own display showing the timer and real time score running on separate computers.  Sounds were slow on 2 different setups.  In one case we had the sound coming from the laptop running the audience display and the other case was sound was run from the scoring computer running the matches.  All of the computers are connected wirelessly.

**Comment by jvens** [comment]
I am going to close this issue.  I haven't seen the issue so far this season, and if it does come back the architecture has changed enough that it is unlikely to have the same root cause.
