### ISSUE TITLE
Pits Display does not display properly screen with resolution < 1920x1080

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#18]
Pits Display: On a screen with a resolution less than 1920x1080 the pit display fills the screen correctly initially, but after 3 minutes the screen fills out as if on a 1920x1080 display. Tested with Chrome browser in full screen mode on laptop w/ 1366x768 screen.

**Comment by adwiii** [comment]
Fixed in v0.4.1
