### ISSUE TITLE
What is the difference between data imports?

### ISSUE THREAD

**Issue by Crossle86** [FIRST-Tech-Challenge/scorekeeper#181]
What is the difference (if any) between the "data import" on the server settings page and the "import league data" on the event dashboard manage leagues page? I have a database file that was corrected by FIRSTWA and need to import that data back into my scoring system. Just want to make sure I do it correctly.

**Comment by tvbarnette999** [comment]
The Server Management data import is used when you have an event database file and want to add the associated event to the software. That import makes a copy of the given database, adds the necessary entries into the software, and makes that event viewable and editable within the scoring software. The state of league data is not affected by the Server level import. The primary use case is an event was created on one machine but a different one is used at the event, so the event and its data needs to move to a different computer or newer version of the software. This operation is valid for any event tye

League import is a very different operation. League data is stored for each event, not at the server level. League imports are how you add data from previous league meets so league rankings can be calculated properly. The league import operation pulls the league team lists and league match history out of the provided file and adds it to the event for which you performed the import. For each league meet, and especially for the League Tournament, the archived output from previous league meets must be imported.

For your scenario, the important part is that you use the corrected .db file when you perform the League Import for the next event. If you want to view the full results of the event, then you can import it via server management. If you do that, you still need to perform the League Import for the next meet/Tournament. 

The risk with this process is that league history for an event is added to the archive file when the event is archived. This means that edits performed on an archive file afterwards do *not* make it into the league import for the next meet.  Edits like this would need to be done using the original db file pulled from the db folder, imported on the server page, edited, and _then_ archived. If you upload the database files I can verify if the league history within it matches whatever changes were made (and that the changed were made if you know what they were).

Note: The archive step was intended as the very last step, so league history is essentially "read-only" at that point. Re-archiving from an imported archive does *not* update the league history. I am thinking about changing this operation if post-archive league meet edits need to be a supported commonplace operation.
