### ISSUE TITLE
League meet 2 combined rankings incorrect

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#184]
The combined rankings for meet 2 of this league does not show the correct rankings.  It only shows rankings for the meet 2 instead of both meets.  Both meets shows up in the league page of the event dashboard for meet 2 so I believe that the league was imported in correctly at the start of the event.  I have attached the database files that were exported at the end of meet 1 and meet 2.  Meet 2 used version 0.5.2 of the score system.

[armstrong_meets.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2570414/armstrong_meets.zip)

**Comment by tvbarnette999** [comment]
Apparently it only imported the meet info, but none of the matches from meet 1. I'll try and replicate that this week. Do you recall how many matches were listed for Meet 1 when you imported it into meet 2? Would you happen to have the log files from that run?

Here's the archive ready for import into the next meet:
[armstrong_11_10_meet2_combined.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2570538/armstrong_11_10_meet2_combined.zip)
Here's the combined rankings I see now:
![image](https://user-images.githubusercontent.com/13516182/48326792-369aaa00-e609-11e8-90de-18c83d2a3ed1.png)

**Comment by jvens** [comment]
I do not recall how many matches were listed when we imported the league, but I do recall everything looked as expected.  I have attached all of the log files.

[Log Files.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2573895/Log.Files.zip)

**Comment by jvens** [comment]
I am going to assume whatever happened here was resolved or a one off issue at this point.  Feel free to reopen if this is something the dev team is still investigating 10 months later 😃
