### ISSUE TITLE
Enhancement: add full screen button to displays

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#185]
Add a button to the display pages that will make them full screen without needing to press F11 or go through the menu in chrome.  

It would also be nice to have a similar button on the pages meant to be accessed on the tablets such as the referee pages.  That will gain a considerable amount of vertical screen real estate by removing the URL bar and minimize the amount of scrolling needed while scoring the match.  

This functionality is built into Chrome and other browsers and just requires a simple javascript call.  Here is some info on how to do it: https://www.w3schools.com/howto/howto_js_fullscreen.asp

**Comment by adwiii** [comment]
This was added in a prior release. Note that after hitting the full screen button (if no other settings were changed) you should hit "Cancel" or else it will trigger a refresh which may (in certain browsers) undo the full screen.
