### ISSUE TITLE
only pit display is available

### ISSUE THREAD

**Issue by UschiBC** [FIRST-Tech-Challenge/scorekeeper#186]
Playing with the scoring software on a Mac I logged in as "local", and then in a different window I logged in as eventmanager. I wanted the eventmanager to display the sponsors, or the timer, but the only display available (for "local", too, BTW) was the pit display.
How can I display the other screens?

**Comment by adwiii** [comment]
Can you provide a screenshot of the main landing page for the event?

The event manager does not have permissions to run a display - for now you need to use the eventadmin (side note: we are working on adding a proper role for displays). However, the local user should have access to run a display. On the main landing page for the event there should be a header toward the bottom of the page that says "Event Administration" and the last link under that header is "Scoring/Timing Displays" which will take you to the display. To control the display, you need to open the "Match Control Page" in a separate tab, which is the link immediately above the displays.

**Comment by UschiBC** [comment]
Sorry, I think it was just me.... after reading your note and realizing that the audience and field displays were under "display" and the pit display had a separate link I had everything displaying in separate windows (all logged in as "local"), and it seemed to work fine.  :-)
