### ISSUE TITLE
Bug: Match Result Score is not calculated correctly. Match history shows the correct score.

### ISSUE THREAD

**Issue by christopherwestcott** [FIRST-Tech-Challenge/scorekeeper#187]
Everything went pretty smooth at meet zero, but there was a glitch in one of the matches. The match scores for this match didn't appear on FTCScores, and that was what tipped us off that something was wrong. It was match 3. We took a look at the Scorekeeper's software and noticed the match was not confirmed like all the other matches, though the scorekeeper said they had confirmed it. We were on match 5 of 9 at the time, so we went ahead and simply confirmed it by just clicking the 'confirm' button. All seemed to work, but we didn't realize until after the meet was finished that that particular match was not stored properly, and the rankings would have been completely different because of it. We were not sure if it was not scored properly by the referees, or if it was corrupted after the match took place, or what happened, but it was too late to be corrected because we had no other record of that match. I went back to look at the scores today. There is an identifiable issue in our League V match 3 that was not related to the referee's scoring it incorrectly. I can send screenshots and the *.db file. I went into match results and it shows Red wins 44-10, but if you go to match history, it shows Blue wins 44-135. So the scores do not match. The match history screen reflects the correct score, blue winning.  Also, as a suggestion. If there are 8 teams or less, there is no need to have scrolling on the pit screen. This is great software! Keep up the great work of improving it.

**Comment by tvbarnette999** [comment]
Can you send the db file as a .zip? Github should allow that. Could you also post the logs, which can be found in bin/logs?

**Comment by cmacfarl** [comment]
When I imported the event, the match results match the scoresheet. 

![image](https://user-images.githubusercontent.com/1435639/48462665-ec8f0100-e78d-11e8-8931-8d821954b243.png)


![image](https://user-images.githubusercontent.com/1435639/48462597-a043c100-e78d-11e8-8d23-6a9e7cba9285.png)

**Comment by christopherwestcott** [comment]
That is what the score should say, but the results on our computer shows 44-10, not 44-135, as you can see in the screenshots I sent. The history shows the correct score, but not the actual results. This was also what went out to FTCScore.com <http://ftcscore.com/>, 44-10 that is, when it should have been 44-135. The 135 should be 125 points scored plus a 10 point penalty, but only the penalty was added the final result. Also, if you go FTCScores, they have sub-scores, and it shows nothing was scored. But when you look at the scoresheet in the program, you can see the 125 points visually there in the check screen.

**Comment by cmacfarl** [comment]
The API endpoint that FTCScores is using also shows correct data.

```
curl -s http://localhost/apiv1/2019/events/meet0leaguev11102018/matches/3/
{"finished":true,"field":0,"time":1541876328748,"redScore":44,"blueScore":135,"red":{"landed":0,"claimedDepot":0,"autoParking":10,"mineralSample":0,"depotMinerals":4,"landerSilver":0,"landerGold":0,"latchedLander":0,"endParking":30,"minorPenalties":1,"majorPenalties":0,"auto":10,"teleop":4,"end":30,"penalty":10},"blue":{"landed":60,"claimedDepot":15,"autoParking":0,"mineralSample":0,"depotMinerals":0,"landerSilver":0,"landerGold":0,"latchedLander":50,"endParking":0,"minorPenalties":0,"majorPenalties":0,"auto":75,"teleop":0,"end":50,"penalty":0}}
```

Note that I'm running 0.5.2 and I do know a bunch of stuff was fixed between 0.5.1 and 0.5.2.

**Comment by cmacfarl** [comment]
One of the strange things I see on your screen photo is the match is showing as played on field 1.

**Comment by cmacfarl** [comment]
I do suggest that you update to 0.5.2+ for your next league meet.   Also note that in the LA region where meet0 results don't count you should be running the event as a scrimmage.   I don't think it matters that you ran as a League Meet, but you'll not want to import that database into the system for meet1.

**Comment by christopherwestcott** [comment]
We only had one field. The score results on FTCScores shows 44-10 in the end, and so does the screen on my computer for match 3. Also, the ranking shows that the blue team did not win that match. Both 10006 and 10673 only won 3 matches, but should show they won 4 matches each, since they both won in match 3.

**Comment by tvbarnette999** [comment]
That means that the data made it to the database, but was incorrect or overwritten in RAM, so we need to figure out what makes the in-memory data incorrect. The weird part is that your commit history showed it correct, but the results page did not. @christopherwestcott Do you happen to have or could get a screenshot of the match control page (schedule tab & score edit tab for that match)?

As @cmacfarl  mentioned, 0.5.2 does have additional measures to prevent, detect, and make recovering from this easier. This symptom seems very similar to #160.

**Comment by christopherwestcott** [comment]
![img_2753](https://user-images.githubusercontent.com/20712828/48517492-50134000-e81b-11e8-8b95-d90f43d8b029.jpeg)
![img_2755](https://user-images.githubusercontent.com/20712828/48517493-50abd680-e81b-11e8-9301-384515838bda.jpeg)
Interesting. The match 3 shows no score on the Schedule Tab, and no scored points in the Score Edit tab.

**Comment by christopherwestcott** [comment]
Our next meet is December 1st. I will wait a day before then to download the latest version and will run with that. Thanks for all your work!!

**Comment by adwiii** [comment]
Given the discussion here I am going to close the issue. @christopherwestcott did you have any issues with the event on the 1st?
