### ISSUE TITLE
Pre-Match Setup Cannot Select Latched

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#188]
Cannot mark a robot as latched if robot was marked as No Show then marked as Present. Can hover over and tap buttons however selection does not persist. Once match is started robot cannot be marked as landed.

**Comment by adwiii** [comment]
What browser and device were you using for the score tracker input?

**Comment by bsimmons99** [comment]
Chrome on windows 10 and chrome on a Samsung s7

**Comment by adwiii** [comment]
Thanks for the quick followup. I found the issue and have it fixed. It will be in today's release. In the mean time, if you refresh the initialization page where you submit the No Show and Latch then it will then allow you to properly mark Latched.
