### ISSUE TITLE
Zip folder invalid in 0.5.3

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#190]
The zip folder is invalid and can't be uncompressed in [Release 0.5.3](https://github.com/FIRST-Tech-Challenge/scorekeeper/releases/tag/v0.5.3).  The tar file works just fine.

**Comment by adwiii** [comment]
Thanks for pointing this out. Not sure how, but I guess the zip got corrupted on my end in the upload process. I have reuploaded a fresh zip to the release and confirmed that I can unzip. Let me know if you have any other issues.
