### ISSUE TITLE
Live Scoring Issue - Limited Functionality

### ISSUE THREAD

**Issue by ericwilliamsneu** [FIRST-Tech-Challenge/scorekeeper#194]
We encountered an issue using the live scoring system.

### Narrative
We were able to run the scoring system, set up the network, create the default users, and log into the scoring server from the our Nexus 7 (2013) tablets using the referee logins. Matches loaded (both via Test Match function and our Qualification 1 match from the match schedule) would show up on the tablet. Referees were able to successfully enter and submit the pre-match information and the Autonomous scoring page appeared on both tablets when the match started.

### Issue
On the Autonomous scoring page, referees were able to select Landed and Claimed status for each robot, as well as Minerals, Parked Status, and penalties (both major and minor). However, they were not able to score either side's sample fields or cargo holds. Finally, they were not able to submit scores using the Submit Autonomous button. For the buttons that did not function, a thin blue highlight appeared around the chosen button indicating registration of the "touch" but nothing else happened.

### Details
- Server version: v0.5.3 downloaded from the FIRST Illinois Robotics events site within a week of the event. 
- Server Laptop: Windows 10.0.17134 x64
- Java: Version 8 Update 191
- Scoring Tablet(s): Nexus 7 (2013) running Android 6.0.1
- Scoring Tablet Browser: Google Chrome version 44.0.2403.633

**Comment by ericwilliamsneu** [comment]
Sorry Trey, I didn't realize it had publicly posted the comment before I had a chance to fill in the details.

**Comment by adwiii** [comment]
Sorry for the late follow up. It is odd that they would be able to enter some things but not others. I have not been able to replicate, but will keep this in mind moving forward. Please let me know if you encounter this issue again.

Separately, you say that you downloaded the software from the *FIRST* Illinois Robotics event site. Can you post a link to that here? In general, regions should point to [the official *FIRST* volunteer resources page](https://www.firstinspires.org/node/5146) (which then points you to the GitHub) to ensure that volunteers always have access to the most recent version.

**Comment by ericwilliamsneu** [comment]
Trey,

FYI I test the system using the same tablets and laptop running the scoring program all functions of the referee pages now worked. Unfortunately, I cannot pinpoint what release the fix was incorporated but sometime between mid-December and now a change was made that solved the problem!

Also, in response to your question about FIRST Illinois Robotics hosting their own version of the scorekeeper software, I believe this is done to reduce the event host workload in league meets and to keep track of division data across meets. Scorekeepers are instructed to download the software specific for their event no earlier than a few days before the event to ensure it is the latest build.

Thanks again!
