### ISSUE TITLE
Make pit display font bigger

### ISSUE THREAD

**Issue by tcflanag** [FIRST-Tech-Challenge/scorekeeper#199]
The current pit display has a very small font which is hard to read from a distance.  I bumped the font from 25pt to 75pt and it made it actually readable from the audience at my recent event.
Before:
![mvimg_20181117_132859](https://user-images.githubusercontent.com/24835710/48669749-a1435e00-eabf-11e8-8a81-f949b7ebd94c.jpg)
After:
![mvimg_20181117_134735](https://user-images.githubusercontent.com/24835710/48669752-a43e4e80-eabf-11e8-9c95-6eec3b5b0579.jpg)

**Comment by adwiii** [comment]
We have doubled the pit display font size in 0.7.5
