### ISSUE TITLE
Match Control – Score Edit screen: The End-Game section allows for a robot to be both Partial/In Crater and Latched at the same time. Points are incorrectly awarded for both.

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#20]
Match Control – Score Edit screen: The End-Game section allows for a robot to be both Partial/In Crater and Latched at the same time. Points are incorrectly awarded for both.

**Comment by jkelbick** [comment]
Can I bump this back to the top? Matches have been getting scored incorrectly because this isn't fixed.

**Comment by adwiii** [comment]
See #200
