### ISSUE TITLE
Add team numbers to award scripts

### ISSUE THREAD

**Issue by pmichaud** [FIRST-Tech-Challenge/scorekeeper#202]
This may be related to #56 , but the award script that we print for announcing awards does not include the team numbers for the teams -- only team names are given.

This gets confusing at events where there may be multiple teams with the same team name, not to mention that many teams expect to hear team numbers (it's part of their team identity).

Pm

**Comment by adwiii** [comment]
The team number has been added to the award script. We are aware that on the award entry page when it shows who has won the award it only displays the team name.:
![image](https://user-images.githubusercontent.com/9453262/49953116-66202900-fecb-11e8-88d5-df6bc4ad73dd.png) 

We will add this in a later release.
