### ISSUE TITLE
User role: Judge should be allowed to enter awards

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#205]
If we create a user with a Judge role, they should be allowed to enter the awards without having to be an eventadmin. It is preferable if the Judge Advisor can enter data into the scoring system for the awards while the event may still be going on and from the security of the Judging Room.  Of course, they would have to be on the event network, but that can be arranged.

**Comment by gearsincorg** [comment]
Agreed.  The event I just worked had a secure judging room remote from the action, buton the network.  Letting the Judge Advisor do this as the awards were determined would definitely have streamlined the process, and enabled a good verification step.

**Comment by adwiii** [comment]
As of v1.0.0, the Judge role can now access the awards management page. However, the judge will not be able to present the awards - this must still be done by an event admin. The system now creates default judge awards as part of account generation.
