### ISSUE TITLE
Database Merge from Previous Leagues not working

### ISSUE THREAD

**Issue by ftc2016** [FIRST-Tech-Challenge/scorekeeper#206]
We tried merging our league meet 3 with the previous league meet database but got errors. Sent an email with databases and Error log to ftcscoremaster@gmail.com

**Comment by adwiii** [comment]
Can you please make a zip file and post them to this issue. I do not know who has that email address.

**Comment by ftc2016** [comment]
My bad. The email I sent is ftc scorekeeper@gmail.com. I will try to zip the files and upload it today.

**Comment by ftc2016** [comment]
Attached here with is the Merged files and error logs.
[hammel_meet_3 (1).zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2613267/hammel_meet_3.1.zip)

**Comment by adwiii** [comment]
I believe this has been resolved offline. If not, please reopen the issue.
