### ISSUE TITLE
Audience Display: Background is dark

### ISSUE THREAD

**Issue by pjbrophytpaa** [FIRST-Tech-Challenge/scorekeeper#208]
This is an enhancement request.

Can we have the background of the audience live scoring changed from dark green to something lighter?

The Audience Display looks great on my laptop but the dark green background and black robots make it hard to see things from the projector. I think a light background would be much easier to read. 

I attached a picture of the screen from our last event. I'm going to dim some of the lights next time, but I still think it'll be dark. I was at another event the previous week which had the same issue. 

![img_0632](https://user-images.githubusercontent.com/29557541/48740328-e1aff280-ec0b-11e8-874f-dd426f665db6.JPG)

**Comment by adwiii** [comment]
With SKYSTONE we kept this in mind and tried to make the displays a lot brighter 😁
