### ISSUE TITLE
Add "blank" display to Video Switch

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#209]
In the old system there was an option to display a "blank" display on the audience display which would effectively make the entire display solid green when using overlay mode.  This was useful during opening ceremony and other times that you wanted to show the video feed only and not have any overlay data on it.  This can be controlled in the live streaming software, but it would be nice if it was just added back into the score system.

**Comment by adwiii** [comment]
This has been added in v1.0.0. On the Match Control page under the "Video Switch" tab in the "Other Displays" section there is now a "Show Blank Screen" option that shows the initial splash screen with the *FIRST* RISE and SKYSTONE logos. There is also a "Show Video Only (Overlay)" button that shows just the chroma color on the overlay.
