### ISSUE TITLE
Match Control – Score Edit screen: A team is allowed to check both yellow and red card for a team. The team should have a yellow, a red or none at all.

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#21]
Match Control – Score Edit screen: A team is allowed to check both yellow and red card for a team. The team should have a yellow, a red or none at all.

**Comment by adwiii** [comment]
This is an incorrect understanding of how the software is meant to be used. Game Manual Part 2 describes that if a Team receives two Yellow Cards in once match, the second Yellow Card is escalated to a Red Card, and the Head Referee signals this by displaying to the Team both a Yellow and Red Card. The software supports this feature graphically on the display. If just Yellow Card is selected, then it shows only a Yellow, and same for Red. If both Yellow and Red are selected, then it shows both in the same manner that the Head Referee would. Checking Yellow and Red versus just Red has no different effect on the score or rankings - it is purely for display purposes.
