### ISSUE TITLE
elimination announcer sheets

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#211]
It would be nice to have a button to get only the elimination announcer sheets.  Currently have to find the page they start on and print only those sheets.

**Comment by emmell620** [comment]
Please make this a necessity, not an enhancement. We are somewhat annoyed by this as well.

**Comment by adwiii** [comment]
Enhancement is meant to denote that it is a feature not present in the system to distinguish it from a bug meaning a feature that is present but not working properly. This is not meant to say anything about the priority of the feature.

**Comment by adwiii** [comment]
This has been added in v0.6.1. There is now a checkbox at the top of the Announcer Report page that allows you to show only Elimination Matches. To print only Elimination Matches, select this checkbox and then print the page as normal.
