### ISSUE TITLE
Elimination Match report only shows 2 teams (captain, first selected)

### ISSUE THREAD

**Issue by hightechkids** [FIRST-Tech-Challenge/scorekeeper#215]
Unlike last year's software where the elimination matches showed all 3 alliance teams, this years only shows the captain and first selected. There's no indication that the 2nd selected is part of the alliance in this report.
![2017-18 matchresults](https://user-images.githubusercontent.com/44174505/49246250-0b220880-f3da-11e8-84e9-11f375b1d2de.jpg)
![2018-19 matchresults](https://user-images.githubusercontent.com/44174505/49246251-0b220880-f3da-11e8-9318-ef5ba26c3c5f.jpg)

**Comment by adwiii** [comment]
This has been resolved in v0.6.0
