### ISSUE TITLE
Format Match Schedule

### ISSUE THREAD

**Issue by peirvine** [FIRST-Tech-Challenge/scorekeeper#216]
It would be nice if the schedule, when exported, was formatted so that it will fit on one page (assuming 32 or 36 matches). It would also be nice if the rows were formatted with alternating colors so we can tell the matches apart.

**Comment by adwiii** [comment]
I am wary of the alternating colors because that is a decent amount of ink for printing a lot of schedules. We will look into making the print one page if possible.

**Comment by rebeccawhitaker** [comment]
I agree to the formatting onto one page, if possible. Regarding color, many venues only have access to black/white printers, so if the reports were colored, it wouldn't make a difference. It could potentially make it more confusing as they would be different shades of grey. I would recommend to keeping it b/w.

**Comment by peirvine** [comment]
What I meant by different colors would be different shades of grey (#ccc) - just to provide some visual contrast between the rows.

**Comment by gearsincorg** [comment]
An alternative would be alternating rows of bold & not bold.
eg: Field 1 would be bold in two-field events.

**Comment by pmichaud** [comment]
Having the schedule automatically formatted to one page would be really nice.  That said, we often use the "More settings..." option of Chrome's print dialog box and set the scale to a smaller number to get the match schedule (and other printed items, such as final qualification rankings) to fit on a single page.

Pm

**Comment by gearsincorg** [comment]
I also agree that a one page match schedule would be an excellent addition.  Since these are the MOST printed output of the entire program, being able to optimize paper usage would be appreciated (Not everyone has duplex printing)

I tried adjusting the scale while printing, and although it CAN be made to fit one page, the type becomes unreadably small.  The real need is to just close down the vertical padding on the table rows.

Thanks for considering this feature.

**Comment by rgutentag** [comment]
I also agree that there is too much white space between the match listings.  Could a line be put between the matches and remove what looks like double spacing.  I can also support the bold and not bold alternating lines. A small event with only 24 matches end up on 2 pages unless I resize the print size.  If it gets too small then people complain it is too small to read.

**Comment by adwiii** [comment]
As of v0.7.7 there is now a checkbox that formats the schedule in a condensed form which is useful for printing. Below are the views as if the page was being printed.
Uncondensed:
![image](https://user-images.githubusercontent.com/9453262/53061041-84d20b80-348a-11e9-9750-5fa1a24bea5a.png)
Condensed:
![image](https://user-images.githubusercontent.com/9453262/53061061-94515480-348a-11e9-890d-af894d8395d8.png)
