### ISSUE TITLE
Allow for a non-league meet event type

### ISSUE THREAD

**Issue by kenpugsley** [FIRST-Tech-Challenge/scorekeeper#218]
A few regions (Missouri is one) run meets outside of leagues.  Currently, these meets have to be set up with an event type of "other" if we want to avoid the overhead of the league setup to run a single ad-hoc meet.  This can be confusing to scorekeepers setting up the meets as they know the event as a "Meet", but the "League Meet" event type isn't the correct event type to choose.

It would be helpful to regions like ours to have an event type of "Meet (non-league)" or something similar.

**Comment by kenpugsley** [comment]
It does in the sense that technically the event will run as expected.  The issue with the word scrimmage is that it has the connotation of an event that has no effect on advancements.  In regions like ours that run non-league meets, the meet results are counted toward advancement to a conference qualifier ... the accounting of the RP/TBP/Highest for advancement from the meet system is accounted across the region for all meets, and outside of the scoring system.

**Comment by JoAnnHalloran** [comment]
Hi Ken, Are you running these like a metro league? I thought that's what Missouri had planned to do.

**Comment by kenpugsley** [comment]
Not sure if it's similar to a metro league or not, I'm not familiar with that term.  Teams are allowed to play in two meets, and can choose any two meets in the state.  Advancement to one of two "conference qualifiers" happens based on meet performance and the team's location in the state.  This system helps ensure that both urban and rural teams all have the same shot at competing.  Teams can always find up to date rankings on our scoring website (http://moftcscores.net).  This meet system is in addition to each team attending a single open qualifier.  

The key ask here is that since the type of event is indeed a meet, but not one that is part of a league, we'd like to be able to tell the meet scorekeepers to choose an event type that matches the wording they expect, and doesn't include the league functionality that isn't part of our system.

**Comment by JoAnnHalloran** [comment]
This is considered a metro league event, and the league event type should be used. In MO, any team can opt into any league event, but it's still considered a meet.

**Comment by ftctechnh** [comment]
@kenpugsley 
Hi Ken - Unfortunately, we will not be able to accommodate your change request.  The FTC Live software follows the Game Manual's definition of what a  meet is and how the rankings for teams competing who are members of a league are calculated.  I am closing this request.

Note that it sounds like from your description, you are actually running a league.  I suggest that you consider doing the following for your events:

1. Create a league (you can call it "Missouri FTC League", or something like that) and add all of the teams in your state as members of this league.

2. When you have an event scheduled, you assign an event type of "meet"in the scorekeeping software and use the Missouri League defined in step 1 (with all of the teams listed as members).  You can select the teams from the Missouri League to participate at an event.  

3. Run your events and score them as league meets.  This means that you don't have judging at these events and that when you are done, you archive the event data and then load this data into your next meet so the ranking information will be current for the next event.

4. After the meets are done and each team has competed in two meets within the state, you can use the rankings from these league meets to help determine who advances to the conference qualifiers.

I hope this helps.  Please respond to this issue (even though it will be closed on the issue tracking database) if you have additional questions.

Sincerely,

Tom
