### ISSUE TITLE
Mineral Live Scoring not Updating

### ISSUE THREAD

**Issue by RollerCoaster45** [FIRST-Tech-Challenge/scorekeeper#219]
In the latest version, during the driver controller period, whenever a referee adds or subtracts minerals to the depot or lander or adds or subtracts penalties, the score does not update and the number of minerals does not update on the live scoring view. The values of minerals and score during the driver controlled period only update on the live display when a robot becomes parked or latched. I tested to see if the same issue exists on version 0.5.3 and the issue didn't exist there, but existed in 0.5.5.

**Comment by rgutentag** [comment]
Just tested this also and agree with rollercoaster45.  I also noticed that the score was not updating on the active match page.

**Comment by adwiii** [comment]
You are correct and thank you for bringing this to our attention. This has been fixed in v0.5.6 which we published just now.
