### ISSUE TITLE
3 matches for custom league event

### ISSUE THREAD

**Issue by jlaipunahou** [FIRST-Tech-Challenge/scorekeeper#220]
Our state championship event (coming up on Dec. 8 in Hawaii) begins with an "Open Division" of 3 matches followed by alliance selections and elimination matches. We are unable to run matchmaker when selecting less than 5 matches. I know this is short notice, but can you help us modify the app to allow for less than 5 matches? Thanks again for all your help so far.

**Comment by JoAnnHalloran** [comment]
I'm sorry, but official FIRST Tech Challenge events require a minimum of 5 matches per team. Please reach out to your Partner Service Manager, Mary Lee, and she can help you work on your schedule so that you can accommodate the required minimum. Thank you! JoAnn
