### ISSUE TITLE
Awards Manager

### ISSUE THREAD

**Issue by ftcohioapt** [FIRST-Tech-Challenge/scorekeeper#222]
Awards Script Manager does not include winning and finalist alliance awards. Software needs to automatically to port from the match results to awards screen. Dean List semi-finalists should not be shown as 1st, 2nd, 3rd, place. It should only list the names of the nominated semi-finalists. Same for finalists.

**Comment by emmell620** [comment]
+1

**Comment by emmell620** [comment]
Dean's List SemiFinalist Award section doesn't save the full description in the comment field. Rather than using the 1st, 2nd, 3rd place, I put the three names nominated in the comment field and it truncated it to about 10 letters instead of 3 lines.

**Comment by mglennon** [comment]
Also, allow for a direct export/import of this so that the judges can run a separate elsewhere and bring an importable file to the scoring table. The judges want to enter the data in their judge's room - outside of my arena wireless. Having the scorekeeper or another assistant copy/paste the data after someone already typed it once is needless work and can cause more errors and mixups.

**Comment by cmacfarl** [comment]
@mglennon You want to run a complete and separate instance of the the scoring server, enter the award data there, and then export only award data, then the sneaker net the award data to a laptop on the same network that a scoring server is running on, and then fire up a browser, connect to the scoring server, and import that award data?

I'd argue at some point in time, whether in the judge's room, or at the scorekeeper's table someone is doing transcription of of award data off of a sheet of paper.  While the judge's room may be more secure than a scorekeeper table, the complication of managing files and importing/exporting could also be a source of errors and mixups.

I'd prefer to see one official source of truth and a simplification of process.  It's not entirely clear to me that implementing a feature whereby the source of truth can come from whatever file was exported from whatever laptop and, oops, I imported the file from last week's competition accidentally, provides a process less immune from errors and mixups.

**Comment by mglennon** [comment]
I'd argue that given some reasonable controls my process is less error-prone.
Displaying the name of the event from the import file and the name of the running event during the import process. Flag / deny import files that weren't created on the same day or with the same version.
This process would be far less error-prone than having someone copy and paste data from a word document. Mixing tasks of copy/paste with team number selections only makes it worse.
Copying from paper or having a judge enter the awards while sitting in the arena also isn't an ideal option.

**Comment by slacter** [comment]
> Awards Script Manager does not include winning and finalist alliance awards. Software needs to automatically to port from the match results to awards screen. Dean List semi-finalists should not be shown as 1st, 2nd, 3rd, place. It should only list the names of the nominated semi-finalists. Same for finalists.

Agreed with this issue as we had no clean way to show winning and finalist alliance awards before progressing to the Inspire award.  We did a workaround by leaving the award slides and showing the elimination ladder through the scorekeeper video switch tab.

**Comment by rickliner** [comment]
The option to print the script is also missing the section on finalist and winning alliances.

**Comment by slacter** [comment]
Also would like to +1 the Dean's List Semi-Finalist award incorrectly having a 1st/2nd/3rd place display (There isn't such a thing for Dean's List anywhere in the process).  

We have one upcoming event where we have 10 nominations, so it will not be possible to show them on the screen.  We currently plan to just read out the names and call them all down to receive their buttons at the closing ceremonies.

**Comment by cshwiki** [comment]
I would also like to +1 on adding the section for Winning and Finalist Alliances. The system should be able to autopopulate these with the data from the event.

**Comment by adwiii** [comment]
In v1.0.0:

The Winning Alliance and Finalist Alliance are populated in the script:
![image](https://user-images.githubusercontent.com/9453262/64704037-978a4d00-d47b-11e9-99e7-64e387ede46d.png)

In addition, Dean's list has been overhauled to support a new format. From the Give Awards tab, users are now presented with a dialog to enter the first and last name of the semi-finalists along with optionally the team they are associated with. The user can add as many rows as necessary for events with more than 3 finalists. 
![image](https://user-images.githubusercontent.com/9453262/64704105-bab4fc80-d47b-11e9-9d43-c947dbedf4a1.png)

The semi-finalists will appear on the screen in the order that they are entered, and will show up one name at a time. The display will adjust to fit the names as best it can.
![image](https://user-images.githubusercontent.com/9453262/64704282-0d8eb400-d47c-11e9-85a8-9cc00db5fe5c.png)


Note that a similar procedure for entering names has been adopted for the Compass Award, except that is fixed at Winner, Second Place, and Third Place.

**Comment by adwiii** [comment]
On a semi-related note, as of v1.2.0, events that are marked as the "Championship" type (which is intended for events that advance to _FIRST_ Championship) have Dean's List Finalist instead of Dean's List Semi-Finalist.
