### ISSUE TITLE
Print all scoresheets

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#229]
Would like to have a way to press one button to produce a report of all the scoresheets for a tournament. To be done at the end of a tournament. (Enhancement request)

**Comment by adwiii** [comment]
This has been added in v1.0.0. While logged in as an Event Admin, on the Match Results page there is a button to "Download Scoresheet Archive". This will download a zip of all scoresheets for the event *as of that moment* - if a match has not been played, an scoresheet with all 0s will be downloaded. This is meant purely for the end of an event if the scorekeeper wants to have a separate copy of the match results. The scoresheets will not render properly unless the zip file is unzipped. Scoresheets will not render properly if moved outside of the folder they come in.
![image](https://user-images.githubusercontent.com/9453262/64703120-d3bcae00-d479-11e9-84b8-49c5429fd56d.png)
