### ISSUE TITLE
dummy event: rankings don't match with alliance selection rankings

### ISSUE THREAD

**Issue by jlaipunahou** [FIRST-Tech-Challenge/scorekeeper#236]
I'm doing some tests and simulating some events. 21 teams, 5 matches. The HTML rankings show an order that doesn't match what is shown in the Alliance Selection tab. Screenshots below along with DB and LOG file attached as ZIP.

This was a League Tournament type.

Any thoughts would be appreciated as our championship is tomorrow morning! (Sat, Dec 8)

Will try other things in the meanwhile.

![screen shot 2018-12-07 at 1 03 32 pm](https://user-images.githubusercontent.com/14628949/49677015-93c72700-fa20-11e8-82b4-b1159ebac662.png)
![screen shot 2018-12-07 at 1 03 42 pm](https://user-images.githubusercontent.com/14628949/49677016-945fbd80-fa20-11e8-9372-a63c54482d9d.png)

[mk2b.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2659022/mk2b.zip)

**Comment by tvbarnette999** [comment]
Did you import previous events? For League events, the Event Rankings report only shows the rankings using the matches played at that event. For League Tournaments you want the Combined Rankings report, shown under the League section on the main page, which includes previous matches in the calculation. The alliance selection process uses those rankings.

**Comment by jlaipunahou** [comment]
Ohh, I didn't realize that. So if it is rankings based purely on the matches at that event, that would be the Championship type?

**Comment by cmacfarl** [comment]
I like to think of League Tournaments as Inter-League Tournaments to more
clearly distinguish them from League Meets.  League Meets never have
elimination rounds.
