### ISSUE TITLE
Let cycle time allow half-minute turn times

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#237]
The previous version of the scoring software allowed the cycle times be incremented by half-minutes.  E.g. 7.0 minutes, 7.5 minutes, 8.0 minutes.  Please consider adding this to the current software.

**Comment by adwiii** [comment]
This has been added in v0.6.1. The system will only allow for half minute cycle times - if the user attempts to enter something other than half-minute it will be rounded to the nearest half.

**Comment by emmell620** [comment]
See new issue #465.
