### ISSUE TITLE
Enhancement: Show Match # Out of total matches on audience display

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#238]
In FRC, the lower third match timer display shows something like 
"Qualification Match 87 **of 104**"
At our event, we have parents coming and asking "how many qualification matches are there?" as well as online streams.

**Comment by cmacfarl** [comment]
Don't they all have schedules?

**Comment by adwiii** [comment]
This has been added in v0.6.1
