### ISSUE TITLE
Change Rockwell Collins to Collins Aerospace

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#241]
I was at an event this weekend with a fellow volunteer who is an engineer from Collins Aerospace (formerly Rockwell Collins, but they changed their name recently) and he mentioned that on the sponsor screen it says "Program Sponsor: Rockwell Collins."  Also, the Innovate Award is still called the Rockwell Collins Innovate Award.  The new name should probably be used in all these places.

Also, several places in other documentation including the game manuals that still list Rockwell Collins instead of Collins Aerospace.

**Comment by slacter** [comment]
This type of change would have to propagate from the sponsor through FIRST and down through the systems and marketing materials.  This is because there is a financial cost to changing materials due to a logo or name change.  Granted, the scoring system is electronic, but the official change would have to come through the proper channels.

**Comment by jvens** [comment]
The new name is now used on the sponsorship screen of the audience display, but the old name is still used for the name of the Innovate Award and for the boiler plate script on that award as well.  Attached is the official name of the awards and the associated script.  Collins donates a lot of money and resources into this program and I believe this should be a very high priority.

[award-descriptions.pdf](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2705781/award-descriptions.pdf)

**Comment by adwiii** [comment]
As of 0.7.1 the award and script have been updated to reflect the new name.

**Comment by jvens** [comment]
The first paragraph of the awards script lists "Official Program Sponsor Rockwell Collins!"  Also, the advancement report still lists Rockwell Collins as the name of the Innovate award.

**Comment by adwiii** [comment]
The advancement report and awards script have both been updated in 0.7.2.
