### ISSUE TITLE
Referee Training/Practice Mode

### ISSUE THREAD

**Issue by jkelbick** [FIRST-Tech-Challenge/scorekeeper#244]
Please create a training mode, so that referees can practice scoring matches that aren't actually running and without the involvement of the scorekeeper. It would be great if something like this could be posted to the internet so that refs could practice before ever coming to the event.

**Comment by davewdavis3299** [comment]
We solve that in a different way. Our Head Ref (me) carries a big screen iPad with event_admin rignts (I'm also a certified scorekeeper).  I can run test matches from the ipad while the scorekeeper is busy with the other duties.  The iPad is also invaluable for conferences with students, you can pull the match score sheets up, I have the game manuals and such at my touch, etc. Saves a bunch of time and frustration. Thanks, Programming team!

**Comment by jkelbick** [comment]
@adwiii Access to "test" versions of the pages that aren't tied to matches at all would be perfect. As soon as the ref submits the finalized score, the entire thing could evaporate. It's all about getting them comfortable with the interface and working within the time constraints.


> We solve that in a different way. Our Head Ref (me) carries a big screen iPad with event_admin rignts (I'm also a certified scorekeeper). I can run test matches from the ipad while the scorekeeper is busy with the other duties. The iPad is also invaluable for conferences with students, you can pull the match score sheets up, I have the game manuals and such at my touch, etc. Saves a bunch of time and frustration. Thanks, Programming team!

That's not a bad solution. I might need to chat with the FTA/scorekeeper about this to make sure they're comfortable with this, but it could work!

**Comment by cmacfarl** [comment]
Test matches are the currently implemented solution for training and practice.
