### ISSUE TITLE
Make All Pages Cell Phone Friendly

### ISSUE THREAD

**Issue by jkelbick** [FIRST-Tech-Challenge/scorekeeper#245]
I've been at several events now where referees were asked to use their personal cell phones. None of the referee score-entry pages seem to scale properly down to a 4-5 inch screen. Can we implement some dynamic sizing criteria to make these pages look better on smaller devices?

**Comment by adwiii** [comment]
We can make a best effort attempt to support smaller screens, though optimizing for this is not a high priority. In testing the software, we received complaints that UI elements were too small and hard to use, especially on smaller devices, and as such we target a 7 inch device. We have found that it is easiest for referees to quickly score elements without diverting too much attention from the field when using a tablet of this size. In testing, it was very difficult to support small phones, particularly in the 4 inch range such as the iPhone SE, etc. On these phones users inevitably resort extensive scrolling around the page, both horizontally and vertically, which distracts from scoring the match.

**Comment by jkelbick** [comment]
7+ inch devices would definitely be ideal, and scrolling is definitely the enemy, but we should be working to deliver the best experience regardless of device. In many areas, finding an extra $200 for referee tablets is a challenge.

**Comment by adwiii** [comment]
I know it is still money, but the [Amazon Fire 7](https://www.amazon.com/Fire-Tablet-Alexa-Display-Punch/dp/B01J90OCNM) is $50 and routinely goes on sale for ~$30. If you get 4 for use across 2 fields then that is $120 which is better than some alternatives. I personally own a [Fire 8](https://www.amazon.com/Fire-Tablet-Alexa-Display-Punch/dp/B01J90OCNM), which I personally think is worth the $10 more, but I know that isn't always the consideration. I use the tablet for more than score tracking though - it has all the manuals and everything for running the event too.

To be clear, the pages are still *functional* on smaller screens, it just won't be the best user experience.
