### ISSUE TITLE
Alliance selection wants first captain to select first partner before selecting second captain

### ISSUE THREAD

**Issue by wcraigtrader** [FIRST-Tech-Challenge/scorekeeper#248]
Using version 0.60 (downloaded on December 8th) at the DC Qualifiers, during alliance selection, we discovered that the input behavior of alliance selection had changed. Previously we would enter the top four teams as alliance captains, then round-robin each captain could select a first partner, then each could select a second parter. This time when I went to add the second captain, the software selected them as the first partner for the first alliance, instead of the captain for the second alliance.

This is a change in behavior between 0.56 and 0.60, and was not mentioned in the release notes.

**Comment by adwiii** [comment]
The alliance selection process has not changed for this year's software. In last year's software the system would fill in captains 1-4 before they were made final as you describe. The behavior for this year's software has always been to only show a team in the alliances when their position in that spot has been finalized.

**Comment by cmacfarl** [comment]
@wcraigtrader This is as designed.  If 1 picks 2 then 3 becomes 2.  Software waits until the first pick happens to decide who 2 is.  You can still line up team representatives in rank order for selection ceremony purposes.
