### ISSUE TITLE
Inspection Schedule shows Not Started after created

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#249]
After creating an inspection schedule the status on the dashboard still shows `Not Started`.  I have only tested this with an event type of League Meet.  I did remove judging since typically at league meets there isn't any judging component.

**Comment by adwiii** [comment]
This is an oversight on the dashboard, and it will happen for all types of events - we will fix that for next release. Inspection and Judging scheduling is not 100% right now and there may be some bugs. Please let us know if you encounter any others. We have a few other tweaks/enhancements coming for this next week.

**Comment by pstrones** [comment]
There does not seem to be an option to print the judging schedule once it is generated.  The format once generated is not sequential by time or by station, it would be good if it could categorize and have it in time order for teams/judges to follow easily.  I was able to copy and dump into excel and manipulate from there (see attached).
[Phoenix Judging.pdf](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2678293/Phoenix.Judging.pdf)

**Comment by adwiii** [comment]
I expect every end user will want to have the data in a slightly different format, so it is good for us to identify a few common ones. The inspectors may want things by station and then by time so they can know who comes to them in order like what you posted, the teams may want all of their activities in one group, sorted by either time (no current view) or activity (the table currently shown), and event organizers may want the grid view to see everything at a glance (the grid shown on the generation page).

We will work on finding a way to show the different formats of data and allow the user to easily pick between them - and we can add the ability to print each, too.

**Comment by jvens** [comment]
Another nice feature would be a way to change the station name.  For example, to put a room number or room name for judging rooms instead of just station 1, 2, etc.  I would consider this a lower priority feature though.

**Comment by adwiii** [comment]
The ability to print the schedule was added in v1.0.0, and the dashboard indicator has been fixed. @jvens if you still want the room number instead of station, please open a new issue for tracking purposes.
