### ISSUE TITLE
Missing announcer sheets (alliances) report

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#25]
Most all reports are missing – Announcer sheets, announcer sheets (Alliances), FTA Match Notes, match results, match results with details, team rankings, team information, awards list, awards scripts, teams eligible for advancement. Only match list is available.

**Comment by adwiii** [comment]
This has been added in 0.5.3, Elimination Bracket report coming, but the announcer report does have the elims matches.
