### ISSUE TITLE
Change Colors When Match is Over on Referee Tablet

### ISSUE THREAD

**Issue by jkelbick** [FIRST-Tech-Challenge/scorekeeper#252]
To hep compensate for audio issues in some venues, it would be very helpful if the referee's scoring tablets would change color (maybe the background of the page) to red (or something similar).

**Comment by adwiii** [comment]
We had discussed a similar idea, but for a different reason - make the background of the page flash when the match phase is over and 5 seconds have elapsed. This would occur if the referee was still in Autonomous when the period ends, or if the referee was still in Driver-Controlled when the match ends. The idea was to encourage the referee to move to the next phase in a timely manner, not necessarily to account for sound failure. The 5 second grace period was intended to give the referee a bit before the page would start bugging them :).

Perhaps we can come up with a good mix of both, where the background color changes slightly at t=0 to signal match end and then begins to flash after a period of time to signal "late scores".

**Comment by jkelbick** [comment]
@adwiii I like all of this idea! Maybe we could even vibrate the device when the period changes? If the ref is already distracted, the tactile feedback might go a long way towards regaining their attention!

**Comment by maths22** [comment]
We have added a yellow flashing background when the referee is on the wrong period.
