### ISSUE TITLE
Add API Route to get team as it appears at event

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#257]
The API returns 404 in `/teams/xxxx/` in I created

**Comment by adwiii** [comment]
Can you post a curl or the exact url and response you received?

**Comment by ofekashery** [comment]
I created a team
![image](https://user-images.githubusercontent.com/16443111/50165930-9f530180-02ee-11e9-9b9b-0358a4c005cf.png)

But I call ``/apiv1/teams/15768/`` this returns ``{"errorCode":"NO_SUCH_TEAM"}``

**Comment by adwiii** [comment]
Ah, hm. The api route you are calling checks the global list of teams. If the team you created is "new", meaning not in the global list of teams, then it will tell you no such team. When you create a new team or edit a team it only updates the team *for that event* so the global team list is unaffected and thus why you are getting a 404. This is the intended behavior there from how the system is set up. Consider you have two events and they each edit the team info, the system would not know what to send, so it always sends what is in the global list, which matches *FIRST*'s team list each release.

It appears there is no way in the API to query the team as it appears at the event. @cmacfarl can correct me if I'm wrong. That would be an enhancement/new route.

**Comment by ofekashery** [comment]
I know it returns from "global" teams. That's the issue.

**Comment by cmacfarl** [comment]
I think the midterm solution is to provide you with a server that contains the team you are looking for.  The longer term solution is to provide hooks into the FIRST registration database so you can pull this information directly from FIRST.

Correct me if I'm wrong, but I don't think there should ever be a case where a team is competing in a FIRST sanctioned event, but is not registered with FIRST.

**Comment by bsimmons99** [comment]
Most of the teams in our state are registered with FIRST and have team numbers however they do not show in the Team and Event search, nor the list of teams distributed with the software.
The API returns `{"errorCode":"NO_SUCH_TEAM"}` which I figure is expected at this point. I don't know why the teams don't show in the lists, however I can see this as a case regarding @cmacfarl's comment.

**Comment by cmacfarl** [comment]
Please give an example a team that is registered but does not show in the list of teams bundled with the latest version of FTCLive.  --Thanks.

**Comment by cmacfarl** [comment]
Convinced.  

I'll look into adding two new routes.  One to dump local teams, one to dump team info for a local team.

**Comment by ofekashery** [comment]
Thanks

**Comment by adwiii** [comment]
The ability to query event specific teams has been added in 0.7.1

`/apiv1/events/<code>/teams/<number/`

The global list of teams can still be queried as before.
