### ISSUE TITLE
auto update of inspection reports

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#263]
Can we get the inspection reports to automatically update when an entree is put in.  Otherwise someone(scorekeeper) needs to constantly hit refresh on the display.  We have been using excel spreadsheets to do this and everytime our input person inputs the data it is immediately available on the display.

**Comment by adwiii** [comment]
The projector display updates every 3 minutes (similar to the pit display). If you are leaving the page up for an extended period of time for updates, we highly encourage using the projector friendly display. The non-projector version is meant for one off checking to see the status at that moment.

**Comment by rgutentag** [comment]
Thanks for the info.  I didn't leave it up that long.  I will test that out next.

**Comment by rgutentag** [comment]
I have tested this and it works as you stated.  This is acceptable to me. I am closing it.
