### ISSUE TITLE
Inspection rule hyperlink requires internet

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#264]
On the inspection checklist the hyperlinks in the `Rule #` column link to www.firstinspires.org.  Since the scoring system should not be connected to the internet these links will fail during an event and should probably link to a local copy of the game manual instead.

**Comment by adwiii** [comment]
These links now point to the copy of the game manual that ships with the scoring software. Note that the links to specific pages do not work on most mobile devices.
