### ISSUE TITLE
Score Tracking doesn't work with older iPads

### ISSUE THREAD

**Issue by sungjuchoi** [FIRST-Tech-Challenge/scorekeeper#265]
We have various iPads to do score tracking. The older iPads do not work with score tracking. More specifically, in the Autonomous phase, Left and Right Sample Field minerals can't be clicked. The Left and Right Cargo Hold plus and minus buttons can't be clicked. And finally, clicking on Submit Autonomous does nothing.

Our setup is as follow
Dell laptop running Windows 10 as the server
iPad 2 with iOS 9 - doesn't work with Safari and Chrome (version may be old)
iPad (3rd gen) with iOS 9 - doesn't work with Safari and Chrome 63.0.3239.73 (will not upgrade beyond)
iPad Air (1st gen) with iOS 12 - works with both Safari and Chrome latest

**Comment by bsimmons99** [comment]
Not that it will probably help much (other than reproducibility), but we had this problem during November, however I don't remember any of the details regarding versions or devices.

**Comment by Nate2019** [comment]
Yeah I have had this same issue. See issue #105

**Comment by maths22** [comment]
iOS 9 is no longer supported
