### ISSUE TITLE
When using a multi-field event, the field timer on the fields not active should display "Field not active" or "Match playing on field __(#?)__" or something else

### ISSUE THREAD

**Issue by Nate2019** [FIRST-Tech-Challenge/scorekeeper#268]

**Comment by tvbarnette999** [comment]
As of v1.0.0, non-active fields will show either:
1. The SETUP/PREVIEW screen for the next match on it if the match has been loaded by the scorekeeper
2. The SKYSTONE background screen. 

This transition occurs on posting the results from the match it last showed or the load of the next match on the other field. Until then, it continues to show the scores and timer as they were upon referees entering REVIEW and locking the display.
