### ISSUE TITLE
Missing awards list, award scripts and teams eligible for advancement reports.

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#27]
Most all reports are missing – Announcer sheets, announcer sheets (Alliances), FTA Match Notes, match results, match results with details, team rankings, team information, awards list, awards scripts, teams eligible for advancement. Only match list is available.

**Comment by adwiii** [comment]
This feature was added in v0.4.0. The script still needs to be updated, but the awards and advancement report is included.
