### ISSUE TITLE
Add support for individual robot info in the API

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#270]
Adding robot-specific info so we know if robot 1 parked partially in the crater and robot 2 parked fully in the crater rather. Re #178

**Comment by adwiii** [comment]
The match details api for 2020 returns robot specific information. See the [swagger documentation](https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation) for more information.
