### ISSUE TITLE
“Check All” During Inspection

### ISSUE THREAD

**Issue by aj-foster** [FIRST-Tech-Challenge/scorekeeper#272]
First and foremost: **thank you** for all of your hard work on this system. It has been a pleasure working with it this year.

In the (new, and awesome) inspection tracking system, it would be very helpful to “check all” or otherwise be able to pass a team without manually checking all of the boxes. We find ourselves with fewer tablets than inspectors, and therefore half of the teams are being entered into the tracker after-the-fact.

**Comment by emmell620** [comment]
I agree with AJ wholeheartedly!!

**Comment by adwiii** [comment]
As of 0.7.1 there is a Lead Inspector role and a default Lead Inspector account. Someone with the Inspector and Lead Inspector roles can now access the Lead Inspector override:
![image](https://user-images.githubusercontent.com/9453262/50658617-edf7d100-0f67-11e9-930a-30fd3eb700fd.png)
From there they have access to a drop down that lets them directly set the state of a team without going through the form:
![image](https://user-images.githubusercontent.com/9453262/50658709-31ead600-0f68-11e9-847e-6eb418cbc713.png)
This will display on the corresponding status pages in the same manner as if the team had gone through complete inspection.

This can be used when there is a paper record and you want to quickly transfer that record to the system.

**Comment by aj-foster** [comment]
Fantastic, thank you!
