### ISSUE TITLE
0.7.0. creates duplicate logins.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#273]
When I create new default accounts. I get two accounts with the same username:

Username | Password
mmdq_fielddisplay | fusarium286
mmdq_fielddisplay | affair517

I'm guessing these may be mmdq_fielddisplay1 and mmdq_fielddisplay2 but I could not get any combination to work.

**Comment by adwiii** [comment]
This has been corrected in 0.7.1
