### ISSUE TITLE
The randomization screens are confusing.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#275]
FWI, I ran some mock matches last night with 0.7.0 and we could not get consensus from the group which way around the silver/gold minerals were meant to be arranged, based on the apparent conflict between the scorer display and the audience display.

The assumption I have seen other events use is that the arrangement that is shown on the scorer pads, is the view of the minerals from the robot's perspective.

However, on the audience display, there is a V shape next to the minerals, and this appears to be listed as "field corner".  If that V is in fact the outer corner of the field, then the mineral order is reversed from the scorer pads.  However, if the V indicates the center of the field (at the lander) then the order is correct.    The use of the word "corner" is confusing.  

We could not find a definitive answer to the question at hand.  I would suggest adding some indication on the scorer pad as to which perspective is correct.  eg: as seen from robot (or lander)

**Comment by cmacfarl** [comment]
The perspective is as seen by the referees outside of the field.

**Comment by rickliner** [comment]
There was confusion among the referees at my first tournament as well. The two displays should be visually consistent.

**Comment by jkelbick** [comment]
There has been confusion at several of my events as well. I agree that the
displays should be visually consistent.

**Comment by adwiii** [comment]
For SKYSTONE we added more reference points to make the meaning clearer:
![image](https://user-images.githubusercontent.com/9453262/64710559-2d2ada00-d486-11e9-9746-b21c5fe4b693.png)
