### ISSUE TITLE
Different time format on displays

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#276]
Is there a reason why the "match time" is shown as minutes and seconds (1:03) on the Audience display, but as a "Seconds Remaining" progress bar on the Overlay display?

This question was raised by my Video Streaming consultant who is assembling a hybrid screen for streaming that can also show some real-time scoring information in the footer area of the Overlay.

The rationale for one method over the other would seem to apply equally to both displays.  I was just wondering what I was missing.

**Comment by adwiii** [comment]
The overlay for *FIRST* Tech Challenge used the X:XX timer format on all screens, including the overlay, prior to this year. However, with the addition of scores this year, it did not make sense to keep the large timer on the Overlay. As such, the timer was converted to a bar with the "Seconds Remaining" counter with the scores shown below - a design borrowed from [*FIRST* Robotics Competition's Overlay timer design](https://youtu.be/tmwz2na5lVM?t=4).

We are in the process of adding live scoring indicators to the Overlay and Field Display, but those will not be in the release this week.

**Comment by gearsincorg** [comment]
Cool.  Thanks for the explanation...  Looking forward to the scoring indicators.
