### ISSUE TITLE
Advancement Report - Include team name with team number

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#277]
Would like the team name to be listed in the advancement report with the team number which is already there.  When providing the report to the announcer/presenter, we currently have to research names for each number and write it in.

**Comment by rgutentag** [comment]
I agree that this would be helpful

**Comment by jkelbick** [comment]
Would be nice to also include options for school name and location.

**Comment by adwiii** [comment]
The advancement report has a checkbox to "Show Team Name" that will add a column with the name of the team. Additionally, using the new Advancement Display added in `v3.3.7`, the display will show the team number along with the team name in smaller font. Please read the release notes for more information on the new feature.
