### ISSUE TITLE
Alliance Bracket - having an option to print out.

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#279]
It would be nice to have the option to print out the alliance bracket to utilize by queuing, inspection volunteers.

**Comment by FrowntownPitt** [comment]
I wrote a script to generate an elimination alliance sheet to be used by referees and other field personnel.  An inclusion of something like this internally is necessary for the success of events as they were used in the past system.

In the meantime, my script can be found at [github.com/FrowntownPitt/FTC_Live_Extensions/tree/master/Elimination%20Sheet](https://github.com/FrowntownPitt/FTC_Live_Extensions/tree/master/Elimination%20Sheet).  I made it look a little more like it belongs in this decade :-)

**Comment by rgutentag** [comment]
All I do to get the elimination brackets is to goto video switch and use show brackets.  I then do cntrl P for a printout.

**Comment by FrowntownPitt** [comment]
> All I do to get the elimination brackets is to goto video switch and use show brackets. I then do cntrl P for a printout.

There are a lot of colors/graphics on this page, which is a waste of toner/ink.  If it works for you, great! I'd rather have a dedicated solution.

**Comment by wcraigtrader** [comment]
I do the show brackets / ctrl-P trick as well, but it actually looks pretty ugly, and is a definite hack. I'd prefer to have a report that was properly formatted for the page as well. Your script looks nice, but as a scorekeeper, I typically end up being provided Windows boxes that won't have Python installed, and I won't have permission (or time) to install Python and a bunch of libraries on match day. 

So this functionality needs to be rolled into the main server (using Java, not Python).

**Comment by tvbarnette999** [comment]
This has been added as the Bracket Report under Event Reports in v0.7.2.
