### ISSUE TITLE
Redirect to inspector page

### ISSUE THREAD

**Issue by YeveRivkin** [FIRST-Tech-Challenge/scorekeeper#281]
Feature request from my LRI and LFI:
Inspectors were confused if the 'Pass' status was saved. Can you redirect to the main inspectors' page (the one that you see all the teams that need to be inspected) after they pressed 'Pass'

**Comment by jvens** [comment]
I second this.  I had inspectors today who were confused if the system correctly registered the team had passed because they expected after clicking pass to return to the team list.

**Comment by adwiii** [comment]
This has been added in 0.7.2. When you pass or fail a team you will be redirected to the team selection page.
