### ISSUE TITLE
League meets not set up correctly

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#283]
We have a league who set up their league meets incorrectly.  This league will be competing in a league tournament on January 12, so please help us to resolve this issue as quickly as possible.

As far as I can tell, here are the problems:
- Meet 1: Was incorrectly configured as a scrimmage instead of a league meet.
- Meet 2: Set up as league meet, and then teams were added to the event instead of being added through a league
- Meet 3: Set up correctly, but did not import data from the other meets.

The attached zip folder contains the export databases from each meet.
[galileo.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2724881/galileo.zip)

Tag @rebeccawhitaker

**Comment by tvbarnette999** [comment]
Here is an archive of the third event with all the data from the previous two imported into it. This should be ready for import into your league tournament

[galileo_league_meet_3.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2738703/galileo_league_meet_3.zip)

**Comment by jvens** [comment]
Everything looks good with this version.  Thanks for your help.
