### ISSUE TITLE
Inspection/Judging screen shows date  in European style (DD/MM/YYYY)

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#289]
Even though it is requested in American style (YYYY-MM-DD).  See image.  This can be very confusing as showing a May 1st judging/inspection date instead of January 5th.

![image](https://user-images.githubusercontent.com/12737153/50720513-4a481700-1074-11e9-8e27-ac3d7fbdcefb.png)

**Comment by rgutentag** [comment]
My question is why to we need the date at all.  All of these activities take place before match play begins.  By removing these will clean up the printouts a little.

**Comment by maths22** [comment]
This page now handles dates consistently with the rest of the software
