### ISSUE TITLE
add teams at event

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#291]
I find that it is difficult to get the cursor into the little box for teams that are participating.  It would be helpful if we could just click anywhere on the line containing the team info.

**Comment by adwiii** [comment]
This has been added in v1.2.0 - you can now click anywhere on the row that contains the team and the team will be added to the event (also works for the add to league page). The row will also now highlight purple when you select a team to make it more clear that the team has been added.
