### ISSUE TITLE
timeout timer for each field

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#293]
During elimination play when using multiple field it would be nice to set a timer for each field.  Since the teams will be playing back to back on each field we need timers for each field.  Currently during semifinal matches a referee on each field uses a watch to time it.  Once we get to finals which occurs on one field we can use the builtin timer in the scorekeeping system

**Comment by tvbarnette999** [comment]
This has been implemented as part of the new timeouts - during elims each series gets its own timeout timer
