### ISSUE TITLE
inspecting and judgeing schedules

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#294]
We would like a way to input our own times to the schedules for inspection and judging.  We try to make sister teams be judged by the same panel.  We also generate the schedules a few days before the event and email the teams the schedules in advance.  Our scorekeeping computers are not easily available at that time.

**Comment by rickliner** [comment]
+1 for the option to manually enter judge interview schedule

**Comment by adwiii** [comment]
Whoops, looks like this was added and I neglected to post on this issue. See my response to #470 on how to import a custom schedule.
