### ISSUE TITLE
Hiding Events - How to unhide and event that has been hidden

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#295]
I can hide events and follow the steps through the server manager, however how do you retrieve an event that is hidden.  Is there a way to "unhide" an event?

**Comment by adwiii** [comment]
Yes, but it is not directly built into the software. From the software directory, navigate to `/lib/db/hidden/` folder and find the db that you want to unhide. Copy it to a different location on your computer (optional, but probably easier). 

Then, you can follow the standard import procedure - from the Server Management page, import the db that you copied out of the `hidden` directory. The event will now show up as normal.

Let me know if you have any issues. Importing may take a few seconds, you may need to wait a bit after clicking the import button.


Note: if you hide an event with the same code more than once, it will have two different names in the folder. For example, if you create event `test` and then hide it, it will have name `test.db`. If you create a new event `test` and then hide that event, it will show up as `test1.db` and the original `test` will still be `test.db` to make sure no data is overwritten. This could possibly get confusing if you have multiple events with similar names. If you run into a problem where you can't tell which db you want in the hidden folder, you can zip the folder and upload it here and we can help sort through,

**Comment by adwiii** [comment]
Closing based on the above. Feel free to re-open if there are additional questions.
