### ISSUE TITLE
Matchmaker stuck on "Estimating time to generate matches" 

### ISSUE THREAD

**Issue by mgoudreault** [FIRST-Tech-Challenge/scorekeeper#296]
When we get to the "Create Match Schedule" section the system seems to get stuck when we click "Run Matchmaker" and the status bar doesn't appear. It seems to work for a couple of runs but then stops, both when recreate an existing match list and to create a match list for a different event.

I've attached the error log and a screen shot, but the error seems to be: "SEVERE: ERROR: surrogate round (3) must be at least one but less than the number of rounds (3)". It seems to be slightly more stable in v. 7.0 than 7.1 but I'm having the error in both.

![image](https://user-images.githubusercontent.com/46531751/50908863-85569b80-1422-11e9-8f6d-0a4975b1e979.png)
[2019_01_09_03_03_22_PM_err.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2741448/2019_01_09_03_03_22_PM_err.log)

**Comment by adwiii** [comment]
I have tried to reproduce and not had any luck re-running matchmaker several times, though I understand from the issue that this is not necessarily a consistent problem so I will keep my eye out to see if I can encounter this again.

Any of the times you have encountered this issue has it said "Error running MatchMaker. Please check settings and try again."?

I see from the log that you are running Windows 10. Can you give me an idea of the specs of the computer? When it does run matchmaker how long does it say it will take?

Does re-starting the server help it to run the next time you try? Can you upload the DB of the event you were trying to run immediately after you encounter the issue? That is, when you get it to hang, zip the DB immediately before doing anything else and post here.

Sorry I have more questions than answers, but hopefully this will help to reproduce the issue.

**Comment by mgoudreault** [comment]
I've attached the db right after breaking (this is now v7.1). After playing around with it a few more times I've  realised it only happens when we list the matches per team as 3. It does throw up the error to please check settings but if I save and run again that is when it breaks (and stays broken until I reinstall). 

Is it possible to run with only 3 matches per team or can the system only run with a larger number of matches? We are planning for a scrimmage with 3 matches per team in a couple weeks where we were going to trial the software so teams can be familiar with the process.

[test003.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2741768/test003.zip)

**Comment by adwiii** [comment]
Yes, you cannot run with 3 matches per team. Version 0.7.2 fixes this. Please run with 5 or 6 matches per team. If you want every team to have 3 matches for scrimmage purposes, then you can play only the first half-ish of matches.
