### ISSUE TITLE
Issue importing db file

### ISSUE THREAD

**Issue by tacklebat** [FIRST-Tech-Challenge/scorekeeper#297]
[ohcleveland.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2746868/ohcleveland.zip)

This event was made in version .7 and I attempted to open it in version .7.2.  Here are the errors I received when i tried to open the file.  Something is off with the file however.  I also tried opening it in version .7 and received similar errors.  I have attached the log files from importing and opening version .7.2.  I don't have the computer that the DB file was created on or the tournament was run on.

[2019_01_10_07_28_47_PM_err.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2746879/2019_01_10_07_28_47_PM_err.log)
[2019_01_10_07_35_42_PM_err.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2746880/2019_01_10_07_35_42_PM_err.log)
[2019_01_10_07_25_12_PM_err.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2746881/2019_01_10_07_25_12_PM_err.log)

Here is the error i think is the problem:
db for ohcleveland updated from 2019_X to 2019_2
[main] ERROR org.usfirst.ftc.event.SQLiteEventDAO - Error saving config for ohcleveland

I'm on TOA and FTC discord if you need to find me.

tacklebat

**Comment by adwiii** [comment]
I downloaded the most recent release (0.7.2) and was able to import the db without issue (though it does take several seconds to import). 

Can you try downloading 0.7.2 again and see if it works? If not, can you upload a full zip of your instance of the scoring software and also describe what kind of computer you are running on?

**Comment by tacklebat** [comment]
I downloaded .7.2 again and ran it on a windows 7 machine and it important the file without issue.  I was try on an amazon EC2 linux box previously.  So maybe something with unix/mac version.  I'll test it on mac and and an Ubuntu vm and if it works on those it is probably something with my ec2 instance and not a bug.

**Comment by Nate2019** [comment]
@tacklebat I assume you are probably posting this in relation to me having an issue with the uploading of this event to TOA. I've imported this event into .7.2 on my mac and I haven't had any issues with the import.

**Comment by tacklebat** [comment]
I tried to import with a new copy of .7.2 on my ubuntu 18.04.1 LTS VM and it had the same issues.  So something about this DB file doesn't like scorekeeping software running on linux, probably.

**Comment by emmell620** [comment]
Newline/Carriage return maybe??

**Comment by tacklebat** [comment]
This issue was user error I believe.  Either way .73 resolved it.
