### ISSUE TITLE
Structure of Match API Endpoint

### ISSUE THREAD

**Issue by ehsanmasdar** [FIRST-Tech-Challenge/scorekeeper#298]
Hi!

I'm part of a team that's been developing a website that provides easy access to FTC scoring at events, called FTCScores (FTCScores.com). Thank you for the great work on the new scoring system - the API has been super solid and easy to integrate.

One of the priorities of FTCScores is to deliver scores and score corrections as near real-time as possible. In order to do this, we have a tight parser loop that runs every few seconds to query match data.

Currently, the structure of the /matches endpoint is:
```
{
    "matches": [{
                "matchNumber": 1,
                "field": 1,
                "red": {
                    "team1": 1,
                    "team2": 2,
                    "isTeam1Surrogate": false,
                    "isTeam2Surrogate": false
                },
                "blue": {
                    "team1": 6,
                    "team2": 20,
                    "isTeam1Surrogate": false,
                    "isTeam2Surrogate": false
                },
                "finished": true
            }, ...
```

Since the /matches endpoint only contains a finished: true flag along with team numbers, it's impossible for us to know about scoring changes that occur after the initial score is comitted (and the finished flag flips) from just querying the /matches page Our temporary workaround has been querying every single match details page. This can be resource-intensive has caused problems with lower-spec computers that use FTCScores.

The match details endpoint (ie /matches/1) also contains a time field, which represents the Unix time of the last match update. If this could be also added to the /matches endpoint for each match, we would only ever have to query match details endpoint when a match has been newly updated. This would look something like:
```
{
    "matches": [{
                "matchNumber": 1,
                "field": 1,
                "red": {
                    "team1": 1,
                    "team2": 2,
                    "isTeam1Surrogate": false,
                    "isTeam2Surrogate": false
                },
                "blue": {
                    "team1": 6,
                    "team2": 20,
                    "isTeam1Surrogate": false,
                    "isTeam2Surrogate": false
                },
                "time": 1545181548282,
                "finished": true
            }, ...
```
Would this be feasible to implement? Thanks!

**Comment by cmacfarl** [comment]
Resolution documented here.  

https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation#apiv1eventsevent_codematches
