### ISSUE TITLE
API returns wrong ranking for league tournament

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#301]
When running a league tournament the API route `/apiv1/events/<event code>/rankings/` should return the combined rankings for the league instead of the "this event only" rankings since it is the combined rankings that determine alliance selection.  Currently this route returns the rankings for the current event only.  This should be considered a very high priority since it currently causes 3rd party sites like The Orange Alliance to report incorrect rankings which can lead to confusion by the teams.

This is similar to the issue #130.

**Comment by ggisme** [comment]
Bump...I agree that this should be a high priority!! Since it has been 15 days, it seems like it unfortunately has been put on the back burner.

**Comment by cmacfarl** [comment]
This is addressed in a forthcoming release by adding a combined rankings endpoint.   It didn't make the cut this week.  Note that no change is made to the existing rankings endpoint.  Expect something in next week's software drop.

**Comment by cmacfarl** [comment]
3rd party clients are free to choose what to display.   The API provides the data.  No more, no less.

Comments on display for audience and pit pages should be addressed in a different issue as this specifically tracks an API enhancement.

**Comment by ggisme** [comment]
Thanks for the update @cmacfarl

**Comment by adwiii** [comment]
As of 0.7.5 there is an endpoint at `apiv1/events/<event code>/rankings/combined/` that returns the combined rankings instead of the event specific rankings.
