### ISSUE TITLE
Recovery from Aborted match is confusing.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#302]
Rev 0.7.1

At our event we had to abort a match due to a field problem during Teleop.
Once aborted, it was difficult to start the next match, and also confusing for the scorekeeper.

1) The Scoring tablets did not reset to a pre-match state.  The last scoring page was still displayed, and attempting to accept or move on was met with a prompt that the period had not yet ended.
Ultimately the scorers had to close the browser window, re-login and the match selection screen came up OK.

2) On the Match control screen, the partial score from the aborted match was still shown on the screen.
Even though the normal staging sequence was working, the scorers were unsure about starting the match because they didn't know if the previous scores would be cleared out.  Ultimately they decided to proceed and watch to see what happened.  Luckily as soon as they started the match, the scores were zeroed out.

I recommend that when a match is aborted the scoring tablets are returned to the ready state, and the "current" score is reset to zero.  Essentially act as if the match had never started.

**Comment by maths22** [comment]
Aborted matches should be handled much more sensibly this season.
