### ISSUE TITLE
Progression from SF1-1 to SF2-1 is confusing.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#303]
Rev 0.7.1

After Alliance selection we started running Semi's on field 1.
Once that match was over, it didn't look like the next match was going to run on field 2.

We loaded the match and set the match preview, but the Field 2 display still did not change.  We tried refreshing it, but it just showed the Rover Ruckus logo.

We were looking for some indication of the fact that field 2 was the next active field...  I was personally expecting the field timer to appear and go to 0:00.  Field 1 was still showing 0:00 so that didn't help.

We staged the teams anyway, and when the randomization was done, the correct display activated, but it prompted me to report this situation as a possible issue.

I can't find anywhere on the normal control display that indicates which field the next match will be played on.  It would be helpful if there were some indication, either on the control screen, or on the field display itself.

**Comment by adwiii** [comment]
As of v1.1.0, the Match Control Page now has a column for the field number. Here is an example screen clip from a two field event for Eliminations:
![image](https://user-images.githubusercontent.com/9453262/66600678-05f22600-eb74-11e9-89c0-f9b2656dc22c.png)

Note that Finals Matches (and Inter-Division Finals Matches for Dual Division Events) are always played on "Field 0". Field 0 means that it will behave as if it is playing on all fields at once - all displays, regardless of what field they are set to show will show the finals matches.
