### ISSUE TITLE
Add boolean to Event API route to tell dual division

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#311]
This would simplify checking for dual division events, as some regions with multiple events in one scoring system could already be using the suffixes "_0" to denote an event, and the division # for a non-dual-division event is the same as the division # for the combined division (the "_0" division) of a dual-division event.

**Comment by adwiii** [comment]
As of v1.0.0, the event route now returns the division info:
![image](https://user-images.githubusercontent.com/9453262/64708800-2fd80000-d483-11e9-8f90-bf4fc29cf060.png)

For more information, see [the swagger documentation](https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation)
