### ISSUE TITLE
Pit Display Font and color

### ISSUE THREAD

**Issue by linkoontz** [FIRST-Tech-Challenge/scorekeeper#318]
The pit display font needs to be adjustable.   We need to display the scores and rankings and the font is so small that it is hard to see unless you are real close to the display.  If we attempt to zoom or make the window bigger, the font size does not adjust like it does on other windows.     It is also very hard to see when the scores have the blue or red background.  Can we have an option to run a pit display that is all white background with black text and no color behind any of the text?   It is simply not very usable in its current format.

**Comment by adwiii** [comment]
We have doubled the pit display font size in 0.7.5, but the coloring remains the same.

**Comment by adwiii** [comment]
In v1.0.0, we have added a number of improvements to the pit displays that hopefully make them more reader friendly.
