### ISSUE TITLE
Randomization Doesn't Feel Random

### ISSUE THREAD

**Issue by jkelbick** [FIRST-Tech-Challenge/scorekeeper#320]
One of the two fields we ran this weekend came up with gold in the middle position for 10/12 matches. Is there anything that can be done to make the randomization feel more random?

**Comment by cmacfarl** [comment]
The software uses the Java Random class, and while it instantiates a new instance of Random for each invocation, the Oracle documentation on the subject indicates that the seed is very likely to be distinct from any other invocation of the constructor.  

See: https://docs.oracle.com/javase/8/docs/api/java/util/Random.html

I personally have not seen this at any of the meets I've attended this year.

**Comment by rgutentag** [comment]
At our last event using 7.2 we saw the same thing.  Our first five matches were gold in the center.  Then it started to get more random but many more were gold center than anything else.  I plan to watch our events this weekend to see if the same thing occurs again.

**Comment by jvens** [comment]
I have been running the system every weekend for the last several months now and I have not seen this happen.  In a truly random system any sequence is equally likely to occur including a sequence of 10 centers.  The exact implementation used to choose a random number in the system is these two lines of code:

~~~java
Random r = new Random();
this.randomization = r.nextInt(6) + 1;
~~~

As @cmacfarl mentioned, the `Random()` constructor seeds the random number generator with a distinct value on each invocation.  Therefore the random number is truly random each and every time.

**Comment by adwiii** [comment]
The internal code "rolls a die" (selects a random number between 1 and 6) and then displays this die face on the screen and the corresponding randomization. 

In our testing of running 1000 trials, we found the following results:
![image](https://user-images.githubusercontent.com/9453262/51857930-7cf6cf80-2301-11e9-8387-11a1e5c40f15.png)
with the longest consecutive streak being 9. Interestingly, gold in the center happened to be the least frequent in this test, even though that is what was noted as being the most above.

The fact that there are only 3 choices for the gold position means that it is very likely that there will be a perceived bias, especially given that our sample sizes are small across one event. 

After the season we can try to do some more aggregate data collection and see if that warrants a change in the randomization methodology, but at this point we do not feel that there is sufficient statistical evidence to warrant a change.

**Comment by HDMScot** [comment]
Data wins! You have shown the data that I suggest closing the issue for now.
