### ISSUE TITLE
Alliance Colors Not Showing When Printing Match Results 

### ISSUE THREAD

**Issue by ZMcElroy** [FIRST-Tech-Challenge/scorekeeper#321]
When printing the match results page either physically or to a PDF it will not show the color background behind the score for which alliance won. I have tried this in Chrome, Edge and IE with the settings turned on to allow the printer to print the background images and colors and still it does not print them.

**Comment by HDMScot** [comment]
+1 for us on this. We thought it was the driver for the selected printer, but today confirm that any method and any platform we tried does not show a color version or backgrounds when using the 'Print' button on the top-right of the reports.

**Comment by adwiii** [comment]
This is the expected behavior. The color gets removed when it goes into print mode, as we expected people did not want to print large amounts of color. We keep the "R" or "B" printed next to the score to serve as indicator when the color is gone.

We can consider this a feature request to give the user the option to add the colors when printing.

**Comment by HDMScot** [comment]
I'll "give you this one" in how you built the reports,  but keep in mind that if I don't want my color printer to print color, I select "Print Greyscale/B&W Only" in my print driver or preferences locally.

I distribute the reports electronically, so I intend to retain as much visual layout and identification as possible. Right now, I print the report not using the 'Print' function, just so I can keep the colors.

**Comment by adwiii** [comment]
As of v1.0.0, there is now an option to "Keep Background on Print" on the Match Results page.
![image](https://user-images.githubusercontent.com/9453262/64707446-028a5280-d481-11e9-8e92-44b594fa1877.png)

When selected, the winning alliance background color will be preserved on print. This only works in Chrome.
