### ISSUE TITLE
Match Controller user not working

### ISSUE THREAD

**Issue by bbugert** [FIRST-Tech-Challenge/scorekeeper#323]
When creating a user and giving access to Match Controller. Shouldn't that login be able to see and access the Match Control on the Dashboard? I setup a login and only granted access to Match Controller (release 7.4}. When I logged on with that new user, on the dashboard I do not have the choice to select Match Control Page.

**Comment by bbugert** [comment]
![match user](https://user-images.githubusercontent.com/19382444/51907916-157e6580-237d-11e9-8d8b-abc930c0cdd8.JPG)
![dashboard](https://user-images.githubusercontent.com/19382444/51907933-2333eb00-237d-11e9-9940-3ea7d54dc46e.JPG)
You can see I have the user with a role of match controller and on the next image at the bottom there is no match control page to select.

**Comment by adwiii** [comment]
As of v1.0.0, the Match Controller role has been removed. The Match Control page can only be accessed with the Event Admin role.
