### ISSUE TITLE
Audience Display "key" for sharing with audience?

### ISSUE THREAD

**Issue by FTCCoachLinda** [FIRST-Tech-Challenge/scorekeeper#324]
I am wondering if anyone has put together an Audience Display "key" for helping audience members read the live scoring display? I would like to include it with the one-page game description at my League Tournament this weekend to help the audience follow along better. I know this is not a software issue, but I wasn't sure where else to ask the question. The scorekeeping manual doesn't even say way the different areas of the display represent (though someone very familiar with the game can figure it out). Anyone have something they can share?
Thanks!

**Comment by adwiii** [comment]
This is a work in progress on our side, and will include the new graphics for the field display/video overlay too. If anyone else has already made something similar, feel free to share here.

**Comment by pmichaud** [comment]
Here's a screenshot of the live display if someone wants to work on this.  I also have invited some of my students to come up with a one-pager as well; will post if they come up with anything.

![screenshot_20190129_134345](https://user-images.githubusercontent.com/41962/51936282-703fad80-23cd-11e9-8b7a-b8846b605e25.png)

**Comment by vchposton** [comment]
I created an explainer.  Feel free to use if you don't have anything else.

1)  Robot latched on lander, either at the start or at end game
2)  Robot grayed out=not eligible for landing in autonomous
3)  Mineral field - gray means knocked out of position
4)  Depot claimed or not (up is claimed)
5)  Robot in crater ("partially in" is off the edge as shown)
     (A is Autonomous, E is End Game)
6)  Silver/gold in cargo holds
7)  Minerals in depot, gold + silver total
8)  Usual stuff: team numbers, score, match timer


![scoring_live_annotated](https://user-images.githubusercontent.com/7231244/52385228-8553b680-2a35-11e9-89d5-7bab13eeb175.png)

**Comment by adwiii** [comment]
We are very happy to have this available for the start of the SKYSTONE season :grin:

On the Match Control page, on the Video Switch tab under the Other Displays section there is a Show Audience Key button. This will cause displays that are not otherwise busy to show the audience key specific for that type of display (Overlay is different from Audience Display, etc). Try it out for yourself, and we will be publishing more info about it in the future.
