### ISSUE TITLE
Dual Division Pit/Match Displays

### ISSUE THREAD

**Issue by hightechkids** [FIRST-Tech-Challenge/scorekeeper#327]
Is it possible to show the division name on top of the Match Results and Pit Display Screens? Might be nice on the Scoring/Timing Display, but that's not as necessary, since it's by the field.

**Comment by adwiii** [comment]
I am not sure if this was an addition in v1.0.0, but regardless this is now supported. It shows the division name at the top of the split pit display and at the bottom for the single division pit display.
## From the finals event
![image](https://user-images.githubusercontent.com/9453262/64713758-73366c80-d48b-11e9-9399-1a08c9de85c4.png)

## From the division
![image](https://user-images.githubusercontent.com/9453262/64713783-7f222e80-d48b-11e9-8d17-58da16aa2f07.png)
