### ISSUE TITLE
Enhancement: Add team numbers to Cycle Time report

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#328]
Put the red and blue alliance team numbers in the cycle time report to help remind us aging FTAs which team caused the delays (if there are any).

**Comment by wdschei** [comment]
@emmell620 and refs too. LOL.

**Comment by HDMScot** [comment]
I would concur that the Cycle Time Report could have additional information in it so it's more useful. As noted in another issue, it currently does not accurately take into account the breaks. When I reviewed the report with some people during our large event, the question being asked was "what teams were on the field?" and "are there any notes about what happened here?". So just like the FTA report where there are some associated notes, perhaps that could be added as well.

**Comment by adwiii** [comment]
Lots of new options are available for the Cycle Time report.
![image](https://user-images.githubusercontent.com/9453262/64713928-bd1f5280-d48b-11e9-962a-28fffd0beba4.png)

The teams checkbox will hide or show the 4 team columns. A team that was marked as a no show will be denoted in parentheses. The detailed checkbox will hide or show the 5 columns for Red/Blue review lag and total time. The Red/Blue lag indicates how long from the end of the match until the referee entered review. The Red/Blue total time indicates how long from the end of the match until the referee submitted review. The total review time indicates how long from the end of he match until the score was committed.
