### ISSUE TITLE
Dual Division Inspections Input/Status

### ISSUE THREAD

**Issue by hightechkids** [FIRST-Tech-Challenge/scorekeeper#329]
An enhancement and probably not an easy fix. I've noticed that if I open Inspection Report in the Inter-Division Finals event, status entered via the individual divisions (*_1 and *_2 events) is not displayed. As suspected, all 3 events have separate inspection data chunks. If there were a way to link these, it would be nice. Entry would be via division based inspectors, but a single display could then show teams in both divisions.

**Comment by adwiii** [comment]
You can run the inspection from the *_0 event and it will unify the display as you noted. In your scenario, could you have the inspectors use the *_0 event too? The *_1 and *_2 displays would then be empty, but it would show the correct status in the *_0 display.

**Comment by hightechkids** [comment]
Yes, that is what we will do. We have separate inspections stations set up,
but our inspectors will simply select teams from the full list ( the *_0
event.) And, of course, our displays will use the *_0 event as well for
inspection status.

Thanks,
Norm

**Comment by maths22** [comment]
This has been in the scoring system for the past couple of seasons
