### ISSUE TITLE
Issue Cards from Scoring Tablet

### ISSUE THREAD

**Issue by jkelbick** [FIRST-Tech-Challenge/scorekeeper#331]
Please give the referees/scoretrackers the ability to issue cards. Currently, someone has to go to the score table to issue a card, and that can only be done after the final scores are submitted. The fact that cards cannot be issued by a referee, and a head referee must go to the score table to have cards entered, has already resulted in several cards being forgotten about. Before we moved to tablets, referees recorded yellow/red cards on paper score sheets without a problem.

These events are already hectic enough. The goal should be to work within the existing referee workflow and not add additional steps. The head referee already discusses all penalties with the referees, and the referees are already entering all penalties to the tablet, so that is the natural point to enter cards.

**Comment by rgutentag** [comment]
There is a head referee role in the create user command.  Why not allow this role to issue red/yellow cards.  A head referee should have a tablet so when they talk to students in the question box can look at the score sheets for the match in question.

**Comment by pstrones** [comment]
As a scorekeeper at the scoring table, we have not experienced any issues with yellow/red cards being put in after the teams have been informed of the card being issued and the scores being submitted, our understanding is those must be entered into the system once the team has been talked with.  We actually haven't had to issue very many at our tournaments and there are times that the head ref is consulting with the scorekeeper to confirm/edit scores anyway.  We have not run into an issue that this request would be necessary.  This all happens while the field is being cleared and reset for the next set of teams competing.

**Comment by jkelbick** [comment]
> There is a head referee role in the create user command. Why not allow this role to issue red/yellow cards. A head referee should have a tablet so when they talk to students in the question box can look at the score sheets for the match in question.

This is a good idea, but at most events, the head referee does not have a tablet. Since entering these cards is the responsibility of the referees when we're using the paper score sheets (event today), it doesn't make sense to take that responsibility away from them.

**Comment by jvens** [comment]
Link to the start of this thread in #313

**Comment by jkelbick** [comment]
> As a scorekeeper at the scoring table, we have not experienced any issues with yellow/red cards being put in after the teams have been informed of the card being issued and the scores being submitted, our understanding is those must be entered into the system once the team has been talked with. We actually haven't had to issue very many at our tournaments and there are times that the head ref is consulting with the scorekeeper to confirm/edit scores anyway. We have not run into an issue that this request would be necessary. This all happens while the field is being cleared and reset for the next set of teams competing.

I'm not assigning blame to any specific role. All I'm saying is that cards are being given to teams, announced, and never entered into the computer because the head ref doesn't talk to the score table, the score table doesn't enter the card, the score table forgets to hit save, etc. The referee manual explains that cards are to be given immediately at the end of a match, so there's no reason that a scoring referee couldn't enter the card.

Again, this is the referee's responsibility when we're using paper score sheets (even today), so I see no good reason to take this responsibility away from them.  Head Referees will continue having discussions with scorekeepers as needed, just as they did before this scoring system was created.

**Comment by jkelbick** [comment]
> How many cards are your referees giving out that this is becoming an issue? I have been to over a dozen events this season and have only seen one single yellow card given out.
> 
> You are correct that it is the Head Referee's responsibility to give out the card and part of that responsibility is to walk over to the scorekeeper table immediately following the match and asking them to give the card to the offending team. The scorekeeper is the person who has been trained in how to enter a card and how to save the match score after a manual edit.
> 
> Yellow and Red cards are a big deal and there should be a process in place where the head ref explicitly communicates to the team and then to the scorekeeper so that there is never a case of a card being accidentally given to a team or given to the wrong team. In fact, I think an argument could be made for removing the yellow and red cards from the paper score sheets and requiring the head ref to talk to the scorekeeper in that case as well.

You could certainly make an argument for that, but the fact remains that the score tracking referee has always been responsible for recording yellow and red cards, and that responsibility should not be taken away in one area and not in the other. In case there's any ambiguity, I believe this responsibility should remain with the referees.

**Comment by pstrones** [comment]
With this being the first year for this scoring system, I can say that it has many of the same qualities that we follow while scorekeeping in FRC.  Yellow/Red cards are not entered from paper or the referee pads in FRC, it is the responsibility of the head referee to inform the team and then communicate with the score keeper.  What I have noticed is that while we have done things different for FTC, we are utilizing features that are consistent with FRC.  I am not placing blame on anyone for who should be doing what but we are evolving the past methods to follow the guidelines established for FTC.

**Comment by jkelbick** [comment]
> With this being the first year for this scoring system, I can say that it has many of the same qualities that we follow while scorekeeping in FRC. Yellow/Red cards are not entered from paper or the referee pads in FRC, it is the responsibility of the head referee to inform the team and then communicate with the score keeper. What I have noticed is that while we have done things different for FTC, we are utilizing features that are consistent with FRC. I am not placing blame on anyone for who should be doing what but we are evolving the past methods to follow the guidelines established for FTC.

Although a Head Referee role exists in the software, it currently has the same capabilities as an unauthenticated user. Additionally, FIRST has not told affiliate partners that Head Referees will need a tablet, so many head referees will not have one. Until those things change, these suggestions put the cart before the horse.

**Comment by emmell620** [comment]
Gentlepersons:  Please note that the developers that read through all of these requests must go through FIRST Tech Challenge staff to prioritize them (assuming they are not major bugs) and then schedule when to work on them to be placed into the queue for addressing.  These developers are doing this chore, like all of us, as volunteers to help FIRST succeed in its mission.  As a volunteer and scorekeeper, I also have placed items in the queue (both bugs and enhancements) and eagerly await their implementation. But I understand that there are other things to be worked on beforehand by our wonderful FTC staff.  Please be patient with any requests for what you may consider to be a show-stopper, but may be determined by FIRST as a nice feature to add.  Thank you to all of you for what you do to "change the culture".

**Comment by adwiii** [comment]
With the new Head Referee features added in `v3.3.7`, the Head Referee has the option to enter Yellow and/or Red Cards to the Team(s)/Alliance(s). Assigning a card in this way will automatically activate the "Match Under Review" workflow at the end of the match. Please see the release notes and internal feature documentation for more information.
