### ISSUE TITLE
Field and audience display are not synchronized

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#332]
For example, the field display showed that there was 3 seconds while the audience display played the buzzers sound and showed that the match was ended.

This is a really big issue.

**Comment by ofekashery** [comment]
I think it's something with the loading time of the digits images.

I would add the following code and add the ``Cache-Control`` header to the images.
```js
// Preload digits
if (document.images) {
    const digitsPath = '../../blah/blah/blah';
    const colors = ['B', 'G', 'R', 'W', 'Y'];

    for (const color of colors) {
        for (let i = 0; i < 10; i++) {
            new Image().src = digitsPath + `/${color}${i}.png`;
        }
        new Image().src = digitsPath + `/${color}colon.png`;
        new Image().src = digitsPath + `/${color}colonoff.png`;
        new Image().src = digitsPath + `/${color}digitoff.png`;
    }
}
```
Then, all the digits images will be loaded from the browser's cache.

**Comment by maths22** [comment]
This should be resolved in in v3 (for Freight Frenzy), please reopen if you see this happening this season.
