### ISSUE TITLE
Ability to hide the scores from the field timer

### ISSUE THREAD

**Issue by YeveRivkin** [FIRST-Tech-Challenge/scorekeeper#338]

**Comment by adwiii** [comment]
If you mean hide the scores completely during the entire match, you can do that already.
In the settings for the display where you select it to be a Field Display, there is a checkbox for live scores:
![image](https://user-images.githubusercontent.com/9453262/52138292-bc336200-261a-11e9-8c47-8627bd98eaca.png)
This box is checked by default, but unchecking it removes all of the scoring information from the page:
![image](https://user-images.githubusercontent.com/9453262/52138248-99a14900-261a-11e9-99f1-1c38fcc9e003.png)
The scores will still display on all other displays that have the checkbox selected.

I am closing this issue as I believe this satisfies the request. If this is meant to be a similar request to #337, then we can keep this closed and use that issue instead. If what I said here does not match what you meant, then we can reopen and discuss.
