### ISSUE TITLE
Match sound repeats itself

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#340]
Video:
https://photos.app.goo.gl/oA5t8pTKbaDRWMoR7

Except for the first sound in the match, they all repeated themselves.
No, there's nothing open twice.
Also, The sound started 4 seconds before the end of the match(maybe #332 or #333)

**Comment by HDMScot** [comment]
We experienced this at two events and at both it was confirmed to be two instances of the display running. It was found to be out-of-sync displays as well...another listed bug for the displays.

**Comment by maths22** [comment]
This should be resolved in in v3 (for Freight Frenzy), please reopen if you see this happening this season.
