### ISSUE TITLE
Add other inspection like tracking

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#341]
Add the ability to track other custom scheduled things similar to inspections.  At the Iowa Championship we schedule each team with a slot to have a team picture taken, and it would be nice to track teams progress through that just like check-in, robot inspection, field inspection, and judging.

**Comment by tfullmer76** [comment]
Hello,

You can already do what your asking.

From your event dashboard select #5 Create Judging & Inspection Schedule
Under ACTIVITIES (right side) - add an activity for a TEAM PHOTO by typing in the required information.
![git hub 1](https://user-images.githubusercontent.com/39835160/52310443-a3031c00-2960-11e9-9f64-f4581da2c9fa.PNG)

Remember to click ADD after you have filled in the new ACTIVITY information.
![git hub 2](https://user-images.githubusercontent.com/39835160/52310473-bf06bd80-2960-11e9-9054-83a3671da6ce.PNG)

The INSPECTION & JUDGING activities are automatically added under the ACTIVITIES column. You can delete any of them if you don't need them.

Good Luck!

**Comment by jvens** [comment]
This will allow for using the score system to schedule additional activities but not the ability to track them.  What I want is to have something similar to the Judging and Check-in inspection pages where you can mark teams as complete.  This way the photographer can have a tablet with them and mark off teams as complete as they get their picture taken.  This way it will show up in the Judging & Inspection Status display.

**Comment by tfullmer76** [comment]
Oh. That makes sense. Great idea!

**Comment by tvbarnette999** [comment]
This has been added in v1.0.0. Use the "Configure Judging/Inspection Tracking" Dashboard item to get to the "Status Tracking Configuration" page. A new "Custom Tracking" section has been added, where you can enter custom items that will appear on the status grids and inspection sections:
![image](https://user-images.githubusercontent.com/13516182/64710338-c1487180-d485-11e9-9a1e-4cf57f454576.png)


It will then appear as an option in the Status-Bind dropdown in the schedule editor if you want to automatically mark a team LATE/VERY LATE to this item:
![image](https://user-images.githubusercontent.com/13516182/64710442-f785f100-d485-11e9-86bc-51e4bf4c157c.png)

It will appear on the event home page for accounts with the "Inspector" role, and the link will take them to a page that matches the LRI override pages for other form types.
![image](https://user-images.githubusercontent.com/13516182/64710488-0d93b180-d486-11e9-8c3c-87be8919ad65.png)

And it will appear in the grid using the abbreviation provided:
![image](https://user-images.githubusercontent.com/13516182/64710593-3a47c900-d486-11e9-97ea-ec306f33f04a.png)
