### ISSUE TITLE
Cycle time report incorrect after break

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#342]
There is a bug that causes the cycle time report to put that first match after a break as the last match before a break instead.  Below is an example from today's event.

When we set up the match schedule we added the break for lunch at the appropriate time.  This was the schedule we used:
![image](https://user-images.githubusercontent.com/7074504/52172345-250dfd80-2733-11e9-8f66-cbac69f6a917.png)

This is the match list that it generated which shows the matches each starting at the correct times, and lunch starting at the scheduled time.
![image](https://user-images.githubusercontent.com/7074504/52172352-39ea9100-2733-11e9-9453-cd0f4f39c990.png)

And here is the cycle time report that incorrectly shows match 11 running at the time lunch was scheduled to start instead of the first match after lunch.  This causes the cycle time report to be off by one match in the afternoon and show us farther behind schedule than we actually were.
![image](https://user-images.githubusercontent.com/7074504/52172376-9483ed00-2733-11e9-81fe-cc564628f703.png)

**Comment by HDMScot** [comment]
We experienced this as well and you did a good job documenting it.

**Comment by adwiii** [comment]
This has been fixed in 0.7.6
