### ISSUE TITLE
sponsor display

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#347]
Would like to be able to display the sponsor on a separate display from the audience display.  This might be put up on the pit display device until matches begin for an example.  Our audience display usually shows inspection status until matches start.

**Comment by pstrones** [comment]
When running 7.4 we noticed that when utilizing the video switch for displaying the sponsors we couldn't toggle back to the other screen, we were stuck on that video until the matches started/resumed.  We could toggle to alliance selection, however it wasn't time for alliance selection.  We have not utilized 7.5 but will be this weekend, not sure if it is an issue in that version.  It would be nice if we could toggle on and off when displaying sponsors via the video switch.

**Comment by adwiii** [comment]
@rgutentag the sponsors are shown on any of the displays (Field, Audience, Overlay) while the inspection status is displayed on its own screen. You could set up an Audience display and then use the video switch to have it show sponsors and then load the inspection status on another screen.

@pstrones what would you like it to swap back to? The screen will automatically swap to anything else that it is told to do, but as you say if there is nothing else happening then it will stay on the sponsor screen.

**Comment by jvens** [comment]
@pstrones you can always click `Show Match` to get back to the normal match display screen on the audience displays.

@adwiii, There is still a use case for a dedicated sponsors display.  For example, an event might have a display that is just scrolling the sponsors throughout the day in addition to the audience and pit displays.  There is a fairly easy work around of creating a second dummy event and using that for this display, but I can see a valid use case for this request.

**Comment by pstrones** [comment]
we typically have a live streaming going and the audience display going which it would override both.  Being able to toggle back to the rover logo when matches haven't been generated yet (we were waiting on teams to confirm participation before generating the matches).

**Comment by adwiii** [comment]
This has been added in 0.7.6. Select "Sponsors Only" from the Display Mode dropdown on the Display Options:
![image](https://user-images.githubusercontent.com/9453262/52742409-aa9c7380-2fa5-11e9-9ba9-3d4da3ab476e.png)

**Comment by rgutentag** [comment]
Can you reopen this request.  As implemented when you create a display only login the sponsor only is able to be clicked but it doesn't show any sponsor info.  To be able to show the sponsor info I had to give my display login the event management function to show the sponsor info.

**Comment by adwiii** [comment]
This has been fixed in v0.7.7

**Comment by emmell620** [comment]
Please reopen.  Still flaky on switching screens when overlay is used on Audience Display.  Recreated by Showing Overlay screen. Clicking on Show Sponsors in Video Switch (works), Clicking on Show Bracket (works). Clicking on Show Sponsors -2nd time (doesn't work).  The Heading says "Thank You to Our Sponsors", but the screen is the Bracket.  Same thing when Show Match is thrown in the mix as well.

**Comment by adwiii** [comment]
This has been fixed in v1.0.0. Display users can open displays that are configured to be sponsor only, and the overlay now properly supports moving between screens.
