### ISSUE TITLE
Add team information to Competing Teams Report

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#348]
Please add the following additional columns to the Competing Teams Report added from #346.

- City
- State
- Affiliation

**Comment by fredsayson** [comment]
what is the password and the user please

**Comment by adwiii** [comment]
The default account has username "local" and no password. This account only works on the machine running the scoring software.

**Comment by adwiii** [comment]
To address the first issue here, there are now checkboxes to select what columns show on the Competing Teams Report.
![image](https://user-images.githubusercontent.com/9453262/52742293-6ad58c00-2fa5-11e9-853d-b9ca56f68b9f.png)
![image](https://user-images.githubusercontent.com/9453262/52742317-7759e480-2fa5-11e9-9144-430b338e8a92.png)


Separately, the login page now tells you the default account if running on the local machine:
![image](https://user-images.githubusercontent.com/9453262/52742143-1af6c500-2fa5-11e9-8210-1246fcac5bd0.png)
