### ISSUE TITLE
Allow switch division from the header

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#349]
![image](https://user-images.githubusercontent.com/16443111/52421521-e1cdd900-2afc-11e9-8954-257413749ddc.png)

**Comment by adwiii** [comment]
This has been added in v1.0.0. The link takes you to the home page for that sub-event.
![image](https://user-images.githubusercontent.com/9453262/64707814-96f4b500-d481-11e9-90fa-6cf946c88dd7.png)
