### ISSUE TITLE
Enhancement: Dual Division Sponsor

### ISSUE THREAD

**Issue by hightechkids** [FIRST-Tech-Challenge/scorekeeper#350]
It would be nice if Sponsors flowed from the dual division event (*_0) to the divisions (*_1, *_2) rather than having to add them to all 3 events.
For the long run, it would be nicer if I only had to insert my regional sponsors once, rather than having to re-import them for every event.

**Comment by maths22** [comment]
The first half of this request is resolved in v3.2.4
The second half is resolved through ftc-scoring.firstinspires.org, where regional sponsors can be entered that will be loaded into every event.
