### ISSUE TITLE
Not an Issue - Dual Division Tournament Comments

### ISSUE THREAD

**Issue by hightechkids** [FIRST-Tech-Challenge/scorekeeper#353]
We ran our 48 team dual-division State Championship this past weekend (Ver. 0.7.5) and it ran great. No issues, no problems.  We uploaded our teams including division selection and already advancing into the *_0 event and ran our inspections out of event *_0.  We then split to *_1 and *_2 events for match play. We did NOT do live-scoring. (Early in the season we had issues with it and decided not use it and wanted to be consistent throughout the season. We plan to use it next year.) Instructions for dual-division finals were clear and we had no problems generating and running it.  Award assignment and advancement report entered and generated out of the *_0 event. By the way - we ran with a single server for the entire event. Match control for the 2 divisions were done with computers connected to the server. (No export and import.)

 I was a bit concerned last fall when updates were being made, problems created and resolved.  Dual Division support arrived later in the season and there were some issues just last week.  But this submit is just a THANKS for addressing issues promptly, explaining concerns, etc.  Getting it all a few months earlier might have been a bit less stressful, but that's the development world.
For the folks who have emailed me about my issues, helped me through some steps, and done all the behind-the-scenes work - THANK YOU.  I'm looking forward to using a very similar system next year.

**Comment by adwiii** [comment]
I am glad you had a good experience with the software! We are always happy to help :smile:.
