### ISSUE TITLE
Print Inspection And Judging Schedule

### ISSUE THREAD

**Issue by YeveRivkin** [FIRST-Tech-Challenge/scorekeeper#354]

**Comment by mcchesneyc** [comment]
I have been copying into MS Excel.  Then you can do sorts other than by team number.  Team number sorts are great for the team, but not so useful for judges or robot/field inspectors.  When print capability is added it would be useful to allow a time sort by station for the benefit of the volunteers who are conducting inspections.

**Comment by adwiii** [comment]
As of v1.0.0, the schedule can now be printed. Only the table will be printed - the colored timing view at the bottom will not.
![image](https://user-images.githubusercontent.com/9453262/64710252-9bbb6800-d485-11e9-942e-10ca70eaf6e0.png)

Will print as:
![image](https://user-images.githubusercontent.com/9453262/64710317-bb529080-d485-11e9-921a-05d045d22b06.png)
