### ISSUE TITLE
Match Details Route for _0 Dual Division event is broken

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#359]
For instance, getting 
`http://localhost/apiv1/2019/events/my_dual_division_0/elim/finals/1`
returns 
```Json
{
    "errorCode": "NO_SUCH_EVENT"
}
```
When in fact an event does exist, because 
`http://localhost/apiv1/events/my_dual_division_0/elim/finals/1` does have data

**Comment by tvbarnette999** [comment]
This has been addressed in v0.7.8.
