### ISSUE TITLE
Logistical issue: Need logistics for handling timeouts for multi-field tournaments

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#361]
This may be an issue for FIRST to handle, but it would be nice to have the full logistics to handle timeouts when dealing with multiple fields.  Given turn times between fields of 5 minutes or less, the field timeout and the alliance timeout can be confusing at times.

**Comment by tvbarnette999** [comment]
Handling timeouts across multiple fields is now implemented as part of the new elimination timing.
