### ISSUE TITLE
Countdown Timer should be modernized

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#362]
In my opinion, the current timer display (the retro scoreboard-countdown style) is unappealing and can in some cases be difficult to read.  This should be replaced with a simple Text display, in an easily readable font like Ariel or Times new roman. In a color that can stand out from the background, such as white for this season.

**Comment by HDMScot** [comment]
Very much agree...but this year the focus needs to continue being on functionality. Post-World Championship(s), there should be effort put towards making this better, but there are still too many issues with the existing software.

**Comment by jvens** [comment]
I agree and want to bring this up again.  This screenshot I think shows how out of place the timer feels on the display.  Everything else looks modern with nice sharp edges and lines and then it looks like the timer was just overlaid over top of it all.  Maybe at a minimum add some black border around it so there is more than one pixel between the edge of the numbers and the edge of the black.

![image](https://user-images.githubusercontent.com/7074504/64657676-2bb3d000-d3fa-11e9-9a7f-dd10169512b9.png)
