### ISSUE TITLE
Reworked scoring display designs

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#364]
This isn't really an issue, but a proposal/suggestion for next season.  I reworked several of the displays to look more polished and be clearer to the audience.   For the live-score displays, I went with the idea that they should present things that are hard for the audience to tell just looking at the field (this year, minerals); things that are easy to see, like if a robot has landed, don't get broken out on the display.

[FTC_Scoring_Display.pdf](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2923529/FTC_Scoring_Display.pdf)

**Comment by adwiii** [comment]
We appreciate the input. We hope you like the SKYSTONE displays, and continue to welcome feedback on them.
