### ISSUE TITLE
Scores Don't Add Up and Somehow Winning Finals Match #1 = Winning the Series?

### ISSUE THREAD

**Issue by jkelbick** [FIRST-Tech-Challenge/scorekeeper#365]
![Finals Match 1 Results](https://lh3.googleusercontent.com/s17LuCSix-V-Tmqy1QXbBPoXzqQi3Ss16TTWqNpyaELmo2fQccIPksBuM3Rxb_W_MqMK8ocHuJnzLfB1C354M0sHz4G7eMKOzEEErPVkPOu064ptolz5Iu2HnJ85u9NY_ZYsRqKUy--MKhbihUNjYiErvFZ-hQU5kjopC6gSWC9_FU6R92ZaJmLgKWl6ioxqfzqs7j2k5CbIQHMze6cjLcLXAU6clhFrhDD8QXj2TdEkdfI3mOnKQolzKU9RsBcyG9SuUbD8V_wM3LX40nDo1uRqQFQjLClKqbq3vmHKmIhhJaYMJy6OrnHC4pCk62m75Bxmqp6Ghzmh5CzNtiNFMSoxrU2t_5YOoJbBR7dOzWm-heDsCpS9UNMYSSAFbEZUYC_DR_MiGYK3qkEXFPgTXmK1PZa05iC8ClF0QPXPn4iu3PkznlaMnPSkAIc7-5cn7NAt2X1N-QVhUs5Y5QQI5RrEMTctBk1fFzsnG778lfK0bD5f6m_55uFCoJ7N9exjIW96fE2gp0W1JR3_kYdh-8kzfxQR-iFv62Oo_xGWnKHK84b8HkRx5wvu62oZ5sRKv6Pu9h_gkcopoWUrCMc0VL9qmX24ngBoXxL1n_ts6eLqYW41bp8qC1rLuQAN4N1fxyXtWjugPBiZsyNnyILriaZKbLFois0c=w920-h522-no)

The picture above should say it all, but just in case, the scores for the red alliance do not add up (150+174+100 = 249 now?). Also, please note that these results were for Finals Match 1, and yet somehow we have a winner for the series (which should've been best of three)?

**Comment by adwiii** [comment]
What state was the event in at this time? Had Finals 1 just been played and posted for the first time? Were there any issues with committing matches (popups from the match control page)?

Also, any log files and the event db would be helpful.

**Comment by jkelbick** [comment]
> What state was the event in at this time? Had Finals 1 just been played and posted for the first time? Were there any issues with committing matches (popups from the match control page)?
> 
> Also, any log files and the event db would be helpful.

This was yesterday at the Maryland State Championships, Opportunity Division. This was the first running of Finals Match 1. The lead scorekeeper (who has a lot of FTC experience) did not report any abnormalities from his end.

**Comment by jkelbick** [comment]
@wcraigtrader Can you shed any additional light?

**Comment by adwiii** [comment]
Okay. Judging by the results on [ftcscores.com for this event](https://ftcscores.com/event/2LCHDbgh) it appears that the scores being shown here are partially those from SF2-2. This likely means that there was an error in the display when rendering F-1 which caused it to get partially through updating the data from SF2-2, but not complete. This explains why the scores don't add up - the final score for red matches the final score for red from SF2-2, but the breakdown matches that of F-1.  This also explains the "Blue Wins Series!" because that was also from SF2-2.

It appears that the backend had all of the data correct - were you able to play F-2 and F-3 without issue? If so, then this appears to just be the display throwing an error, which we can look into. We received a similar report from another event this weekend and believe we have isolated the issue.

I know Finals is not a good time to have display errors cropping up, and I do apologize for the high profile issue.

**Comment by jkelbick** [comment]
> Okay. Judging by the results on [ftcscores.com for this event](https://ftcscores.com/event/2LCHDbgh) it appears that the scores being shown here are partially those from SF2-2. This likely means that there was an error in the display when rendering F-1 which caused it to get partially through updating the data from SF2-2, but not complete. This explains why the scores don't add up - the final score for red matches the final score for red from SF2-2, but the breakdown matches that of F-1. This also explains the "Blue Wins Series!" because that was also from SF2-2.
> 
> It appears that the backend had all of the data correct - were you able to play F-2 and F-3 without issue? If so, then this appears to just be the display throwing an error, which we can look into. We received a similar report from another event this weekend and believe we have isolated the issue.
> 
> I know Finals is not a good time to have display errors cropping up, and I do apologize for the high profile issue.

I hadn't noticed the scores matching SF2-2, so it's nice to see some logic behind this error, but it's worth pointing out that a completely different alliance received that score in SF2-2. You're right, division finals at a state championship are a particularly bad time for this to occur, but luckily announcer recognized the issue and explained it before the audience had a chance to get too excited. 

I wasn't behind the score table, but I've reached out to our FTA and Lead Scorekeeper for comments and a copy of the logs & db.

I appreciate the apology, but my larger concern is that this might've gone unnoticed for lower profile matches, either at the state champs yesterday, or just at any qualifier. Luckily, I've done a lot of FTC events this year and this is the first time I've seen this issue. Honestly, this software has come a long way in the 5 months I've been using it, so a bug like this was bound to come up... As long as you can fix it for World's, I think we'll be OK.

**Comment by maths22** [comment]
This is resolved in v3 (for Freight Frenzy).
