### ISSUE TITLE
Add match times to the API

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#366]
``actual_time``: The time that the scorekeeper clicked _Start Match_
``scheduled_time``: The time of the match according to the schedule
``post_result_time``: The time that the scorekeeper clicked _Post Result_

(use unix timestamps)

I'll help so many things like automated cutting of full gameday stream to each match video, to show the schedule on TOA, and more.

**Comment by adwiii** [comment]
As of v1.0.0, the system now returns the `startTime`, `scheduledTime`, and `resultPostedTime` in the api. Information that is unavailable will return `-1`, for example if the match has not started, the schedule is marked as private (see #198), or the match has not been posted yet. See the [swagger documentation](https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation) for more information.
