### ISSUE TITLE
Calculating TBP at league tournament

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#369]
This isn't an issue and is probably a GDC question, but since the forums aren't available yet I am not sure a better place to ask this question, and the answer may directly impact the development of the score system.

The new rules for Tie Breaker Points (game manual part 1, section 4.8.1) subtract the lowest TBP score before taking the average for events with 5-6 matches, and subtract the two lowest for events with 7 or more matches.

In the league system teams compete in league meets and then when they go to the league tournament the best 10 scores from all the league meets they attended are taken into the tournament.  In an example of a league tournament with 5 matches does that mean that the two lowest TBP scores are subtracted from the 15 matches (10 from meets and 5 from that event), or is the 1 lowest subtracted from the 5 matches at that event before being combined with the 10 from the meets?

Another edge case; in the case that the two lowest should be subtracted then if a team didn't compete in any league meets, would their average TBP score at the league tournament be based only on 3 matches because the 2 lowest from that days event would be dropped?

**Comment by adwiii** [comment]
Version 1.0.0 supports the changes made to the rankings calculation. If you have additional questions about the ranking system, please direct them to the game forum when that becomes available.
