### ISSUE TITLE
When will Skystone version release?

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#371]
Is there a date planed to release this years score system?  We are running our first league meets in Iowa on October 15th and will be holding our volunteer training conference on October 5th.  It would be preferable to have this years scoring system released before then so we can train our scorekeepers and referees on how to use it.

**Comment by VHSCSteacher** [comment]
Someone said it was going to be release on Monday 9/9.

**Comment by adwiii** [comment]
https://github.com/FIRST-Tech-Challenge/scorekeeper/releases/tag/v1.0.0

As detailed in the release notes, this is not intended for use at events. We will be releasing an event-ready version in early October.

**Comment by jvens** [comment]
@adwiii, when can we expect the event-ready version to be released?  Regions are starting to have their official meets in the next week and it would be nice to have the fully released version for those events.

**Comment by adwiii** [comment]
We were so very close but I didn't want to promise anything in case we ran into issues today 😅 https://github.com/FIRST-Tech-Challenge/scorekeeper/releases
