### ISSUE TITLE
IS THERE A MAC VERSION?

### ISSUE THREAD

**Issue by ArshiaKo** [FIRST-Tech-Challenge/scorekeeper#373]

**Comment by cmacfarl** [comment]
It's a java application.  It will run on Mac.  See page 14 of the documentation here: https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2563026/FTC.Scorekeeper.Manual.v0.5.1.1.pdf

**Comment by ArshiaKo** [comment]
SICK!!!
