### ISSUE TITLE
rankings and results display

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#374]
the rankings and results display does not work.
https://user-images.githubusercontent.com/32021115/64661181-535e6480-d409-11e9-9bb0-1e9cb9b6ebc4.jpg

**Comment by jvens** [comment]
I was able to replicate this issue.  It occurs on the audience display when you click `Show Ranks & Results` button on the `Video Switch` tab of the match control.

**Comment by adwiii** [comment]
I believe this only occurs when the event is a league meet and no match has been committed? Is that the scenario that you were in @jvens @GamingWithaAlexYouTube ?

**Comment by jvens** [comment]
I have matches committed.  Here is what I see on the display endpoint when displaying rankings and results (note the URL is http://localhost/event/test1/display/config/field/false/field/field/true/0/00ff00/true/false/false/false/hybrid/):
![image](https://user-images.githubusercontent.com/7074504/64662856-80157a80-d40f-11e9-8626-e769cfd00d9f.png)

And this is the direct route to the pit display (URL: http://localhost/event/test1/display/pit/):
![image](https://user-images.githubusercontent.com/7074504/64662908-ad622880-d40f-11e9-8739-1f68106ca4ab.png)

**Comment by jvens** [comment]
To add another thing to this issue, I just noticed that display I screenshot as an example is a field display which should probably never show rankings.  I see the exact same issue when it is configured as an audience display as well (URL: http://localhost/event/test1/display/config/ad/false/ad/ad/true/0/00ff00/true/false/false/false/classic/).

**Comment by jvens** [comment]
OK, one more update on this.  I narrowed it down and it occurs for *League Meets*.  I just created an even that is a Qualifier and the ranking page works perfectly.  When the event type is League Meet and I attempt to go to the rankings page it is failing to load `http://localhost/event/test1/display/leaguepit/combined/` because the correct endpoint should be `/event/<eventid>/display/leaguepit/`

**Comment by adwiii** [comment]
Thanks - fixed and will be in the next release. If you want to discuss the rankings on the field display, please open a separate issue to track that.

**Comment by GamingWithaAlexYouTube** [comment]
> I believe this only occurs when the event is a league meet and no match has been committed? Is that the scenario that you were in @jvens @GamingWithaAlexYouTube ?

yes it is in league meets witch for Illinois needs to fixed because we only have league meets. and it happens both when nothing is committed and after matches are committed.

**Comment by GamingWithaAlexYouTube** [comment]
am i able to change it manually for right now until the next version comes out.

**Comment by adwiii** [comment]
This has been fixed in v1.1.0
