### ISSUE TITLE
The extra pages displayed on the field display

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#375]
When the display is set to be a field display most of the non-match related displays do not show with a couple of exceptions.  

Pages on Audience and Field displays (ignoring match related pages that obviously need to be on both):
- Ranking & Results
- Audience Key
- Message
- Alliance Selection
- Blank Screen

Pages only on Audience displays:
- Match Results
- Sponsors
- Bracket
- WiFi Reminder

I don't know what this should be, but some of these seem somewhat arbitrary and I wonder if the community has any opinions on this.  

I personally feel that `Ranking & Results` and `Audience Key` should not show up on the field display because these are pages that an event may go to if their is a short delay getting a match setup.

**Comment by adwiii** [comment]
As of v1.1.0, the Field Display does not show Rankings & Results, nor the message screen. It will only show the Audience Key if it is on a blank screen or Alliance Selection. This is meant so that the Key can be shown if the display is idle, but will not be shown if it is in the match workflow.
