### ISSUE TITLE
Chrome blocking video autoplay

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#377]
The winning alliance video does not play if the user hasn't interacted with the display first (ie clicking it after a refresh) according to Chrome's autoplay policy.

**Comment by adwiii** [comment]
As you mention, this is a Chrome issue and by definition we cannot fix this without user input. 

Is this a request for us to add an indicator to the page that informs the user that they have not interacted with the page and thus sounds/video will not work? We don't want this to interfere with the operation of the display if the user chooses to ignore this, and the pages are supposed to gracefully fail if Chrome prevents the sounds/video from not playing.

**Comment by jvens** [comment]
At a minimum this restriction should be documented in the manual.

Reading through https://developers.google.com/web/updates/2017/09/autoplay-policy-changes I noticed that it says "**Muted** autoplay is always allowed."  Perhaps an option is split the video and audio into two separate files and start them both at the same time.  Not the most elegant solutions, but it would likely solve this issue.

**Comment by bsimmons99** [comment]
I agree with @jvens in that it should at least be documented, it took opening the dev console for me to figure out why the video sometimes wouldn't play.

**Comment by adwiii** [comment]
The "Unmute" button added this year is intended to address this issue.
