### ISSUE TITLE
Preload images and videos on displays

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#379]
Images and videos should be preloaded on the displays such that when the display is switched it doesn't need to download everything before it displays correctly. Very noticeable in some cases with the winning alliance video.

**Comment by ofekashery** [comment]
For the first thing I would add the `Cache-Control` header to all the assets.

**Comment by tvbarnette999** [comment]
The ```Cache-Control``` header has been added to resources in v1.1.0. Note that in our testing, chrome ignores it for the .mp4 files. 

Most images (specifically, timer digits and scoring achievement images), audio, and video were already pre-loaded, but not all of them. Not all of the backgrounds are yet, I'm continuing to work on that. If you are still seeing bad display behavior, please let me know what chrome version you are running, any chrome settings you've customized, and any other details about the setup. (and maybe a picture of your waterfall graph).

**Comment by maths22** [comment]
This is resolved in v3 (for Freight Frenzy).
