### ISSUE TITLE
Access to scoresheets blocked in v1.0.0

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#380]
The scoresheets linked in release v1.0.0 link to files in `event_management_software` repo and are not available from the public scorekeeper repo.

Example: https://github.com/FIRST-Tech-Challenge/event_management_software/files/3593629/Blue_Alliance_Scoresheet.pdf

**Comment by adwiii** [comment]
Updated:

 &nbsp;&nbsp;[Blue_Alliance_Scoresheet.pdf](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3600983/Blue_Alliance_Scoresheet.pdf)
&nbsp;&nbsp;[Red_Alliance_Scoresheet.pdf](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3600984/Red_Alliance_Scoresheet.pdf)
