### ISSUE TITLE
Persistent inspection notes

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#382]
There are times during early league meets where in the process of getting teams through inspection we find something illegal that doesn't give the team a competitive advantage and isn't easy to fix during the event.  An example that I have seen many times is the robot number being too small.  Many times in these cases we give the team a one time exception and tell them to fix it before their next event or we won't pass them.  The problem is it might be a different inspector at their next event that doesn't know that team has already been warned about an issue.

Would it be possible to make it so that notes entered by an inspector for a team would be visible at future events?  This is probably only possible for league meets and league tournaments where you import previous event data into later events.

**Comment by jvens** [comment]
Bump.  This is still a feature that would be very useful to have.  I realize there are lots of logistic issues with it, but I would like to see it stay on the back burner for now.

**Comment by tvbarnette999** [comment]
This has been added in v4.1.1 - previous inspector comments are populated automatically during event setup and are accessible from a button at the bottom of the inspection form.
