### ISSUE TITLE
/api/.../rankings/ should include highest score tiebreaker

### ISSUE THREAD

**Issue by kenpugsley** [FIRST-Tech-Challenge/scorekeeper#384]
The current rankings API only includes RP and TBP.  It should also include the Highest score which is the third tiebreaker.  This should definitely be included in the API response since it's shown on the Rankings report.

Technically there is the fourth tiebreaker ("Random Electronic Draw") that ideally would be nice to also be included, though since it's not included on the Rankings report it's less important.

**Comment by adwiii** [comment]
This is a subset of #121. Please add any further discussion to that issue. Closing as a duplicate.
