### ISSUE TITLE
Display Bind to Field not Binding

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#389]
Binding the display to the field shows information for all matches. I would expect it to only show match previews, randomization and matches for the field it is bound to.
Possibly caused by #388.

**Comment by bsimmons99** [comment]
After applying the fix described in #388, the issue persists. I believe this is a separate issue.

**Comment by adwiii** [comment]
Yes. We have identified a separate potential fix for this issue, but we need to do more extensive testing. Thanks for pointing this out!

**Comment by adwiii** [comment]
This has been fixed in v1.1.0
