### ISSUE TITLE
Eliminations Stuck

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#39]
I seem to have gotten my elimination matches stuck so that I can't save matches one and two, but 3 and 4 are saved.  Every time I commit, if I reload the page, the match is uncommitted again.  I therefore cannot complete the semifinal matches, and final matches do not get generated.

[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2438517/db.zip)

**Comment by tvbarnette999** [comment]
@maths22 Thanks for the db file! When you try to commit matches 1 or 2, does the schedule tab change the match state to COMMITTED before you refresh? If you get a chance, can you try to commit matches 1 or 2 with the Chrome debug console open to the network tab, and see if the commit request returns any error? 

Additionally, in loading your db, I have encountered another problem. Could you also post a screenshot of the rankings page for this event, and what version of Java you are running?

**Comment by maths22** [comment]
Well this is sad...  When I restarted the application, the event `test-event` isn't even loading.

```
[main] ERROR org.usfirst.ftc.global.SQLiteGlobalDAO - Could not add event test-event
java.lang.IllegalArgumentException: 3758 is not next captain.
	at org.usfirst.ftc.event.management.ManagementSubsystem.selection(ManagementSubsystem.java:646)
	at org.usfirst.ftc.event.management.ManagementSubsystem.initSelection(ManagementSubsystem.java:163)
	at org.usfirst.ftc.event.Event.<init>(Event.java:110)
	at org.usfirst.ftc.event.EventsManager.init(EventsManager.java:78)
	at org.usfirst.ftc.server.Server.main(Server.java:223)
```

**Comment by maths22** [comment]
I may have-I was doing a lot of very strange things.  Let me roll back the issues in the db with match one and see if I can repro the other issue.

**Comment by maths22** [comment]
Once I unscored match 2 in the database, everything worked fine with the finals matches.  I have no idea what exactly happened there, but I'm going to close this issue and if I manage to reproduce it later, open a new ticket with a more consistent db.

**Comment by adwiii** [comment]
To save you some time, here is a db that will let you run the event. I removed match 2.
[db - removed match 2.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2439426/db.-.removed.match.2.zip)

**Comment by adwiii** [comment]
Ah, I see you already got it. Thanks for testing it and do let us know if you manage to get back into that state.
