### ISSUE TITLE
Option to Show Field on Match Control Page

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#390]
Enhancement
Add option to see which field a given match is going to play on on the Match Control page.

**Comment by adwiii** [comment]
As of v1.1.0, the Match Control Page now has a column for the field number. Here is an example screen clip from a two field event for Eliminations:
![image](https://user-images.githubusercontent.com/9453262/66600678-05f22600-eb74-11e9-89c0-f9b2656dc22c.png)

Note that Finals Matches (and Inter-Division Finals Matches for Dual Division Events) are always played on "Field 0". Field 0 means that it will behave as if it is playing on all fields at once - all displays, regardless of what field they are set to show will show the finals matches.
