### ISSUE TITLE
Ranking points

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#393]
I am wondering why are the ranking points calculated now. And for it to be simple could it be changed back to normal please.

**Comment by cmacfarl** [comment]
Rankings are calculated per section 5.8.1 of the SkyStone Game Manual.  As such the scoring system must follow the manual.  Software can not be changed in this regard.

Game manuals may be found here:  https://www.firstinspires.org/resource-library/ftc/game-and-season-info

**Comment by jvens** [comment]
Just a small correction to what Craig said: it is actually section 4.8.1 of the Game Manual.

**Comment by cmacfarl** [comment]
@jvens That's what I meant. :-)
