### ISSUE TITLE
Dual Division Elimination Bracket

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#398]
![DualDivisionBracket](https://user-images.githubusercontent.com/32021115/65808959-03e49c00-e15e-11e9-9cb9-847dd18970d6.png)
for dual division events could you create a bracket where it shows both divisions like the picture above. where the left side is one division and the right side is the other. the picture is just an example.

**Comment by GamingWithaAlexYouTube** [comment]
for the bracket display what is the file name i created the bracket and need to know what file type i need to do so it works?

**Comment by jvens** [comment]
@GamingWithaAlexYouTube if you are attempting to print or save the bracket to a PDF then in the event you can go to `Event Reports` and then `Bracket Report` and click the printer icon in the upper right corner.  You can then print the page using a printer or create a PDF document in chrome.  Note that the bracket will be empty until alliances are generated.

If you are wanting to project the bracket for the audience display you will need to create an audience display and then from the `Match Control` page `Video Switch` tab you can click `Show Bracket`.

If you have further questions on creating and setting up an audience display please see the `FTC Scorekeeper Manual` which is linked to on the [Releases Page](https://github.com/FIRST-Tech-Challenge/scorekeeper/releases)

If I have not answered your question then please elaborate with more details on exactly what you are trying to do.

**Comment by GamingWithaAlexYouTube** [comment]
![bg_primary](https://user-images.githubusercontent.com/32021115/65804925-4780db00-e149-11e9-8bf6-417ff13fa61c.png)
here is the bracket i made for the dual division Elimination Bracket

**Comment by GamingWithaAlexYouTube** [comment]
here is the bracket i made for the dual division Elimination Bracket
![dualdivisionbracketRR](https://user-images.githubusercontent.com/32021115/65823724-6652a080-e221-11e9-8e77-04e8f28a98f7.png)

i was not able to do the extras if you do diced to add this into the scoring system you will able to put it in.

**Comment by maths22** [comment]
A dual division elimination bracket has been added to the latest version of the scoring system.  It shows the alliances playing in the divisional finals and the interdivisional finals.
