### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#399]
It would be extremely helpful for us (as The Orange Alliance) to have access to the timezone of the Scorekeeper computer when the event was run. Would it be possible to add a field for this to the database?

**Comment by ofekashery** [comment]
Or alternatively return the times in GMT.

**Comment by jvens** [comment]
Or another alternative is return all times in ISO 8601 standard [wikipedia](https://en.wikipedia.org/wiki/ISO_8601)

**Comment by tweirtx** [comment]
Turns out it does already return in UTC, on both Linux and Windows. nice
