### ISSUE TITLE
Check boxes for Scoring/Timing Display options are too small and hard to see and use.

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#4]
Scoring/Timing Displays – Display Options. The check boxes for Enable Advanced Settings, Bind to Field, Show Live Scores, and Mute are really small and hard to see/click on a laptop

**Comment by adwiii** [comment]
As of v1.0.0 the checkboxes have been made much larger and we have swapped to use dropdowns as much as possible:
