### ISSUE TITLE
Live Results Uploading

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#40]
The system should support live posting of results to the internet on post (or with a timeout after commit).  Feel free to close this issue if that is already covered by the 3rd party API item.

(a la ftclive.com or https://ftc-results.firstillinoisrobotics.org/webroot/live/sites/il-cmp-rr/#d1-teamlist)

**Comment by adwiii** [comment]
The 3rd party API has been released and we will continue to add features as we are able.
