### ISSUE TITLE
Auto Update Scorekeeper Software

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#401]
This is probably a longer-term feature request.

As a user I would like to be told when I start the scorekeeper software on a machine with internet connection if there is a new version available and have the option to update to that new version.  Additionally this update should seamlessly install over the running version and not require any manual intervention to import existing events.

**Comment by GamingWithaAlexYouTube** [comment]
when is the new software going to be about ready

**Comment by maths22** [comment]
This has finally been added with the CENTERSTAGE season.
