### ISSUE TITLE
Match Preview Renders Incorrectly When No Teams Present

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#404]
When there are no teams present in the match, the match preview is missing the coloured bars.

Reproduce by creating an event, add no teams, generate empty alliances, generate elim matches, load one of the matches.
Probably not a high priority.
![image](https://user-images.githubusercontent.com/28027434/66186553-b322f500-e6c1-11e9-9abe-e72c73f8c903.png)

[test5.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3689275/test5.zip)

**Comment by tweirtx** [comment]
trophy.png missing is an issue that occurs on a populated match preview as well, tested on Chrome on Ubuntu 18.04.3 and Arch

**Comment by adwiii** [comment]
The issue of the trophy not rendering has been fixed in v1.1.0. The issue on non-existent teams not showing up is "expected behavior" - Without a team to show, we default to show nothing. Given that this is not an expected use case for normal events this is acceptable.
