### ISSUE TITLE
Missing Event and Import Failure

### ISSUE THREAD

**Issue by aj-foster** [FIRST-Tech-Challenge/scorekeeper#405]
Hello there,

Today we used the v1.0.0 preview release to run a scrimmage. Our experience during the day was fantastic; it's obvious you've been working hard. Thank you for your time.

After the event I downloaded the event archive from the dashboard. Here's the file: [tesla_practice.db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3695327/tesla_practice.db.zip). Everything was closed down at the end of the event.

Now I face two problems:

1. When I start the scoring software again (same installation, same database files), no events appear in the listing.
2. I'm unable to import the event's archive into either (a) the same instance of the scoring software, because it runs into a uniqueness constraint with the event's code in the database, or (b) a new instance of the scoring software, because it thinks the archive was created by too early of a version of the software.

For good measure, here are the database files as they were at the end of the day: [db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3695393/db.zip)

I'm here to help debug in any way, just reach out. Thanks for everything!

**Comment by aj-foster** [comment]
Here is an error log from our attempt to import the meet's data into a new instance of the software: [2019_10_07_09_01_10_PM_err.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3700227/2019_10_07_09_01_10_PM_err.log)

The software is running on macOS 10.14.6 with an unprivileged user (using a custom port).

**Comment by tvbarnette999** [comment]
Thanks for the logs and archives. I've found the problem in the archive, but I'm having difficulty replicating how it happened. Can you get the remainder of the logs from the time the event was setup and run? Here's the parts of the timeline I've been able to piece together from the database:
1. 2019-10-05 23:41:52 UTC (Saturday evening): A data download was performed, updating the team data.
2. 2019-10-06T13:29:53 UTC (Sunday morning) - Team 1065 was added to the event. This team does not exist in FIRST's list of currently registered teams, so it appeared empty, and you had to fill in the data
3. 2019-10-06T13:33:29 UTC - Last Edit of the data for Team 1065
4. 2019-10-06T15:34:37 UTC - MatchMaker run

Sometime either before or after or around step 2, 23 teams were added to the event, 12 of those were then removed before matches were generated. Can you provide any additional details about when that occurred relative to the timeline above? In addition to the logs, if you know any of the following, it would be helpful:
1. When was the event created? Was it before or after the data download?
2. Were any teams added to the event Saturday evening?
3. Was the software closed/restarted at any time in this timeline?
4. Was team 1065 added and removed and re-added to the event? Did anything else weird happen with team 1065 that you noticed?


Thanks for your help debugging this. In the meantime, if you'd like, I can attempt to manually repair the archive and upload a copy with the problem corrected so you can import to see results or other reports.

**Comment by aj-foster** [comment]
Here are the log files: [logs.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3703168/logs.zip). There are a few later log files from my attempts to get the system back up and running after the event, which you can probably ignore. For reference, our local timezone is Eastern Time.

Based on the logs and my memory, here are the answers to your questions (to the best of my ability):

>When was the event created? Was it before or after the data download?

I believe the event was created immediately **after** the data download on Saturday evening.

>Were any teams added to the event Saturday evening?

Almost certainly **no**. We added everyone, including the non-existent team 1065, on Sunday morning.

>Was the software closed/restarted at any time in this timeline?

The software was **started once on Saturday** evening — then shut down completely — and then **once on Sunday** through the end of the event. The next time we started it up was Sunday evening (when we discovered the issue).

>Was team 1065 added and removed and re-added to the event? Did anything else weird happen with team 1065 that you noticed?

Yes. For context, team 1065 was a fake team meant to be a derivative of the real team 10650 who kindly brought a backup robot to make the scrimmage more interesting. What you're seeing there is me **adding the team**, **forgetting to click the save button** while filling in the team name and details, and **then adding those details** afterwards (oops). The first save was just a team number, and the second was a team number + details. Can't remember anything else weird happening with that team.

>I can attempt to manually repair the archive

If you have time, that would be great. Despite it being a scrimmage, we would love to make the match results available to teams.

---

Thank you for your work on this. I've attempted to replicate the issue with no luck so far, but will let you know if we can find a reduced test case.

**Comment by tvbarnette999** [comment]
Thanks for the info! I've found the cause of the bug and fixed it for the next release. 

Here's a repaired archive that you should be able to import into your system:
[tesla_practice_repaired.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3704454/tesla_practice_repaired.zip)

**Comment by aj-foster** [comment]
Fantastic! The repaired archive imported correctly and we were able to get the match results. Thank you for your time.
