### ISSUE TITLE
Blue & Red Scoresheet Links are Broken as of the Release of FIRST Tech Challenge Live v1.1.0

### ISSUE THREAD

**Issue by tfullmer76** [FIRST-Tech-Challenge/scorekeeper#408]
When either Red or Blue Scoresheet link is clicked on on the FIRST Tech Challenge Live v1.1.0 page, a "not found" message appears.

Thanks :)

**Comment by adwiii** [comment]
😅 they have been updated to point to the URL on the [volunteer resources page](https://www.firstinspires.org/resource-library/ftc/volunteer-resources).
