### ISSUE TITLE
Announcer Tablet

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#41]
It would be nice to have a page + role for announcers.  For an idea of what could be on it, here are some screenshots of the tool I made with the old scoring system:

![image](https://user-images.githubusercontent.com/3067361/46370547-7b671480-c64b-11e8-9410-1a4dfe1f6866.png)
 
(I later added the ability to pull custom information [like a fun fact] from a google sheet, and the other tab has controls for switching the video display, but those are definitely in the nice to have extras, not the core feature)

**Comment by GamingWithaAlexYouTube** [comment]
@ftctechnh could you add this in. this is the kid who made the scoring system for the Chicago robotics invitational. and this would be a good role for the announcer to do instead of just announcing.

**Comment by maths22** [comment]
Closing in favor of #628 which is better specified and fleshed out.
