### ISSUE TITLE
PTC Logo on Sponsor Display gets partially chroma keyed out when using green overlay color

### ISSUE THREAD

**Issue by Tomrish** [FIRST-Tech-Challenge/scorekeeper#411]
If I select the green overlay color and set my chroma key to green for the audience display, it chroma keyes out the green element of PTC's logo when using the sponsor display. Pictures below.
You might be asking "well why don't you just play with the similarity slider? Well if I do that and I activate the "Audience Key" display, my video overlay doesn't show over the audience display. If I switch the overlay color in the audience display options to magenta, the "Audience Key" display only shows the green overlay color as I mentioned in issue #410 so not only can't I use magenta but I also can't choose another custom color. Rock and a hard place.

NORMAL:
![ghi2 2](https://user-images.githubusercontent.com/33290191/66611290-039bc600-eb8c-11e9-984c-b35a097e0a0b.PNG)
WHEN USING GREEN OVERLAY COLOR AND GREEN CHROMA KEY:
![ghi2 1](https://user-images.githubusercontent.com/33290191/66611300-0eeef180-eb8c-11e9-9fdc-a6f43a0759ed.PNG)

**Comment by bsimmons99** [comment]
A potential work around for this in the meantime:
- Use a second chroma filter in whatever software you are using if you have that available, and have them both set tightly.
- Set the Overlay Color to 89B789, this is the same as the audience key background.
- Modify the overlay_*_key*.png images (there are 4) in the lib/public/img/bg/ directory to use your overlay color of choice (See my comment in #410).

**Comment by Tomrish** [comment]
I went ahead and set the overlay color to magenta and then setting a seperate COLOR key for the shade of green used in the audience key and that seems to work just fine. Still keeping the issue open because I can see this being a challenge for less advanced users and/or production companies who may not be able to easily add chroma and color keys all at the same time, so it probably is beneficial for them to fix this down the road especially when large state tournaments start coming around.

**Comment by adwiii** [comment]
Closing as 1) the proposed solution solves the issue and 2) the sponsor logos have changed and they are now both blue.
