### ISSUE TITLE
Dual division double brackets enchantment 

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#415]
![DF5FE935-CE31-4347-83E2-364225E8BD20](https://user-images.githubusercontent.com/32021115/66667278-4c00c580-ec18-11e9-9b54-b81af55d0732.jpeg)

**Comment by GamingWithaAlexYouTube** [comment]
This would be good for dual division events

**Comment by adwiii** [comment]
@GamingWithaAlexYouTube please only create one issue for a given enhancement request. #398 contains the image listed here already. We revisit old issues between releases and implement features as we can.
