### ISSUE TITLE
League Ranking Points

### ISSUE THREAD

**Issue by khoyt5** [FIRST-Tech-Challenge/scorekeeper#416]
Last year, your top 10 matches during the leagues season is where your ranking started for the league championship. So if a team played in two league meets, had 9 wins and 3 losses, would start with 18 Ranking Points at the league championship. This year, with the averaging it will start with 1.80 Ranking Points. If a team went to one league meet and won all 6 matches. They would start the league championship with 12 Ranking Points (behind the team with 9 wins). Now with the averaging, they will start with 2.00 Ranking Points, ahead of the team with 9 wins.

Is this the intent? Doing an a test with the 1.0 version has the team with 6 wins ahead of the team with 9 wins.

**Comment by jvens** [comment]
This is directly related to my issue #369 which was never fully answered.

**Comment by adwiii** [comment]
@khoyt5 I can't speak to intent. Please ask [on the official forum](https://ftcforum.usfirst.org/forum/first-tech-challenge-skystone-presented-by-qualcomm-game-q-a-forum) for questions related to intent.
