### ISSUE TITLE
Pit display rankings don't scroll smoothly like match results do

### ISSUE THREAD

**Issue by Tomrish** [FIRST-Tech-Challenge/scorekeeper#417]
Not a software-breaking issue, but noticeable cosmetic issue from a perfectionist's standpoint. Probably could be labeled as low-priority enhancement. Watch the rankings on the left in the GIF below. The results scroll up the screen to the threshold smoothly, while the rankings just pop up on the bottom of the screen.
![252d6fda55cf6ccf9d844cd0924873ac](https://user-images.githubusercontent.com/33290191/66681709-479cd280-ec41-11e9-93d1-30d6a824cd81.gif)

**Comment by adwiii** [comment]
For what it's worth, this happens for the match list if there are fewer than 9 matches, and this does not happen for the ranking list if there are 10 or more teams. 


What would you propose as an alternative? The only way I know to fix this would be to have the same team appear on the screen multiple times at once, and I don't know if that is what we want.

**Comment by Tomrish** [comment]
@adwiii If this doesn't happen when there's more than 10 teams in the event then I don't think anything needs to be changed. I haven't tested with more than six teams during my tests so I didn't realize this was the case. I really don't see a possibility of there being less than 10 teams in an official event where a pit display would be active. In the rare case there is one, like I said, this is really just cosmetic and doesn't affect the actual rankings so it's mostly a non-issue. Thanks for the heads up though!

**Comment by jvens** [comment]
So I agree with @Tomrish that this issue is not worth spending development time to resolve.  But I have run several official events with fewer than 10 teams and a pit display in the past, and we have several events this year with fewer than a dozen teams in them.  But as long as it functional I don't think anyone really minds the weirdness of rendering at the smaller events.

**Comment by bsimmons99** [comment]
I understand this is closed, but just a thought, what if when there is less than 10 teams/matches, it just doesn't scroll?
