### ISSUE TITLE
Video Overlay Coloration Issues

### ISSUE THREAD

**Issue by jonwelsch** [FIRST-Tech-Challenge/scorekeeper#420]
There are several places where using the video overlay causes graphics to disappear:

Top capstone in fullscreen graphic
Green countdown on last 10 seconds of timer.

**Comment by adwiii** [comment]
Can you elaborate on what you mean for both of these? 

Which capstone image are you referring to, and what is different between the top capstone and the other?

The countdown timer goes from orange to yellow at the 30 second mark and then flashes red for a few seconds at the end of the match. Was the yellow being picked up by the overlay and made transparent?

**Comment by jonwelsch** [comment]
It probably was the yellow; I'm a little colorblind and just noticed the overlay showing up, with the colored background fading out.

When trying to switch it to magenta, it grabs all the red.

As for the capstone, it was all of the capstones getting pulled. 

I think it's just the yellow used that gets grabbed by OBS's default green range.

**Comment by bsimmons99** [comment]
If you don't mind using a different color in the meantime, I use these settings with no issues:
Display Overlay Color: FF00FF
In OBS:
Effect Filter: Chroma Key
Key Color Type: Magenta
Similarity: 389
Smoothness: 1
Key Color Spill Reduction: 1
Opacity: 100
Contrast: 0
Brightness: 0
Gamma: 0

Catches all the magenta keys including edges and the hybrid alliance selection.
But doesn't catch any display elements including the red text on the Wifi Reminder screen.

**Comment by Tomrish** [comment]
@jonwelsch I'm also using OBS to handle my audience displays and livestreaming. Was having the exact same issue you were having with certain graphic elements being inadvertently keyed out. Tested @bsimmons99's color setup and I can confirm those settings work perfectly.
