### ISSUE TITLE
Refreshing Display/Match Control Loses Track of Timeout

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#422]
If a display is refreshed during a timeout, the display will not show the correct timeout time (shows default and it doesn't count down), it also does not overlay the timeout on top of other displays (eg  Wifi Reminder).

If the match control page is refreshed during a timeout, it will lose track of the timeout time and the presence of a timeout preventing any prior running timeout to be stopped and allowing another timeout to be started.

If a display already has a timeout running and another timeout is started, that specific display will add multiple timeout times together causing a longer timeout.
If the timeout is long enough, the minutes image on the display will 404 and fail to show.

--
Could not reliably reproduce (and determine cause of) bug causing the match control page to lose track of a timeout when switched to and from test mode.

Could not reliably reproduce (and determine cause of) bug preventing the timeout overlay from stopping showing (eg on top of Wifi Reminder) once the timeout had finished.

**Comment by maths22** [comment]
This is resolved in v3 (for Freight Frenzy).
