### ISSUE TITLE
Client Computer Disconnecting from Server

### ISSUE THREAD

**Issue by jonwelsch** [FIRST-Tech-Challenge/scorekeeper#423]
After about 15 matches, the client computer started dropping connection to the server.
Both were confirmed to be on the same network, on, and still logged in.

After the match would start, the client computer would not update to reflect live scoring, but the server computer continued to do so. This was resolved by refreshing the client computer, but began to be consistent between every match.

Log file: https://drive.google.com/open?id=1NfxHUlmHGx4Apy5KNBBAScF6lTsnhhai

Will work to reproduce it when I get back to the other computer tomorrow.

**Comment by adwiii** [comment]
Can you document here what devices and browsers were used for the referees, displays, and scoring system computer?

**Comment by jonwelsch** [comment]
Certainly!

Referee tablets used Amazon Kindles (Amazon - Fire 7 - 7" - Tablet - 8GB 7th Generation, 2017 Release) with Google Chrome (will update with browser version later)

General ranking displays were on Intel Compute Sticks (https://www.amazon.com/gp/product/B01AZC4NHS/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1) running google chrome on windows 10

Scoring displays were Intel NUC computers running windows 10, OBS pulling logitech webcams. The scoring overlay was the built in OBS browser plugin

The server used was a 2019 MacBook Pro, running Catalina 15.1 Beta 19A582a

The client with the issues is a Mac mini running Mojave 14.6, running safari browser (This is the device that needed refreshes)

**Comment by maths22** [comment]
This should be resolved in in v3 (for Freight Frenzy), please reopen if you see this happening this season.
