### ISSUE TITLE
Generating Inspection Schedule With 0 Stations Runs Indefinitely

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#424]
If you add an inspection activity with 0 stations and try to generate a schedule, no error is thrown and the system tries to generate indefinitely (but I didn't wait around to find out if it truly is indefinite). Adding a station to the activity and attempting to generate another schedule works fine.
Should display an error if 0 stations are present.

**Comment by adwiii** [comment]
This has been fixed in v1.1.1 - it will now show an error if any activity has 0 stations.
