### ISSUE TITLE
Awards Overlap With Long Team Names

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#426]
When teams have long names, they overlap with other teams on the awards display.

Attached screenshot of example.
![image](https://user-images.githubusercontent.com/28027434/66796421-27298c80-ef4f-11e9-987f-86142fd3ab25.png)

**Comment by adwiii** [comment]
This has been fixed in v1.1.2. The awards are now centered, and will adjust their font size to ensure they do not overlap.
