### ISSUE TITLE
Add API route to get all the elim matches

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#427]

**Comment by cmacfarl** [comment]
This was a specific design decision as you don't know how many elimination matches there are until they've been played.

Unlikely to be changed unless you have a really compelling argument for doing so.

**Comment by adwiii** [comment]
This also looks like a duplicate or subset of #113 and related to #115

**Comment by ofekashery** [comment]
@cmacfarl Also when you call each one individually you don't know how many elimination matches there are. If you put them in one list is much easier to know.
I mean there will be just played matches.

**Comment by adwiii** [comment]
As of `v1.4.1` the `/api/v1/events/{code}/elim/all/` endpoint contains a list of all completed eliminations matches.
