### ISSUE TITLE
TBP shows "--" upon restarting for an in progress or completed event.

### ISSUE THREAD

**Issue by kenpugsley** [FIRST-Tech-Challenge/scorekeeper#428]
When the scoring software is restarted, any existing in-progress or completed event shows TBP as "--" on the Rankings page (similar to what it would look like if the event hasn't had any matches played yet).  All other fields (RP, Highest, Matches) shown correctly.  The  /api/v1/events/{code}/rankings/ endpoint does the same.

To replicate (tested on v1.1.1):
1. Set up a match (I did a scrimmage with 12 teams)
2. Enter scores for 1 or more matches
3. Shut down the scoring system completely, then restart it
4. Look at the Ranking page.  TBP will show "--", while other fields are correct.

Note... this seems to resolve itself once any match is edited or a new one is scored.

**Comment by adwiii** [comment]
Thanks for pointing this out - it will be fixed next release. I want to stress that this is entirely a display issue and that the ranking order will be correct even though the TBP display is incorrect.

As you noted, as soon as the system does another ranking calculation everything is fixed. A ranking calculation is performed whenever a Qualification Match is committed and when Alliance Selection starts.

**Comment by adwiii** [comment]
This has been fixed in v1.1.2
