### ISSUE TITLE
Audience Key Overlay Colour Background Renders Incorrectly with Scoring Bar at Top

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#429]
Similar to #402, The overlay background colour has a gap at the bottom where the colour ends early.
See attached screenshot.
![image](https://user-images.githubusercontent.com/28027434/66970779-22dbab80-f0d6-11e9-8e63-d28f6c7f97b0.png)

**Comment by adwiii** [comment]
This has been addressed in v2.1.0
