### ISSUE TITLE
Set up

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#43]
I was able to set up an event but not add teams by the list or individually in order to get to the next step.  I have disabled my firewall and ad blocking software.  Not sure how to proceed.

**Comment by adwiii** [comment]
A few questions:
1. What is your event code?
2. Can you see the list of teams in the "Find by State/Province" list - could you upload a screenshot of that page?
3. Can you please upload here a copy of your database folder?

Thanks for testing!

**Comment by pstrones** [comment]
Thank you for your quick response and questions.

  1.
I made two thinking I needed to start over after taking care of firewall - northernarizona and Arizona
  2.
When I click to view the list it doesn't proceed and it's the same for trying to add team numbers, I can click Done and it takes me back to the dashboard.
  3.
Uploaded what I believe you are looking for, let me know if there is something else I need to upload.

I screenshot the pages I can see with the screen for listing the teams.


Thank you for your assistance.


Patricia (Patti) Strones
FIRST ®  AmeriCorps VISTA, Southwest Region



[72dpi_sm2]

For Inspiration and Recognition of Science and Technology

200 Bedford Street  |  Manchester, NH 03101  |  www.firstinspires.org<http://www.firstinspires.org/>

Phone:  928-607-7563  |  pstrones@firstinspires.org<mailto:bmartin@firstinspires.org>




________________________________

**Comment by adwiii** [comment]
Unfortunately with the way Github works, uploading the files does not work when you respond via email, so I did not receive the screenshot or file. To upload them, please visit the Github issue page [here](https://github.com/FIRST-Tech-Challenge/scorekeeper/issues/43) and then drag the files into the text box at the bottom or click the "selecting them" link at the bottom of the text box. Sorry for the extra step.

**Comment by pstrones** [comment]
[FTC Scorekeeper Test.docx](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2444080/FTC.Scorekeeper.Test.docx)

It won't let me attach the database folder or file, states it doesn't support that file

**Comment by pstrones** [comment]
It appears my system automatically prompts it in internet explorer and I just forced it to chrome, so it may work.  I will let you know if it doesn't.

**Comment by adwiii** [comment]
Ah, yes, so I have replicated your error then using Internet Explorer. The issue was that there was a syntax error in the page that apparently Chrome ignores, but Internet Explorer throws an error for, which is why the page doesn't finish loading. 

Let me know if it does not work for you in Chrome.
