### ISSUE TITLE
inspections status display

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#434]
The status were not updating on the inspection status display.  If I would refresh the screen it would then show the updated info.  Last years system would update every few seconds without doing a screen update.

**Comment by jvens** [comment]
We used the inspection display at my event today and it was updating on its own just like last year.  We were using the one-column display if this is something that only effects one layout and not the others.

**Comment by rgutentag** [comment]
We also was using a 1 column display.  We were using version 1.1.1  We have another event tomorrow so will check again.  This was a small event with onlly 9 teams.

**Comment by adwiii** [comment]
There are two different versions that both have one column. There is the one that has the header like a normal page and one that is meant for projectors that has nothing but the status table. Only the one for projectors updates automatically.

**Comment by rgutentag** [comment]
Didn't realize that 1 column worked 2 different ways.  today worked as expected so closing
