### ISSUE TITLE
event data upload

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#435]
Is there another method to upload the data files to first.  Most of our locations have wifi turned off.  Can we take the saved file and send it to first after the fact.  Tried today but got error.  Will be trying tomorrow at a different site.

**Comment by tvbarnette999** [comment]
You can try again later when you are at a location with better or non-firewalled wifi. If you import the downloaded archive into another install of the scoring system, you will need to input the region key again, but it will work, so you could do that with a personal laptop if you don't have access to the one used at the event. Let us know if you keep running into problems.

**Comment by rgutentag** [comment]
I was able to upload yesterday's and today's event so closing this item
