### ISSUE TITLE
Issue adding team to league meet

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#436]
One of our events this weekend had a strange issue.  I was not at the event, but I did provide support to them to resolve the issue during and can relay any questions back to them.

For some background, I generate the scorekeeper events for all the league meets and send them out to the scorekeepers ahead of their events.  I have attached the exact database file from the score system I sent out.  This event has the league created with all the teams in the league added to it, and the event created.  The score keeper just marks teams as present the morning of the event.  I have verified that team 13206 was correctly added to the league at creation time.

During the event when they attempted to add 13206 to the event they said that the team was missing from the league.  They then attempted to manually add the team and said it wouldn't let them add it.  The logs look like it failed because that team was already in the DB which would be expected.  My suggestion to them was to completely close out of the server and restart it and see if that resolved the issue.  That did fix the issue and they were then able to add that team to the event and move on.  The After.zip is the Database and log files that she sent me after the event was over.

Let me know if you would like any additional information.

[Before.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3780541/Before.zip)

[After.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3780543/After.zip)

**Comment by adwiii** [comment]
Closing as league management is deprecated in FTCLive. All league data is handled through the [online scoring system](ftc-scoring.firstinspires.org) and automatically imported when the event is imported into FTCLive.
