### ISSUE TITLE
overlay scoring bar on top not working.

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#437]
![Screenshot 2019-11-02 at 10 57 24 AM](https://user-images.githubusercontent.com/32021115/68073622-03907f80-fd60-11e9-96d4-764cc152f222.png)

**Comment by GamingWithaAlexYouTube** [comment]
here is the link.
http://localhost/event/fvnm1/display/config/overlay/false/overlay/ad/false/0/00ff00/true/false/true/true/hybrid/false/

**Comment by jonwelsch** [comment]
<img width="1680" alt="Screen Shot 2019-11-11 at 1 23 47 PM" src="https://user-images.githubusercontent.com/44350125/68610774-8b743900-0486-11ea-96cc-2f21ad874a0f.png">

**Comment by bsimmons99** [comment]
Can confirm this was present since V1.1.1

**Comment by adwiii** [comment]
This has been fixed in v1.2.0
