### ISSUE TITLE
Ability to insert bad data when importing leagues

### ISSUE THREAD

**Issue by bkeeneykid** [FIRST-Tech-Challenge/scorekeeper#438]
As I accidentally discovered, when attempting to import a league into an event, it is still processing after you press the "import" button. I pressed this button, which appeared to place the scoring system in a position where the system only imported about 8 of the 21 teams I attempted to import, and I could not import the rest of the teams (it would simply fail silently). I've attached the league I attempted to import, the DB (not a production system, no FIRST key) and the logs below.
 
[2019_11_02_07_57_56_PM_err.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3801129/2019_11_02_07_57_56_PM_err.log)
[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3801131/db.zip)
[chi_north_meet_1a_leagues.db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3801130/chi_north_meet_1a_leagues.db.zip)

**Comment by bkeeneykid** [comment]
Looks like a quick restart of the scoring system meant I could see the "ghost" teams that I couldn't insert earlier and then fix the team list to be correct from there.

**Comment by jvens** [comment]
Not sure, but this sounds like it might be related to #436.

**Comment by bkeeneykid** [comment]
Yup, looks like the same issue. The root cause looks like a mistaken double import on the Leagues page since the page doesn't provide any input that it's importing the leagues, so it locks the database for the first import, the second import can't import things properly, some cache internally thinks you've added the team, when you haven't because the database was locked.

**Comment by adwiii** [comment]
Closing as league management is deprecated in FTCLive. All league data is handled through the [online scoring system](ftc-scoring.firstinspires.org) and automatically imported when the event is imported into FTCLive.
