### ISSUE TITLE
Field Inspection Checklist: Electronic inspection page in version 1.1.2 does not match rule RS02

### ISSUE THREAD

**Issue by JGreenOS** [FIRST-Tech-Challenge/scorekeeper#439]
Rule RS02:  "DS and RC apps are version 5.2 or higher and the DS and RC apps have the same version numbers".

Electronic Field Inspection Page:  "DS and RC apps are version 4.0 or higher and the DS and RC apps have the same version numbers."

Rule:
![R02](https://user-images.githubusercontent.com/10423865/68088256-0f954380-fe2b-11e9-9a85-5e79970a7d61.png)

Electronic Inspection Page:
![2019-11-03_11-12-06](https://user-images.githubusercontent.com/10423865/68088262-381d3d80-fe2b-11e9-9ca6-8f0e1d576768.png)

**Comment by tvbarnette999** [comment]
This has been fixed in v1.2.0.
