### ISSUE TITLE
Alliances API route returns NOT_READY for some events after importing

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#440]
[dbs.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3803507/dbs.zip)

``http://localhost/api/v1/events/fimmq/elim/alliances/``
``http://localhost/api/v1/events/fimahq/elim/alliances/``

**Comment by adwiii** [comment]
I have identified the problem and am working on a fix. It will likely be in the next release.

**Comment by adwiii** [comment]
This was addressed in `v1.3.2`
