### ISSUE TITLE
Randomize showing early

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#443]
The match control page has a randomize button and a show random. Last year, we could randomize early and then show random when all the teams were ready. Is the change to have the randomize results immediately intentional?

**Comment by adwiii** [comment]
The randomize button has always immediately displayed the randomization on the field display and scoring tablets. The show random button causes the audience display and overlay to swap to show the randomization. The logic here is that if the field is ready to randomize, then field personnel need to know ASAP what the randomization is to set up the field, while the audience may want to view the match preview longer.

On a bit of longer note, this is one of the behavior differences that define the difference between a field display and an audience display. If you want your field displays to look like field displays but act like audience displays on when they show the randomization, then you can configure that in the settings of the display. I can provide a screenshot later if that would be helpful.
