### ISSUE TITLE
Posted score not showing on field display

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#444]
Last season, posted scores would show on the field display. This year, they do not. We can announce our scores, but not easily show them. We have no audience display - we have a large screen for the field and a small screen in the pits with the pit display. Maybe we are doing something wrong.

**Comment by vwestin** [comment]
Note that we are working around this by being able to flip between the audience display and the field display on the same screen. It is just complicated.

**Comment by tvbarnette999** [comment]
If you want it to look like a field display during a match but show screens like an audience display, you can enable the advanced display settings and set Appearance to "Field Display" and Behavior to "Audience Display". Since you only have one display, I'd recommend just using an Audience Display.

**Comment by vwestin** [comment]
We will work past this. Some notes in the scoring manual on displaying scores where the only display is both a field display and the audience display would be helpful.

**Comment by vwestin** [comment]
Using the recommended settings worked perfectly. Thanks.
