### ISSUE TITLE
Strange issue importing league data

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#449]
I am having a very strange problem importing meet 3 data to create meet 4 for one of our leagues.  The archive file from from meet 3 is attached and when I look at the Manage Leagues in this event I see meets 1 and 2 as expected.  When I create a new event for Meet 4 and import the Meet 3 archive it only imports in Meets 1 and 2 and doesn't import Meet 3 data.

[kashyyyk_2019_11_09_meet3.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3834155/kashyyyk_2019_11_09_meet3.zip)

**Comment by adwiii** [comment]
It appears that the db did not go through the archive procedure (or the archive procedure broke down). If you import that db, then download the archive, it will work for importing into the next meet.

[kashyyyk_2019_11_09_meet3 (1).zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3834181/kashyyyk_2019_11_09_meet3.1.zip)

**Comment by jvens** [comment]
That resolved the issue.  Thanks!
