### ISSUE TITLE
Match Schedule

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#45]
I created a match schedule of 24 and then modified to a schedule of 29 but it didn't clear out the schedule of 24.  It doesn't appear that there is a way to clear a schedule if there is a conflict, to generate a new one.
[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2444289/db.zip)

**Comment by adwiii** [comment]
Duplicate of #75. I am closing this since #75 has a more descriptive title.
