### ISSUE TITLE
Dual Division Elimination Bracket Enchantment 

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#450]
![65808959-03e49c00-e15e-11e9-9cb9-847dd18970d6](https://user-images.githubusercontent.com/32021115/68906069-d1d8ca80-0708-11ea-8401-9b308b57b8ac.png)

**Comment by GamingWithaAlexYouTube** [comment]
this will be cool if you added it in.

**Comment by adwiii** [comment]
Closing in favor of #398
