### ISSUE TITLE
Low Priority - Allow for single team "Practice/Demonstration Mode"

### ISSUE THREAD

**Issue by RichardJFoster** [FIRST-Tech-Challenge/scorekeeper#452]
Not everything is a competition, but giving people the "Competition Experience" would be nice for some outreach and practice events. For example, after this year's competition is over the team I help mentor would like to host an open-to-all community event where they and (hopefully) some of the other local novice teams can show off what they've learned in a more ad-hoc manner than a traditional competition or scrimmage session.

It would be really nice if there was a simple mode where it was possible to select one or more teams from a list (max 4 at once, naturally), optionally randomize the alliance (otherwise the teams remain with an alliance assigned at selection time), then run a "match" with full sound effects and live scoring active. This mode might also be useful for independent driver practice as it would accurately reflect match timings (including the delay between the end of autonomous and the start of driver controlled phases), and might help teams empathize with any challenges that may be faced by the scorers.

(Apologies in advance if this feature is already available. I did play around with the current 1.1.2 release briefly and didn't find it.)

**Comment by adwiii** [comment]
While not exactly what you ask for, I believe that "Test Mode" in the system accomplishes what you are after. Steps to use:
1. Create an Event, the type is not important as all types support test mode.
2. Add all teams that could possibly show up in a match. Test mode can only use negative team numbers or team numbers from the event.
3. Do not generate a match schedule
3. Set up the Field/Audience/Overlay Displays and Referee tablets as normal.
4. On the Match Control Page, on the Settings tab, select "Test Mode"
![image](https://user-images.githubusercontent.com/9453262/68963120-3432d900-07a4-11ea-8f9d-580f8fb6628b.png)
5. This will cause the system to enter "Test Mode", indicated by the top portion of the Match Control Page turning purple:
![image](https://user-images.githubusercontent.com/9453262/68963201-65aba480-07a4-11ea-938d-8bdee29f8dab.png)
6. From this, you can select "Add Test Match" which will present you with the following dialog
![image](https://user-images.githubusercontent.com/9453262/68963278-8ffd6200-07a4-11ea-8ad2-19c86a10d97c.png)
7. The default is to use -1, -2, -3, -4 for the team numbers. However, these can be edited, and you can enter any team that was added to the event earlier. If you enter a team that was not added to the event in step 2, the system will ignore the number entered and default to the negative number. If you forget to add a team, any negative number will work. Say you did not add team `9999`, then you could add team '-9999' and that would work, but they will show up negative on the display. In the example below, the event I created only has teams 11115, 7105, 5064, and 724. In Match 1, the default negative numbers are used. In Match 2, I use teams that are entered into the event. In Match 3, I use negative numbers that correspond to teams, but were not added to the event.
8. As you add matches, they will show in the list as normal, and can be played like a normal match
![image](https://user-images.githubusercontent.com/9453262/68963543-229e0100-07a5-11ea-9ef6-b18d56b8d731.png)
9. The name of the match will show up on the displays as "Test Match XX" and on the Referee tablets as "Match T-XX"
![image](https://user-images.githubusercontent.com/9453262/68963695-904a2d00-07a5-11ea-90ed-097b3a9da912.png)
![image](https://user-images.githubusercontent.com/9453262/68963734-a7891a80-07a5-11ea-865c-dd647f1cc411.png)




A few notes:
1. You can run as may test matches as you want.
2. They do not count toward any sort of rankings, and it is not possible to see what the rankings would be based on the test matches. 
3. The Display will always show "-1" and down for the rankings when the results are posted, this is an artifact of there not being any rankings to show.
3. If you use the "Show Ranks & Results" button on the Video Switch tab, it will show the ranks and results of the event and does not include Test Mode matches. 
3. If you reboot the system, the test matches will be lost. They are not saved in any form.
4. There must always be 4 teams, even if you wish to play with fewer than 4 teams. If you do not specify a team then the default negative number will be used. Also, the randomization of the alliances you mentioned would have to be done by hand in step 7 by the scorekeeper entering the teams into the desired "random" slot.

I am going to close the issue as I believe this provides what you are after. Feel free to re-open if it does not address your needs. Also feel free to post with additional questions on how to use Test Mode.

**Comment by RichardJFoster** [comment]
Excellent. Thank you @adwiii, that sounds just like the sort of thing I was looking for. I'll verify that's the case, but I'm 95% certain it'll meet the limited use case I had in mind.

**Comment by Eikthyrnir821** [comment]
> While not exactly what you ask for, I believe that "Test Mode" in the system accomplishes what you are after. Steps to use:
> 
> 1. Create an Event, the type is not important as all types support test mode.
> 2. Add all teams that could possibly show up in a match. Test mode can only use negative team numbers or team numbers from the event.
> 3. Do not generate a match schedule (it doesn't hurt anything to generate one, but you can't use it for what you want)
> 4. Set up the Field/Audience/Overlay Displays and Referee tablets as normal.
> 5. On the Match Control Page, on the Settings tab, select "Test Mode"
>    ![image](https://user-images.githubusercontent.com/9453262/68963120-3432d900-07a4-11ea-8f9d-580f8fb6628b.png)
> 6. This will cause the system to enter "Test Mode", indicated by the top portion of the Match Control Page turning purple:
>    ![image](https://user-images.githubusercontent.com/9453262/68963201-65aba480-07a4-11ea-938d-8bdee29f8dab.png)
> 7. From this, you can select "Add Test Match" which will present you with the following dialog
>    ![image](https://user-images.githubusercontent.com/9453262/68963278-8ffd6200-07a4-11ea-8ad2-19c86a10d97c.png)
> 8. The default is to use -1, -2, -3, -4 for the team numbers. However, these can be edited, and you can enter any team that was added to the event earlier. If you enter a team that was not added to the event in step 2, the system will ignore the number entered and default to the negative number. If you forget to add a team, any negative number will work. Say you did not add team `9999`, then you could add team '-9999' and that would work, but they will show up negative on the display. In the example below, the event I created only has teams 11115, 7105, 5064, and 724. In Match 1, the default negative numbers are used. In Match 2, I use teams that are entered into the event. In Match 3, I use negative numbers that correspond to teams, but were not added to the event.
> 9. As you add matches, they will show in the list as normal, and can be played like a normal match
>    ![image](https://user-images.githubusercontent.com/9453262/68963543-229e0100-07a5-11ea-9ef6-b18d56b8d731.png)
> 10. The name of the match will show up on the displays as "Test Match XX" and on the Referee tablets as "Match T-XX"
>     ![image](https://user-images.githubusercontent.com/9453262/68963695-904a2d00-07a5-11ea-90ed-097b3a9da912.png)
>     ![image](https://user-images.githubusercontent.com/9453262/68963734-a7891a80-07a5-11ea-865c-dd647f1cc411.png)
> 
> A few notes:
> 
> 1. You can run as may test matches as you want.
> 2. They do not count toward any sort of rankings, and it is not possible to see what the rankings would be based on the test matches.
> 3. The Display will always show "-1" and down for the rankings when the results are posted, this is an artifact of there not being any rankings to show.
> 4. If you use the "Show Ranks & Results" button on the Video Switch tab, it will show the ranks and results of the event and does not include Test Mode matches.
> 5. If you reboot the system, the test matches will be lost. They are not saved in any form.
> 6. There must always be 4 teams, even if you wish to play with fewer than 4 teams. If you do not specify a team then the default negative number will be used. Also, the randomization of the alliances you mentioned would have to be done by hand in step 7 by the scorekeeper entering the teams into the desired "random" slot.
> 
> I am going to close the issue as I believe this provides what you are after. Feel free to re-open if it does not address your needs. Also feel free to post with additional questions on how to use Test Mode.
> 
> Edit: Clarified that you whether or not you generate a match schedule doesn't matter, it is just easier if you don't since you don't need one.

The test mode is no longer available is scrimmage, off-season, or other equivalent?

**Comment by RichardJFoster** [comment]
I used the test mode just a couple of weeks ago for an outreach event. It was still there as of FTCLive V7.2.2.

The thing I think I was missing when I asked my original question was that you need to generate some sort of event with a date that is the current day or in the future. (Attempting to reuse a previously generated event with a past date was not allowed. It wasn't possible to enter the control screens to enable test mode.)
