### ISSUE TITLE
Red "Start Match" Button

### ISSUE THREAD

**Issue by jonwelsch** [FIRST-Tech-Challenge/scorekeeper#455]
Setup from this weekend:

2019 MacBook Pro (15") running Catalina 10.15.2 running the server
Surface Pro 6 on current windows 10 running match control.
2 Fields

The start match button changed from green to red for several matches.

Will link similar tickets from this weekend.
#454 #456

**Comment by adwiii** [comment]
The start match button is red until both referees have submitted their pre-match setup if using live scoring. This is meant to signal to the scorekeeper that the referees are ready for the match to start.
Before either referee has submitted the button is red:
![image](https://user-images.githubusercontent.com/9453262/69167687-5fc70380-0ac3-11ea-8df7-dcfe2461b9c8.png)
Once both referees have submitted, the alliances highlight green and the button turns green indicating the referees are ready for the match to start.
![image](https://user-images.githubusercontent.com/9453262/69167850-97ce4680-0ac3-11ea-8121-c3882c5e0a2a.png)


Is this consistent with what you saw? When I wrote the above I did not realize you had written that it changed from green to red, and thought it said red to green - do you mean that within the same match it was green and then changed to red?

**Comment by adwiii** [comment]
Closing as I believe this was expected behavior. If the above explanation does not match what was observed, feel free to reopen.
