### ISSUE TITLE
ROCKFORD_MEET_1

### ISSUE THREAD

**Issue by ericwilliamsneu** [FIRST-Tech-Challenge/scorekeeper#459]
Hi FTC Scorekeeper Team,

Unfortunately, we wrapped our event before the guidance on #458 came out, and I ran the "Submit to FIRST" process before correcting and updating the improperly committed matches. I have since used the workaround to correct the matches, I cannot resubmit the results. Please let me know what needs to be done to correct this.

Thanks again for all of your effort and quick resolution on the issue!
Eric

**Comment by tvbarnette999** [comment]
If you can download the fixed archive file from the Event Dashboard and post it here, we can replace the submitted one.

**Comment by ericwilliamsneu** [comment]
Team, corrected DB file attached. Thanks again for your help.
[corrected_db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3889818/corrected_db.zip)
