### ISSUE TITLE
Schedule:  Default the date of new block to Event date, rather than current date.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#46]
Since I have to set an event date range when creating an event, this seems like a great time to use this data...

**Comment by adwiii** [comment]
This is a duplicate of #44. I am closing #44 since the title of this issue better captures the issue.

**Comment by emmell620** [comment]
Would like to raise the priority of this up a notch. When doing qualifiers, the scoring system is generally set up a couple of days in advance of the actual tournament date.

**Comment by maths22** [comment]
The scoring system now requires that matches be scheduled for event dates.  (If you need to schedule them for a date it isn't showing, you should update the event dates first, since you can't actually play matches on a date the event is not happening.)
