### ISSUE TITLE
DQ indicator in Match Results for nominal eliminations play seems inaccurate 

### ISSUE THREAD

**Issue by messenger-sean** [FIRST-Tech-Challenge/scorekeeper#460]
**Issue:**
It seems there is an intent for the 1 team of 3-team alliances that does not participate in an Eliminations match to be indicated in the match results page (e.g., http://192.168.0.2/event/fimoq2/results/) by a strike-through of the team number. 

However, we see that some matches have zero teams for an alliance indicated as such, and in others 2 are indicated as dq/no-show. In both of these cases, we had the normal 2v2 match play with referees correctly entering the "Present" (as confirmed with them and by checking the Match Control Page -> Schedule -> Edit match view).

**Images:**

Match Results view:

![image](https://user-images.githubusercontent.com/4318057/69502912-53d3ab00-0ee2-11ea-9d91-d4ba06a2da6f.png)

Match Control Page Results (Finals 1), notice how one team is selected "N" for No-Show, but that this does not seem to match the Match Results strikethroughs:

![image](https://user-images.githubusercontent.com/4318057/69502931-8aa9c100-0ee2-11ea-9ec7-3bc568993d85.png)

Match Scoresheet (Finals 1), notice how two teams are listed for each as expected:

![image](https://user-images.githubusercontent.com/4318057/69502923-71a11000-0ee2-11ea-81a6-11ff3aa8fe2f.png)

Match Scoresheet (SF 2-1), notice how this seems to agree with the Match Results strikethrough as 15353 is listed as a No-Show (but that the other robot that actually played is not listed, and in Match Results 7305 is also shown to be a No-Show): 

![image](https://user-images.githubusercontent.com/4318057/69502960-d9eff180-0ee2-11ea-8290-e18c3544d3e2.png)

**System:**
- FIM Oxford Wildcat Quest 2 (Nov 24) event
- Scorekeeper 1.2.1 with database imported from a 1.2.0 event archive (before the event begun/played its first match, we had only entered inspection status/a match preview)
- Chrome 73.0.3683.75

**Additional Info:*
I can provide the database file separately if desired.

**Comment by adwiii** [comment]
Thanks for pointing this out - I have identified the issue and it will be addressed next release.

**Comment by adwiii** [comment]
This has been fixed in v1.3.0. Now instead of striking through the team(s) that did not play, the teams that did play are bolded.
