### ISSUE TITLE
Event Code field rejects FIRST assigned event code.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#463]
In latest web training it was recommended that when events are created, the event code should match the FIRST assigned event code, as seen in the FTC-EVENTS.firstinspires.org event list.

Unfortunately my MD event has an event code of 63703969204.303  which is rejected by the scorekeeper program, because it contains a period.

There is a disconnect here somewhere.

**Comment by cmacfarl** [comment]
The garbage event codes are a known issue with the internal FIRST databases.   We are attempting to get this fixed within the internal database.  In the meantime, those event codes should not be used within the scoring system.  Pick something sensible and reasonable.
