### ISSUE TITLE
Match generation on 7.5 turn time broken in 1.2.1 - see #237

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#465]
Trying  to generate match schedule with 7.5 minute turn time (I imagine it's any half-minute turn time) doesn't seem to work.  When I press the save button, I see the POST message in the log, but a journal entry doesn't get created, nor the .db file be updated.  If I do it for 7 minute or 8 minute turns, the schedule generation works.

**Comment by tvbarnette999** [comment]
Can you post a screenshot of the schedule page at the point of failure and the logs? Does it work if you click "Preview" or "Run MatchMaker"? If you refresh the page, does the cycle time input box stay at 7.5 or does it revert to an integer?
