### ISSUE TITLE
Possible incorrect red/yellow card colors.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#467]
I'm not sure if I'm interpreting this correctly, but while testing, I gave an alliance in the playoffs a red card.  When they were playing in their next match, the three teams were highlighted in yellow (I was expecting red)

Is this just an issue that Red carded teams can't play again?

**Comment by emmell620** [comment]
Hi Phil:  A red card in the playoffs is a DQ for the alliance for the entire match.  Their next match is automatically flagged as having 1 Yellow Card. If they receive another Yellow Card in that next match (or future matches in the playoffs), it automatically goes to Red and they are DQ'd for that match again.  So it is behaving correctly.

**Comment by gearsincorg** [comment]
OK, good.  Thanks for explaining the logic.   I've never gotten a card (in FTC) :)

**Comment by adwiii** [comment]
Closing this issue as expected behavior. Please feel free to re-open/comment with any further questions.
