### ISSUE TITLE
Delete an event that is still in "Setup"

### ISSUE THREAD

**Issue by VHSCSteacher** [FIRST-Tech-Challenge/scorekeeper#469]
So I get the obvious reasons for not being able to delete an event. But, there are legit times where a mistake has been made in the setup and the need to be able to delete the event is there. This is especially true with importing data files for league meets. 

Would it be possible to add the ability to delete an event while the event status is still in "Setup"? This would be most beneficial.

**Comment by adwiii** [comment]
Under the "Event Admin" dropdown, there is an option to "Manage Server". From the Manage Server page, there is a section for "Event Hiding". If you select the event you want to remove from the dropdown, it will prompt you to type in the event code to verify that you want to hide the event. Once you type the event code you can click the Hide button (note, hitting enter is purposefully disabled here) and the event will be removed from the main list of events. 
![image](https://user-images.githubusercontent.com/9453262/70473533-3f291280-1a9f-11ea-992b-82716a21c552.png)

Does this fulfill what you are trying to accomplish?

**Comment by jvens** [comment]
This is already possible.  When logged in as `local` click the menu and select `Manage Server`.  Then in the section `Event Hiding` select the event you would like to hide.  This technically just moves the .db file to the sub folder of `/lib/db/hidden`, but if you want to fully delete it you can safely go into that folder and completely remove it.

![image](https://user-images.githubusercontent.com/7074504/70473460-bc9c5500-1a96-11ea-8aa1-2683ca02beee.png)

**Comment by jvens** [comment]
Sorry, Trey beat me to posting by 10 seconds apparently :)

**Comment by VHSCSteacher** [comment]
I thought about hiding the event, but then thought I wouldn't be able to use the same event code on another event. Will I be able to use the same event code?

**Comment by adwiii** [comment]
Yes, if you hide an event you can use that same event code again. Practically, hiding has the same effect as deleting.

 As @jvens noted, we don't actually delete it. The `/lib/db/hidden/` folder is meant to act like the Windows Recycle Bin in case you decide you need to get that event back for whatever reason. You can use the Manage Server to import the db back in from the hidden folder if you decide you want to use it in the future.

**Comment by VHSCSteacher** [comment]
Great, thanks for the quick responses!!
