### ISSUE TITLE
Event list sort

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#47]
With a large number of events, it would be helpful to have the event list sorted by name or date (if date, using name as a secondary sort.) . See the below screenshot for an example of the disorder otherwise resulting:

![image](https://user-images.githubusercontent.com/3067361/46589610-5f130f80-ca71-11e8-98a2-947ed4e1a3b2.png)

**Comment by adwiii** [comment]
As of v0.7.7 events are sorted with most newer events first, with the event code used as a secondary sort.
