### ISSUE TITLE
Number format on hybrid alliance selection display

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#473]
I am not sure of the exact cause of this issue, but I noticed that during alliance selection the bottom row of numbers goes off the bottom of the space on the hybrid alliance selection display.  Below is a screenshot from the livestream.  We were running the audience display in Chromium on a raspberry pi.  I can't replicate the issue at this moment on my windows computer running chrome, so I don't know if it is a chrome vs. chromium or a windows vs. linux thing?  I do know that lots of regions use raspberry pi's for remote audience displays though.

![image](https://user-images.githubusercontent.com/7074504/71825911-6a812c00-3062-11ea-9c85-7e950b9f3997.png)

**Comment by Tomrish** [comment]
I'm going to test this ASAP on my setup because our 28-team championship is coming up soon and we are going to be using the hybrid display. Would love it if we can make things look somewhat professional.

**Comment by tvbarnette999** [comment]
I was able to replicate this on a pi at 1080p. It appears to only be a pi chromium issue. When I changed the pi to 720p, this did not occur, so that may be a workaround for current releases. I have tweaked the CSS to fix this at 1080p on the pi for the next release. If anybody runs into this at a different resolution or on a different OS/browser, please note it here.

**Comment by jvens** [comment]
Can you post what tweak you made to the css?  Because of the way the video switcher works it is far easier to edit some CSS in the chrome devtools than it is to change the resolution for me.

**Comment by tvbarnette999** [comment]
For  ```.select #selectionAvailable td```, change the two 10s in the padding to 9s. Let me know if this doesn't work for you. It's not a great fix, but it keeps the text in the boundaries. The pi's Available Teams table still appears taller than it does on other OS/browsers, which I will look into some more.
```
.select #selectionAvailable td{
	font-size:38px;	
	padding: 9px 4px 9px 4px;
}
```

**Comment by maths22** [comment]
This should be resolved in in v3 (for Freight Frenzy), please reopen if you see this happening this season.
