### ISSUE TITLE
Not eligible to win inspire

### ISSUE THREAD

**Issue by tacklebat** [FIRST-Tech-Challenge/scorekeeper#475]
It would be useful if teams could be marked as not eligible to win inspire because they have already won it at the level they are competing.

**Comment by adwiii** [comment]
On the Add Teams page each team can be marked as ineligible for advancement and/or inspire. On the [online scoring system](ftc-scoring.firstinspires.org), the Add Teams page additionally has the ability to check the prior events of teams and highlight if any teams should be marked as ineligible:

![image](https://user-images.githubusercontent.com/9453262/98068845-3f569d00-1e2b-11eb-95df-876d25c5f566.png)

We encourage users to add all teams during event setup on the online scoring system, run the eligibility check, and update the eligibility before importing the event into FTCLive. This info will all be imported into the system.
