### ISSUE TITLE
Data Import File fail in v1.3, also happens in v1.1.2

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#478]
I was attempting to import data back into the scoring system to upload to orange alliance and one of our database files indicates it fails and doesn't list it as an "active event" but lists it under "all events" but with a different name.  Our events have been submitted to FIRST, however they are not reflected on The Orange Alliance.  We were given the go ahead to upload our past events but it has been unsuccessful, when attempting it indicates our access has expired.  
I am providing the information about our "07" database which is giving us a fail when attempting to import (screenshots) as well as the submission verification.  All other events/db import correctly, not able to attach the db to this message.

[Chandler Event 07.docx](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/4069151/Chandler.Event.07.docx)
[Chandler Submission.docx](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/4069155/Chandler.Submission.docx)

**Comment by adwiii** [comment]
This is a known bug this year. There is currently not a work around, and we are working on fixing this but it will not be in the next release. If you email the database directly to TOA, they can reach out to me and I can repair the database for them. If you need to get access to the database, you can find it in the `/lib/db` folder. 

When you import the database it will show as archived and be mostly usable. However, once you reboot the scoring system it will not be usable. The long way work around here is to use a fresh copy of the scoring system if you need to access it again, though this is clearly not desirable.

**Comment by ftcohioapt** [comment]
I seem to be having the same problem (contact your FTA message), but it does not happen with all db files. Is there a way to prevent certain scoring files from corrupting the software. This is very painful to keep reloading the software each time to process or just print out some results or awards from an event.  [
![dberror](https://user-images.githubusercontent.com/45543906/72680068-9ac5c300-3a83-11ea-9609-50093f249745.JPG)
](url)

**Comment by adwiii** [comment]
This has been addressed in `v1.3.2`.  If you have an event that has been completed that you cannot access, you can import it into `v1.3.2` for access. If you cannot access the event by booting the old copy of the scoring software, you can find the database file in the `libs/db/` folder and import that into `v1.3.2`. 

**LEAGUE MEETS:** if you manually take the database from `libs/db/`, once you have imported into `v1.3.2`, you must export it from `v1.3.2` for it to import properly into future meets/league tournaments.
