### ISSUE TITLE
Awards Entry by separate login entry glitch when saving one field always blank after save

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#484]
Not sure if anyone has experienced this, I have been the scorekeeper and delegated ipads and computers for use with the provided usernames/passwords at 7 events.  I have been fortunate to have all awards entered by the Judge Advisor at each event in range of our router.  I walk them through what they need to do on the page and after all their entry as been completed with the corresponding award tab turning green and verified, they then click the save & exit button believing it has all been contained and saved.  At the conclusion of the finals I open up the awards and review and inevitably the Inspire award is missing the chosen winning team which was originally entered.  I thought when it first occurred that maybe the judge advisor was not clicking off of the field before hitting save & exit button, however I have now sat with the individual entering awards at the last two events and it continues to happen.  When I go back in as the scorekeeper I make a point to review and correct the missing piece before saving and exiting, at that point it shows up the next time I enter the awards page.  I hope this makes sense, not sure why it is happening.

**Comment by emmell620** [comment]
I can confirm this exact same situation.

**Comment by Tomrish** [comment]
I, too, can confirm that this has happened. I thought it was due to the tablet I was using being slightly older and running an older version of the Chrome iOS app, but I guess not because my symptoms mirror your situation almost entirely.

**Comment by adwiii** [comment]
We have attempted to make the auto-save process more robust in `v1.3.2`, though we are not 100% confident we have ironed out the issue completely. @pstrones @emmell620 @Tomrish at you convenience, can you try to reproduce the issue in `v1.3.2` and report back if still experience this issue?

**Comment by pstrones** [comment]
I will be running the 1.3.2 version this weekend at our qualifier and will be able to report back about this issue.  Thanks

**Comment by emmell620** [comment]
I ran 1.3.2 and just entered the awards using the local/admin account. It appears that the issue may be fixed.  I'll let others comment.

**Comment by pstrones** [comment]
I also ran the 1.3.2 version and it appears that the glitch with a missing team winner has been fixed.  Thank you.
