### ISSUE TITLE
Enhancement: Ability to add logos to sponsor entry

### ISSUE THREAD

**Issue by kwstoudt** [FIRST-Tech-Challenge/scorekeeper#485]
Scorekeeping for a qualifier this last week, my event coordinator was a bit dismayed that I could only display text for the local event sponsors. It would be nice if we could upload an image such as the sponsor's logo alongside or in place of the text.

**Comment by adwiii** [comment]
This is something that we are looking to add back into the system, though we do not have a timetable for the return of this feature. This is being tracked under #413; I am closing this issue in favor of that one.
