### ISSUE TITLE
Enhancement Request: Advancement Report

### ISSUE THREAD

**Issue by ftcohioapt** [FIRST-Tech-Challenge/scorekeeper#487]
Would like team name to be included in advancement report as well as team number, Also a feature that can highlight the teams that are advancing from the tournament in the advancement report.

**Comment by pmichaud** [comment]
I think this already exists in the later versions of the scorekeeping software -- there's a "Show Team Name" checkbox at the upper left of the advancement report page, right next to "Condensed".

Pm

**Comment by ftcohioapt** [comment]
so it does - yes I see the checkbox now. So lets leave the request open to highligh teams advancing in the advancement report.

**Comment by adwiii** [comment]
As noted, the team name feature was added in v1.3.1 in response to #477.

@ftcohioapt do you mean to highlight only the teams that are newly advancing from this event and not highlight duplicates? Essentially, highlight the first `x` advancing teams the first time they appear in the list?

If so, the current limitation here is that the scoring system does not track Qualifier host team (optional advancement criteria 1) and does not know how many teams will advance from the event to the next level of competition. Figuring out an easy and intuitive way to add these is something we will explore long term.

**Comment by ftcohioapt** [comment]
**adwii**  Yes - teams that are newly advancing would be my request. I understand the issue with the host team and if they do not compete in their own tournament would not appear anywhere in the advancement report. I was thinking there would be some entry field in the software (linked to the report) that would simply ask how many teams advancing from the tournament excluding any host team). If they leave it blank or null there would be no highlighting in the report. 
In Ohio, we post these advancement reports on our website and I have to go in and edit the pdf report with the highlighter tool to show which teams advanced from the tournament. Not a big deal - just a possible enhancement. May be more useful for events with many advancements as the emcee would easily see where to stop announcing the advancing teams.

**Comment by adwiii** [comment]
With the updated advancement features in `v3.3.7`, the number advanced is highlighted on the advancement report, and the Advancement Display will present the advancement criteria through the number of teams advancing. The advancement information *must* be configured in the Online Scoring System (ftc-scoring.firstinspires.org) prior to the event being transferred to FTCLive. Please read the release notes for more information on the new feature.
