### ISSUE TITLE
API Error after Event Upload

### ISSUE THREAD

**Issue by ehsanmasdar** [FIRST-Tech-Challenge/scorekeeper#488]
Hello!

I'm one of the developers on FTCScores (FTCScores.com). We're noticing that after a scorekeeper uses the "Send Results to FIRST" tab to upload event results, all elimination matches cease to be accessible in the API (NOT_READY error). The "event status" is reported as "Qualifications" in the event selection panel (as shown below) even though eliminations matches have been completed.
![image](https://user-images.githubusercontent.com/1329436/73097476-3f496a00-3eb5-11ea-8b2b-c562918a494c.png)

This has impacted our ability to properly parse and store eliminations match data for events - as there's no way to recover eliminations match data once the event is in this state without inspecting the database file. Qualifications data, however, appears to remain accessible as normal.

**Comment by adwiii** [comment]
Hm. I thought this was addressed in `v1.3.2`. Can you send me an example db that this does not work for?

**Comment by ehsanmasdar** [comment]
@adwiii Ah, didn't realize this was addressed in 1.3.2. We haven't gotten any coverage on 1.3.2 yet, but should this weekend. I'll close for now and reopen if we're still seeing issues. Thanks!!

**Comment by adwiii** [comment]
Sounds good, let me know if you have any issues in the newest version. `v1.3.2` should not have the discontinuities in the API access that you mention. Additionally, any databases that were run pre-`v1.3.2` can be imported into `v1.3.2` and the API will function correctly.

For continued support of versions prior to `v1.3.2` you will likely need to check if there is a winner for the finals series and cache those results in case the user uploads to *FIRST* while you are connected.
