### ISSUE TITLE
Future Feature: Code name of event

### ISSUE THREAD

**Issue by rebeccawhitaker** [FIRST-Tech-Challenge/scorekeeper#490]
First, I appreciate having the events pre-loaded into the scoring database and the code name generated. However, looking ahead to next season and Iowa having over 90 events (majority are league meets), its going to be very confusing when the code names are randomly generated with a number at the end, and the number is unrelated to the event. I'm assuming it will be "2020iameetXX" with XX representing a number. I would like to add/suggest the addition of a date, city, or league name, to help differentiate one meet from another. This also applies for the league tournaments and super qualifiers. Thanks!

**Comment by rgutentag** [comment]
I agree with this request.  In NJ we have 4 different leagues.  To keep them straight I have started naming my event code as follows: FRIST name_league name_date  Using this convention I can easily determine which league file to load at the correct event.  We use the same scorekeeping computer for all leagues.

**Comment by adwiii** [comment]
Starting this year, events should be imported from [the online scoring system](ftc-scoring.firstinspires.org). The events on the online system are pulled from the HQ system. Feedback on event codes has been relayed. The event code attempts to convey, in a few characters, basic information about the event. This includes the region, event type, and a small additional identifier. For example, this year the NJ FTC Southern League Meet #4 is USNJSOM4. We hope that this strikes a good balance between being short yet identifiable. Additionally, with the incorporation of the online scoring system, we hope that event management and importing into FTCLive will be more streamlined.
