### ISSUE TITLE
broken links on Releases page of this repo

### ISSUE THREAD

**Issue by devillechris** [FIRST-Tech-Challenge/scorekeeper#491]
Links to ftc-events.firstinspires.org are failing on this page:
https://github.com/FIRST-Tech-Challenge/scorekeeper/releases

I believe it can be resolved by using the full URL for markdown links, as explained by nadiajoyce here:
https://github.community/t5/How-to-use-Git-and-GitHub/Why-is-my-README-hyperlink-going-to-the-wrong-URL/td-p/10710

A very low priority issue. But it seemed like an invitingly low-stakes opportunity for this first-time github user to get involved  :)

**Comment by adwiii** [comment]
Updated! Thanks for catching that 😅
