### ISSUE TITLE
Edit break end time could cause MatchMaker error

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#493]
When editing the end time of a schedule break, the duration field doesn't change automatically, and remains unsuitable for the start/end times.
Once the duration doesn't match the start/end time, the MatchMaker throw an error.
This is an unexpected behavior because once the duration is edited, the end time does change.
<hr/>

![gif](https://user-images.githubusercontent.com/16443111/73540393-76c99080-4438-11ea-9881-607c87a56000.gif)
![image](https://user-images.githubusercontent.com/16443111/73540423-919c0500-4438-11ea-8b65-3f26f3a2b897.png)

**Comment by adwiii** [comment]
This has been addressed in `v1.4.0` - editing the end time will now update the duration.
