### ISSUE TITLE
Warning when sending dual divisions event

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#495]
When sending a dual division event, it shows a warning that there are not qualification matches, even though the finals division shouldn't have qualification matches.
![image](https://user-images.githubusercontent.com/16443111/75041047-761a9c00-54c4-11ea-80fa-7bfe49550345.png)

**Comment by adwiii** [comment]
That is a very good point :sweat_smile:

**Comment by pstrones** [comment]
We encountered this same message this past weekend at the Arizona State Champs.

**Comment by adwiii** [comment]
This has been fixed in `v1.4.2`
