### ISSUE TITLE
Sponsors in Dual Division Event & Logo Display background

### ISSUE THREAD

**Issue by mcchesneyc** [FIRST-Tech-Challenge/scorekeeper#496]
Regional and Event Sponsors don't show in the sub events for a dual division event.  Dashboard for sub events show the appropriate number of sponsors, but the display hangs up on the "regional" sponsor page, continues to show the second page of national sponsors (Collins Aero) with title of "Regional Sponsors" and the display stops cycling.  Only way to show the sponsors (with logos) is to revert to the -0 event and display through match control from that level.  In v 1.4.0 sponsors (no logo) had to be entered at each level (- 0 and each division) to get the names to display at division level.  Attempts to add or modify sponsors in v 1.4.1 at the division level generates server error 500 - contact your FTA.  Thought I'd give this a shot for our region champs this weekend, but I'm reverting to v 1.4.0 at this point.  One other comment on logo display.  The locally inserted logos appear with a white background.  For the future it would  be best to have the background of Regional and Event sponsors also be white or very very light gray to minimize the contrast.  Doesn't look very professional like the national sponsor pages.

**Comment by adwiii** [comment]
Noted about the division events - I will look into that. 

The white background may be an issue with the file format of the upload. The logos are stored in PNG format which preserves transparency, so I was able to locally upload sponsors that had a transparent background and thus showed up on the gray overlay. Can you post an example image that you had the issue with (or if you do not want to share a sponsor logo can you find a random image that exhibits the issue)?

**Comment by mcchesneyc** [comment]
Attaching 2 sponsor logos as we received them from the vendors.  I can try to convert to .png format to see if that solves the issue.  Was just working with what was sent.
![With Tagline - Full Color](https://user-images.githubusercontent.com/13721345/75066779-3a2a0b80-54b1-11ea-8289-67e0bddda363.JPG)
![TMMTX logo](https://user-images.githubusercontent.com/13721345/75066804-4ada8180-54b1-11ea-9ea5-a6cd6f59b460.jpg)

**Comment by adwiii** [comment]
These image files have the white as part of the image because JPG format does not allow for transparency. Converting to PNG will not remove the white, but it would allow you to use an image editor to translate the white into transparent. Depending on the sponsor, they may have a PNG format with transparency already available.

**Comment by maths22** [comment]
Sponsors in divisions work correctly now with v3.2.4
