### ISSUE TITLE
Multiple Dean's List Entries "add row" not working in vers 1.3.1 & vers 1.4.0

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#498]
When attempting to enter multiple Dean's List nominations at our qualifiers, the "add row" button would not provide another row when clicked.  This happened in both 1.3.1 and 1.4.0 versions.  I didn't utilize 1.3.2, so I am not sure if it experienced the same issue.  In the previous versions the "add row" button did work.  Not sure if something was disabled.

**Comment by maths22** [comment]
I've experienced this on some computers but not others (or possibly some accounts but not others, as the working computers were the master scoring computer (logged in as local), whereas the nonworking ones were auxiliary computers signed in with the judge role)

**Comment by adwiii** [comment]
This has been added in `v1.4.2`. As @maths22 pointed out it was a permissions issue - the judge accounts did not have permission to edit the number of winners whereas the local account did. This fixes the issue by making judges have the proper permissions.
