### ISSUE TITLE
Show Match Display During Match

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#50]
If a new audience display is opened or an audience display is refreshed while a match is underway, there is no way to show the match on it as the "Show Match" button is disabled.

[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2458510/db.zip)

**Comment by adwiii** [comment]
File this under "working as implemented" 😅. The ability to refresh any display during a match and have it recover will be added in the future.

**Comment by adwiii** [comment]
This functionality has been implemented in v0.4.3. If a page is refreshed while a match is in progress, it will re-synchronize with that match.
