### ISSUE TITLE
Dual Division - Inspection/Judging division status reflected in primary event

### ISSUE THREAD

**Issue by pstrones** [FIRST-Tech-Challenge/scorekeeper#500]
We established our judging session in the primary event and didn't set up each division with a separate judging session.  While our inspection is completed in each division (not a specific schedule), the inspectors have their assigned username/password for the specific division for completing each teams inspection.  It would be nice if this information would be carried up to the primary event, so that when looking at the judging/inspection status, you don't have to toggle back and forth between divisions and the primary event.  We manage with utilizing and assigning specific tablets to each division so it's not a big issue, it just would be nice if it could be reflected in the primary event otherwise it looks like inspection needs to be completed again.  

Another idea on this would be to utilize the primary event for the inspections that are to be completed for those teams that make it on an alliance for eliminations.  Just have the required inspection items for that and not the entire inspection page.

**Comment by maths22** [comment]
This has been in the scoring system for the past couple of seasons
