### ISSUE TITLE
#4 seed defeats #1 seed, then becomes #1 seed

### ISSUE THREAD

**Issue by vchposton** [FIRST-Tech-Challenge/scorekeeper#501]
If the # 4 seed defeats the # 1 seed in semifinal 1, the software makes that alliance the # 1 seed (higher seed=Red alliance), although they should be still seeded lower than the winner of the # 2 or # 3 seed. 
Observed in 1.4.1, not tested in other versions.

**Comment by pmichaud** [comment]
I believe the software's behavior is correct per section 4.10 of Game Manual Part 1 ("Elimination Matches"):

> **Semi Finals**
> o Seed #1 and Seed #4 compete against each other in the Semi Finals 1; Seed #1 is assigned as the red Alliance and Seed #4 is assigned as the blue Alliance.
> o Seed #2 and Seed #3 compete against each other in the Semi Finals 2; Seed #2 is assigned as the red Alliance, and Seed #3 is assigned as the blue Alliance.
> **Finals**
> o The winner of Semi Finals 1 is assigned as the red Alliance.
> o The winner of Semi Finals 2 is assigned as the blue Alliance.

In short, if seed #4 makes it to the finals, they play as the Red Alliance even though they were seeded lower than either #2 or #3 (which play as the Blue Alliance in Finals).

Pm

**Comment by vchposton** [comment]
Yes, 4.10 seems to spell out that situation exactly, and the software conforms.

But it seems to conflict with Part 2, <G3>b, Pre-Match Robot Placement:

> b) During the Elimination Matches, the 3rd and 4th seeded Alliance Robots are set up on the Playing Field first, unless the higher seeded Alliance waives their right to set up on the Playing Field second. Alliance color doesn’t change the seeding of a Team during the Elimination Matches. If the 4th seed defeats the 1st seed in the Semi-Finals, they will still have to place their Robot on the field first in the Finals because **_their seeding will be lower than the 2nd or 3rd seed._**

**Comment by cmacfarl** [comment]
> 
> 
> Yes, 4.10 seems to spell out that situation exactly, and the software conforms.
> 
> But it seems to conflict with Part 2, b, Pre-Match Robot Placement:
> 
> > b) During the Elimination Matches, the 3rd and 4th seeded Alliance Robots are set up on the Playing Field first, unless the higher seeded Alliance waives their right to set up on the Playing Field second. Alliance color doesn’t change the seeding of a Team during the Elimination Matches. If the 4th seed defeats the 1st seed in the Semi-Finals, they will still have to place their Robot on the field first in the Finals because **_their seeding will be lower than the 2nd or 3rd seed._**

Seems rather clear.  Alliance color does not determine who places first, and alliance color only plays into the initial seed in the semi finals.  I don't see any conflict here, nor an issue with the scoring software.
