### ISSUE TITLE
High CPU usage on pit display

### ISSUE THREAD

**Issue by nickmcski** [FIRST-Tech-Challenge/scorekeeper#502]
I've recently noticed the pit display is pinning one of our computers CPU usage at 100%. The pit display is the only chrome tab open and is using over 50% of the CPU.
![High CPU Pit Display](https://user-images.githubusercontent.com/1342509/75601879-e903b400-5a7c-11ea-8b54-5cc48ae1f993.png)
This appears to be caused by the high polling of the animate() function. After calling jQuery.fx.stop() CPU usage of the tab reduces to 0%. I've tried increasing jQuery.fx.interval to reduce the number of updates but this does not seem to have any affect.

**Comment by nickmcski** [comment]
Just to clarify this is a low priority issue for me. I'm mitigating the issue by not running any programs other than the pit display on this computer.

Eventually I would like to consolidate our tech setup and run other simple programs on the same computer.

**Comment by maths22** [comment]
This should be resolved in in v3 (for Freight Frenzy), please reopen if you see this happening this season.
