### ISSUE TITLE
Pass path to database file in startup, instead of default initialized database.

### ISSUE THREAD

**Issue by JamieSinn** [FIRST-Tech-Challenge/scorekeeper#508]
We're (Ontario) working on centralizing/making a remote server that will host the FTC Live software, is there an easy way to load in a SQLite DB from a remote path during startup? This allows simple updates on the application, while being able to persist the DB between updates.
This could also trigger the new beta import from previous install option.

**Comment by maths22** [comment]
While this is not directly supported, the scoring system now uses the same directory throughout the whole season with auto updates, so the underlying use case should be easier to handle now.
