### ISSUE TITLE
Disabled Buttons On Live Score Tracking Can Still Be Clicked

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#51]
Example,
The "Robot 1 Landed" button is greyed out if the robot is not latched in the setup however during autonomous the Yes and No buttons can still be clicked/tapped. These buttons act as if they had not been disabled however show no indication of their present state, therefore if accidentally pressed the score will be added but the ref will not know.

This applies to all buttons that can be disabled in the ref score tracking (including robots that no-show).
Present on both mobile and desktop browsers.

[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2458521/db.zip)

**Comment by adwiii** [comment]
Good catch. I had realized this on the initialization page (no shows cannot be selected whether latched or not), but had forgotten to make this change on the other pages. This fix should be in the next release.
