### ISSUE TITLE
Clicking the Unmute Button has no Effect

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#512]
Sometimes clicking the unmute button has no effect and dialog reappears
I can reliably reproduce every time, but some other users cannot
Clicking any of the test audio buttons in the setting menu clears the warning
![gg](https://user-images.githubusercontent.com/28027434/96471047-7303c580-1276-11eb-8625-e634fb657449.gif)

**Comment by adwiii** [comment]
What OS/browser and version are you using?

**Comment by bsimmons99** [comment]
Windows 10 (19041.572)
Google Chrome (86.0.4240.75)

**Comment by adwiii** [comment]
I have been unable to reproduce this locally. However, since you noted that playing the test sound fixed it, the "Unmute" button now plays a short tone. Let me know if you continue to experience this in v2.1.0.
