### ISSUE TITLE
Field Display Showing False Scoring Elements

### ISSUE THREAD

**Issue by kwstoudt** [FIRST-Tech-Challenge/scorekeeper#515]
While testing the system to refresh my memory in preparation for this season, I have found that when selecting a postiion for Red Wobble Goal 2, the field display updates both Red and Blue Wobble Goal 2s (points are only assigned to red). This affects all three options (None, Start Line, and Drop Zone).

Version 2.1.0

I have attached pictures of the field display and the active match in FTC Live below.

![Field Display](https://user-images.githubusercontent.com/4512688/98453852-019f9000-211b-11eb-88bd-86ab889369ca.jpg)
![FTC Live](https://user-images.githubusercontent.com/4512688/98453853-02382680-211b-11eb-9f96-dfbebae04372.jpg)

**Comment by adwiii** [comment]
This has been fixed in v2.3.0
