### ISSUE TITLE
Windows MatchMaker.exe

### ISSUE THREAD

**Issue by DualFlames** [FIRST-Tech-Challenge/scorekeeper#516]
Opening the program gives the unprotected program could put your PC at risk blah blah, I run the program anyway and it tries to open but fails. I have tried opening the program with admin privileges and redownloading the .zip and extracting it.

**Comment by adwiii** [comment]
Does a terminal window open when you hit "Run anyway"? Do you have any log files in the `/bin/logs` folder?

**Comment by DualFlames** [comment]
No no terminal opens, some icon pops up on the taskbar, for a quick second and then closes. in the /bin folder this is all there is this in the image below.
![Screenshot 2020-11-09 182710](https://user-images.githubusercontent.com/69734803/98608438-321d3080-22b9-11eb-9d50-cf9a4b61ea43.png)

**Comment by adwiii** [comment]
If no terminal opens then there is likely an issue with Java. If you run FTCLocal.bat from the command line it will give you a more detailed error message. The system requires Java 1.8 or greater to run.

**Comment by DualFlames** [comment]
![image](https://user-images.githubusercontent.com/69734803/98609033-76f59700-22ba-11eb-870f-507c086c7b83.png)
Okay, how can I install this version of Java 1.8? 

npm - something...?

**Comment by adwiii** [comment]
You should be able to download it from this page:
https://java.com/en/download/

**Comment by DualFlames** [comment]
Okay, thanks. Will let you know how this goes!

**Comment by DualFlames** [comment]
I have gotten to this, but this doesn't look like things I have seen...Is this correct, and where do I go from here?
![image](https://user-images.githubusercontent.com/69734803/98610230-2895c780-22bd-11eb-8b6e-81274aa835ba.png)

**Comment by adwiii** [comment]
Yes, that is the main landing page for FTCLive used for traditional events so it looks like things are set up correctly. The full manual for the software can be found [here](https://www.firstinspires.org/sites/default/files/uploads/resource_library/ftc/scorekeeper-manual.pdf). The online scoring system (https://ftc-scoring.firstinspires.org/) is used to set up events and then transfer them into FTCLive to run at the event. 

What are you trying to do and I can direct you to the relevant documentation.

**Comment by DualFlames** [comment]
I'm trying to get my team's live scoring system thing up and running for us to do our virtual scrimmages. I tried going through the manual where I needed help and was very lost.

**Comment by adwiii** [comment]
For scoring matches for remote events, you only need to access the online scoring system (https://ftc-scoring.firstinspires.org/) - no downloaded software is required. The software on this GitHub repository is for volunteers running traditional events. Using the online system, the Lead Mentor (or another user they have authorized) logs in using their account on firstinspires.org and can then access the pages to score matches. 

This manual is specifically about using the online scoring system to score your matches: [Scoring System - Team Guide](https://www.firstinspires.org/sites/default/files/uploads/resource_library/ftc/ftc-cloudscoring-team-user-guide.pdf)
[This YouTube playlist](https://www.youtube.com/watch?v=5pGDi_Kq7ks&list=PLEuGrYl8iBm48sXHM8wOIPECDvD1zGgr2) also gives a walkthrough of using the system.

**Comment by adwiii** [comment]
@DualFlames sorry for the confusion. We have updated the README on the main page to hopefully help others looking for the online scoring system. I am closing this issue - feel free to re-open if need be.
