### ISSUE TITLE
Different results on local db and firstinspires.org

### ISSUE THREAD

**Issue by DimastX** [FIRST-Tech-Challenge/scorekeeper#517]
[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/5555986/db.zip)
11/15/2020 I was Lead Scorekeeper on Saint-Petersburg`s League Meeting#2 (https://ftc-events.firstinspires.org/2020/RUSTM2/qualifications). On this link there are qualification results, they have same score but if you will look at the scoresheet, it`s different. For example, in first match red team in autonomous hasn`t delivered any Wobbles, but on firstinspires.org they had. It`s not unique. In next match there are also troubles with Wobbles, so I suggest it`s system error

**Comment by tvbarnette999** [comment]
Thanks for reporting that! It was an issue with the importing of data into the online system, which has now been fixed. We have gone back and repaired the 4 completed Traditional Events:
* RUSTM1
* RUSTM2
* USGAETM1
* USGAETM2

Note to API users: this affected the API as well, and should be corrected for subsequent fetches of these events. The specific error was `wobbleDelivered1` was always equal to `wobbleDelivered2`.
