### ISSUE TITLE
Overlay Background Fails After Audiency Key

### ISSUE THREAD

**Issue by devyntk** [FIRST-Tech-Challenge/scorekeeper#521]
After switching the display to the Audience Key, from there on forward the match overlay will be broken, showing a branded FIRST background instead of the solid color chroma key. The background of the match overlay will be in this broken state even after switching to any of the other different screens/displays until the display page is refreshed. 

v.2.5.0 offseason, confirmed using both OBS Browser (chromium embedded framework based) and Chrome 91.

**Comment by tvbarnette999** [comment]
This has been fixed in v2.5.4_OFFSEASON. Thanks for letting us know about it!
