### ISSUE TITLE
Scoring Logic

### ISSUE THREAD

**Issue by ftcohioapt** [FIRST-Tech-Challenge/scorekeeper#522]
Please confirm with GDC whether the scoring logic is correct in v3.0.1: 

1) Robot places 1 piece of freight in storage unit during auto and correctly gets 2 points, but then if do nothing and still have same 1 piece of freight in storage unit at end of match it scores an additional 1 point. 
2) Robot places freight in level 1 of alliance shipping hub during auto and correctly gets 6 points, but then if do nothing and freight is still in level 1 at end of match it scores an additional 2 points.

Is expectation that any freight scored in storage area or shipping hub at end of auto gets scored again at end of match even if it was not moved? I believe, in previous seasons, (such as Skystone) the scoring logic did not re-credit achievements at end of match that were already completed and scored in auto. Maybe this season is different but GM2 is not explicit in this aspect.

**Comment by adwiii** [comment]
The current behavior is consistent with the behavior in prior seasons. However, this is not the appropriate forum for questions related to rules interpretations, including scoring definitions. For additional follow up, please post this question on the official forums for a direct GDC response. The FTC Q&A forums will be available soon at [https://ftc-qa.firstinspires.org/](https://ftc-qa.firstinspires.org/), or you can request access to the volunteer forums following the instructions in the Game Manual.
