### ISSUE TITLE
Unable to add teams from outside our region

### ISSUE THREAD

**Issue by vchposton** [FIRST-Tech-Challenge/scorekeeper#524]
Unable to add teams from outside our region to event (scrimmage).

**To Reproduce**
1. Login ftc-scoring.firstinspires.org
2. Select Region
3. Select Events
4. Select Manage Event
5. Select Step 2 - Add/Manage Teams
6. Select Find by State/Province - use pulldown to select different region
7. Click on a team - does not highlight purple.  If you click the checkbox, it is marked, but team is not added.
8. Select Add Individually, enter team number from out of region.  Click Add.  Team is not added.

**Expected behavior**
I expect to click on a team row, have it highlight in purple, click Done, and have it added to the event.  In the local version, it does work properly.

**Device (please complete the following information):**
 - OS: Win 10
 - Browser [Vivaldi]
 - Version [4.3.2439.56]
 - Browser [Chrome]
 - Version [95.0.4638.54[

**Additional context**
Local software (3.1.1) works as expected.

**Comment by wxtrav** [comment]
I can confirm that the same problem exists even if you have added the out-of-state team to a league and they appear in the league roster.  You cannot add them from the "League Members" list, either.

**Comment by tvbarnette999** [comment]
This has now been fixed in the Online Scoring System.
