### ISSUE TITLE
Automatic Event Import to FTC Live Showed Wrong Date

### ISSUE THREAD

**Issue by silvanoc109** [FIRST-Tech-Challenge/scorekeeper#526]
### **The Issue**
While utilizing the "Automatic Import" of the event data from FTC Scoring to FTC Live, FTC Live showed that the event was taking place on a different date.

FTC Scoring showed (Oct 30 - correct).
FTC Live showed (Oct 29 - incorrect).
This import was done the night of Oct 29. The night before the event.

### **Workaround**
After importing the event, I was able to go back into the Event Management section and manually change the date to match the information found in FTC Scoring.

### **Device**
Windows 10 - FTC Live v3.1.1

### **Additional Context**
Date of Issue: Oct 29, 2021
Submission ID: 04238ef0-29e9-4fd1-989c-02e3c6739a0f

Attached is a screenshot showing the mismatch of the date.
![dateMismatch](https://user-images.githubusercontent.com/11062571/139560262-f8ea6cd6-b726-4ade-bdfc-9920a892d957.png)

**Comment by VHSCSteacher** [comment]
I also had this exact same issue when importing my events.The date on the "Confirm Event Setup" was 1 dat earlier than the actual event. I imported 4 events and all 4 were a day off. I was doing the import a few days before the event so it was not the current date. I just ignored the fact that the date was wrong on the confirmation screen and everything seemed to be okay.

**Comment by adwiii** [comment]
This has been fixed in `v3.3.7`.
