### ISSUE TITLE
display issue in OBS

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#528]
**Describe the bug**
when you go into obs and you create a browser source and set the link to the computers ip and then log in to the created account in the scoring system and then go into either pit display of Scoring/Timing Displays the screen just goes black and nothing ever happens it was working in the last Preview Release of the scoring system

**To Reproduce**
1. open obs studio  
2. create a browser source in obs studio
3. put in the IP of the computer into the URL space 
4. then click inspect and then login to the created account
5.  then try clicking on either pit display or Scoring/Timing Displays and the screen should go black and do nothing

**Expected behavior**
once you do that the browser source display should go black and the pit display or the Scoring/Timing Displays should not appear 

**Screenshots**

**Device (please complete the following information):**
 - OS: [windows]
 - Browser [obs studio browser]
 - Version [3.1.1 scoring stystem ]

**Additional context**

**Comment by tvbarnette999** [comment]
This has been fixed in v3.4.1
