### ISSUE TITLE
Show Password Button

### ISSUE THREAD

**Issue by afera15** [FIRST-Tech-Challenge/scorekeeper#529]
When typing in a password, either to update a password or to login, please add a show password 

![image](https://user-images.githubusercontent.com/16884208/140450952-952803f2-90e4-431b-a16b-83f65a7df32b.png)

THIS IS NOT TO DISPLAY A USER CURRENT PASSWORD

**Comment by tvbarnette999** [comment]
This has been implemented in v3.1.4. It appears on both the login screen and the create custom account screen.
