### ISSUE TITLE
event rankings

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#530]
In prior versions of the live scoring system we had both event rankings and combined league rankings.  This past weekend I realized that we now only have combined ranking listings.  We had a 11 team league meet but had some teams showing rankings of 15, 18 and 25.  This was the second event in this league so some teams had 10 plays and some only had 5 plays.  This shows on the preview screen and the match results page.  This is very confusing to the teams.  Any way we can get the event rankings back also.  When I looked at the pit display is when I got the aha moment.

**Comment by silvanoc109** [comment]
Agreed - this sounds like it should be a toggle or have two different screens.

The other thing that is confusing about this (or has been in the past) is the rankings that were shown during the Match Results screen were for that event, not the league.

If the Blue Alliance wins (during a league meet), a team may be shown as "▲ 2" and a team may think they are 2nd in the league. It is not until you find the league rankings that you realize the team may not be 2nd for the league, they are only 2nd for that event.

**Comment by maths22** [comment]
We have improved this for v3.2.0.  From the release notes:

> * League Meet Rankings display changes
>   * Show Meet & League Rankings on Preview, Results, and Pit displays.
>     * IMPORTANT: The "Meet Rankings" are still cumulative, but only include the teams present at the meet.
>   * Rankings report will show both ranks, but will always show every team in the league.
>   * Pit display has option to show or hide teams in the league that are not present.
>   * Showing of meet rankings can be turned off through the control page's settings tab. If turned off, displays will revert to only showing the league rank. This setting is automatically set to "off" when MatchMaker is run if and only if the meet team list and league team list match.
