### ISSUE TITLE
Create User Fails when "Show Password" is Selected 

### ISSUE THREAD

**Issue by silvanoc109** [FIRST-Tech-Challenge/scorekeeper#531]
### **Initial Info**
This bug was encountered and replicated on multiple computers during a training session with another scorekeeper.

### **The Issue**
When the "Create User" feature is used, any time the newly added "Show Password" checkbox is selected, an error will occur and the account will not be created. The message appears to be a malformed HTML error message containing the text `It appears that a Server error occurred. Please contact your FTA.`.

The HTML message in its entirety is attached down below.

This bug does not care whether the new user is created for a specific event or if the "All Events" option is selected. This issue also occurs with the "Show Passwords" checkboxes selected if the account was previously created and then is modified to use a different password.

### **Workaround**
Unchecking _**both**_ "Show Password" checkboxes will allow the account to be created.

### **To Reproduce**
1) FTC Live was running.
2) Go to "Event Admin" -> "Create User"
3) Enter a username, password, re-confirm the password.
4) Check one or both of the "Show Password" checkboxes.
5) Click "Create Account"

### **Device**
Windows 10 - FTC Live v3.1.4

### **Additional Context**
Date of Occurrence: November 12, 2021

The screenshot below show the error occurring when both boxes are checked.
This [html_errorText.txt](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/7531398/html_errorText.txt) file contains the entire HTML error message.

![newUserShowPassword](https://user-images.githubusercontent.com/11062571/141605538-a6ae4db7-0eeb-46b4-a272-46809fa6083d.png)

**Comment by maths22** [comment]
This bug has been fixed in v3.2.0
