### ISSUE TITLE
Live scores can show negative due to penalties

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#532]
**Describe the bug**
If a penalty is given to a team during the match the live score on the audience and field display will show a negative value, however on the active match page it will show a live score of 0.  When the score is committed and posted it will show the correct value of 0 if the penalty would make the team go negative.  

**To Reproduce**
1. Run a match
2. Give a team a minor or major penalty
3. Look at the live scores

**Expected behavior**
According the Game Manual Part 1, Section 5.2 "Penalty points are subtracted from the Team's score at the **end of the Match**.... any negative score will be recorded as zero (0)..."  My interpretation of this is that the major and minor penalties should not effect the live score on the audience and field displays at all, and should only effect the score that is shown to spectators when the score is posted.  

**Screenshots**
N/A

**Device (please complete the following information):**
Effect all equally

**Additional context**
From my experience this weekend this caused confusion both for the teams and the audience on why the score showed negative during the match and then changed to zero after the match was over.  We worked around it by not entering any penalties into the system until on the final review page of the score trackers.

**Comment by tvbarnette999** [comment]
This is the intended functionality. From Section 5.2: "A Team’s score will go negative if the Penalties incurred are more than the points they have earned in a Match". 

The display shows the negative scores to indicate to the teams during a match how far below 0 they are and thus how much they need to recover to get positive again. Once the scores are committed, any negative scores become 0 per Section 5.2. Please do not wait to enter known penalties as this reduces the accuracy of the live scores. Please direct any further questions about the display of negative scores to the [Q&A](https://ftc-qa.firstinspires.org/).
