### ISSUE TITLE
Bonus for cargo/TSE delivery during autonomous not being awarded

### ISSUE THREAD

**Issue by JannieRee** [FIRST-Tech-Challenge/scorekeeper#533]
**Describe the bug**
The scoring system did not award the bonus points for delivery of cargo/TSE to the correct level (based on barcode randomization) of the shipping hub.

**To Reproduce**
During scoring of an event, cargo/TSE is shown to be delivered to the correct level of the team shipping hub, but bonus points weren't awarded, no way to input, etc.

**Expected behavior**
If cargo or TSE is delivered to the correct level (based on barcode randomization) of the alliance shipping hub, bonus points (cargo - 10pts, TSE - 20 pts) should automatically be awarded to the alliance.  Either that or we need somewhere to indicate that the points should be awarded.

**Screenshots**

**Device (please complete the following information):**
I'll have to get this from our Lead Scorekeeper

**Additional context**
It would be helpful if the scoring system captured the barcode randomization for each match, so we can go back and see on what level the cargo/TSE should have been delivered.

**Comment by pmichaud** [comment]
> **Describe the bug** The scoring system did not award the bonus points for delivery of cargo/TSE to the correct level (based on barcode randomization) of the shipping hub.

By way of possible further clarification -- there are no bonus points for additional "cargo" or "TSE" being placed on the correct level of the Alliance Shipping Hub.  Only the Pre-Loaded Box placed on the appropriate level receives bonus points, and that is dependent on whether the team started the match with a Duck or Team Shipping Element on the barcode.

> **Expected behavior** If cargo or TSE is delivered to the correct level (based on barcode randomization) of the alliance shipping hub, bonus points (cargo - 10pts, TSE - 20 pts) should automatically be awarded to the alliance. Either that or we need somewhere to indicate that the points should be awarded.

This is not a correct interpretation of the scoring.  Only placing the Pre-Loaded Box on the appropriate Alliance Shipping Hub level earns the bonus.

Pm

**Comment by JannieRee** [comment]
I probably presented it incorrectly - it was delivering pre-loaded
cargo/TSE to the correct level.
