### ISSUE TITLE
Inspection Status Display does not Auto Update

### ISSUE THREAD

**Issue by Crossle86** [FIRST-Tech-Challenge/scorekeeper#535]
During our event over the weekend the inspection status display did not auto update. We had to hit the refresh button to get an updated status display. I believe it should auto update and I think I saw it update during a simulation run, but at the actual event no auto update at all.

**Comment by silvanoc109** [comment]
Which page were you on?

- If you were on "Inspection Status", that page has a note that it doesn't automatically update.
- You have to click on a "Projector Friendly" option to get it to refresh every 15 seconds.

(I had a scorekeeper who had this happen to them as they were on the wrong screen. There could be another bug but it's a known point of confusion.)

![Inspection](https://user-images.githubusercontent.com/11062571/142088066-01fba6d8-b74d-4461-a821-8b0e0cb1e1fe.png)

**Comment by Crossle86** [comment]
Ah, missed that. Will try the projector fix.
