### ISSUE TITLE
Importing all teams into League Tournament

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#538]
Describe the bug
When I went to import teams into my League Tournament, I clicked on the "Add All" button. It asked if I wanted to import all 14 teams and I answered "Yes". The screen flashed as if it selected all, but on further observation, only two teams were selected.  I clicked the button a second time, and it asked if I wanted to add 12 teams (14-2), and I answered "Yes". This time, all teams were selected and then I chose "Done" and all teams were imported.

Steps to reproduce
See above. But when I tried to remove all the teams and press Done, and then tried to import them all again, it selected all 14.

Device:
Windows 10 on Lenovo laptop
Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by vchposton** [comment]
> The screen flashed as if it selected all, but on further observation, only two teams were selected. I clicked the button a second time, and it asked if I wanted to add 12 teams (14-2), and I answered "Yes". This time, all teams were selected and then I chose "Done" and all teams were imported.


I observed identical behavior.

**Comment by maths22** [comment]
This has been fixed
