### ISSUE TITLE
Match Results Page Shows Incorrect/Misleading Information When No Schedule Present

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#54]
Clicking "Match Results" from event home tells the user "Teams have not been added to this event yet" even though teams have been added and a schedule has not been generated. This is probably due to no schedule being present and should probably reflect that.

[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2458579/db.zip)

**Comment by adwiii** [comment]
This has been fixed in v1.0.0
