### ISSUE TITLE
Autonomous Bonus not tracking

### ISSUE THREAD

**Issue by ldbierman** [FIRST-Tech-Challenge/scorekeeper#540]
We had a situation today that I could not figure out. 
The Blue Alliance in Match 10#  placed the preload block on level `#3` of the Blue Alliance Shipping Hub. The software gave them the points for the block on the Blue Alliance Shipping Hub but did not give them the bonus points. The field was randomized to be level `#3`.
I tried putting a preload block on each different level but the software did not give any bonus points.
Not sure if this is going on in all of the matches but definitely the team put the block on the correct randomized tier for this match.

Archive File from FTC [Live](https://drive.google.com/file/d/1xwtgZTFrU8fT0Md4lS4o2lgLeWhyYmqO/view?usp=sharing)

**Comment by maths22** [comment]
In match 10, it appears that neither robot has "Yes" marked for the preload box.  The bonus is tied to the appropriate preload box being checked. (In theory a team could instead have delivered a non-preload block, and then they wouldn't get the bonus, so we can't calculate the bonus from where a block is)

Please see this comment for more information: https://github.com/FIRST-Tech-Challenge/scorekeeper/issues/533#issuecomment-969132219
