### ISSUE TITLE
Importing from previous version

### ISSUE THREAD

**Issue by VHSCSteacher** [FIRST-Tech-Challenge/scorekeeper#541]
**Describe the bug**
Import Data doesn't work (v3.2.0). It is stuck on "Importing Data". The progress bar never moves.

**To Reproduce**
Try to import data from a previous version of the scoring software.

I realize that Import Data is Beta but there still needs to be a way to upgrade to the latest version of the scoring software without starting over from scratch every time there is a new release. Either the Import Data needs to work, or when you do a Version Check/Update it needs to just download the new version and install it over the old version without affecting any previous data.

**Comment by cmacfarl** [comment]
Not saying that bug doesn't exist here, but can you help me understand what starting over from scratch entails with respect to your workflow?

**Comment by VHSCSteacher** [comment]
Sure...we have a metro league so I have to get all the teams in the league (62 teams) then separate them into 4 separate events. Then I have to re-create all the users and passwords for Lead Referee, Lead Inspector, Referees, Inspectors, and other scorekeeper.

**Comment by maths22** [comment]
With the new installer-based/auto-update workflow this is now a non-issue
