### ISSUE TITLE
Duck Scoring during Autonomous

### ISSUE THREAD

**Issue by daven78** [FIRST-Tech-Challenge/scorekeeper#542]
If a team scores the duck during autonomous, you have to score it live.  If you miss it and move on it is locked and you can't change it either way. It only scores or doesn't score during the autonomous period. Even during the review on the scoring tablets before submitting, it won't change the score :(

I didn't try to change it at the scoring app, only on the tablets the referee uses.

**Comment by tvbarnette999** [comment]
This is working as intended, and is true of all scoring achievements. The scores shown on the live scoring displays are frozen for each alliance once the referee enters review. This is to prevent the displayed scores from potentially jumping around during any referee discussions after the match. Any changes made post-match are reflected on the control page's active match tab once the referee submits review and then once the scorekeeper posts scores they are shown on the audience display's results screen.
