### ISSUE TITLE
Scorekeeper Manual Link Broken FIRST-Tech-Challenge / scorekeeper documentation

### ISSUE THREAD

**Issue by ftcohioapt** [FIRST-Tech-Challenge/scorekeeper#543]
I could not find the best place to post this issue, but the hyperlink to the FTC Scorekeeper Manual (in documentation section of github FIRST-Tech-Challenge / scorekeeper) is broken. Can you please fix the link?

**Comment by maths22** [comment]
Thank you for reporting this.  Fixed in aa5d6e957ce1a2a61664c2812bf17bb5e83e5484
