### ISSUE TITLE
not showing event completed

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#544]
**Describe the bug**
We finished our event on 11/28 in NJ.  I uploaded the file to FIRST.  The event shows all the matches completed and event completed on ftc-events website but not on the ftc-scoring website.  Why did this happen.  The 11/27 event everything show completed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by tvbarnette999** [comment]
Did the "Send Results" page give you a submission ID?

**Comment by rgutentag** [comment]
No

⁣Get BlueMail for Android ​

**Comment by tvbarnette999** [comment]
Does the page still have the "Submit Results" button? 

If so, try clicking it again and seeing if the submission goes through.
If not, please go back to the event dashboard (in the traditional scoring system) and select "Download Archive File" and post it here. You will need to zip it before github will allow posting it. If possible please also zip up the `logs` directory inside the scoring system folder and post those as well.

**Comment by rgutentag** [comment]
I won't have access to our scoring computer till Saturday at our next event.

⁣Get BlueMail for Android ​

**Comment by rgutentag** [comment]
Was able to upload data
