### ISSUE TITLE
Change match schedule after it is generated

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#546]
**Is your feature request related to a problem? Please describe.**
After the match list is generated there is no ability to change any aspect of it.  For example it might be created with the assumption that matches will begin at 10AM but a speaker might talk too long and matches don't actually start until 10:30.  This makes the cycle time report inaccurate.

**Describe the solution you'd like**
A way to change the match schedule elements after it has been generated.  Especially to change the start time and expected cycle time.  Nice to have features would be to insert breaks so if we are ahead of or behind schedule we can insert lunch at the time we actually stop rather than a guess at the beginning of the day.  Obviously this would not include changing anything about which teams compete in each match, just the metadata about the match list.

**Describe alternatives you've considered**
Manually calculating offsets in the cycle time report.  In theory this could be tracked in a spreadsheet, but would be much cleaner if it was built into the system.

**Comment by jvens** [comment]
Bumping this issue again as something that would still be very useful.  Sometimes Drivers Meeting runs long and we are late starting matches, or lunch ends up being at a different time or not in the original schedule.  It would be really nice to have a way to adjust these things after the schedule is adjusted to make both the cycle time report more accurate as well as the ahead/behind indicator on the match control page more accurate and useful.

Also, this is tagged with cloud, but it should be local.

**Comment by maths22** [comment]
This has been added in v5.4.0
