### ISSUE TITLE
Add Head Referee Default Account

### ISSUE THREAD

**Issue by ftcohioapt** [FIRST-Tech-Challenge/scorekeeper#547]
Default accounts can be created for event admin, inspector, lead inspector, judge, and referee. There is no default account for head referee(s) to view match scoresheets. The scorekeeper must separately create a user account and password (selecting the head referee option). Can the head referee account be set up as a default?  One head referee would be needed for single division event and up to three for dual division.

**Comment by adwiii** [comment]
This has been added in `v3.3.7` to coincide with the new Head Ref page feature. Please read the release notes and the internal documentation for more information on the new feature.
