### ISSUE TITLE
Remote Events missing whether team is parked in end game or not

### ISSUE THREAD

**Issue by khoyt5** [FIRST-Tech-Challenge/scorekeeper#548]
The ftc-events.firstinspires.org is not showing that the robot is parked but has the right end game score
![Example](https://user-images.githubusercontent.com/14354979/144944599-e69d4357-954c-4066-83cc-46eb1c325cbd.png)

For example it says no robot parked but 6 points allocated. This only happens for remote events.

**Comment by maths22** [comment]
This issue was fixed
