### ISSUE TITLE
How to stop webserver on OSX

### ISSUE THREAD

**Issue by nebomusic** [FIRST-Tech-Challenge/scorekeeper#55]
After testing the Scorekeeping Application:
1. Closed Terminal Window on OSX
2. The localhost and ip address still broadcast access to App.

How do you stop the webserver from running on OSX after finishing with application?

**Comment by adwiii** [comment]
Hm. In windows closing the window kills the underlying process. If the Mac is allowing the process to continue to run, then you would need to use the equivalent of CTRL+C to kill it from the command line before closing the terminal. 

@ftctechnh can you verify how to close on a Mac?

**Comment by audiomoddified** [comment]
Control-C in the terminal window does kill the process on a Mac.

**Comment by ofekashery** [comment]
Open the ``Activity Monitor`` and kill ``java``

**Comment by ofekashery** [comment]
@adwiii I found a fix for this issue.
In the bash start script, you should change the last line (``read -p "Press enter to continue"``) to **``exit 1``**.
Then, the web server will then be killed if you close the terminal, as we expect.
