### ISSUE TITLE
Enable two/multiple tablets per alliance

### ISSUE THREAD

**Issue by colatuttorf** [FIRST-Tech-Challenge/scorekeeper#550]
**Is your feature request related to a problem? Please describe.**
Yes, FTC matches can be very eventful, particularly in games like Freight Frenzy where overall speed is stressed in the game design - and catching all the scoring for an alliance with one score keeper can be very difficult, and very exhausting match after match.  I've always suggested for referees to be "1 referee per robot", this way any robot to robot interactions have at least two pairs of referee eyes on them, but this is incompatible with the current FTC Live scoring system.  Matches are becoming increasingly difficult for the referees, and this could help lighten their load substantially.

**Describe the solution you'd like**
Enable two tablets per alliance to work together to record an alliances match score.  ie: 1 referee/scoring tablet per robot

**Describe alternatives you've considered**
Using pencil/paper to record match results without use of the FTC Live system

**Additional context**
N/A

**Comment by maths22** [comment]
This is not a feature we intend to support for the foreseeable future
