### ISSUE TITLE
Incorrect high score reported on ftc-events

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#551]
High score on Rankings report is incorrect based on scores from match

**To Reproduce**
Team #13176 scored a 154 in Match # 3 from Meet # 4 in Mississippi Central League, yet on the Rankings page, it shows that their high score is 147.  As they say on SNL, "What up with that?"

**Expected behavior**
The high score should be accurate

**Screenshots**
Ranking list:
![image](https://user-images.githubusercontent.com/12737153/146692819-3d9bea89-367f-4b26-9d92-cfe114b27470.png)

Match results:
![image](https://user-images.githubusercontent.com/12737153/146692769-058f877d-0ba4-4e3b-a5dc-495a59d2985f.png)

**Comment by emmell620** [comment]
Here's the real Rankin list:
![image](https://user-images.githubusercontent.com/12737153/146692800-d0f4394d-fa6c-4a65-ba3c-09893274f2cb.png)

**Comment by adwiii** [comment]
This is the intended behavior. The high score shown in the rankings list is the highest score achieved in the Matches that count for that Team's ranking. Team 13176 is a Surrogate for Qualification 6, meaning that Match is not used in calculating their ranking, and thus does not reflect in their high score. Note that their Alliance partner, Team 12390, is not a Surrogate and 154 is shown in the rankings as their highest score.

![image](https://user-images.githubusercontent.com/9453262/146694064-ceffab7d-35cc-4a36-ad1b-ad663ec900fc.png)

Note also that high score is not used as part of the sort for rankings.
