### ISSUE TITLE
Add link to ftc-events as a display page

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#552]
**Is your feature request related to a problem? Please describe.**
Need a convenient way tell people how to view the real-time scores on ftc-events.

**Describe the solution you'd like**
Add a page to the audience display that could be shown from the video tab of the match control page that would show information about viewing the event and detailed match score data on [ftc-events.firstinspires.org/2021/eventid]().  Bonus points if you also include a QR code on the page that people could scan with their phones from the audience.

**Describe alternatives you've considered**
Do similar to above using the message display page.

**Additional context**

**Comment by adwiii** [comment]
This has been added in `v3.3.7`. From the "Video Switch" Tab on the Match Control Page there is a "Show Online Results Info" button that will show information on the display about how to access ftc-events including a QR code (bonus points achieved! 🙂 )
