### ISSUE TITLE
Request Additional Websocket Update Types 

### ISSUE THREAD

**Issue by KingLinkTiger** [FIRST-Tech-Challenge/scorekeeper#553]
**Is your feature request related to a problem? Please describe.**
The justification for this request would be to notify event, production, and field volunteers of various milestones of a match so that they can take an action based on it.

A real world example of a problem this would solve is: Notifying video production staff of Match Randomization so that they can switch camera views of that field. Which is especially useful as video production volunteers may be responsible for multiple events and fields at the same time. 

Implementing this feature would also allow for automation, such as providing the ability to automatically switch camera views/scenes within OBS.

**Describe the solution you'd like**
The Websocket currently only provides updates for the following events/types: MATCH_LOAD, MATCH_START, MATCH_COMMIT, MATCH_POST, MATCH_ABORT

Requesting additional Websocket events/types for the following events:
1. "Show Random" Button Clicked
2. "Show Preview" Button Clicked
3. Match End

Optionally the addition of the following events would also be useful:
- Start of Teleop
- Start of End Game
- Timeout Start/Stop/End

**Describe alternatives you've considered**
The alternative is to have a volunteer continuously watching the Scoring/Timing Displays and informing other volunteers of the various match states. As this is a manual process it is not guaranteed to receive the alerts on time if at all.

**Additional context**
N/A

**Comment by lilyinstarlight** [comment]
Having a `MATCH_PREVIEW` event when the "Show Preview" button is clicked to update the audience display would help significantly for timing when to start automatic match recordings for the OBS script<sup>[1]</sup> we've been working on for a few years now

Right now it just starts with MATCH_LOAD and we will probably just go back and trim the YouTube videos as needed this season when a match is loaded a while before the preview is shown

<sup>[1]</sup>: https://github.com/FIRST-South-Carolina/obs-ftc-stream-manager

**Comment by adwiii** [comment]
`v4.2.0` has added the following events:
* `SHOW_PREVIEW`
* `SHOW_RANDOM`
* `SHOW_MATCH`

Note that we do not provide a "Match End" (or other similar transitions for DC, EG, etc) as the match will either end at the scheduled time or you will receive an abort event prior to that time.

**Comment by ofekashery** [comment]
@adwiii Thank you!

**Comment by nomad-geek** [comment]
:clap:
