### ISSUE TITLE
Websocket Does Not Send MATCH_LOAD If Match Has Previously Been Loaded

### ISSUE THREAD

**Issue by KingLinkTiger** [FIRST-Tech-Challenge/scorekeeper#556]
**Describe the bug**
The Websocket API does not send a MATCH_LOAD event if the match being loaded has been loaded before.

**To Reproduce**
Note: The following assumes that you already have an event with a match schedule generated.

1. Connect to Websocket API
2. On the match control page, load Qualification 1.
3. Verify that the Websocket has received the MATCH_LOAD event for Q1.
4. On the match control page, load a different match (e.g. Qualification 2).
5. Verify that the Websocket has received the MATCH_LOAD event for Q2.
6. On the match control page, load match Q1 again.
4. Observe that the Websocket has NOT received the MATCH_LOAD event for Q1.

The same will now also occur if you now load Q2. But for Q3 and on the Websocket will send a MATCH_LOAD event as expected.

**Expected behavior**
The Websocket API sends a MATCH_LOAD event on every match load.

**Screenshots**
N/A

**Device (please complete the following information):**
 - FIRST Tech Challenge Live Version: 3.2.0
 - OS: Windows
 - Browser: Google Chrome
 - Version: 97.0.4692.99

**Additional context**
N/A

**Comment by tvbarnette999** [comment]
This has been fixed - `MATCH_LOAD` will now be sent on re-load of a previously loaded match.
