### ISSUE TITLE
Ability to change IP address displayed in UI

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#559]
**Is your feature request related to a problem? Please describe.**
The system reports at the top of most pages the IP address of the score system which is very convenient and great.  It seems to get this IP address by enumerating all the network interfaces on the server and then picking the first one.  This isn't always the correct interface and can cause some confusion.  The most common cause of this is when the server is connected to two networks: 1 for the local event router the tablets are on, and the other for the internet.  

**Describe the solution you'd like**
Same functionality as current, but in the Manage Server page a select box that lists all found network interface IP addresses with the option to change which to display in the UI.  This way if the first network is 10.10.0.20 for the internet and the second is 192.168.1.100 for the event network the UI can display the 192.168.1.100 network.  

**Describe alternatives you've considered**
Communicating this to volunteers directly.  It is rarely an issue as I usually have the tablet logged in before handing it to a ref, but sometimes they might accidentally close the tab or something and then try to reconnect by looking at another tablet and it won't work.

**Additional context**
N/A

**Comment by tvbarnette999** [comment]
This has been added in v4.0.7 - the IP displayed can be set from the Server Management page.
