### ISSUE TITLE
Elimination matches result display shows misleading number under trophy icon

### ISSUE THREAD

**Issue by khojlo** [FIRST-Tech-Challenge/scorekeeper#560]
**Describe the bug**
For the elimination matches (semifinals and finals) when the result are posted on audience display, it shows a number below the trophy icon for both red and blue alliance representing the number of matches each alliance has won so far. These numbers look good, as shows in the first attached screenshot, if the result is posted right after the match concludes (meaning before the next match has been committed). But if the result is posted afterwards, e.g. posting the result of first match when all three matches have concluded, these numbers (though correct) but look misleading, as shown in the second screenshot. In such case, if let's say Red alliance had won 2 of the three matches and Blue alliance had won 1 match, it will show 2 under Red and 1 under Blue. But, it is misleading/confusing because it is suppose the state of matches as of Match 1. By this point in time of the competition, Red had won only 1 and Blue had won 0.

**To Reproduce**
1. Play 2 or 3 matches and have either red or blue win 2 matches
2. After all matches have been scored/committed, post the result of first match
3. Audience display will show misleading 2 and 0 (or 2 and 1) numbers under the trophy icons

**Expected behavior**
The result display page should ideally show the number of matches won up until that particular match, not based on all concluded matches.

**Screenshots**
Correct - Result Display Right After The Match:
<img width="1280" alt="Correct - Result Display Right After The Match" src="https://user-images.githubusercontent.com/94494646/153555333-061042d8-8480-448f-8510-e0334a2ed6f4.png">

Misleading - Result Display After All Three Matches:
<img width="1280" alt="Misleading - Result Display After All Three Matches" src="https://user-images.githubusercontent.com/94494646/153554048-3fec530f-f7a4-4995-9818-2b7b207616d6.jpg">

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 98.0.4758.80

**Additional context**

**Comment by adwiii** [comment]
This is the intended behavior. The displays are designed to show the current state of the series any time results are posted. There are several practical reasons that we must do this, primarily resulting from edits/replays. If Match 1 must be edited or replayed after Match 2 has been played, then the result of Match 1 is the determining factor in whether an additional match is played or if an Alliance has won the series. The same logic applies for any Elimination Matches posted out of order. Accordingly, the display will always show the full number of wins for each alliance at the time of the post, allowing the audience to identify the current state of the Eliminations series, regardless of when it was posted.
