### ISSUE TITLE
Add issue to FTA Notepad not tied to match

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#565]
**Is your feature request related to a problem? Please describe.**
Have a convenient method of logging team technical issues that might not be tied to a match.  e.g. during field inspection, or on the practice field.  Things that might be useful in noticing trends with a recurring issue.  Also, useful as a way to communicate with the CSAs that a team has an issue during field inspection that they need assistance with.

**Describe the solution you'd like**
Have a way to add an issue tagged to a team but not to a specific match in the FTA Notepad.  Or tagged to a dummy match that doesn't actually exist.

**Describe alternatives you've considered**
Slack channels.

**Additional context**
If possible I would really like to make use of this feature in Houston as a way to communicate between inspectors and CSAs instead of slack which we have used in previous years.

**Comment by tvbarnette999** [comment]
This has been added in the championship build and the offseason build, which we will release shortly after Championship.
