### ISSUE TITLE
Add the ability to do WiFi channel assignment w/in Scorekeeper Application

### ISSUE THREAD

**Issue by kellyds** [FIRST-Tech-Challenge/scorekeeper#566]
**Is your feature request related to a problem? Please describe.**
Request: For larger events it would be handing to be able to have the ability to assign WiFi Channels w/in the scorekeeper application and have a display that can be shown with the channel assignments.

**Describe the solution you'd like**
The ability to declare which band and channels will be available for the event.
Have either an automated or specified assignment of for each band for each team (each team would have 2.4ghz and 5.0ghz, since we don't know for certain what devices they will be using)

**Describe alternatives you've considered**
Right now the team list is generated, imported into excel and the channel assignments are added to the spreadsheet. Then, a copy of this spreadsheet is distributed. Generally, there is only once version of the spreadsheet, but it is conceivable that multiple, conflicting copies could be distributed.

**Additional context**
This would provide the field inspectors, FTAs and WTAs to have this information more readily available for use.

**Comment by cmacfarl** [comment]
Would this feature be hosted in the cloud, or on the local instance?

We don't typically give FTA's access to the scoring system network.   The only devices typically on that network are displays and scoring tablets.

If in the cloud, would this display live on ftc-events, or would all FTA's need a FIRST dashboard account to access an ftc-scoring page that displayed this information?

Note that we could add a POST route to ftclive that takes robot channel.   And if you had a utility that say, used pyshark to scan for beacon frames on an adapter that's channel rotating looking for robots you could push the channel they are on into ftclive and build a display around that.  But there are also Android apps that will scan for beacons and do much the same thing, without the ftclive integration of course.

**Comment by kellyds** [comment]
With the new FTA's Notebook, wouldn't the FTA's be on the scoring network now?  More critical use-case would be during the Field Inspections so they can get setup early in the event. Then, if needed an FTA or WTA could get a report from the scoring system.

With respect to the Cloud vs disconnected, I strongly suspect the larger events that are likely to need/want to use this would be using the cloud version.

While I didn't think about 'detecting' the channel that would be cool, but might be out-of-the-scope of the scorekeeping event processing. This is just an administrative-type task to help reduce reliance on paper reports and make the data available to those that need it.

**Comment by cmacfarl** [comment]
> With the new FTA's Notebook, wouldn't the FTA's be on the scoring network now?

Oh right.  Silly me.  Those events that are using this feature would need to give them access.

If it were set up in the cloud, then we could add a page sitting off the event details on ftc-events that lists the channel assignment for a team.  Then it's all just public and no special accounts or permissions are needed.   We could also display channel assignment on the team's event page on ftc-scoring.  And we could message to teams that they should arrive at the event with their channel assignment configured properly on their robot controller.

**Comment by kellyds** [comment]
Right, that is what I was thinking too. Also, since the 'source of truth' for the Team List is the scoring system, we would have a 'source of truth' for the channel assignment if the event needed to use it.  Assigning channels w/ 12 robot event is probably not worth the lift :)

**Comment by maths22** [comment]
This has been added to the CENTERSTAGE scoring system
