### ISSUE TITLE
resultPostedTime Incorrect

### ISSUE THREAD

**Issue by KingLinkTiger** [FIRST-Tech-Challenge/scorekeeper#567]
**Describe the bug**
The resultPostedTime field returned from the API returns [Epoch](https://en.wikipedia.org/wiki/Epoch_(computing)) + 1 Second for some matches.

I attribute this issue to the next match being randomized BEFORE the score is posted. I based this on video recordings frequently showing the following situation and correlating it to the issue occurring: Next Match Preview > Next Match Randomization > Next Match Show Randomization > Previous Match Results

**To Reproduce**
Note: I have not personally successfully reproduced this issue yet. I will provide updated steps once I am able to successfully reproduce the issue.

Suspected steps to reproduce the behavior:
1. On the match control page, load Qualification 1.
2. Play Q1 as normal but hold displaying the match results.
3. Load Q2
4. Randomize Q2
5. Post results for Q1
6. Use the API pull Q1 Match Data (/api/v1/events/{code}/matches/{number}/)
7. Verify resultPostedTime in the returned data is Epoch + 1 second

**Expected behavior**
The resultPostedTime field accurately reports the time when the match was posted.

**Screenshots**
N/A

**Device (please complete the following information):**

- FIRST Tech Challenge Live Version: 3.3.9
- OS: Windows
- Browser: Google Chrome
- Version: 100.0.4896.88

**Additional context**

**Comment by AlexOberfranc** [comment]
king that is last season's scoring software they are not going to update that anymore

**Comment by tvbarnette999** [comment]
We haven't been able to reproduce this, and the internal tracking of `postedTime` has changed some as part of the new timeout implementation (it is now the time of the first post after the last start for each match instead of just last post). Please reopen if you notice this again.
