### ISSUE TITLE
Judge match observer request

### ISSUE THREAD

**Issue by vchposton** [FIRST-Tech-Challenge/scorekeeper#568]
Not a problem, but I'm seeing judge match observers doing a ton of unnecessary clerical work with paper and pen.

I'd like to see a "Judge Match Observer Sheet" Report available from FTC Live.
It's one sheet per team, with basic format available in the Judge's Manual.
Each row is one of the team's matches, first column is Match #/Alliance Color, then good-size columns for handwritten notes:  Autonomous, Game Play, Reliability, and Standout Notes.
Not all competitions use the form, but Worlds definitely does.

The alternative is the status quo: the admins are looking up eight matches from the 160-match schedule for each of 80 teams and writing them on a pre-printed form.  Tediosity!
![Capture](https://user-images.githubusercontent.com/7231244/164317207-6ed45cad-76d4-4514-bda8-fde8f6e27b0f.PNG)

**Comment by JohnMMcD** [comment]
This is a feature I've wanted for years. I finally snapped and did it myself. The output of the code below can be redirected to a file which can imported into Excel, then you can use Excel for data input.

`
import java.sql.*;
import java.util.ArrayList;

public class Connect {
    /**
     * Connect to the FTC database
     */
    public static void connect() {
        Connection con = null;
        try {
            String url = "jdbc:sqlite:C:/ftc.db";
            // create a connection to the database
            con = DriverManager.getConnection(url);

            showMatches(con);

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }

    public static void showMatches(Connection con) {
        // select number from teams -- store in array
        // for each team, generate a list of what matches the team is in
        var selectTeamNumbers = "select distinct number from teams order by number";
        var teamList = new ArrayList<Integer>();
        try (Statement stmt = con.createStatement()) {
            ResultSet rs = stmt.executeQuery(selectTeamNumbers);
            while (rs.next()) {
                teamList.add(rs.getInt("number"));
            }
            System.out.println("Team|Match|Autonomous Mode|Game Play|Reliability|Standout");
            for (Integer teamNumber: teamList) {
                var selectMatches = String.format("select match, (select TeamNameShort from Team where TeamNumber = %d) from quals where (red1 = %d or red2 = %d or blue1 = %d or blue2 = %d);", teamNumber, teamNumber, teamNumber, teamNumber, teamNumber);

                ResultSet rsGetMatches = stmt.executeQuery(selectMatches);
                while (rsGetMatches.next()) {

                    System.out.printf("%d | %d %n", teamNumber, rs.getInt(1));
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    public static void main(String[] args) {
        connect();
    }
}
`

**Comment by maths22** [comment]
This report has been added to the CENTERSTAGE scoring system
