### ISSUE TITLE
HTTP ERROR 500 java.lang.RuntimeException: Velocity could not be initialized!

### ISSUE THREAD

**Issue by deenial** [FIRST-Tech-Challenge/scorekeeper#569]
Running on macOS 12.3.1, Java 8 Update 331 (everything up to date).

I downloaded v3.3.9 today and when I ran it, the screen below popped on my browser instead of the usual scoring system. This haven't happened with the previous version I was using, v3.2.4, which I just deleted and replaced with v3.3.9.
Any clues?
Thanks in advance.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/22546631/167406711-1aa2051d-89b8-4a3a-a0d2-e5812df03f7a.png">

**Comment by jvens** [comment]
Looking at the the screenshot stack dump produced by the exception it looks to me like it can't find the template files in the archive.  They might have gotten corrupted during the download or extraction process.  Perhaps try re-downloading and extracting the files and see if that resolves the issue.

It is working for me on Ubuntu 20.04 with java version openjdk 11.0.15.

**Comment by maths22** [comment]
If you copied forward your db directory from your previous installation, I have seen that cause this issue.  You must use the version of db/global.zip that came with this release.

**Comment by deenial** [comment]
> If you copied forward your db directory from your previous installation, I have seen that cause this issue. You must use the version of db/global.zip that came with this release.

I have deleted the whole folder from v.3.2.4 and placed the new one on my user's directory, as I usually do.
I havent transplanted the db folder in any way.
