### ISSUE TITLE
Default awards missing

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#57]
The standard awards are missing (I think global.db wasn't updated in the zip)

**Comment by adwiii** [comment]
Where are you looking for the default awards? When I pulled the build just now and ran, I was able to see them under the "Give Awards" part of the "Manage Awards" functionality from the dashboard.

![image](https://user-images.githubusercontent.com/9453262/46706790-72a2af80-cc04-11e8-8392-ce0849758115.png)

If this is not what you see, can you provide a screenshot and upload your db?

**Comment by maths22** [comment]
I think I was dumb.  It works for me now.  Thanks!
