### ISSUE TITLE
Persistent Accounts

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#573]
**Is your feature request related to a problem? Please describe.**
Recreating user accounts through upgrades of the FTC Live system is a process that is time-consuming and frustrating.

**Describe the solution you'd like**
Being able to have accounts persist through upgrades of FTC Live on the same computer.

**Describe alternatives you've considered**
A file that can be imported easily to automatically create accounts.

**Additional context**
This feature was also referenced in #541

**Comment by maths22** [comment]
With the new installation method of the scoring system/auto updates user accounts are now preserved
