### ISSUE TITLE
Match Replay old scores did not update every time

### ISSUE THREAD

**Issue by jdo01** [FIRST-Tech-Challenge/scorekeeper#577]
As soon as you press "Replay" on the Match Control "Schedule" screen and confirming it, the old match scores should be cleared. In most cases the scores are updated after the replayed match is committed. I did have one test match where the old match numbers were not updated after committing new match. The scores on the audience display were updated OK, but not on the Match Control "Schedule" screen. 
V4.07

**Comment by tvbarnette999** [comment]
This has been fixed in v4.1.1
