### ISSUE TITLE
Head Referee Scoresheets reverse the junction grid

### ISSUE THREAD

**Issue by KevinEmery** [FIRST-Tech-Challenge/scorekeeper#582]
**Describe the bug**
When viewing scoresheets on the (beta) Head Referee interface, the junction grid on both the red and blue alliance scoresheets are vertically from how they are actually stored. If a blue cone is scored in X1 during the match, when reviewing the scoresheets on the Head Referee interface that blue cone is shown in Z1 (on the red side) and V1 (on the blue side). Attached below is a side by side of the match review page under the Match Control page and the Head Referee Scoresheets tab

**To Reproduce**
1. Play a match with live scoring enabled
2. Enter a single cone on the center line (column X) as the only scored cone
3. Submit the scores after the match
4. Review the scores on the head referee "Scoresheets" tab. That cone will show up in Column Z and V instead of in Column X.

Step 2 is not a requirement but it's the easiest/minimal repro of the issue. Both the red and blue scores mirror vertically from how they are entered during the match/how they're stored in scoring.

**Expected behavior**
The scoresheets available to the head referee match the score sheets for the match

**Screenshots**
![image](https://user-images.githubusercontent.com/3441303/197633372-8dfcd9e1-2b2c-47cc-a68a-cbe04e4cf80d.png)

**Device (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: v4.1.1

**Additional context**
While the match is being played the Head Referee "Active Match" display shows the scored cones correctly.

**Comment by maths22** [comment]
Thank you for bringing this to our attention.  This has been fixed in v4.1.5
