### ISSUE TITLE
Active Match and Edit Match Page Does Not Show Team Numbers

### ISSUE THREAD

**Issue by silvanoc109** [FIRST-Tech-Challenge/scorekeeper#585]
### **Initial Info**
The Active Match and Edit Match page show "Robot 1" and "Robot 2" and not the team numbers.

### **The Issue**
The issue noted above can cause confusion for the scorekeeper attempting to modify scores. During a League Meet today a head referee asked me "Can you tell me on match X which robot got the bonus for parking in Y zone in Autonomous?" and I was unable to answer the question as I only saw "Robot 1" and "Robot 2".

### **Workaround**
The digital scoresheet shows the team numbers, but this is a long workaround when making small edits to scores.

### **Device**
Windows 10 - FTC Live v4.1.5

### **Additional Context**
Date of Occurrence: October 29, 2022

The screenshot below shows what the Edit Match screen displays to a scorekeeper.
![RobotNumberNotShown](https://user-images.githubusercontent.com/11062571/198857292-66ed310f-6d4a-43aa-bda7-6a2c04774e6f.png)

**Comment by maths22** [comment]
the equivalent page in the CENTERSTAGE version of the scoring system shows team numbers instead of Robot 1/Robot 2
