### ISSUE TITLE
Put four buttons in each grid square?

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#587]
**Is your feature request related to a problem? Please describe.**
Removing cones on grid in the middle of the match is difficult to do. 

**Describe the solution you'd like**
Is it possible to add 4 buttons each grid square - a blue +, red +, blue -, and red - so that all action for a junction can be done in that one grid square?

**Comment by Techno11** [comment]
I do agree removing cones is a bit tedious.  Additionally, the re-rendering of the buttons on older (but still supported) tablets can take a second or two to load.  

However, adding more buttons creates confusion, takes up more screen real-estate (especially in small displays, more buttons will make the already existing buttons even smaller), and creates more elements on screen to render (with the possibility of additional lag)

Disclaimer: I'm not a UI/UX person at all, but just sharing some personal thought
