### ISSUE TITLE
System should not require user to enter unique database key

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#59]
The score system should not require the user to provide the unique key that is use in the database.  The software should generate this key without user interaction.  This is true for both events and leagues.

**Comment by cmacfarl** [comment]
I don't know whether or not I'm a fan of auto-generated keys.    I see it as a very minor burden to enter a key.  Additionally the public api uses the key, and so a well known key is useful if a scorekeeper is setting up a 3rd party client.

I just don't see this rising to the level of a user burden significant enough to warrant a change at present.

**Comment by jvens** [comment]
I have come around to agreeing with Craig that this is probably ok.  I still see some potential concerns with allowing the user to submit their own keys (mainly in collisions such as importing two `meet1` from two different leagues into one league tournament), but I am satisfied enough to close this issue.
