### ISSUE TITLE
Randomization results should ALSO be displayed in the Autonomous scoring page

### ISSUE THREAD

**Issue by JCBond** [FIRST-Tech-Challenge/scorekeeper#591]
At the moment the randomization results are displayed on their own page within the scoring app. I believe that it would be beneficial for the Scoring Referee to have a reminder image with the results of the randomization right on the Automation scoring page.

Because running an FTC meet is a very active endeavor, it is possible to forget or get confused as to what was the result of the randomization step for the current match. So a reminder when it is needed (during scoring) would be helpful.

**Comment by maths22** [comment]
We have added this in v4.1.8
![202042810-f6fa93a0-fe4a-4c4e-b2b2-ae964898bc70](https://user-images.githubusercontent.com/3067361/202492514-3b0fac6b-4e46-45b4-8a94-434b110e5fa2.png)

**Comment by JCBond** [comment]
This is great. Thank you
