### ISSUE TITLE
Commit stops and zeroes Field Timeout

### ISSUE THREAD

**Issue by marcsol** [FIRST-Tech-Challenge/scorekeeper#593]
**Describe the bug**
Here are the steps that cause the problem:
1. Team from the current match is playing in the next match
2. When the head referee releases the teams from the field, the Scorekeeper starts the Field Timeout.
3.  During the Timeout, the Scoring Referees finalize their scoring, which triggers the "Commit" button to appear on the Scoring display.
4. The Scorekeeper commits the event.
5. For some reason that triggers the Field Timeout to end and show 0:00.

**To Reproduce**
1. Follow the above steps...

**Expected behavior**
The Field Timeout should not be affected by the commit button being depressed.

**Screenshots**

**Device (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version ???

**Comment by maths22** [comment]
This has been fixed in v4.1.8
