### ISSUE TITLE
Driver Controlled Cone in Terminal Scoring is backwards

### ISSUE THREAD

**Issue by kcsvoboda** [FIRST-Tech-Challenge/scorekeeper#594]
Cone in Terminal scoring is backwards based on scoring ref standing position at the back of the field. 

Red Scoring Ref has Reference Terminal Triangles adjacent to grid for Junction Scoring showing Red Terminal at the top and Blue Terminal at the bottom.  Below the Grid, F6 (blue) Terminal [Cone Scoring] box is above F1 (red) terminal [Cone Scoring] box.  This is opposite to the visual indicators on the grid, and opposite of how the refs are looking at the field.  Swapping the order of these would help reduce referee confusion.

![image](https://user-images.githubusercontent.com/118329724/202083649-70fdf84c-d51b-4943-943f-e7dda852615a.png)

**Comment by maths22** [comment]
This has been done in v4.1.8
