### ISSUE TITLE
Alliance Selection Team Count

### ISSUE THREAD

**Issue by djnucci** [FIRST-Tech-Challenge/scorekeeper#595]
**Describe the bug**
When selecting alliances through the alliance selection tab, as per section _4.9 Alliance Selection - Game Manual p1_, the number of teams per alliance should only be 3 teams (i.e. team captain and 2 chosen robots) when the number of teams in the event is greater than or equal to 21. The current implementation only has this option, however if the number of teams is less than 21 then the alliance selection tab should not allow for more than 2 teams per alliance.

**To Reproduce**
Steps to reproduce the behaviour:
1. Complete Qualification matches in an event with less than 21 teams
2. Open the Alliance selection tab
3. Finish the first round of alliance selection

**Expected behaviour**
After the first round, the alliance selection should no longer allow for additional teams being selected, similar to how the selection works when the second round of selections is completed.

**Device (please complete the following information):**
 - OS: Windows 10 Home edition (version 1909, OS build 18363.720)
 - Browser: Google Chrome (Version 107.0.5304.107)
 - Version: 4.1.8

**Additional context**
I feel this needs to be added to the functionality of the application so that future score keepers do not get confused and accidentally create an invalid Elimination schedule / alliances.

Additionally I am not certain if the devs consider this to be a bug. I do however know that this functionality has been outlined in the game manual, therefore why I've reported this as a bug. If needed, I will re-raise this item as a feature upon request.

**Comment by maths22** [comment]
If you actually go to add the second team to an alliance you should get this popup:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/3067361/202872596-d028874b-e7a6-4728-91b8-0f806a041714.png">
and if you ignore that popup when you go to generate matches you should get this popup:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/3067361/202872604-0db28d14-33ec-423b-b936-ad9c0e0cb9cd.png">

If you tried it but didn't see those popups, please let us know.

The reasons we don't block it entirely are:
1. Some extenuating circumstance where FTC support tells an event they should run with three team alliances despite having < 21 teams.
2. Scrimmages/offseason events that want to have three team alliances despite being too small.

**Comment by djnucci** [comment]
The primary reason I rose this as an issue is due to the UI of the audience display. As the number of teams per alliance is always 'Captain', '1st Pick', and '2nd Pick' (seen in attached screenshots). As many audience members do not know about the rule I outlined in the original bug report, this can cause confusion surrounding the alliance selection process. This being the case, my preference would be that the UI be directly affected by the number of teams and a manual '3-team alliance' override in the 'settings' tab. This, in my opinion, would cut down on the confusion for all event attendees, rather than just the score keeper.

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/10066175/202874323-5e9a0504-2f21-454e-858b-ed9eb10cc031.png">

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/10066175/202874387-c70d243a-be4e-437f-a27d-0dfc559d38fe.png">
