### ISSUE TITLE
Game manual out of date on resources page

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#596]
**Describe the bug**
The version of the Game Manual is out of date on both the local FTC Live and cloud FTC Scoring website.  There was a new version 1.3 of Game Manual Part 2, but local has 1.2 bundled with it, and cloud has 1.1 version.

**To Reproduce**
N/A

**Expected behavior**
Correct latest version of the game manuals.

**Screenshots**
N/A

**Device (please complete the following information):**
 - N/A

**Additional context**
N/A

**Comment by tvbarnette999** [comment]
This has now been fixed - both GM 2s and the JA manual. Doing a Data Download from the "Manage Server" page accessed from the Admin dropdown will update the local copy of the manuals. A hard refresh in the browser may be required as the local relative URL of the manuals do not change and thus are likely to have been cached.
The next release will ship with the updated manuals. Thanks for reporting!
