### ISSUE TITLE
Unactivated Match Schedule is Accessible

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#600]
**Describe the bug**
When a qualification match schedule is generated but not yet activated, it seems like it should be still private. Instead, it is accessible.

**To Reproduce**
1. Generate a qualification schedule, but do not activate it.
2. Access the match schedule page, the schedule is shown.

**Expected behavior**
An unactivated match schedule is not shown.

**Screenshots**

**Device (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 108.0.5359.94

**Additional context**

**Comment by jvens** [comment]
I am not sure what the intention is, but we use this feature to be able to print off match schedules before we have activated the match list.  Then we distribute the printed match schedules and activate it at the same time usually during the drivers and coaches meeting.  Since teams do not have any access to the scoring server or the network it is connected to they can't actually access the match schedule until it has been activated and pushed to ftc-scores website.

**Comment by jvens** [comment]
Personally I would be VERY hesitant to give any guest access to the score system.  Depending on how many guests are on it, and how much they might be refreshing that could cause any number of issues with the server (not to mention the very unlikely but possible case of someone actively trying to interfere with, DDOS, or hack the system).

I have also been pushing for paperless, and we encourage people to look at the schedule and results on the https://ftc-events.firstinspires.org/ website.  The problem is we have run a number of events in schools that don't have any guests internet network.  Currently we just print a single copy for each team.

**Comment by tweirtx** [comment]
If we were to restrict access to the scoring system, I'd like to see at least relevant pages have some sort of caching-friendly headers to run a local cache server that people *could* access.

**Comment by texasdiaz** [comment]
While we understand the desire to provide local access to the scoring system, there are security issues that we need to address before we could reliably (and safely) make that a viable option at an event. It is currently a requirement that the FTC network be a closed network only for trusted clients using established interfaces. As it stands, what you are proposing is not a tested nor established process and is not recommended for any event.

I recommend that you ask your local event leadership to submit a request for FTC to support this in a future season (unfortunately it's not a small feature request) and we can work with them to define the ultimate use-case, processes, and interfaces once we've addressed the relevant security issues that must first be dealt with.

**Comment by tweirtx** [comment]
Understood. One solution I may try is a restrictive reverse proxy configuration that limits the scoring system access to only allowed pages (and adds a caching buffer). That should work in the interim at least.

**Comment by jvens** [comment]
Does https://ftc-events.firstinspires.org/ not provide all the information you would need and want to provide?  I am not sure what is gained by giving access to the score system server.

That said, if you really want to provide access to the information in the score system locally it might be better to create a separate server that the public can access and then use the API from the score server to mirror the information.  This is at least a well tested and established flow and unlikely to cause any issues with the score system.  In this case the score server can be on an isolated network from the public and your custom server would be connected to both networks.  This is considerably more work and I would still urge you to consider just encouraging people to use ftc-events.

If you want more information about the API you can read the documentation by starting FTC Live and then going to http://localhost/swagger-docs/api.html in the browser.

Also, another concern that I thought of is in the vast majority of cases the score system is not using SSL encryption (https) which means that all network traffic between clients and the server is sniffable by anyone connected to the network.  In practice what this means is in theory a team with access to the network running the score system could use wireshark to see the network packets when the judges enter the awards.  Yes, I realize this is very unlikely to actually occur, but the fact remains that it is possible.  There is a workaround for this which I have done where you setup a proxy server with a self-signed SSL certificate on port 443 which proxies all data to internal port 80 and then you turn off outside access to port 80 in the computer firewall and now you can connect to the score system with https on port 443.  This is certainly not an easy to setup up thing and I have only done it on Linux so I don't even know if it is possible or how to set it up on Windows.

**Comment by pmichaud** [comment]
> Does https://ftc-events.firstinspires.org/ not provide all the information you would need and want to provide? I am not sure what is gained by giving access to the score system server.

Several venues in our region are unable to provide internet access at the event, so... no, it doesn't work when there's not an internet connection available to the scoring system.  We could look at cellular options -- e.g., tethering a cell phone to the scoring system for synchronizing with FTC servers -- but that typically requires someone to lend their personal device to the event.  That's not a showstopper, but it does mean using up someone's mobile data and mobile device for the day.

Even when a venue has some sort of internet connection available, it's sometimes spotty.  We've had a number of instances where the venue-provided connection failed at some point during an event, resulting in the local scoring system no longer synchronizing with the FTC servers.  When this happens, the scorekeeper (a) needs to somehow learn that synchronization is no longer taking place, (b) attempt to re-synchronize using the hard-to-find-option in the match control page, and (c) know how to check/do these things in the first place.

So yes, so far this season I've been to several events, including in other regions, where ftc-events.firstinspires.org simply wasn't available for teams to use.  In those cases teams either had access to the local system som ehow, or they were left completely in the dark such that the only option was to send someone to the question box to ask for match details.

Pm

**Comment by cmacfarl** [comment]
> That said, if you really want to provide access to the information in the score system locally it might be better to create a separate server that the public can access and then use the API from the score server to mirror the information. This is at least a well tested and established flow and unlikely to cause any issues with the score system. In this case the score server can be on an isolated network from the public and your custom server would be connected to both networks. This is considerably more work and I would still urge you to consider just encouraging people to use ftc-events.

This is the solution that has the broadest applicability to the most people in the community who lack internet access at an event.  To which it has the lowest barrier to entry for an event host.  It is simply a laptop to act as the bridge with two network adapters and to run a small local server that just serves static pages, and a small client that consumes data via the officially supported API.   You'd just have two relatively user friendly, low configuration, pieces of software to install and an extra laptop.

If the goal is to run paperless events, and efficient distribution of match schedules is the blocking factor there, then the public server could be as simple as a consumer and distributor of the match schedules alone.   Or it could be scaled to be something equivalent of a local instance of an orange alliance or ftcscores clone.  Do we have any TOA or ftcscores devs watching this thread? :-)

**Comment by pmichaud** [comment]
> 
> > That said, if you really want to provide access to the information in the score system locally it might be better to create a separate server that the public can access and then use the API from the score server to mirror the information. This is at least a well tested and established flow and unlikely to cause any issues with the score system. In this case the score server can be on an isolated network from the public and your custom server would be connected to both networks.

> This is the solution that has the broadest applicability to the most people in the community who lack internet access at an event. To which it has the lowest barrier to entry for an event host. It is simply a laptop to act as the bridge with two network adapters and to run a small local server that just serves static pages, and a small client that consumes data via the officially supported API. You'd just have two relatively user friendly, low configuration, pieces of software to install and an extra laptop.

Well, sort of.  As @jvens indicates, it does mean having two separate networks.  So, that means either another wireless router, setting up the custom laptop as a wireless network access point (along with DHCP services), or configuring the existing router to run two separate isolated networks.   To me, none of these are "relatively user friendly" to do for the typical scorekeeper, or even the typical PDP or FTA.

I do appreciate the ftc scorekeeping software very much, it's amazing what has been done.  It's a vast improvement over what existed 3 or 4 years ago.  That said, it's disappointing how many times the answer to things are "throw another laptop (or tablet) in", as if laptops are super inexpensive and readily available to allocate to all of the tasks wanted at an event (scoring computer, field timers, audience display, field timers).  

If all that's being requested is a laptop with Chrome and an HDMI output... then yeah, those can often be borrowed, and the switch to browsers as the primary interface is fantastic.

But if a (borrowed) laptop needs to have software installed on it, school-mandated firewalls and filters disabled, and perhaps set up as a temporary access point (which then needs to be disabled and possibly uninstalled after the event conclusion)... then that's not so straightforward or easy to accommodate.  In North Texas alone we've already purchased 10+ laptops to be used as dedicating scoring systems for each of our leagues; now it's suggested we increase that number even further.  This doesn't account for devices needed for field timers, audience displays, referee tablets... pretty soon the technical needs of the event become a significant expense. 

So, if the recommendation is indeed "add another laptop", then I think I start recommending back to FIRST in Texas to just buy some $!$% printers (way less expensive), print the match schedules, and tell teams at those events that they won't see match details or learn about penalties until the event is completed and the results are posted on ftc-events when it's all over.

Or, perhaps the answer is "absolutely require that venues have internet availability", which also often means "dedicated venue-approved person on call to troubleshoot day-of-event issues" that seem to arise frequently.  I've lost count of how many times I've been at a venue where the internet connectivity fails for one reason or another on the morning of the event.

Pm

**Comment by tweirtx** [comment]
It would have been nice to have the local network option for teams while FTC-events wasn't accepting syncs from FTCLive instances yesterday, just sayin'

**Comment by tweirtx** [comment]
Closing this issue for now as the original problem has been solved. Public access is beyond the scope of my original problem
