### ISSUE TITLE
Inconsistent Match Start Sounds

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#601]
**Describe the bug**
The match start sound does not play consistently even though the rest of the sounds play fine.

**To Reproduce**
1. Run a series of matches with an external computer showing audience display.
2. Observe that the match start sound is inconsistently played.

**Expected behavior**
Match start sound plays consistently.

**Screenshots**

**Device (please complete the following information):**
 - OS: Windows 11, ChromeOS, and Ubuntu.
 - Browser: Chrome
 - Version 108

**Additional context**
Multiple laptops were tried to troubleshoot.

**Comment by tweirtx** [comment]
Further testing shows bug also present in Firefox

**Comment by tweirtx** [comment]
This only appeared to affect qualifications, elims is working correctly with no changes.

**Comment by LazyKoala82** [comment]
For me personally, I've been looping some audio on mute in the background.  That seems to help with the audio output inconsistency that was happening for me (for my setup, my theory was that it takes a bit of time to "reopen" the audio output for some reason when nothing has been playing for a few minutes).

**Comment by cyberluz** [comment]
Experienced the same issue, although it was also an issue in the elimination rounds as well.
We have the most recent upgrade to try between now and the championships, obviously this is not hardware oriented.
Win 10, Chrome, never tried Fireox, doesn't look like it would help.  We ran sound from two machines and got more results in total.
Clearly a software glitch it seems, we hope it is "corrected" next year as we only have one event to go and the results will be whatever happens.

**Comment by tweirtx** [comment]
I haven't noticed the same issue occurring with new updates, even with equipment that we realized later was faulty. I consider this handled.

**Comment by cyberluz** [comment]
We updated before our state competition.  It was not as prominent, but
still was missing the correct sounds once in the day.  I expect it may
reoccur next year, but we will see!  With all regards to "Murphy" ... we
hope it has run it's course!
