### ISSUE TITLE
Add Inspection Status Display to list of type of displays that a display window may have

### ISSUE THREAD

**Issue by marcsol** [FIRST-Tech-Challenge/scorekeeper#607]
Usually, before inspections are started in the morning, I have the Field, Audience, and Pit display windows configured for the screens where they are needed. Then when inspections start I need to convert the Audience and Pit Displays over to display inspection status. After inspections are finished, I need to go back and reconfigure these systems to display the original displays. These systems are frequently unmanned nodes with no keyboard, mouse, nor remote SSH. For me to switch them I need to go physically to these nodes with a mouse and keyboard and reconfigure them.

It would be nice for the Additional Displays section of the system if I could switch back and forth between inspections status, Audience, and Pit. This would prevent Scorekeepers from having to run around the building switching to and from the inspection status display.

**Comment by tweirtx** [comment]
We follow the same workflow in NTX and I personally would love to see this added.

**Comment by LazyKoala82** [comment]
A workaround for now would be to use the Show Message option with raw html to iframe the inspection status page URL to the remote screens (need to manually set height and width to match though).

**Comment by maths22** [comment]
This has been added to the CENTERSTAGE version of the scoring system
