### ISSUE TITLE
Game sounds in live event are inconsistent

### ISSUE THREAD

**Issue by cyberluz** [FIRST-Tech-Challenge/scorekeeper#611]
**Describe the bug**
Running the scoring system in a live event, some of the sounds do not play while others do.  Because sounds were missing, we fed one sound system with the main server and another sound system with the audience computer.

On the main/server computer, from the Scoring software window: Display Options->Audio Settings, each sound can be selected and triggered and play through the computer output.  On the audience computer all sounds sounded individually when tested as well. Both COULD play the sounds.

During LIVE play one or two sounds will not play.  It is random, and can be all but two play, or only two play.  It is impossible to predict. As we were in full play, it was impossible to determine which played which sounds and it changed!

**To Reproduce**
1. This happens when ANY round is run, but the sounds that play or do not can vary.  

**Expected behavior**
All sounds play during the match.

**Screenshots**
n/a

**Device (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 109.0.5414.74

**Additional context**
This was totally unpredictable rom match to match.

NM FTC
Ford Davis
ford.davis@nexgenacademy.com

**Comment by tweirtx** [comment]
Curious if this is similar to #601

**Comment by cyberluz** [comment]
Thanks!

Same issue, I commented on the link.  Nothing to add since we couldn't
correct the issue and we only have one event in two weeks.  Never had
anything like this before.

**Comment by maths22** [comment]
We think this has been largely resolved in [v4.2.3](https://github.com/FIRST-Tech-Challenge/scorekeeper/releases/tag/v4.2.3)
