### ISSUE TITLE
A "full screen" clock on the field display would be benneficial for laptops.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#612]
When running the Field Timer on a typical laptop screen (for smaller events, or ones with less resources), the timer-digits part of the display is quite small.  It utilizes less than 20% of the screen real-estate.  It's also right next to a backdrop with the same color as the digit's so it's often hard to see the numbers at a glance.

There are times when all the other info on the field timer is usefull (setup, or after end of match) , but once the match is actually running, all the teams really need is a big clock they can see at a glance, to prepare for endgame and end of match.

I would propose either an alternate "big clock" field timer, or one that switches to "big clock" mode while counting down.  
I've include the current field timer in full screen mode and a suggested alternate "big Clock" version for comparison.

![Field Clock](https://user-images.githubusercontent.com/14909461/212930739-42483634-94f0-4912-a9f8-ea401fe59381.jpg)
![Field ClockNew](https://user-images.githubusercontent.com/14909461/212930740-cbc4fc82-3415-4267-9b67-261a6ece328d.jpg)

**Comment by maths22** [comment]
The CENTERSTAGE version of the displays uses a timer that should be notably more readable than the seven segment display.  It's not notably *larger*, but it should be much more readable.  If you find it isn't, please reopen this issue.

**Comment by gearsincorg** [comment]
Hi.

I just tried the updated timer and the new FONT and BACKGROUND COLOR make the timer MUCH more readable.  Thanks!!

And overall there are a ton of great inprovement and enhancements to the User Interface.

I will admit that I'm a bit dissapointed that there's still a lot or real-estate around the timer itself that seems wasted.
If that neat "game period" ICON had been put in front of the timer (instead of below it) I'm sure the clock font could have been another 50% bigger.  Digit height seems to be the limiting factor there... there is plenty of spare screen width.

Anyway... really appreciate the improvement.
