### ISSUE TITLE
Add randomization number to hr tablets

### ISSUE THREAD

**Issue by byboyd** [FIRST-Tech-Challenge/scorekeeper#616]
**Is your feature request related to a problem? Please describe.**
After randomization is completed and autonomous begins, there is no way on the hr tablets to reference what the randomization was on the signal sleeve. Our scoring referees are usually the least experienced, so having that extra reference without having to go to their tablets to see would be nice. 

**Describe the solution you'd like**
Somewhere near the top or near the parking check boxes have a 1,2, or 3 indication for the randomization. 

**Describe alternatives you've considered**
Usually if I don't remember the randomization, I have to reference a scoring tablet or look for a signal cone that was not touched during auto. 

**Additional context**
I checked this over the last few qualifiers and didn't see anything with the randomization number so I could just be looking over it if it's there. When all four robots are going during auto to different levels of success in parking, sometimes we forget which number was called during randomization.

**Comment by adwiii** [comment]
This has been added in v4.2.3. It does not give the randomization number (1-6), but rather the target zone for the Navigation, e.g. `Navigation [Z3]` as shown below:

![image](https://user-images.githubusercontent.com/9453262/217890750-699fd7b3-66a0-447f-b68d-23d879c02398.png)
