### ISSUE TITLE
Scoring software for practice matches (four robots)

### ISSUE THREAD

**Issue by tpacer** [FIRST-Tech-Challenge/scorekeeper#617]
**Is your feature request related to a problem? Please describe.**
The practice match software is for one team only. We'd like to use a version of the working scoring software so we can score practice matches with 4 teams. 

**Describe the solution you'd like**
I would like to see a working version of the scoring software that can be run outside an official event. We would use this for practice matches with four teams. 

**Describe alternatives you've considered**
We've tried running the single team practice match software on two laptops / ipads. It's tricky to synchronize and if your team scores a cone on the "other side" of the field, you can't score it in the software. Also autonomous can't score two teams on one side and account for double robots parking in the correct signal zone.  

**Additional context**

**Comment by tweirtx** [comment]
It is possible to set up a fake event locally, and run test matches (or just put in some demo teams to generate a normal match schedule)

**Comment by cmacfarl** [comment]
The practice match feature on ftc-scoring, in the cloud, is an artifact of the pandemic era remote events.

As @tweirtx says, you are free to download a release from the releases sidebar in this repository and once unzipped and running the server, select from the banner Event Admin -> Setup Event, then select Offline Setup, then Manual Setup, then Create New Event, from which you can create a stand alone "fake" event from which you can add teams, generate a schedule and run as many "practice" matches as you like.
