### ISSUE TITLE
Pit Display Link

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#619]
**Is your feature request related to a problem? Please describe.**
It was brought to my attention today that it is possible to access the pit display from the FTC-Scoring cloud, however this is not clearly documented anywhere and no links are provided in the system that makes this obvious.

**Describe the solution you'd like**
A clickable link in the ftc-scoring system that opens the cloud pit display view, and corresponding documentation.

**Comment by tcflanag** [comment]
Could you give an example link?  This seems useful to know.

**Comment by tweirtx** [comment]
https://ftc-scoring.firstinspires.org/event/<insert_event_code>/display/pit

**Comment by maths22** [comment]
This been added to the volunteer-facing event homepage in FTC-Scoring (e.g. https://ftc-scoring.firstinspires.org/event/<code>/ )
<img width="1164" alt="image" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/3067361/e591ec10-f097-4420-b5e2-1a5a930bf6d8">
