### ISSUE TITLE
Awards Header is Broken when Pit Map is Enabled

### ISSUE THREAD

**Issue by devyntk** [FIRST-Tech-Challenge/scorekeeper#620]
**Describe the bug**
When a pit map has been created for an event, the FTC-Events awards page has a misaligned title bar on desktop due to the presence of both this pit map tab, as well as a seasons tab. You can see this on a page such as [https://ftc-events.firstinspires.org/2022/USILCMLTB/awards](https://ftc-events.firstinspires.org/2022/USILCMLTB/awards)

**Screenshots**
![image](https://user-images.githubusercontent.com/10481864/218538900-26af0f20-c61c-429d-a54c-00855cfa8394.png)

**Comment by maths22** [comment]
This has been fixed.
