### ISSUE TITLE
Make more clear how to setup League Meet 2+

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#63]
Add more info and make UI more clear that you have to import in the export db file from previous league meet into the new event for League Meets 2 and on.  It is not intuitive that you import the previous event information from `Manage League` -> `Import League Data`.

**Comment by adwiii** [comment]
Closing as league management is deprecated in FTCLive. All league data is handled through the [online scoring system](https://ftc-scoring.firstinspires.org) and automatically imported when the event is imported into FTCLive.
