### ISSUE TITLE
Ref Training cut off

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#633]
**Describe the bug**
The ref training box seems to be cut off in some cases.
**To Reproduce**
1. Create a test match with ref training turned on.
2. Click through training
3. Observe on some resolutions the top of the training information is cut off

**Expected behavior**

**Screenshots**
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/d7644061-5fca-4bd3-a53e-2e840f19532f)

**Device (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 5.0.1

**Additional context**
N/A

**Comment by tvbarnette999** [comment]
This particular one has been shrunk to fit better, but we target a 7inch tablet when testing, so we cannot guarantee the rendering on smaller screens.
