### ISSUE TITLE
Not Started and Very Late use same color

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#634]
**Describe the bug**
In the inspection status page the colors for Not Started and Very Late are both the same.  In the old system Not Started was white and Very Late was black.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/34d3590e-48f5-4353-a43d-7cc1afb6cf6f)

**Device (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by maths22** [comment]
This has been resolved with a new color for Very Late in v5.0.6
