### ISSUE TITLE
Can't change overlay color

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#636]
**Describe the bug**
When full screen or maximized it is impossible to change the color of the overlay.  When the screen is reduced in width it becomes possible to change is.

**To Reproduce**
1. Go to display
2. Set type to `Overlay`
3. Open `Overlay Settings`
4. Click `Pick Color`

**Expected behavior**
Should be able to change the color of the overlay

**Screenshots**
When maximized:
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/90d78038-b0df-47c5-b01c-22c6110da479)

When reduced in width: 
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/089b4ba6-eba6-4b49-a677-3a18a2946962)

In OBS Studio Interact Screen:
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/d2de0fcf-2a21-408f-b135-e361b5557899)

**Device (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and OBS
 - Version: 5.0.1
 
**Additional context**
N/A

**Comment by maths22** [comment]
This has been fixed in v5.0.6
