### ISSUE TITLE
Typo: Emcee Alliance Selection Script

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#638]
**Describe the bug**
Small typo in the alliance selection script for emcees.

**To Reproduce**
1. Begin alliance selection on the match control page
2. Navigate to the Emcee Alliance selection script
3. Observe typo

**Expected behavior**
The script should read "and team one will need to extend the invitation to anothe**r** team."

**Screenshots**
<img width="1129" alt="image" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/6354860/db470d4d-21c9-4940-9a11-4e757f0670d3">

**Device (please complete the following information):**
 - OS: macOS 13.5.2
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] 116.0.1938.76

**Additional context**
N/A

**Comment by maths22** [comment]
This has been resolved in v5.0.6
