### ISSUE TITLE
When creating new league go directly to add teams

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#64]
It is not very clear that after creating a new league the `Add Teams` button becomes visible.  This button should be more visible.  On top of that, I can't think of a case where you would create a league without also adding teams to it.  When you click the button to save the league information it should navigate you directly to the page to add the teams to the league.

**Comment by jvens** [comment]
I still believe that this should be the case.  Having not entered league data since last year I found myself trying to remember where to add teams to the league after creating it.

**Comment by adwiii** [comment]
Closing as league management is deprecated in FTCLive. All league data is handled through the [online scoring system](https://ftc-scoring.firstinspires.org) and automatically imported when the event is imported into FTCLive.
