### ISSUE TITLE
Extra unused select box in Field Inspection Team Present

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#641]
**Describe the bug**
There is an empty select box with id `table_1_0_1` in the field inspection checklist that doesn't seem to be used for anything.

**To Reproduce**
Go to a field inspection

**Expected behavior**

**Screenshots**
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/18396bee-f974-430b-8cc9-c06167a969ab)

**Device (please complete the following information):**
 - Version 5.0.6

**Additional context**
N/A

**Comment by tvbarnette999** [comment]
Whoops! That should be fixed now. To get the fix to appear locally for you, do a Data Download (or restart the scoring system) and create a new event.
