### ISSUE TITLE
New Files Dragged and Dropped Into the System Lead to a 404 Error

### ISSUE THREAD

**Issue by silvanoc109** [FIRST-Tech-Challenge/scorekeeper#642]
**Describe the bug**
After new files are dragged and dropped into the scoring system, when a user attempts to open the file, they encounter an Error 404 screen.

**To Reproduce**
1. Log in as 'local'
2. Navigate to 'Resources'
3. Click 'Add Files'
4. Drag and drop a file into the file tree structure
5. Attempt to open the file. This will lead to an Error 404.

**Expected behavior**
Files that are dragged and dropped into the system should open without an issue. This problem does not occur when manually adding the files to `.../uploads/resources`.

**Device:**
 - OS: Windows 10 22H2
 - Browser: Google Chrome v.117.0.5938.132 (64-bit)
 - Version: _FIRST_ Tech Challenge Live v5.0.6 (Preview)

**Additional context**
We are aware this is a preview version that should not be used for official events. This system was used during a test day to allow both volunteers and teams to become accustomed to the new version of the scoring system.

When dragging and dropping a file into the scoring system, it looks like the system is attempting to open the file like it existed in the `.../uploads/resources` directory, even though it does not exist in that directory and it didn't get copied to that location.

**Comment by maths22** [comment]
This has been fixed in v5.0.7
