### ISSUE TITLE
Setting No Robot doesn't override Team Prop

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#644]
**Describe the bug**
If the refs enter that a team has a prop and also mark as not having a robot it will not let you submit final scrores.

**To Reproduce**
1. Go to Match Setup on the ref tablet
2. Select Team Prop for the first team
3. Set the team to No Robot (this will cause Team Prop to become disabled, but the backend keeps the Team Prop Setting)
4. Set Alliance ready
5. Run the entire match submitting Auto and Driver Controlled scores
6. Click Submit Final Score
7. Observe error message `No-show Team cannot use Team Prop`
8. Also observe on the Active Match page Team Prop and NR are both checked

**Expected behavior**
If a team is marked as no robot this should take precedents over the Team Prop setting.  This is already the case in the UI on the Match Setup page, but the backend logic is not handling that case correctly.

**Screenshots**
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/6307dc25-c32d-4336-90ca-cb92d3312fe1)

![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/83edb63f-35d6-4db8-8530-b9bcbbff4e0f)

![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/37957451-9ec1-43bb-a6d4-c8ba3b066739)

![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/334db33a-eb87-4ea2-b7c7-f1b41f100a89)

**Device (please complete the following information):**
 - Version 5.0.6

**Additional context**
I didn't test but I suspect this might also be an issue for no show teams, and possible other edge cases as well.  One of our refs found this issue tonight when testing the tablets and I could see this coming up in a real event if a team has to pull their robot off the field last minute which has certainly happened in the past.

**Comment by maths22** [comment]
This has been fixed in v5.0.7
