### ISSUE TITLE
FTA Notepad Socket Error

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#647]
**Describe the bug**
When attempting to create a new Team Issue on the FTA Notepad it returns a socket error.

**To Reproduce**
1. Go to FTA Notepad
2. Click the `+` next to a team
3. Fill in issue dialog
4. Click `Save`
5. Observe following error in console:
```
chunk-P2UJD6LH.js:17 Uncaught ReferenceError: socket is not defined
    at x (index-3CLMSBBV.js:1:11340)
    at Object.onClick [as clickfalse] (index-3CLMSBBV.js:1:9483)
    at HTMLButtonElement.X (chunk-DNOI7M3U.js:1:3795)
    at HTMLButtonElement.r (chunk-P2UJD6LH.js:17:4767)
```

**Expected behavior**
Should create a new issue.

**Screenshots**
N/A

**Device (please complete the following information):**
 - Version 5.0.7

**Additional context**
The offending line of code is:
```
socket.send(JSON.stringify({
    type: "ISSUE",
    issue: a
}))
```

**Comment by maths22** [comment]
This has been fixed in v5.0.8
