### ISSUE TITLE
LR Text cutoff in match preview page

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#648]
**Describe the bug**
The LR text runs off the edge of the screen in the match preview page in overlay mode.

**To Reproduce**
1. Run match with league rankings
2. Observe match preview

**Expected behavior**
Not cut off text.

**Screenshots**
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/f8c5b983-0c1b-4036-8aff-11e0a5933dce)

**Device (please complete the following information):**
 - 5.0.8

**Additional context**
N/A

**Comment by maths22** [comment]
This has been fixed in v5.0.9
