### ISSUE TITLE
Team numbers 99990-99999 need to be listed as paid for CENTERSTAGE

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#654]
**Describe the bug**
I'm trying to add a demo team to compete at a scrimmage, so I'm using the team range of 99990-99999. When I try to add them to the event, I get the message "Team 99991 is not registered with FIRST".  Can this be resolved for this season?

**Expected behavior**
Demo Team should be added to the event as a legal team.

**Comment by rachmo** [comment]
Thank you for your feedback, this request is outside of the scope of what we can support for this season, but we will consider it for future seasons. 

This year we have prioritized support for a better unsecured team override experience to ensure PDPs supporting teams facing payment delays would have the best possible support at official events.
