### ISSUE TITLE
Can't add more than 3 user accounts

### ISSUE THREAD

**Issue by Crossle86** [FIRST-Tech-Challenge/scorekeeper#655]
Just starting with this years scoring software. I added 3 user acccounts successfully. The fourth account does not get added to the database. The create account button is clicked, screen clears for next account but the account I just added does not appear in the list of user accounts.

**Comment by vchposton** [comment]
Just as a datapoint, I was able to add all the user accounts I wanted - probably 7 or 8 of them.

**Comment by Crossle86** [comment]
Update: I don't know how, after adding 3 users, but the First Inspires folder is marked read only and the log does show database access failure. I am investigating...

**Comment by Crossle86** [comment]
I am closing this issue and opening a new one about read only access to the database.
