### ISSUE TITLE
Match Display w/ Live Scoring Disabled Mis-renders

### ISSUE THREAD

**Issue by JackkoCodes** [FIRST-Tech-Challenge/scorekeeper#659]
**Describe the bug**
When using the match display w/ timer config set to "Use field-style timer", both sides are off the vertical-center and the top two teams are unreadable.

**To Reproduce**
1. Open a display
2. Disable 'Show Live Scores' under 'Advanced Settings'
3. Start a match

**Expected behavior**
All team numbers should be readable

**Screenshots**
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/35432552/8bf8edc1-98da-47d3-ac21-79d8b2d191a1)

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser: Tested on Chrome and Edge
 - Version: Chrome version 118; Edge 118

**Comment by maths22** [comment]
This has been fixed in v5.1.0
