### ISSUE TITLE
Print match list from match list generation page

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#66]
The most likely place that a user is going to look for the option to print the match list is the page that generates the match list.  Please add a button to this page to print the match list as soon as it is generated.

**Comment by jvens** [comment]
I would like to bump this as a feature I would still like to see added to the system for Skyzone.  Or at the very least a direct link to `event/<eventid>/schedule` page.

**Comment by adwiii** [comment]
Printing from the match schedule generation page is not a very straightforward fix. As such, for now (as of `v1.3.1`) we have added a link to the regular schedule page that allows you to print:
![image](https://user-images.githubusercontent.com/9453262/72581075-1836db00-38ac-11ea-81f4-f6fde63fead9.png)

This link will take you to the schedule page. That page will still say "Back to Event Home" at the top, even though the user came from the generate schedule page. The browser back button can be used to go back to the schedule generation page and then the dashboard if needed.

I will leave this issue open as this does not fully achieve the desired result, but this likely will not be revisited in the near term.

**Comment by jvens** [comment]
The solution  to have the link to print has seemed to be effective and this issue is not really an issue any more.  Closing.
