### ISSUE TITLE
Awards Lower third has shadow that makes chroma angry

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#666]
**Describe the bug**
Shadow outline on awards lower third makes chroma need extra help

**To Reproduce**
1. "Present Awards"
2. Setup standard chroma
3. See error

**Expected behavior**
Shadow to be absent so chroma isn't confused

**Device (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 103 (via VMix)

**Additional context**
Love the shadow. Would it be possible to keep the shadow if the chroma BG is set to transparent?  Hopefully, once some of our antiquated software actually supports transparency through browser inputs (cough cough vmix) we can retain the cool shadow

**Comment by maths22** [comment]
We still haven't fixed the shadow issue, but we have fixed the issue where the transparency didn't work in vmix (OBS by default applies a stylesheet to make the body transparent, vmix doesn't so we actually have to make sure the body is transparent in the displays)
