### ISSUE TITLE
Add "Match End" event for Event Streaming API

### ISSUE THREAD

**Issue by ssysm** [FIRST-Tech-Challenge/scorekeeper#669]
**Is your feature request related to a problem? Please describe.**

Currently working with the websocket event streaming api. I want to monitor the status of the matches on different fields. Currently the only event type emitted in the streaming api is the "MATCH_ABORT" type. When a match is finished there's no event emitted.

**Describe the solution you'd like**

Add a new event that is emitted from the event streaming api with type like "MATCH_ENDED".

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by cmacfarl** [comment]
This is the intended behavior.  The recommended solution for API users that want to know when the match ends is to set a timer in your software on match start.

**Comment by ssysm** [comment]
Ah I see, thanks for the clarification. Closing the issue.
