### ISSUE TITLE
League Rankings Display only shows Child League Data

### ISSUE THREAD

**Issue by rachmo** [FIRST-Tech-Challenge/scorekeeper#673]
**Describe the bug**
Unable to find any views which showed the combined rankings for both child leagues.  Ranking reports either only show the child league teams competing at the event, or shows all league teams but with blank data for the teams in the other league.

**To Reproduce**
1. View League Ranking display page at a League Meet after both child leagues have already played at least one league meet

**Expected behavior**
The "combined" ranking view should show all league team data combined into an overall League Ranking table.

**Screenshots**
Attached one picture shows a url which says "combined" but only shows active child teams, another shows the correct full list of teams in the league, but with no data for the other child league teams even though they have data available online. 

**Device (please complete the following information):**
 - unknown (can confirm is needed)

**Additional context**
![PXL_20231202_191841357](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/24320246/3fc0d8a3-a855-4e0b-8c51-5f968c9de1f7)
![PXL_20231202_191716563](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/24320246/f22b4f1f-830c-4e7c-b7d3-77f112246a5c)

**Comment by timtim17** [comment]
+1. My events also observed that the audience display "league ranking" seemed to always match the local meet ranking, and did not include data from sibling leagues.

Also found that clicking the "History" link on the rankings report on a team in a sibling league (indicated as NP) caused an error (HTTP 500 if I recall) and a "contact your FTA" page.

**Comment by rachmo** [comment]
Thanks @timtim17 We also got to the error 500 page "contact your FTA" but I wasn't sure how they got there so I didn't include it in my original report. ![PXL_20231202_191724966](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/24320246/7cf7f690-abba-43a1-8298-b469e30a6dbb)

**Comment by rachmo** [comment]
Upon further discussion, we might not want to allow "merged" league rankings in event local display since we cannot ensure any of the data is updated outside of the local event and would that be more confusing or misleading than sticking to only showing what we know is true and complete (local event data).

**Comment by timtim17** [comment]
Very fair. I'm inclined to question what the purpose of the league ranking indicator is -- from what I've seen at my events, it always matches the local league ranking.

**Comment by jvens** [comment]
@timtim17, it is because in many regions not every team will compete in every league meet.  So the difference is the ranking among the teams competing at that given event vs the ranking overall in the league.  For example, in Iowa most leagues have around 2 dozen teams, but each meet will have between half and two thirds of those teams actually competing.

**Comment by rachmo** [comment]
We have dedicated split child leagues (not mix and match attendees) here in our region, but our PDP still really wanted the "excitement" of the local event matches stacking up against what had been played to date for the other child league meets. I still think from an ease of understanding and ease of ensuring we are presenting truthful data, it still probably makes sense to keep it to the local event data only. 

Making the league qualifier page which has combined data easier to find on ftc-events might be the middle ground for teams who want to be actively sizing themselves up.  It's a little hard now (imo) to find that page.

**Comment by cmacfarl** [comment]
Given that we can not guarantee that any data in an FTCLive local database is up to date, and given that we've designed a system where the concept of a league itself is fungible, and wherein one may understand how it is done in their region, but not in another region, it is my view that displaying rankings at an event that do not reflect the results of that event, and that event alone, is guaranteed to to mislead in about 42 different ways.

The only accurate league ranking location is the league tournament page for that league on ftc-events, and even then, on a Saturday, only if all events with league participants are syncing match data to ftc-events in real time.
