### ISSUE TITLE
[Low Priority] Launcher looks weird when minimized on MacOS

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#674]
**Describe the bug**
The icon for FTCLive when minimized on MacOS looks very strange and pixelated.

**To Reproduce**
1. Start FTCLive on a Mac
2. Minimize the window that appears

**Expected behavior**
Icon for FTCLive looks reasonable

**Screenshots**
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/17951807/d828c011-2f18-4272-b0d7-19503f29beee)

**Device (please complete the following information):**
 - OS: MacOS 12
 - Browser N/A
 - Version 5.1.5

**Comment by maths22** [comment]
This has been fixed in the CenterStage offseason release
