### ISSUE TITLE
Pressing 'Commit' updates the pit display before the scores are "Post"ed to the audience display 

### ISSUE THREAD

**Issue by marcsol** [FIRST-Tech-Challenge/scorekeeper#675]
The '**Commit**' button causes the pit display to update the rankings and reveal the score before the scores are "**Post**"ed to the audience display.

**Describe the solution you'd like**
The pit display should not be updated _until_ the "**Post**" button causes the score to be displayed to the audience (preferably after the post animation finishes).

**Describe alternatives you've considered**
I try to use the "**Commit and Post**" button, but it is not always an option. If a score is edited or the next match is started, the "**Commit and Post**" button becomes inactive.

**Comment by maths22** [comment]
Rankings updates are now delayed 30 seconds from match commit.  We currently have no plans to make it wait for post, but this should still address the most common issues.
