### ISSUE TITLE
Inspection Display Disconnected

### ISSUE THREAD

**Issue by joshua-alvares6** [FIRST-Tech-Challenge/scorekeeper#676]
**Describe the bug**
The Inspection Status Display is broken. Consistently has "Disconnected" banner. All other display's work fine. I strongly suspect this is due to the event name containing single quote symbols which divides the string when displayed. I have tested this by creating an event without quotes and the display works as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an Event with " ' " in the event name.
2. Click on Judging and Inspection Tracking
3. Observe Disconnected Status

**Expected behaviour**
The display should work regardless of Event name

**Screenshots**
2 screenshots attached. One for the problem event and one test event with the display working.
![Screenshot from 2023-12-07 20-32-55](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/23661756/34b2a15d-2e44-46c7-a689-2aef288f08c6)
![Screenshot from 2023-12-07 20-36-15](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/23661756/1dca76cb-cab4-48e1-973b-1c5bb1b44f3b)

**Device (please complete the following information):**
 - OS: Tested Linux, Android, Windows
 - Browser: Tested Chrome and Firefox
 - Versions: Ubuntu 22.04 (Chrome 119 and Firefox 120), Assorted Android versions all running Chrome, Windows 10 running Chrome

**Additional context**
From the Firefox debugger you can see the page load the event name with quotes breaking the string:
<script>
	window.eventCode = 'caabsawm4';
	window.eventName = 'AB Naa'miis'stii - Meet 2';
	window.cols = 1;
	window.projector = false;
</script>
DB Folder:
[InspectionDisplayIssue.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/13608624/InspectionDisplayIssue.zip)

**Comment by maths22** [comment]
This has been fixed in v5.2.6
