### ISSUE TITLE
Links should open in new tabs

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#68]
The links to the `Pit Display`, and `Scoring/Timing Displays` should open in new tabs by default.  Some users may not be aware they need to ctrl+click on the links to open them in new tabs.  This is necessary to move the field timer display to the second monitor running on the field for example.

**Comment by adwiii** [comment]
Should this be the default behavior? I would have expected that the `Pit Display` and `Scoring/Timing Displays` will be on computers whose sole job is to display that page, meaning that the user would not need to navigate back to the event home page to open another page.

My guess would be that those using the field display on a second monitor probably also know how to open a link in a new tab, but I could be wrong.

I suppose it couldn't hurt though - it doesn't hurt anything to have the event home page open at the same time as the display.

**Comment by adwiii** [comment]
Upon further thought, the user has multiple options to introduce this behavior themselves - any action on our part would make it harder for users who do not want this behavior.
