### ISSUE TITLE
All Awards display "undefined" for 2nd and 3rd Place Winners if only 1st Place is given in Awards Manager

### ISSUE THREAD

**Issue by Tomrish** [FIRST-Tech-Challenge/scorekeeper#681]
**Describe the bug**
For New Hampshire Qualifiers we only designate a 1st Place Winner for all awards **except** Inspire (which gets 1st, 2nd and 3rd). While presenting awards on the standard Audience Display (Not the Overlay), all awards that only had a 1st place winner would show "undefined" for 2nd and 3rd place.

**To Reproduce**
1. Go to Awards Manager
2. Assign only a 1st Place winner to any award
3. Click present awards
4. Click the award that you have assigned only a 1st place winner to
5. See error on Audience Display

**Expected behavior**
If only 1st Place is assigned for an award, hide any mention of 2nd or 3rd place.

**Screenshots**
![IMG_1250](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/33290191/f94e9543-561d-4556-b261-0d8718ec4de4)

**Device (please complete the following information):**
All Server/Client/Display devices at this event were Windows 10/11 with supported versions of Chrome.

**Additional context**

**Comment by maths22** [comment]
This has been fixed in v5.2.6
