### ISSUE TITLE
After Live Scoring server restart, Displays in video switch show the wrong information in the table

### ISSUE THREAD

**Issue by ToddInIowa** [FIRST-Tech-Challenge/scorekeeper#684]
**Describe the bug**
If the Live scoring system is restarted some/most displays not show correct information in the video switch page.  At an event last weekend we needed to restart our scoring server after we already had all of the displays connected.  After the restart, all of the displays reconnected without an issue (the cloud pit display didn't update league ranks, but did display match updates, different bug report), however the video switcher tab only had names for 2 of the 6 displays.
All of the displays that lost their information showed as an audience display for all fields like bellow:
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/42328950/7db9d912-6e93-4df1-8426-7928cdcab3f8)
However the displays still worked as configured before the reboot (They were bound to the correct field, with the correct timer types etc.

**To Reproduce**
1- Setup multiple displays with different names
2- restart the scoring software
3- verify the names and configuration has changed in the video switch page, however you can verify that the actual display is still configured as done in step 1

**Expected behavior**
I expect the displays to show the correct configuration in the video switch page after a restart.

**Device (please complete the following information):**
Scoring server is running on Windows 11
displays are running on Windows 10, Windows 11, and Ubuntu OS
All displays are running on current releases of Chrome
The scoring server was running version 5.2.6

After restart:
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/42328950/53fbd987-fd6d-4666-a526-7b1dee5f9fb5)

If you press F5 on the display web browsers, the information is updated on the video switch page:
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/42328950/d1742543-7ae9-4c53-9a82-ffc78bc5c704)

**Comment by maths22** [comment]
This has been fixed in v5.2.8
