### ISSUE TITLE
High Scores not showing in FTC-scoring

### ISSUE THREAD

**Issue by ftcohioapt** [FIRST-Tech-Challenge/scorekeeper#689]
![rankings](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/45543906/8aaf000d-c5f0-4acd-af39-8845a8e6fc00)
**Describe the bug**
After an event is complete in FTC-scoring, the high scores do not show in the Rankings section, however TBP1 and TBP2 are correctly shown.

**To Reproduce**
1. Go to 'events'
2. Click on 'a completed event'
3. Click on 'rankings'
4. See error - Hi scores show as zero

**Expected behavior**
The high score should have a value greater than 0 (and be the same as found in ftc-events.firstinspires.org for the same competition.

**Screenshots**
see attached

**Device (please complete the following information):**
 - IOS and PC (Edge)
 
**Additional context**
High score does not show for any completed events in FTC-scoring

**Comment by ftcohioapt** [comment]
the bug is still there - hi scores not showing in ftc-scoring

**Comment by maths22** [comment]
This has been fixed now
