### ISSUE TITLE
Change red/blue backgrounds on score page

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#69]
The red and blue backgrounds on the `Score Edit` tab on the `Match Control Page` are hard to look at and read.  Any event that is doing paper scoring will have a scorekeeper looking at this page all day and it is very hard to read due to the bright colors and lack of contrast.  Just have a red/blue banner at the top and a cleaner UI for entering the scores.  Here is an example of a possible alternative design.

![scoreexample](https://user-images.githubusercontent.com/7074504/46886399-7579ec00-ce20-11e8-9d98-8e22111cca3b.png)

**Comment by jdo01** [comment]
I totally agree!

**Comment by jvens** [comment]
Can we please address this issue?  You can leave everything else the same just please tone down the colors.  My suggestion is for red instead of `#FF4444` use `#FFAAAA` and for blue instead of `#44AAFF` use `#77BBFF`.  This way it is still very clear which one is red and which is blue, but it is much easier to read the black text and not get a headache if looking at the screen all day.

**Comment by tvbarnette999** [comment]
This has been addressed in v3.1.4. There are 4 contrast options to pick from: `Standard`, `High`, `Max`, and `Dark`. The dropdown is on the control page's settings tab, under "Control Page Appearance".
