### ISSUE TITLE
Awards Manager "Stealth Mode"

### ISSUE THREAD

**Issue by thomasjosif** [FIRST-Tech-Challenge/scorekeeper#694]
**Is your feature request related to a problem? Please describe.**
Currently, while in "Present Awards / Manage Awards" all winners are displayed for all to see.

In the case where your audience can see behind the score table and possibly see award winners before release. (I.e. Pits are behind the score table, and the pipe and drape doesn't give you full coverage, publicly accessible catwalk above score table)

**Describe the solution you'd like**
In FRC FMS there is a "Stealth Mode" that is enabled by default that hides all award winners and only displays winners if explicitly turned off. It would be nice to have something similar to that in FTC Live where it tells you that an award is given, but no details about it unless you "peek" the winner or disable stealth mode.

**Describe alternatives you've considered**
Current alternative is using some blanket / people / object to obstruct the prying eyes.

**Additional context**
N/A

**Comment by tvbarnette999** [comment]
This was added in the v6.0.0 preview, but we forgot to call it out in the release notes - oops!

It is on by default and hides the award winner info on the "Present Awards" page.

![image](https://github.com/user-attachments/assets/39a4f77c-3a75-4e8f-b8d1-28b8725a29d2)

Peeking a row:
![image](https://github.com/user-attachments/assets/2fc08f6e-b7a0-4c41-9de8-6d0063eae3da)

Stealth mode disabled:
![image](https://github.com/user-attachments/assets/416ed9a3-4274-48da-9c83-42170d90df88)

**Comment by thomasjosif** [comment]
> This was added in the v6.0.0 preview, but we forgot to call it out in the release notes - oops!
> 
> It is on by default and hides the award winner info on the "Present Awards" page.
> 
> ![image](https://private-user-images.githubusercontent.com/13516182/384014476-39a4f77c-3a75-4e8f-b8d1-28b8725a29d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNTg2OTgsIm5iZiI6MTczNDA1ODM5OCwicGF0aCI6Ii8xMzUxNjE4Mi8zODQwMTQ0NzYtMzlhNGY3N2MtM2E3NS00ZThmLWI4ZDEtMjhiODcyNWEyOWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDAyNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNjFmMzQzZjAwNmE4MzE0OTYwNmMxOWE1NWQyOGMzZjA0ZmRkMWFlNjc5OTgxMDQ1OWU3ZDc3YjFmZmMzZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qR2xJYwM00VO6_V3ptdEjSs1R222p7Rj9alSLico0NQ)
> 
> Peeking a row: ![image](https://private-user-images.githubusercontent.com/13516182/384014547-2fc08f6e-b7a0-4c41-9de8-6d0063eae3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNTg2OTgsIm5iZiI6MTczNDA1ODM5OCwicGF0aCI6Ii8xMzUxNjE4Mi8zODQwMTQ1NDctMmZjMDhmNmUtYjdhMC00YzQxLTlkZTgtNmQwMDYzZWFlM2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDAyNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYmQ2NDZkMjliZjQ4OTg0NDllYTc3ZTRjNGJlY2ExMjljMWU4Yjg2ZmFlNTJkNDM4Yzk3NzI0ZTZjNmI4MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AQdMr-Sx7sb82oMAKKm--cMNZRFWVKKnmL0xhK68ygI)
> 
> Stealth mode disabled: ![image](https://private-user-images.githubusercontent.com/13516182/384014573-416ed9a3-4274-48da-9c83-42170d90df88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNTg2OTgsIm5iZiI6MTczNDA1ODM5OCwicGF0aCI6Ii8xMzUxNjE4Mi8zODQwMTQ1NzMtNDE2ZWQ5YTMtNDI3NC00OGRhLTljODMtNDIxNzBkOTBkZjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDAyNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYWZjZWMzODQwN2RkMTVmN2RjNzU2ZDgxOTE1N2RmMWRmODc1ZWYxYjAyNTMwMDFmYmJmOWVkNDQ4MjVjZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZlycLDsO6FpSqi7wWFoaLXUM7BEVFXuh-HMEZLtiBKk)

That's awesome! I've tested it out at a few events and it's great, thanks for implementing it :)

Any chance it could be ported to work in the "Give Awards" section too? Something to verify that the award is given, without all the names on the left hand side? I.e. The row goes green, and GIVEN (HIDDEN) is shown or similar? Mainly because when you hit the "Sync From Online Scoring System" you get redirected to that tab, and the same issue occurs.
