### ISSUE TITLE
Problem with sending scores

### ISSUE THREAD

**Issue by StripierWig208** [FIRST-Tech-Challenge/scorekeeper#695]
Hello!
I faced an issue with the scoring system. A week after the event, I received an email on Wednesday stating that I hadn't submitted the scores to FIRST. Subsequently, I accessed the FIRST platform and submitted the scores. However, as a result, the event scores no longer appear on the FTC Events website.
What should I do?
<img width="1521" alt="Screenshot 2024-01-27 at 11 02 27" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/110335276/3b485d80-c70d-4eec-b23f-eb99b21c71f6">
![first events problem](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/110335276/3696f6a5-18a9-4006-90a7-06f1816f5da5)

**Comment by maths22** [comment]
This event data for this event has been fixed up
