### ISSUE TITLE
Incorrect capitalization of teams and alliances fields in FTC API.

### ISSUE THREAD

**Issue by Dragon-Hatcher** [FIRST-Tech-Challenge/scorekeeper#698]
**Describe the bug**
The `teams` field of the `Match` types and the alliances field of the `MatchScores` family of types are now capitalized. They weren't before and the api docs say they should not be.

**To Reproduce**
`curl 'https://ftc-api.firstinspires.org/v2.0/2023/schedule/USTXWLALT1/qual/hybrid' -H 'Authorization: Basic YOUR_API_KEY'`. Observe that the `teams` field is `Teams`. 

**Expected behavior**
`teams` and `alliances` should be all lowercase as it says in the docs.

**Comment by maths22** [comment]
This has been fixed.  Thank you for bringing it to our attention.
