### ISSUE TITLE
ftc.events redirect doesn't resolve

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#699]
**Describe the bug**
Previously, http://ftc.events would redirect to https://ftc-events.firstinspires.org, similar to how http://frc.events would redirect to https://frc-events.firstinspires.org. ftc.events no longer resolves.

**To Reproduce**
1. Navigate to http://ftc.events
2. Observe the page does not resolve
3. Navigate to https://ftc-events.firstinspires.org
4. Observe that the request resolves

**Expected behavior**
ftc.events redirects to https://ftc-events.firstinspires.org

**Screenshots**
![screenshot](https://i.imgur.com/VFuNBZf.png)

![terminal](https://i.imgur.com/b4qo9Z0.png)

**Device (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 22H2 (OS Build 22521.3007)
 - Browser [e.g. chrome, safari] Firefox 122,0.1

**Additional context**
(TBH, both ftc.events and frc.events should really work with https, as neither do. However, ftc.events, which used to work, no longer does.)

**Comment by tweirtx** [comment]
Seems to be working now...not sure what happened there
