### ISSUE TITLE
Audience Display does not have indicator for penalties accumulated and score does not reflect penalty points.

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#7]
Audience Display: The Audience display does not have a counter/other indicator for the penalties accumulated. The score does reflect penalty points.

**Comment by adwiii** [comment]
This is by design - other programs do not do this and so we decided not to implement this as well. As pointed out, the score does reflect the penalties, so the Audience does have a mechanism to tell.

**Comment by rebeccawhitaker** [comment]
I would encourage a display of penalties on audience display. There are frequent questions by parents/spectators/other students who watch the matches and may not understand why the score was lower than what they were calculating.

**Comment by jkelbick** [comment]
I agree, the audience display should show penalties. This is one of the most frequent questions asked.
