### ISSUE TITLE
Inspection Process for Team Scoring Elements and Team Game Elements

### ISSUE THREAD

**Issue by Veeryuk** [FIRST-Tech-Challenge/scorekeeper#702]
**Is your feature request related to a problem? Please describe.**
A problem I am consistently running into as a FIRST Technical Advisor/ Robot Inspector for smaller events like league meets and league tournaments is teams not having things like a Team Scoring Element (TSE) or a Team Game Element (TGE) which is completely fine. The issue is that the current inspection process (at least on the live scoring system) does not have the ability to say "not applicable" if they don't have a TSE or a TGE. This makes it an issue as I cannot pass a team in inspection on the live scoring system unless I mark that their TSE or TGE is within the rules even if they do not have one. This makes it hard to keep track of teams who have a TGE or a TSE that have been inspected as some teams this year that I ran into during the inspection process, did not have a TSE but had one after they were inspected which meant their TSE never went through the inspection process but, the inspection sheet on the live scoring system said they did.

**Describe the solution you'd like**
A checkbox inside the inspection process on both the paper inspection sheet and the live scoring system sheet that allows me and other Robot Inspectors to be able to check that marks an entire section of the Team Game Element or Team Scoring Element as "not applicable" or something similar so we have the ability to track teams that do and do not have TGE's and TSE's so that in the chance they do make one after inspection, we have the ability to look back at the inspection notes quickly to see that the entire section was marked as "not applicable".

**Describe alternatives you've considered**
One alternative that I have been training my inspectors to use is the notes feature and put "no TSE" or "no TGE" if a team does not have one of those. It does clog up the notes section, especially if you have other things you need to put notes for like notes on why a team failed inspection which I have been getting around by training my inspectors to clear any notes that are not needed after re-inspection.

**Additional context**
N/A

**Comment by maths22** [comment]
You can skip those sections of the form if they do not have a TSE/TGE.  When using the software you can just leave those unchecked and still click "pass"
