### ISSUE TITLE
Event Date inconsistency

### ISSUE THREAD

**Issue by ShaharIlany** [FIRST-Tech-Challenge/scorekeeper#703]
**Describe the bug**

I recently submitted a request to change the date of our upcoming event. However, upon reviewing the details, I noticed an inconsistency regarding the selected date. While I initially opted for February 19th, the system appears to display February 18th.

<img width="1138" alt="image" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/31574996/4a4afcd0-a655-4451-8db9-f6bdcb5f7b73">

Interestingly, upon reviewing the request from "Request History" tab, everything appeared to be in order.

<img width="1182" alt="image" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/31574996/cd4f87f2-c334-4b2d-8166-86fc960d1969">

I did some further investigation and came across more issues with the dates. Interestingly, on the "Current Info" tab in the event editor, the new date is already visible, even though the request hasn't been approved yet.

<img width="1203" alt="image" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/31574996/6ee67de5-d5a9-40b4-b0ad-013948aeceea">

However, the event preview still reflects the original date of February 18th.

<img width="1162" alt="image" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/31574996/d4db164b-a044-4cee-861e-2996f39be6d6">

Additionally, the inconsistency persists on ftc-events.firstinspires.org.

<img width="1363" alt="image" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/31574996/a47b6b7b-77c4-4ca4-ba86-ce48855540da">

**To Reproduce**
1. Go to Events tab
2. Click on an event and Manage Event
3. Click on Event Info
4. Scroll down to Create Edit Request
5. Change the date and submit the request.

**Expected behavior**
The system should reflect the selected date throughout all relevant sections, including the event preview and any associated platforms, once the request for date change has been approved.

**Device (please complete the following information):**
 - OS: MacOS Sonoma 14.1.1 (23B81)
 - Browser Chrome
 - Version 121.0.6167.139 (Official Build) (arm64)

Please notice that the timezone of my Mac is Israel Standard Time (Asiz/Jerusalem)

**Comment by adwiii** [comment]
Event requests, both to create an event or edit an existing event, are manually processed by HQ for approval.
Your request has not yet been processed - as noted in your first screenshot, the request is still "PENDING"; the changes requested will not be reflected in the system nor on ftc-events until the request is approved.
HQ routinely processes requests a few times a week during eastern time business hours.

**Comment by adwiii** [comment]
This event request has been processed and should reflect as updated on ftc-scoring and ftc-events. In the future, please reach out to event-day support/*FIRST* HQ for urgent event request issues.
