### ISSUE TITLE
Dual Division Finals Overlay Screen Text Overlap

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#712]
**Describe the bug**
The division name overlaps with the score in the overlay audience view.

**To Reproduce**
1. Run dual division finals
2. Look at the overlay screen

**Expected behavior**
Be able to read the division name

**Screenshots**
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/7074504/8ca29860-7715-40ba-a4c6-35e0f4f49a7f)

**Device (please complete the following information):**
 - N/A

**Additional context**
N/A

**Comment by aj-foster** [comment]
Beat me to the report :)

![4BB7CC04-DBAE-4566-8A17-7B10C3DEDC55_1_105_c](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/2789166/063e16f7-a04b-4d32-a6f9-617269aa7e72)

**Comment by maths22** [comment]
This has been resolved in v5.2.18
