### ISSUE TITLE
The full bracket display doesn't update 

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#715]
**Describe the bug**
When using the Dual Division audience display with the the display set to `Show Bracket (full)` the wins numbers don't update and the next level doesn't populate until clicking the `Show Bracket (full)` button again.  For example, after playing SF1-2 if red has two wins nothing updates on the screen until pressing the button, and then pressing the button forces the display to update to fill in `2` next to the red alliance and populate the red teams in the division finals.

**To Reproduce**
1. Run elimination matches in a dual division event on each division
2. Set the display for the `_0` event to `Audience` type and in the `_0` event `Match Control` page select `Show Bracket (full)`
3. Observe that as matches are played the display doesn't update
4. Click `Show Bracket (full)` again
5. Observe that the display updates

**Expected behavior**
The display should update automatically as scores are posted for each division.

**Screenshots**
N/A

**Device (please complete the following information):**
 - 5.2.14

**Additional context**
N/A

**Comment by maths22** [comment]
This behavior has been improved in v5.4.0.  All brackets now auto-updates with a 30-second delay.
