### ISSUE TITLE
Scrolling Team Names Go Out of Bounds

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#723]
**Describe the bug**
Team Names that are long enough to scroll go out of the boundary on the preview overlay

**To Reproduce**
1. Have a really long team name
2. Preview their name on the overlay

**Expected behavior**
Scrolling team names stay in bounds

**Screenshots**
![P_20240321_165014.jpg](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/17951807/32ba485d-22c1-4bf7-847a-691d84c6cc67)

**Device (please complete the following information):**
 - OS: Windows 11
 - Browser: OBS Browser source (Chromium) 
 - Version 5.2.19

**Comment by maths22** [comment]
This has been fixed in v5.4.0
