### ISSUE TITLE
Inter-Division Alliance name overlap

### ISSUE THREAD

**Issue by ShaharIlany** [FIRST-Tech-Challenge/scorekeeper#724]
**Describe the bug**
The alliance name for dual division events are overlapping the team numbers in inter-division matches.

**To Reproduce**
1. Create dual-division
2. Play the events normally until each division have a winner (In our case there was two teams per alliance)
3. Generate inter-division matches
4. Show preview of the first match

**Expected behavior**
The names should not overlap and shoud be clear and visible to the audiance.

**Screenshots**
![IMG_4929 (1)](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/31574996/c894b323-9e32-411f-a6e7-fb17a3a8a52b)

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 123

**Comment by maths22** [comment]
This has been fixed in v5.4.0
