### ISSUE TITLE
Match results timeout logo off of the screen

### ISSUE THREAD

**Issue by ashermyers** [FIRST-Tech-Challenge/scorekeeper#727]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/43706372/932c765d-b5c5-4f39-a608-adb720c86937)

**Comment by maths22** [comment]
This has been fixed in v5.4.0
