### ISSUE TITLE
Multi-League Metro Model

### ISSUE THREAD

**Issue by devinbreise** [FIRST-Tech-Challenge/scorekeeper#733]
**Question:**  If I configure 2+ Leagues in a Metro model and then construct Meets that include teams from 2 or more of those Leagues, will the League Standings be calculated and reflected correctly?

**Example:**
- League A with team #s 1-24
- League B with team #s 25-48
- Meet 1 with a random collection of 12 teams from League A and 12 teams from League B
- Meet 2 with a different random collection of 12 teams from League A and 12 teams from League B
- Meet 3 with a different random collection of 12 teams from League A and 12 teams from League B
- Meet 4 with a different random collection of 12 teams from League A and 12 teams from League B

Will the League Standings for Leagues A and B reflect match outcomes for _their_ teams from all Meets?

**Question 2:** If the above doesn't work, is it possible to set up an event of type "League Tournament" associated with a _child-league_?  This could serve as an alternative approach to enable the league mixing described above.  E.g. League A and B would be Child Leagues of a Parent League that contained all 48 teams.  League Tournaments would be associated with League A and League B.  There would be no Tournament associated with the Parent League.

Thank you!

**Comment by emcclurg** [comment]
@devinbreise The answer to question 1 is these need a Parent league then two child leagues A and B or just one big parent league, then feel free to add meets with both child leagues.  Question 2 you need to setup all league tournaments in the parent league then divide up the child leagues.

Here's a breakdown from @tvbarnette999 
Longer Answer: What you have described are two _Child_ Leagues of the same Parent League. A League Event only involves _one_ League, so you would set this scenario up as a League "P" with all 48 teams. Then make children Leagues "A" and "B" with the split you mentioned. All Meets would be P League Meets. The rankings for League P would show all 48 teams ranked relative to each other. League A's rankings will show only the teams in League A and B's will only show B's, but the metric values for each team (RP, TBP1, TBP2, etc), will be the same in both League P and League A's Rankings. For example, Team 1 will have the same RP in League P's ranking as they do in League A's, just where that falls relative to other teams will differ.

**Comment by devinbreise** [comment]
Thank you, that is very helpful.  And just to confirm, setting up and configuring a "League Tournament" event associated with one of the Child Leagues (A for example) is a supported use case?

**Comment by emcclurg** [comment]
We do not currently support tournaments in the child league but you can have two tournaments in the parent.  All advancement history needs to be tied to the parent league for now.

**Comment by devinbreise** [comment]
Hmmm...so if I set up two _League Tournaments_ in the Parent League P, and for each of these tournaments, I only include the teams from _one_ of the Child Leagues (A or B), that works?  For example, the rankings of the teams as Qualification matches comes to a close in that League Tournament would only include the teams in that tournament?  Or would I need to ensure folks were looking at the first-events page that corresponded with the Child Tournament which held those teams?
Thanks!

**Comment by maths22** [comment]
Chicago uses a metro league model very similar to what you have described with two league tournaments.  You can see that here: https://ftc-events.firstinspires.org/2023/region/USIL/league/CM. The rankings going into the league tournament will match the ordering of ones shown on the league, just with teams not in tournament removed.

**Comment by devinbreise** [comment]
Perfect.  Thank you for all the quick answers!
