### ISSUE TITLE
Adding an "Additional Runner-Up" (> 3 rows) shows "undefined" on the audience display on presentation

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#739]
**Describe the bug**
On the Audience Display, when presenting a custom award with an "Additional Runner-Up", the display shows "&lt;Award Name&gt; undefined"

**To Reproduce**
1. Go to the Awards Manager
2. Create an award in Manage Awards
3. In Give Awards, award the "Additional Runner-up"
4. Create an Audience Display.
5. Present the Additional Runner-up.

**Expected behavior**
Some text is shown, similar to the other positions -- "Winner", "2nd place", "3rd place"

**Screenshots**
<img width="1512" alt="Screenshot 2024-09-19 at 21 41 53" src="https://github.com/user-attachments/assets/d45a13ed-7485-4ae9-ad65-d01f72a6a201">

**Device (please complete the following information):**
 - OS: [e.g. iOS] macOS 14.6.1 (23G93)
 - Browser [e.g. chrome, safari] Firefox 130.0 (64-bit)

**Comment by maths22** [comment]
This has been fixed in v6.1.3
