### ISSUE TITLE
Awards overlay is not centered/there is an uneven amount of horizontal margin

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#740]
**Describe the bug**
There is an uneven amount of margin between the left and right sides of the Awards overlay.

**To Reproduce**
1. Open an Overlay Display
2. Present an Award
3. Observe the spacing

**Expected behavior**
The overlay should be centered/there should be an equal amount of margin on each side.

**Screenshots**
<img width="1512" alt="Screenshot 2024-09-19 at 21 54 59" src="https://github.com/user-attachments/assets/7eacf214-00f2-48f8-9db9-d91096d08d14">

**Device (please complete the following information):**
 - OS: [e.g. iOS] macOS 14.6.1 (23G93)
 - Browser [e.g. chrome, safari] Chrome 128.0.6613.138 (Official Build) (arm64) (as well as Firefox 130.0 (64-bit))

**Comment by timtim17** [comment]
Purely for reference/comparison, the 2024 FRC awards overlay:

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/958f5abb-267c-494c-80a5-3cce5295c686">

There is a roughly even amount of space on each side of the lower third.

<img width="896" alt="image" src="https://github.com/user-attachments/assets/97f94891-b080-41eb-a6ed-6e26309befb9">

**Comment by maths22** [comment]
This has been fixed in v6.1.3
