### ISSUE TITLE
Suggest separating the "Start" and "Abort" match button positions 

### ISSUE THREAD

**Issue by Cannongeorge** [FIRST-Tech-Challenge/scorekeeper#744]
**Is your feature request related to a problem? Please describe.**
When starting a new match, immediatley upon starting a match the underlying "Start Match" button turns into an "Abort Match" button. 
When using foreign scorekeeper computers with unfamilier track wheels, mice, or "nibs" I'm always terrified of key bounce and accidently triggering an "Abort" when I don't want to. 

**Describe the solution you'd like**
Immediatley upon successfully starting a new match, "Grey out" the start match button and illuminate a new pop-up, an "Abort Match" button, to be located immediatley to the right of the previously mentioned "Start Match" button. 

**Describe alternatives you've considered**
Upon successfully starting a new match, carefully "nudging" the mouse away from the (newly defined) "Abort" pad location.  But when using "nibs" or fingerpads on foreign machines I'm still terrified of accidentially introducing an "abort" when I don't want to!

**Additional context**
If I travel to other meets I cannot always use the laptop computer that I am used to for match control.

**Comment by Cannongeorge** [comment]
Thank you for confirming that!  I stand corrected thus this issue not as
concerning as I thought.
George

**Comment by maths22** [comment]
Because aborting a match requires active confirmation in the popup message, we will not be adding a separate button for this purpose
