### ISSUE TITLE
Remove Robot 3 Columns in Match Control Page

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#745]
**Describe the bug**
The `Red 3` and `Blue 3` columns on the match control page are no longer needed now that playoffs are 2-team alliances.  Those columns should be removed to help de-clutter an already very busy page.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Device (please complete the following information):**
 -  v6.0.2

**Additional context**
N/A

**Comment by maths22** [comment]
This has been fixed in v6.1.0
