### ISSUE TITLE
Swagger docs page not loading

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#746]
**Describe the bug**
Attempting to go to the built-in swagger docs page gives a 404 error.

**To Reproduce**
1. Attempt to go to http://localhost/swagger-docs/api.html
2. See Error 404 page

**Expected behavior**
The swagger docs with updated documentation for the score details of this years game.

**Screenshots**
N/A

**Device (please complete the following information):**
- v6.0.2

**Additional context**
N/A

**Comment by cmacfarl** [comment]
It is now just [http://localhost/swagger-docs/](http://localhost/swagger-docs/api.html)

I'll leave this open until we've verified that we've updated the public facing documentation.

**Comment by maths22** [comment]
https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation has been updated to reflect the new URL.
