### ISSUE TITLE
Match data not updated in API

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#747]
**Describe the bug**
When attempting to get match data from the API Some fields don't seem to be updated after match is played.

**To Reproduce**
1. Generate match list
2. Play a match, commit and post non-zero scores
3. GET http://localhost/api/v1/events/{code}/matches/
4. Observe the `matches[1].matchState === "UNPLAYED"`
5. GET http://localhost:8080/api/v1/events/test1/matches/1/
6. Observe the result similar to the example below where all the score fields are 0, and the times are still default.
```json
{
    "matchBrief": {
        "matchName": "Q1",
        "matchNumber": 1,
        "field": 1,
        "red": {
            "team1": 6,
            "team2": 11,
            "isTeam1Surrogate": false,
            "isTeam2Surrogate": false
        },
        "blue": {
            "team1": 5,
            "team2": 10,
            "isTeam1Surrogate": false,
            "isTeam2Surrogate": false
        },
        "finished": false,
        "matchState": "UNPLAYED",
        "time": 1725826635516
    },
    "startTime": 0,
    "scheduledTime": 1726318800000,
    "resultPostedTime": -1,
    "redScore": 0,
    "blueScore": 0,
    "red": {
        "auto": 0,
        "teleop": 0,
        "end": 0,
        "penalty": 0,
        "dq1": false,
        "dq2": false,
        "robot1": 6,
        "robot2": 11
    },
    "blue": {
        "auto": 0,
        "teleop": 0,
        "end": 0,
        "penalty": 0,
        "dq1": false,
        "dq2": false,
        "robot1": 5,
        "robot2": 10
    }
}
```

**Expected behavior**
After the match is played the status should change along with the time, and the score information should be filled in on the details route.

**Screenshots**
N/A

**Device (please complete the following information):**
 - v6.0.2

**Additional context**
N/A

**Comment by maths22** [comment]
This appears to be working correctly in the current release, though we didn't make any changes that were intentionally aimed at fixing this, so please let us know if it continues to happen.
