### ISSUE TITLE
Video does not play on score post

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#749]
**Describe the bug**
FTC Live v6.1.0. When posting scores, the animation does not play. The browser console reports a 404.

**To Reproduce**
1. Open a scoring/timing display
2. Post a score

**Expected behavior**
An animation is played and the score is revealed

**Screenshots**
<img width="1244" alt="Screenshot 2024-10-17 at 21 28 08" src="https://github.com/user-attachments/assets/718d3695-f5a0-4e6e-9871-ecce847951f6">

**Device (please complete the following information):**
 - OS: [e.g. iOS] macOS 14.6.1 (23G93)
 - Browser [e.g. chrome, safari] chrome 129.0.6668.100 (Official Build) (arm64) 
 - FTCLive v6.1.0

**Comment by maths22** [comment]
This has been fixed in v6.1.1
