### ISSUE TITLE
Side scrolling happens on match preview screens for all team names.

### ISSUE THREAD

**Issue by PythonAtSea** [FIRST-Tech-Challenge/scorekeeper#751]
**Describe the bug**
Side scrolling happens on match preview screens for all team names.

**To Reproduce**
1. Load the preview for any match.
2. See all team names are side scrolling, even really short ones. 

**Expected behavior**
Short team names do not scroll, long ones still would.

**Screenshots**

**Device:**
 - OS: Windows 11
 - Browser Google Chrome
 - Version 6.1.1

**Comment by maths22** [comment]
Thank you for pointing out this bug.  We have released v6.1.2 to address this issue.
