### ISSUE TITLE
All Architectures Release Fails to Launch

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#753]
**Describe the bug**
All Architectures Zip archive, The `FTCLauncher.bat` script references a non-existent file `bin\FTCLocal.bat` causing the scoring system to fail to launch.

**To Reproduce**
1. Download All Architectures Zip archive `FTCLive 2025-6.1.2.zip`
2. Unzip
3. Run `FTCLauncher.bat`

**Expected behavior**
Scoring system launches.
Launcher script should reference `bin\FTCLauncher.bat`.

**Screenshots**
![image](https://github.com/user-attachments/assets/a946ee3e-6d03-48df-a59a-2ed607bbc5e8)

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser N/A
 - Scorekeeper Version 2025-6.1.2

**Comment by tweirtx** [comment]
Can repro, looks like the file it's looking for was renamed to bin/FTCLauncher.bat

**Comment by maths22** [comment]
This has been fixed in v6.1.3
