### ISSUE TITLE
Undefined bookmarks in Scorekeeper Guide

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#754]
** Requested Change **
Fix the table of contents in the Scorekeeper Guide:
![image](https://github.com/user-attachments/assets/b4b889cc-e1b7-4a64-a75a-10adb7c2c53f)

** Relevant existing documentation **
[Scorekeeper Guide Page 4](https://www.firstinspires.org/sites/default/files/uploads/resource_library/ftc/scorekeeper-guide.pdf)

**Comment by ShaharIlany** [comment]
Can you please check again?
I can't find the referenced error in the scorekeeper guide

<img width="815" alt="image" src="https://github.com/user-attachments/assets/5fe40294-cbc0-4172-8e0a-df6159e93004">

**Comment by maths22** [comment]
The scorekeeper manual was updated this morning, and this issue was corrected in that update.
