### ISSUE TITLE
Printing Match Schedule - Condensed doesn't do anything and the time is always displayed

### ISSUE THREAD

**Issue by hightechkids** [FIRST-Tech-Challenge/scorekeeper#756]
Running 6.1.2 when you select the match schedule, there is a checkbox to "condensed" the printout, but it doesn't change the schedule at all. (16 matches still takes 2 pages to print). Also there's no option to NOT display the time on the printed schedule.

**Comment by rachmo** [comment]
Thank you for your bug report. We have confirmed the issue with the "condensed" button not working and it will be addressed in a future release. 

The ability to hide times from the schedule has intentionally been removed. The Competition Manual has some specific rules for Head Referees based on the match schedule, so we need to have displayed times on all schedules. We are asking scorekeepers to work with their PDP, Event Director, or Head Referee to generate accurate timing on their schedules.

**Comment by maths22** [comment]
The "condensed" checkbox issue has been fixed in v6.1.3
