### ISSUE TITLE
Can auto and teleop times be configurable for our custom Mini-FTC event?

### ISSUE THREAD

**Issue by EducHTech** [FIRST-Tech-Challenge/scorekeeper#757]
**Is your feature request related to a problem? Please describe.**
Each year, we use the official scoring system for our Mini-FTC, a competition where students prototype mechanisms using wood and Lego. The control system includes an EV3 brick for the main operations and an Arduino for controlling servomotors and 12V motors. The match timing is unofficial! Since the robots are slow (EV3 motors), we’d like longer matches to strategize. The autonomous mode is weak, so we prefer to start teleop immediately rather than wait for the auto period to end. We do hold distinct matches for those who have an autonomous mode, but we want to avoid unnecessary delays.

**Describe the solution you'd like**
I’d like the timer to be configurable (a config file is sufficient) so we can:
- Disable the autonomous timer to start teleop immediately.
- End the match after auto by disabling teleop.
- Adjust the times: for example, 1 minute for auto and 3 minutes for teleop.

**Describe alternatives you've considered**
We use the scoring system for results but recorded sounds to play without it.

**Additional context**
The Mini-FTC is this Saturday, October 26th, in Montreal, Quebec. If you have an early version of this feature to test, I’d love to use it; otherwise, it’s a suggestion for next year!

**Comment by IsyRivers** [comment]
To add to this, I also do FLL events and use the same systems for displaying scores (flltournament scores) and we have a custom timer that some created.  It would be nice if the FTC scorekeeping timer could also be used as an FLL Timer. Just need the 2:30 countdown.  Option to remove the 8 second delay after autonomous but still have the FTC sound effects.  

More of a nicety thing to have that doesn't seem to be much outside the scope of the FTC score system.
