### ISSUE TITLE
FTA Notepad: Editing an existing Issue does not properly update state

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#759]
**Describe the bug**
When updating an existing issue in the FTA Notepad, checking the resolved checkbox or changing the type does not update the UI in the modal, though the change is made.

Additionally, changes are made even if "Cancel" is pressed on the modal.

**To Reproduce**
1. Go to the FTA Notepad
2. Create an Issue on a team
3. Attempt to edit the issue by changing the resolved state or type
4. Observe that the UI is not actually updated to reflect the change
5. Click "Cancel"
6. Observe that the notepad is actually updated with the changes

**Expected behavior**
The resolved checkbox and issue type dropdown should reflect the changes.

**Screenshots**
[edited link] https://github.com/user-attachments/assets/d6206842-a931-40e9-a392-85b4c74b76c2

**Device (please complete the following information):**
 - OS: macOS 14.6.1 (23G93)
 - Browser: Google Chrome 130.0.6723.70 (Official Build) (arm64) 
 - FTCLive v6.1.3

**Comment by timtim17** [comment]
Additionally, editing the summary does not properly reflect the updates in the text box, and on save/cancel only the last keypress is appended to the field.

**Comment by tvbarnette999** [comment]
This has been fixed in v6.1.4
