### ISSUE TITLE
Output Database

### ISSUE THREAD

**Issue by khoyt5** [FIRST-Tech-Challenge/scorekeeper#76]
We post the standings of the different leagues in our state. So I read in the output from the scoring software to generate the league standings. This year the output is a SQL Lite database and so I am trying to understand the format of the database. The teamInfo table has all the teams but it does not include the team number. Any reason why? I can look at the unique number is in the quals table and assume the teamInfo table is sorted numerically.

What does the 'S' mean in the quals table? There is blue1, blue1S, blue2, blue2S, red1, red1S, red2, and red2S.

**Comment by adwiii** [comment]
Well, regardless of the database format, this raises a red flag for me. The scoring system is the only official source for rankings, and these cannot be recovered from the database since they are calculated internally and never stored.

If this should be changed to a feature request for there to be a way to obtain league rankings, then this sounds closer to a request for a 3rd party API - which is something we have on the docket for the near term. We would need to make it so there was an easy way to query for rankings.

Would a 3rd party API resolve this issue?

**Comment by cmacfarl** [comment]
Please do not peek into the database,   It's a lot of work, you may be wrong, and we've already done the work for you and can hand you nice JSON.

If there's data you want that we don't yet have API support for , we can likely give it to you.   @adwiii the rankings endpoint exists as of earlier this week and will be in 0.4.1.

**Comment by khoyt5** [comment]
Don't know if a 3rd party API works for me or not as it would have to work with our State website. I did error and was not looking at column 0 so I do see the team number in the teamInfo table. Basically, I would take the matches.csv file (from last year's scoring system) and divisions.csv file and import that into my own database on the website. We did put on the website that it was the "unofficial" rankings for the leagues. I would verify that the rankings that the website computes from the matches were the same as the scoring software. This gave everyone a view of the league rankings since you could only see them at the end of a meet.

**Comment by cmacfarl** [comment]
The 3rd party api will give you all the matches and rankings via a few simple http GET queries that return JSON formatted data.  You can write a script to convert json to whatever csv file you need, but again, you should not be doing raw database queries yourself.

**Comment by jvens** [comment]
Is there any documentation for this 3rd party API available yet?  I have not been able to find what endpoints are planned to be supported or exactly what format is expected for queries.

**Comment by cmacfarl** [comment]
Documentation is coming in the next release.
