### ISSUE TITLE
HTTP 500 when loading event dashboard

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#761]
**Describe the bug**
At an event, we encountered an HTTP 500 when attempting to load the Event Dashboard.

**To Reproduce**
Unsure if I am able to repro. What we had done at our event was:
1. Load event as normal (the event was a meet of a WA child league)
2. Remove one team that was unable to come via the event dashboard
3. Generate and activate a match schedule
4. Attempt to access the Event Dashboard and observe an HTTP 500

**Expected behavior**
The event dashboard loads

**Screenshots**
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/1e6ab89d-d1dd-4858-a582-bdfe29d1f78d">
![4A4022A6-9C3B-4C9E-967B-2B124D522055_1_105_c](https://github.com/user-attachments/assets/284e0dd9-1c7a-4207-a355-c6a7f9dbea46)
![D7271068-D030-45B6-A2D1-F2D65F7941EA_1_105_c](https://github.com/user-attachments/assets/34e21787-16d7-43d0-8bc8-5636484a412e)

**Device (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Unknown

**Additional context**
I do not own the laptop that ran the scoring server, so unfortunately cannot retrieve any further information myself. We did engage the support chat for this issue, and got help accessing the Upload Event page directly.

**Comment by timtim17** [comment]
Not exactly sure if this is what happened, because I'm not sure if the event ran an Inspection Schedule, but I was able to encounter an HTTP 500 error based on what I inferred from the stack trace:
1. Generate an Inspection Schedule
2. Remove a team using Add/Edit Teams
3. Refresh the Event Dashboard and observe an HTTP 500

**Comment by tvbarnette999** [comment]
This has been fixed in v6.1.3
