### ISSUE TITLE
Create Match Schedule page gives incorrect rule citation for 5-minute breaks in smaller events

### ISSUE THREAD

**Issue by pmichaud** [FIRST-Tech-Challenge/scorekeeper#762]
**Describe the bug**
On the "Create Match Schedule" page for events with small numbers of teams (11 in this example), there is a blue box that correctly states that breaks must be inserted into the schedule for back-to-back matches.  However, the rule cites a non-existent "T607" rule.   The correct reference should be "T206".

**To Reproduce**
1. Set up an event with a small number of teams (11 in this example)
2. Click on "Create Match Schedule"
3. A blue box is displayed with text "With 11 teams, there must be a break under T607 approximately every other match. Therefore, the average minimum match cycle time is 8 minutes."  The T607 rule cited doesn't exist in the current manual.

**Expected behavior**
The blue box should cite rule T206.

**Screenshots**

![image](https://github.com/user-attachments/assets/b41e15af-0427-404c-8232-752695d1731b)

**Device (please complete the following information):**
 - OS: Linux 64-bit
 - Browser: Chrome
 - Version: 130.0.6723.69

**Comment by maths22** [comment]
This has been fixed v6.2.0
