### ISSUE TITLE
Foul points are displayed incorrectly in score breakdown

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#765]
**Describe the bug**
Foul points appear to be displayed under the wrong alliance.

**To Reproduce**
1. Go to a published match score with fouls, for example https://ftc-events.firstinspires.org/2024/USWARIM1/qualifications/18
2. Observe the count of fouls under one alliance. For example, with 2024 USWARIM1 q18, the Red Alliance committed 1 Minor Foul for a total 5 points credited to the Blue Alliance.
    - This seems confusing. The rest of the entries in this column are scoring achievements that add to the alliance score. These foul points do not add to this alliance's score, but the other alliance's.
3. Observe that the foul points do not line up -- for example, with USWARIM1 q18, despite the 5 foul points in the red score breakdown on the left, the score summary shows "RED FOULS 5" on the right, blue score.
4. Observe that the Score Breakdown graph shows the foul points on the graph of the alliance that committed the foul. For USWARIM1, the red alliance graph on the left shows 5 foul points, when those were actually added to the blue alliance score.

**Expected behavior**
Foul points should remain consistent and be shown in the same column with the other components that add up to the final score. The breakdown graph should show foul points for the correct alliance.

**Screenshots**
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/36ef1311-b996-4c87-8965-a18c684e9c20">
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/a303d9a6-03a5-4eb3-bb45-e45d2469faae">

**Device (please complete the following information):**
 - OS: macOS 14.6.1 (23G93)
 - Browser: Firefox 131.0.3 (aarch64)
 - FTC Events as of 2024-10-28 17:58 PDT

**Comment by pmichaud** [comment]
I might also suggest that the score breakdown use colors other than red and blue, to avoid unintentional confusion with red alliance versus blue alliance scoring.  (Perhaps this belongs as a separate issue.)

Pm

**Comment by pmichaud** [comment]
Perhaps pale red and full red for red's auto and teleop points, and pale blue/full blue for blue's points

And I don't know if I would prefer this or not, but I'll offer it as a concept:  the foul points for could then be colored some shade of red or blue to show that they were contributed by the opposing alliance.

The only other thing I might want to see is that the circles become stacked bars, so that the relative heights of the bars indicate the relative scores.

**Comment by rachmo** [comment]
Thanks for the bug report. We'll look into making the following correction:
> Foul points should remain consistent and be shown in the same column with the other components that add up to the final score. The breakdown graph should show foul points for the correct alliance.

I agree there are additional possible color scheme and formatting improvements that should be considered but I think those will need to be addressed separately as an enhancement not a bug.

**Comment by maths22** [comment]
This has been fixed
