### ISSUE TITLE
Minor Scorekeeper Guide table of contents errors

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#766]
## Requested Change
1. In **Bluevolt**, the Scorekeeper guide table of contents has some errors
<img width="876" alt="image" src="https://github.com/user-attachments/assets/82c7adca-c16d-4d40-a6d8-be20890fbf19">
2. In all versions of the guide, the table of contents has picked up the first sentence of Appendix B as a very long chapter marker. This should be removed, as the heading directly above and the appendix itself are already listed in the TOC.
<img width="875" alt="image" src="https://github.com/user-attachments/assets/9fc5031a-e998-46d6-82f0-fa8c4a9f69fe">

**Comment by emcclurg** [comment]
Thanks for noticing this. I’ll update it this week

**Comment by emcclurg** [comment]
This will be published soon.
