### ISSUE TITLE
QR Code in Pit Display results in broken Link

### ISSUE THREAD

**Issue by Cannongeorge** [FIRST-Tech-Challenge/scorekeeper#769]
**Describe the bug**
Version  6.1.4.   The QR Code diusplayed on the Pit display results in a broken link; though it does land within the First Inspires website.  However, the QR code displayed on the "Match Results" page is correct.  

Using WIN 11 and Chrome on Match Control laptop.

**Comment by rachmo** [comment]
Thank you for your bug report, can you confirm what event you were at which was experiencing this issue?

**Comment by Cannongeorge** [comment]
Rachel - The event was "uscalavm1", SoCal FTC League V - Meet 1, conducted 11-2-2024.  (Event was uploaded same day).

**Comment by maths22** [comment]
This has been fixed so that link works correctly
