### ISSUE TITLE
Fill award information in awards script

### ISSUE THREAD

**Issue by jmessing-29** [FIRST-Tech-Challenge/scorekeeper#772]
**Describe the bug**
Generating the award script still shows a message like "Award info for INTO THE DEEP will be added soon..."

**To Reproduce**
1. Go to manage awards
2. Click on 'view/print script'
3. See error on each award

**Expected behavior**:
Have a description of the award

**Screenshots**
<img width="411" alt="image" src="https://github.com/user-attachments/assets/e53f6887-d021-4b1a-aab5-a4bc313fe529">

**Device (please complete the following information):**
 - OS: macOS Sonoma
 - Browser: Chrome
 - Version 6.1.4

**Comment by maths22** [comment]
There will be a release later this week which will include the complete scripts.

**Comment by maths22** [comment]
v6.2.0 has been released with the scripts added.  Note that any event downloaded from the cloud scoring system before today will not have scripts and should be re-downloaded/imported.
