### ISSUE TITLE
Erroneous winner / finalist flags

### ISSUE THREAD

**Issue by dbehrens** [FIRST-Tech-Challenge/scorekeeper#774]
**Describe the bug**
On https://ftc-events.firstinspires.org/2024/USMIKEQ at the end of round one, it flagged two alliances as winner and finalists.  

**To Reproduce**
1. Go to '...' https://ftc-events.firstinspires.org/2024/USMIKEQ
3. Scroll down to '....'  alliances, and you'll see
4. See error--still only shows finalists, and not the event winners

**Expected behavior**
Expect no flags to be shown at the end of round one, but expect them to be shown at the end of the event.

**Screenshots**
![Screenshot_20241102_184328_Chrome](https://github.com/user-attachments/assets/7bf2dc57-c1c9-4fe5-b343-cb007602810e)
![Screenshot_20241102_171136_Chrome](https://github.com/user-attachments/assets/253b8e9f-11c6-4fe5-a953-e8270ca5ae38)

**Device (please complete the following information):**
 - OS: [e.g. iOS] Android 14
 - Browser [e.g. chrome, safari] Chrome

Also shows up in chrome on a Windows 10 desktop.  Version 130.0.6723.117 (Official Build) (64-bit)

**Additional context**

**Comment by maths22** [comment]
These incorrect tags have been removed.  Thank you for the report.
