### ISSUE TITLE
Cloud pit display not working

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#776]
**Describe the bug**
When going to the pit display from the cloud there is only the blank background and no match results or rankings.

**To Reproduce**
1. Navigate to the cloud pit display (e.g. https://ftc-scoring.firstinspires.org/event/usiacorm4/display/pit)
2. Observer that there is no ranking or match information

**Expected behavior**
Information shown

**Screenshots**
N/A

**Device (please complete the following information):**
 - v6.2.0

**Additional context**
I can see the correct information in the websocket on that page, it just isn't rendering that information in the DOM.

**Comment by maths22** [comment]
This has been fixed
