### ISSUE TITLE
retrieving schedule doesn't work

### ISSUE THREAD

**Issue by qweztech** [FIRST-Tech-Challenge/scorekeeper#777]
I'm using Python 3.12.3 on Ubuntu Linux 24.04.1 LTS. I have a valid API key.

I'm trying to retrieve the schedule from an FTC event.

When I use python package 'requests' and the URL 'https://ftc-api.firstinspires.org/v2.0/2024/schedule/USTXNSM1' I get an empty response string (''). 

To verify it works, I run the same request with the URL 'https://ftc-api.firstinspires.org/v2.0/2024/rankings/USTXNSM1' to get rankings, and it returns a valid response status of 200 with rankings data.

The code I'm running for bot the successful and unsuccessful requests is:

    def get_info(self,url):
        key_str = self.encode_key()
        
        payload={}
        headers = {
            'Authorization': 'Basic ' + key_str,
            'If-Modified-Since': ''
        }
        
        # Grab some data
        response = requests.request("GET", self.url, headers=headers, data=payload)

**Comment by tvbarnette999** [comment]
You need to add either a `teamNumber` or `tournamentLevel` query parameter. Try:
`https://ftc-api.firstinspires.org/v2.0/2024/schedule/USTXNSM1?tournamentLevel=qual`

[Event Schedule Endpoint Documentation](https://ftc-events.firstinspires.org/api-docs/index.html#tag/Schedule/paths/~1v2.0~1{season}~1schedule~1{eventCode}/get)

**Comment by qweztech** [comment]
Thank you, I apologize, I need to read the doc’s more closely

 

Joe Varnell

Super Nerd



FIRST ®  Technical Advisor

FIRST ®  Senior Mentor Emeritus

FIRST ®  in Texas Key Volunteer


More than Robots


Phone:  214-502-7326  |  ***@***.*** ***@***.***>

**Comment by rachmo** [comment]
Thanks Joe! Since it sounds like this will solve your problem, I'll go ahead and close this issue. 

Please feel free to reopen or open a new issue if you're still experiencing a problem.
