### ISSUE TITLE
Third Place Alliance Award Bug

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#779]
**Describe the bug**
The "Third Place Alliance" award is present.

**To Reproduce**
1. Open "Manage Awards" screen
2. Scroll to "Third Place Alliance" award

**Expected behavior**
This award probably shouldn't be present as indicated by it's description.

**Screenshots**
![image](https://github.com/user-attachments/assets/0899fd27-0ef7-4cbd-bc2f-0ca4ebf258ff)

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 130.0.6723.117
 - Scorekeeper Version: v6.2.0

**Comment by maths22** [comment]
This has been fixed in v6.2.2
