### ISSUE TITLE
HR Notes - Selecting a team tag when adding a new detail causes a client side failure

### ISSUE THREAD

**Issue by FrowntownPitt** [FIRST-Tech-Challenge/scorekeeper#783]
**Describe the bug**
On the HR Notes page, when adding a note to a match which already has a summary, selecting a team tag when creating a new detail breaks the page.

It appears the note is still saved if you press "save". Refreshing the page after clicking "save" persists the note and tag, or after clicking "cancel" is in the same state as before the error.

**To Reproduce**
1. Go to HR Notes tab
2. Click on 'By Team'
3. Select a team (99995)
4. Select the match to apply the note to (Q7)
   * <img width="803" alt="Pasted Graphic 1" src="https://github.com/user-attachments/assets/20c89f12-7bc6-45f7-92c0-5b536a4225a3">
6. Observe the previous note summary
   * <img width="801" alt="Match Note" src="https://github.com/user-attachments/assets/997d33e4-a8b8-465b-b30e-f4d2c962ebe3">
7. Select the team checkbox
   * <img width="977" alt="Pasted Graphic 3" src="https://github.com/user-attachments/assets/059bc609-6ede-4610-8c83-0ef1f6d5b436">
8. Observe the error
```
TypeError: a is null
    Ce NotesTab.jsx:90
    Be NotesTab.jsx:101
    React 14
    r helpers.js:90
console.js:36:19
```
9. Clicking "Try again" yields a different error in the console
```
Uncaught TypeError: this is undefined
    resetError LocalErrorBoundary.tsx:30
    React 11
    r helpers.js:90
LocalErrorBoundary.tsx:30:8
```
10. Optionally save or cancel, and refresh.

**Expected behavior**
The team is selected and the note can be applied. clicking "save" closes the modal and displays the notes screen.

**Screenshots**
added inline above

**Device (please complete the following information):**
 - OS: MacOS (server), MacOS (client) / iPadOS (client) / Android (client)
 - Browser: Chrome, Firefox
 - Version 6.2.1

**Additional context**
It may just be a client side error. Refreshing the page after clicking "save" persists the note and tag, or after clicking "cancel" is in the same state as before the error.

The error appears to happen regardless of how many "detail" sections are filled out (0, 1, many). Only if "General/Summary" has content saved.

**Comment by maths22** [comment]
This has been fixed in v6.2.2
