### ISSUE TITLE
Cycle Time Report Explanations

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#785]
**Is your feature request related to a problem? Please describe.**
The columns on the detailed cycle time report are unclear as to what they actually describe.

**Describe the solution you'd like**
Tooltips or some explanation of how each column is calculated.

**Describe alternatives you've considered**
Documentation in the Scorekeeper guide with a comprehensive list of how each column is calculated.

**Additional context**
![image](https://github.com/user-attachments/assets/e116c6e4-9d97-4ebd-8ed8-f4448026055a)

**Comment by maths22** [comment]
We have added tooltips for each column in both the cloud and local versions of this report
