### ISSUE TITLE
Presenting advancement with "> Present" on the audience overlay does not work

### ISSUE THREAD

**Issue by LazyKoala82** [FIRST-Tech-Challenge/scorekeeper#787]
**Describe the bug**
When trying to present the advancement, with the video overlay shows a "Something went wrong. Please contact FIRST event support." The Details says "TypeError: Cannot read properties of undefined (reading 'slot').

**To Reproduce**
1. Open a new display. Set to audience and 'Use Overlay'
2. Go to the Awards Manager, and click Present Adwards.
3. Hit '> Present'.
4. Hit 'Next'.
5. Hit 'Present Advancement'
6. Hit '> Present'
7. Observe bug (hitting 1st place inspire does not fix the screen, though hitting 1st place inspire, then reloading the display does... hitting '> Present' after that also results in the bug).

**Expected behavior**
Hitting '> Present' should not result in an error.

**Screenshots**
![Screenshot 2024-11-17 203021](https://github.com/user-attachments/assets/1efc3fac-3ef3-4734-907f-fbcc90b51c46)

**Device (please complete the following information):**
 - OS: Windows 11 Home
 - Browser: Chrome 131

**Comment by bsimmons99** [comment]
We also ran into this issue at our event.
As above, only audience displays configured as an overlay were affected.

**Comment by maths22** [comment]
This has been fixed in v6.2.2
