### ISSUE TITLE
Record the Blue and Red scoring table submit times

### ISSUE THREAD

**Issue by qweztech** [FIRST-Tech-Challenge/scorekeeper#788]
Have the scoring system record, to ftc-events, the time the Red and Blue scoring tablet Auto submit time, Teleop submit time, and time the final submit from the ref scoring tablets (Blue and Red) are recorded. Have these times retrieved from the ftc-event API for the match data for the event.

I just want more data to be able to know what we need to work on to keep events moving.

**Comment by qweztech** [comment]
The main problem, is after the end of the event, everyone is more focused on getting packed up out of there and don’t think about.

 

I’m a head ref and data nerd. I try to use data to improve my performance and, if others are interested, there performance. Like my last event, after I left and was thinking about it, I felt like the red scoring ref got most of my time and was having them submit first, wheather most of the issues were there or not, just because, after thinking about it, it was easier to get there. 

 

All this was speculation without data. Since I wasn’t requesting the cycle time report from the scorekeeper at the exact end of matches, I missed it. He was logged off and packing up almost as soon as the last match was posted. I had to point out to him and the people tearing down the field, we had to wait for 5 min for any questions. He said he could power it back up and plug things back in if needed.

 

I want to be able to go back, check my performance, check performance of other HR’s if they want. If you’re not a HR, I’m sure the data’s not relevant.

 

Thanks

 

Joe Varnell

Super Nerd



FIRST ®  Technical Advisor

FIRST ®  Senior Mentor Emeritus

FIRST ®  in Texas Key Volunteer


More than Robots


Phone:  214-502-7326  |  ***@***.*** ***@***.***>

**Comment by rachmo** [comment]
@qweztech  (Hi Joe!), we are not comfortable exposing cycle time data publicly through ftc-events api for the reasons @timtim17 pointed out. The data does continue to live in the cloud scoring system after the event, but is not currently exposed to the Head Referee role.  We agree this would be helpful to grant access to, so we'll work on adding it. 

For now, anyone assigned an event role in the scoring system can see it today so you can always ask your PDP, league admin, or Scorekeeper to log-in and get it for you.  (or if you tell me what event I can try to grab it for you this time)

**Comment by qweztech** [comment]
Hi Rachel,

 

It was just a request and I understand. I just like to slice and dice data myself, sometimes it’s interesting what you can come up with

 

Thanks

 

Joe Varnell

Super Nerd



FIRST ®  Technical Advisor

FIRST ®  Senior Mentor Emeritus

FIRST ®  in Texas Key Volunteer


More than Robots


Phone:  214-502-7326  |  ***@***.*** ***@***.***>

**Comment by rachmo** [comment]
Hi @qweztech,

Head Referees can now log into https://ftc-scoring.firstinspires.org/ and see the cycle time reports for any completed event they were assigned to in VMS.  Give it a try and let us know if you have an issues.

Happy data analysis!

**Comment by jkelbick** [comment]
@rachmo This is really cool, thanks!
