### ISSUE TITLE
Commit and Post

### ISSUE THREAD

**Issue by hightechkids** [FIRST-Tech-Challenge/scorekeeper#79]
On the Match Control page, does the "Commit and Post Last Match" button work? It was never active and I was never able to select it.

If you save and the commit a score, that score is updated in the database and separate displays (Match, Ranking, Pit) will display this change, before the "post" display button is hit. Generally, we want it first to show up when the score is "posted" on the audience or field displays. So the Commit and Post last match button is exactly what we want.

**Comment by tvbarnette999** [comment]
It should become available after both referees have submitted their final scores, if the next match has not been started. This option is only available when live scoring is being used. It is a convenience button to prevent the scorekeeper from having to change tabs for every match when they don't need to edit anything. It should be used when a match ends, and nothing unusual happens, so the scores submitted at the end of the match are correct and ready quickly. This allows for final scores to be shown _before_ the next match is played. If the next match is started or something needs to be edited by the scorekeeper (cards, referee submitted something incorrectly, etc), this option becomes unavailable and the scorekeeper should use the individual Commit and Post buttons within the edit tab for the match.

**Comment by adwiii** [comment]
Please re-open if there are any additional questions.
