### ISSUE TITLE
Playoff matches not shown for teams in FTC Events

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#792]
**Describe the bug**
Teams who have played in Playoff Matches at an event, do not have any playoff matches shown on their team page.
https://ftc-events.firstinspires.org/2024/AUTOQ/playoffs

**To Reproduce**
1. Go to [https://ftc-events.firstinspires.org/2024/AUTOQ/playoffs](https://ftc-events.firstinspires.org/2024/AUTOQ/playoffs)
2. Click on any team in any of the playoff matches
3. Scroll down to _Playoff Matches_
4. See _Team xxxxx did not appear in, or there were not, any Playoff Matches at this Event_

**Expected behavior**
Playoff matches are shown like qualification matches above.

**Screenshots**
![image](https://github.com/user-attachments/assets/d7e0e65f-8ab2-474a-8649-cc8c77bef234)

<hr>

![image](https://github.com/user-attachments/assets/45263509-57bd-491e-90ca-9431b38f78b4)

**Device (please complete the following information):**
 - OS: Windows 10 / Android 14
 - Browser: Chrome 131.0.6778.70 / Chrome 131.0.6778.39
 - FTC Events Version: v5.1.0

**Comment by rachmo** [comment]
This issue has been resolved. Thank you for reporting!
