### ISSUE TITLE
[Minor] Overlap on score edit page

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#796]
**Describe the bug**
The starting configuration/cards panel slightly covers the autonomous specimens fields for the red alliance, blocking the arrows.

**To Reproduce**
1. Use a system with a specific aspect ratio/resolution combo (more information is provided below).
2. Edit a match.
3. Observe the arrows of the specimens fields on the red alliance are covered.

**Expected behavior**
The specimens field is not covered.

**Screenshots**
![image](https://github.com/user-attachments/assets/30a5438d-0b93-4e1d-b68d-852809e5117d)

**Device (please complete the following information):**
 - OS: Windows 10 and 11, MacOS 12
 - Browser: Chrome
 - Version: 6.2.2

**Additional context**
Aspect ratio/scale combinations that cause it:
- 1920x1200 at 150% (initial computer where I noticed the bug, 16:10)
- 1920x1280 at 150% scale (3:2)
- "Looks like 1280x800" on a Mac (16:10)

Aspect ratio/scales that work as expected:
- 2560x1600 at 150% scale (16:10)
- 1920x1080 at 100% scale (16:9)
- 1920x1080 at 150% scale (16:9)
- "Looks like 1440x900" on a Mac (16:10)

**Comment by maths22** [comment]
This was fixed in v6.3.0
