### ISSUE TITLE
Can't Edit/Remove teams from event

### ISSUE THREAD

**Issue by ShaharIlany** [FIRST-Tech-Challenge/scorekeeper#798]
**Describe the bug**
When trying to edit the participating teams, there are no teams in the list.

**To Reproduce**
1. Go to event dashboard
2. Click on Add/Edit Teams
3. Click on Choose file and upload the attached file
5. Click on Upload
6. Refresh the page
7. See the error

**Screenshots**
<img width="1440" alt="Screenshot 2024-12-04 at 22 15 45" src="https://github.com/user-attachments/assets/22694576-5a0e-482d-a18e-ad2a4802dbfa">
<img width="1440" alt="Screenshot 2024-12-04 at 22 15 28" src="https://github.com/user-attachments/assets/8344a237-e6ae-4e4d-bffd-87c7073d95e7">

**Device (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Browser: Google Chrome
 - Version: 131.0.6778.109 (Official Build) (arm64)

**Additional context**
[Neptune.csv](https://github.com/user-attachments/files/18013797/Neptune.csv)

**Comment by tvbarnette999** [comment]
This should now be fixed, thanks for letting us know!
