### ISSUE TITLE
Difficulties entering playoff match start time when generating alliance selection

### ISSUE THREAD

**Issue by pmichaud** [FIRST-Tech-Challenge/scorekeeper#802]
**Describe the bug**
Updating the "Playoff Match Start Time" field requires entering full date and time.  This is similar in nature to #782 but not as extreme, although it takes a bit of fiddling to figure out the correct workaround.

**To Reproduce**

See the video at https://youtu.be/hW3S_o9SGh4?si=52_3NsMWbepCmrl8 to see a live demonstration of the problem (observed/recorded at the USTXDTQ2 event held on Dec 7).

1. Go to Alliance Selection tab on Match Control page.
2. Click on "Start Alliance Selection".  A dialog box appears asking for the Playoff Match Start Time.
3. Click on the "minutes" portion of the time to change the minutes (e.g., to change "4:20 PM" to "4:30 PM").
4. Type in the new number of minutes (e.g., "30").  The match start time minutes changes to ":00" (bug).  Try again (enter "30"), the match start time minutes remains at ":00" (bug).
5. Click on the hour field to try typing in the full hour+minute time, then type "04" for the hour.
6. (bug) The entire date/time entry is zeroed out, and "04" gets entered for the month.

**Expected behavior**

The scorekeeper should be able to individually set hour and minute fields of the playoff match start time.  The only workaround we found (by trial and error) was to completely enter the full date and time from the start of the field.

**Screenshots**

Full video available at https://youtu.be/hW3S_o9SGh4?si=wforlZtNZbgwMubX .

**Device (please complete the following information):**
 - OS: Kubuntu Linux 24.04.1
 - Browser  Chrome

**Comment by maths22** [comment]
This has been fixed in v6.4.2
