### ISSUE TITLE
Scoresheets in Match Results do not reflect card status for both alliance members in playoffs

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#811]
**Describe the bug**
In the Match Control page, issuing a card to one team in playoffs causes both checkboxes to be checked on the client side, indicating that both teams (the whole alliance) receives the card. But, in the scoresheets in Match Results, only the first team is checked. (Maybe this matches paper scoring? Can't recall.)

**To Reproduce**
1. Issue a card in playoffs to an alliance
2. Navigate to the scoresheet for that match in Match Results
3. Observe that only the first team is checked for the card

**Expected behavior**
Both teams should (?) be checked for the card

**Screenshots**
<img width="460" alt="image" src="https://github.com/user-attachments/assets/989a5081-9cf0-4b9b-951a-c16a115fdfa7" />

<img width="111" alt="image" src="https://github.com/user-attachments/assets/e4a80692-392f-4ebc-a152-965ff999a0fa" />

**Device (please complete the following information):**
 - OS: macOS 15.1.1 (24B91)
 - Browser: Firefox 133.0 (aarch64)
 - FTCLive v6.4.1

**Additional context**
Maybe this might be correct behavior, I don't recall if in paper scoring alliance cards are only checked for one team. I could see it being checked for the team that "committed" the violation (despite the card being issued to the alliance), but it seems like it is always registered to the first team.

**Comment by maths22** [comment]
This has been fixed in v6.4.2
