### ISSUE TITLE
Giving a team a DQ incorrectly and fixing it causes RS not to calculate correctly

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#813]
**Describe the bug**
In one of our matches last weekend, we had a team show without a robot (did have a human player). The referee incorrectly marked them on the scorepad as NR (No Robot) and DQ (disqualification).  We played the match and posted the results. We then noticed that the DQ was posted. We corrected the error by removing the DQ and saving the edit.  Later, the team in question spoke with us about an incorrect ranking score. At the time, the team was 3-1 and should have an RS of 1.5. However, the team's RS was 1.0 (which showed that the DQ wasn't removed from the RS calculation). We double checked the score and the DQ was removed correctly. We thought, may their next match will correct the issue with the updated RS. They won the next match, but the RS didn't update (it should have been 1.6, but it showed 1.2). This also had an effect on the rankings.

**To Reproduce**
See above

**Expected behavior**
See above

**Screenshots**

**Additional context**
What we did to fix it on the spot was to print the scoresheets from the DQ'd match, then we re-ran the match without any robots on the field (i.e. virtually). We got the score correct and then posted. The new replay calculated the RS correctly this time.

I was worried about this during the event, so did call Tech Support who escalated the issue to one of the developers, but we already reran the match by the time I heard back from them on what they wanted us to do.

**Comment by thecocohead** [comment]
Wasn't able to replicate on v6.4.1. Just to confirm- the scorekeeper recommitted (not reposted or saved) the changes? 

I was able to remove the DQ mark from a team and repost the results (which plays the winning animation on the audience screens) but as long as I didn't commit the change it didn't change the rankings.

**Comment by emmell620** [comment]
The original score (with DQ) was committed and posted.  Then the team saw the problem and told us. We noticed our error and removed the DQ and reposted. No change to the RS (still in error).  Then reran the match virtually and reposted. RS corrected.

**Comment by maths22** [comment]
This has been fixed in v6.4.2
