### ISSUE TITLE
fire tablets

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#82]
We have a number of fire tablets that we want to use for the scoring refs.  We found that chrome was not working correctly but silk was working ok.  Will there be any problem if we use silk instead of chrome in the future.

**Comment by adwiii** [comment]
This concerns me because I had the exact **opposite** experience - silk was not working and Chrome was working. Can you give me model numbers of the fire tablets as well as chrome and silk version numbers and a description of what exactly was not working in chrome?

**Comment by rgutentag** [comment]
I don't have the tablets with me and won't have my hands on them for a few weeks.  I suspect that they have older versions of everything on them since we don't put them on a live internet connection.  They have only been on the private local network at events.

**Comment by adwiii** [comment]
Hm. Okay, well get back to me if the problem re-surfaces. In general if the browser appears to work then it should be fine - you just need to test it yourself before hand. I am curious though - how did you get Chrome on the Fire Tablets? Current models do not ship with Chrome, so I had to manually install it. 

Also, was the problem a rendering issue or functionality? No buttons/unusably sized buttons or the buttons were not updating the display?

**Comment by rgutentag** [comment]
We loaded chrome a few years ago so have an older version.
The problem we saw was that the table could login as the scoring ref function but when we tried to input any scoring data the tablet would not accept any key strokes.  If I get a chance in the next few weeks to try it again I will let you know.

**Comment by adwiii** [comment]
@rgutentag have you used the tablets and how did it go if so?

**Comment by rgutentag** [comment]
We have been using silk with no problem on our older tablets.  We are in the process of putting newer version of chrome on our older tablets.  We just got 3 newest model and have put chrome on them and they worked very well at today's event.  You can close this item for now.

**Comment by adwiii** [comment]
Thanks for the update. Let me know if any issues arise.
