### ISSUE TITLE
number of fields for league meet

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#84]
Many of our league meets have 24 teams participating and we use 2 fields.  When I pick league meet the system will not allow me to specify more than 1 field.

**Comment by LazyKoala82** [comment]
From Game Manual Part 1, Section 6.2, the official definition of a league meet is:
"A League Meet is a one-field competition that uses the same field and game as other tournaments."
which is probably why the scoring system restricts it to one field?

**Comment by ftctechnh** [comment]
@rgutentag 
LazyKoala82 is correct - officially a League Meet is defined as a one-field competition.  However, after consulting with the FIRST Tech Challenge program staff, the software has been modified in the v0.4.2 release to remove the one-field restriction in the user interface when creating an Event of League Meet type.

**Comment by ftctechnh** [comment]
This issue has been resolved with version v0.4.2.
