### ISSUE TITLE
Delete League

### ISSUE THREAD

**Issue by bbugert** [FIRST-Tech-Challenge/scorekeeper#90]
Can an option be added to delete a league should we enter one incorrectly? Maybe with a BIG warning that this will delete all data associated with this league.
For example, If we enter the wrong code. we can't edit or delete the code.

**Comment by adwiii** [comment]
Closing as league management is deprecated in FTCLive. All league data is handled through the [online scoring system](https://ftc-scoring.firstinspires.org) and automatically imported when the event is imported into FTCLive. The online scoring system does have the ability to delete leagues.
