### ISSUE TITLE
Integrate live event data uploading to a common server

### ISSUE THREAD

**Issue by cheer4ftc** [FIRST-Tech-Challenge/scorekeeper#91]
FTC has a growing community eager for access to live and semi-live FTC event results for scouting and research, which has led to many tools such as TOA, ftcscores, ftcstats, the FTCEventViewer android app, and numerous AP-specific event reporting solutions (e.g., pennfirst, iowa, illinois, ftclive in NC, etc.).  

The development of new scoring software provides a unique opportunity to address the unnecessary fracturing of FTC data availability.

There are two problems 1) developers don't know where to get event data from (as it is distributed among many different sites and formats) and 2) sometimes the data never comes (as many APs don't bother to post event data, either live or after-event, often because they don't know how). 

A proposed solution to integrate into the scoring software is to 1) default a data push to go one primary common server (and optionally others at the choice of the AP) and have that server have a reliable public API for all interested developers to utilize the data for their own purposes, and 2) have the data get pushed by default without direct input from the scorekeeper (though APs could turn off this option if they choose to). This would result in a much larger and consistent database of results that could be used by the wider community. Integrating the solution in the scoring software will likely result in the solution being a defacto standard to the benefit of all involved.

**Comment by afera15** [comment]
I second this completely, having a centralized place helps out a lot so we devs don't need to go everywhere to get data.  However there are two other points I want add to the request:
1.) Make this an automatic thing if the host site/db/write API is detectable
2.) A plan for how to get data to the site without internet

**Comment by Techno11** [comment]
+1 Great way for teams to scout during an event without the Event manager or scorekeeper having to setup an extra app to upload scores.

**Comment by jvens** [comment]
I agree with this idea in general, but I do have one concern.  We do run some events where the score system has no access or unreliable access to the internet.  This feature should be designed in a way that it will not break in the absence of internet connection, and ideally be able to upload easily after the fact when the computer does have internet.

Another possible concern is if an event sets up a local router without internet for live scoring and connects the score system computer to it with Ethernet windows defaults to only using the Ethernet connection for all tcp traffic.  This can be fixed by disabling the gateway on the Ethernet interface, but that is not something most event volunteers are going to know about and could cause some headaches.

**Comment by MC42** [comment]
> 
> 
> I agree with this idea in general, but I do have one concern. We do run some events where the score system has no access or unreliable access to the internet. This feature should be designed in a way that it will not break in the absence of internet connection, and ideally be able to upload easily after the fact when the computer does have internet.
> 
> Another possible concern is if an event sets up a local router without internet for live scoring and connects the score system computer to it with Ethernet windows defaults to only using the Ethernet connection for all tcp traffic. This can be fixed by disabling the gateway on the Ethernet interface, but that is not something most event volunteers are going to know about and could cause some headaches.

The FRC Field Management System allows for ZIP and Excel export to be sent to FIRST HQ after the fact in event of no internet (uncommon), or to community resources like The Blue Alliance for import.  I see no reason why FTC as a community couldn't arrive at the same solution.

**Comment by adwiii** [comment]
The [online scoring system](https://ftc-scoring.firstinspires.org) should help to solve this. All events should be imported from the online scoring system and then uploaded to the online scoring system once completed. All data uploaded to the online scoring system will be visible on [ftc-events.firstinspires.org](https://ftc-events.firstinspires.org) which has an API that third-parties can use to access event data. 

Event data is currently uploaded manually after the event has concluded. If the event venue does not have internet access, it can be uploaded later when internet is available.

**Comment by adwiii** [comment]
Update: as of version v2.3.0, the Traditional Scoring System now uploads data to *FIRST* throughout the event if there it has been set up properly online and there is an internet connection. This happens automatically in the background.

From the release notes for v2.3.0:
 * Updates made to a Traditional Event are pushed to [ftc-events.firstinspires.org](http://ftc-events.firstinspires.org):
      * Team List Edits
      * Quals Generation
      * Match Commit
      * Alliance Selection
  * Updates are pushed after a slight delay (10 seconds)
      * Can change to 30s, 1m, 5m on "Settings" tab of Match Control Page
      * Delay time is from "Commit"
        * To save scores but not publish them, use the "Save" button, not the "Commit" or "Commit & Post" button. (This is not new, but more relevant now)
             * Remember to come back and commit them!
             * This workflow is not recommended
             * Rankings will not consider uncomitted matches
      * Events can be setup in "Test Mode", which will not push updates. 
          * ONLY for testing a setup
              * Preferred method to test setup is to create an obviously fake local event
          * This disables *all* uploading, including archive uploading once the event is complete - so do not use this for official events.
      * Control page has a sync status indicator in bottom-left corner
      * Control page settings tab has a "Test" and "Force Sync" button
      * If there is no internet connection, it will send all queued update on reconnect
