### ISSUE TITLE
Match score preservation

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#95]
We had an issue where we edited the score for the wrong match. Since there are no paper records, the teams had to come back to us with their score details, and the referees had to use their memories to attempt to verify the mistake we had made and the changes to put it back.
It would be very helpful if the system kept versions of the score for a match any time it is committed, and allowed the ability to revert to a prior version. Without a paper trail, we really have no other good way to have a history.
It would also be helpful to have a warning if we are committing an edit to anything other than the active match. Something like "Are you sure you want to change match 5 when the active match is 9?"

**Comment by adwiii** [comment]
This has been addressed in v0.5.1

If the user has permissions to view the Match Control page, then on the Match Results page there will be an additional column for the history of the match:
![image](https://user-images.githubusercontent.com/9453262/47880225-0a0cb400-ddf9-11e8-93de-d9e96db5d998.png)
The user can then select "View Match History" to see all previous commits of that match, including the winner, final scores, and time of commit:
![image](https://user-images.githubusercontent.com/9453262/47880272-26105580-ddf9-11e8-9058-23615c636aae.png)
The user can then select to view the scoresheet for any of the specific commits. If the user views an old commit, it will prominently display that the data being viewed is not current:
![image](https://user-images.githubusercontent.com/9453262/47880323-52c46d00-ddf9-11e8-9ce5-3c8eb604c898.png)

This way, if you need to "return" to a previous commit, you can pull up the scoresheet view for that commit and copy the results into the Match Control page and make a new commit that has the same scores as the previous version. We purposefully do not support "rolling back" to a previous version as that introduces several complications.
