### ISSUE TITLE
Background color of incomplete count

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#96]
The background color of the incomplete count is always bright red. When the incomplete count is zero, it would be helpful not to have that bright red glowing on the screen. That bright red should urge action to complete the incomplete matches, not become something that the user ignores.

**Comment by adwiii** [comment]
As of version 0.4.3 the Incomplete Count is hidden if it is 0. 

There is a separate bug where if you are not using live scoring, on commit it will briefly show the red badge and then disappear. We have noted this and are working to fix it in v0.4.4.
