### ISSUE TITLE
Match Control - score commitments

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#97]
At the end of the match, the 'Commit & Post Last Match' goes green when both referees have submitted their scores. It would be helpful to be able to tell which referee (or both) we are waiting on. Especially in the early matches or when a new referee comes on, the electronic scoring is something they can forget to submit. This might be as simple as coloring the left 1/3 green if only Red is committed and the right 1/3 green if only Blue has committed.

**Comment by tvbarnette999** [comment]
This has been added in v1.1.0. The same location that highlights green when a ref has submitted init now turns green when they submit (just under active match, not loaded match). It also lists the teams that have NOT submitted in the yellow bar with the lockout button when you try to edit an incomplete match.
